### ISSUE TITLE
Some thoughts on #feedback_positive_percentage

### ISSUE THREAD

**Issue by gil27** [sharetribe/sharetribe#1000]
Hey guys, just thinking about this method: https://github.com/sharetribe/sharetribe/blob/master/app/models/person.rb#L371
```ruby
def feedback_positive_percentage
    if received_positive_testimonials.size > 0
      if received_negative_testimonials.size > 0
        (received_positive_testimonials.size.to_f/received_testimonials.size.to_f*100).round
      else
        return 100
      end
    elsif received_negative_testimonials.size > 0
      return 0
    end
  end
```
How can we improve this method? Remove those "if" statements?
After some thought on that I came up with something like that:
```ruby
def feedback_positive_percentage
  positive_testimonials = received_positive_testimonials.size
  received_testimonials = received_testimonials.size  

  (positive_testimonials/(received_testimonials * 100)
   # OR (positive_testimonials/received_testimonials) * 100
end
```
As an example we can take `positive_testimonials = 8` and `received_testimonials = 10`
Then we have:
```
8/(10 * 100) = 0,008
(8/10) * 100 = 80

# with zero
0/(10 * 100) = 0
(0/10) * 100 = 0
```

What do you think? Does that make any sense?

**Comment by ovan** [comment]
Hi @gil27. Sound like good direction. You must still add a check to precent division by zero. I'll close this issue but would be happy to see a pull request about this so the CI server gets to run tests on it etc.

**Comment by rap1ds** [comment]
Congrats for the issue number 1000! :tada:
