### ISSUE TITLE
"uninitialized constant Mercury" at rake db:schema:load

### ISSUE THREAD

**Issue by 3bbing** [sharetribe/sharetribe#1040]
Dear Sharetribe Team,

When going through your installation I faced the above mentioned error 

- uninitialized constant Mercury::Engine(NameError)

Fixed it by adding 

- require 'mercury/rails'

to the application.rb like said in this thread [1]. Fine for me, anyhow in the thread there is an ongoing discussion why or why not this may happen and they say the require call shouldn't be neccessary actually. No biggy but probably something you might wnat to look into some day. 
Also imho good to just have it in here for people facing a similar problem.  

Thanks & all the best!

[1] https://github.com/jejacks0n/mercury/issues/324

**Comment by kaskavalci** [comment]
Thanks for the tip. After that I  had the error

``` ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. ```

Even though I had execJS. Apparently, you need nodejs as well to run it. For ubuntu users simply 

``` sudo apt-get install nodejs ```

CentOS/RedHat Users

``` sudo yum install nodejs ```

**Comment by rap1ds** [comment]
As it was said in the thread you linked, you shouldn't need to add this line.

Which installation step gave you this error? Are you able to reproduce it? Can you describe the exact steps to reproduce the error. You can use the issue template: https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md Thanks!

**Comment by rap1ds** [comment]
Inactive. Closing.
