### ISSUE TITLE
rake assets:precompile fails with aws S3

### ISSUE THREAD

**Issue by Pequi-eu** [sharetribe/sharetribe#1107]
Hi everyone and first, thanks for the great job to the sharetribe team!

I deployed Sharetribe on my Mac without any problem and I'm now trying to do it on AWS (EC2 + RDS + S3).
Everything was fine, I just did some modifications (to avoid mistakes) like:

- add 'mercury/rails’ in config/application.rb
- modified config.assets.compile = false by true in config/environments/production.rb

I created a 'aws_access_key_id' and a 'aws_secret_access_key' for S3 with the IAM (the user with the id has a complete access to S3)

I've been now for 2 days at rake assets:precompile, and nothing seems to happen. I have the following:

----------------------------
[ec2-user@ip-XXX-XXX-XXX sharetribe]$ rake assets:precompile
Digest::Digest is deprecated; use Digest
/usr/local/rvm/rubies/ruby-2.1.2/bin/ruby /usr/local/rvm/gems/ruby-2.1.2/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
Digest::Digest is deprecated; use Digest
AssetSync: using /home/ec2-user/sharetribe/config/initializers/asset_sync.rb

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     XXXXXXXXXXXXXXXXXXXXXXXX
aws_secret_access_key: ****************************************
fog_directory:         Not available
fog_provider:          Not available

Digest::Digest is deprecated; use Digest
AssetSync: using /home/ec2-user/sharetribe/config/initializers/asset_sync.rb

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     XXXXXXXXXXXXXXXXXXXXXXXX
aws_secret_access_key: ****************************************
fog_directory:         Not available
fog_provider:          Not available

--------------
That's all it does, and of course 'rake RAILS_ENV=production jobs:work' does not work after that. I thought it was a S3 mistake so a follow instructions here https://github.com/sharetribe/sharetribe/issues/665 by creating the same CORS. But it still does not work.

Regarding fog, I don't if I have to specify something and if yes, where ;-).

If you have any idea/suggestion, feel free to tell :-)

Thanks a lot

**Comment by Pequi-eu** [comment]
UPDATE:

I redo the install today and I still have the impossibility to connect to S3 but Sharetribe is working (except that images cannot be downloaded of course).

Also, I think it is not a Sharetribe issue but an issue on my side regarding S3 parameters. However, I still do not understand what is going wrong. I have the AWS Keys I entered in config.yml. I also specified the bucket.

If any idea/suggestions feel free to tell.

Tanks!

**Comment by bingxie** [comment]
Have you set up the policy to a group or user on AWS?

**Comment by bingxie** [comment]
For the asset_sync, I also found maybe we need to config 
fog_directory         = app_config.FOG_DIRECTORY
fog_provider          = app_config.FOG_PROVIDER
in config.default.yml.

**Comment by Pequi-eu** [comment]
You're right. The config.yml is made to work with Heroku I presume. So I made the following changes in config.yml:

- I added: FOG_PROVIDER = AWS
- I added: FOG_DIRECTORY = mybucket
- I deleted: s3_bucket_name
- I added: FOG_REGION = eu-west-1

in asset_sync.rb I added:

- fog_region            = app_config.FOG_REGION
- config.fog_region            = fog_region.get

With that, it is a little better. Sharetribe is now connecting to S3, but I have a HTTP error 301:
Excon::Errors::MovedPermanently: Expected(200) <=> Actual(301 Moved Permanently)

I read that it could come from the FOG_REGION, that's why I added it. Without FOG_REGION I have a HTTP error 400, so yes it's better with the FOG_REGION, but still not working. I will continue to search.

**Comment by bingxie** [comment]
Why did you delete 's3_bucket_name'? So you don't need to use S3 as image uploading storage?

**Comment by Pequi-eu** [comment]
When looking at config/initializers/asset_sync.rb, it is coded:

aws_access_key_id = app_config.aws_access_key_id
aws_secret_access_key = app_config.aws_secret_access_key
fog_directory = app_config.FOG_DIRECTORY
fog_provider = app_config.FOG_PROVIDER

Where 'fog_directory' refers not to 's3_bucket_name' but to 'FOG_DIRECTORY'. However, there is no parameter in any Sharetribe files, to specify FOG_DIRECTORY. I suppose it is maybe because it's an Heroku parameter (I'm not using Heroku)? That's why I added FOG_DIRECTORY = mybucket.

Then always in config/initializers/asset_sync.rb, Asset Sync is enable when:

enabled = [aws_access_key_id, aws_secret_access_key, fog_directory].all? { |x| x.is_some? }

So, with that, I activate Active Sync.

When I run rake assets:precompile, I have now:
-----------------
AssetSync: using /home/ec2-user/sharetribe/config/initializers/asset_sync.rb

AssetSync enabled: true

Using the following AssetSync configuration:
aws_access_key_id:     AAAAAAAAAAAAAAAAAAAAAAA
aws_secret_access_key: ****************************************
fog_directory:         mybuket
fog_provider:          AWS

AssetSync: Syncing.
--------------
But then it fails with a HTTP error 400 (and finally not 301, because I made a mistake in the Region).
Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)

When I activate EXCON_DEBUG, I can check that it is trying to access to the good server, but I don't understand why the request is not good.
-----------

excon.request  {:chunk_size=>1048576, :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.25.3", "Date"=>"Thu, 02 Apr 2015 11:56:05 +0000", "Authorization"=>"REDACTED", "Host"=>"mybucket.s3-eu-central-1.amazonaws.com:443"}, :idempotent=>true, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :uri_parser=>URI, :write_timeout=>60, :host=>"mybucket.s3-eu-central-1.amazonaws.com", :path=>"/", :port=>"443", :query=>{"prefix"=>"assets"}, :scheme=>"https", :user=>nil, :password=>"REDACTED", :instrumentor=>Excon::StandardInstrumentor, :expects=>200, :method=>"GET", :response_block=>#<Proc:0x000000096f0668@/usr/local/rvm/gems/ruby-2.1.2/gems/fog-1.9.0/lib/fog/core/connection.rb:17 (lambda)>, :retries_remaining=>4, :connection=>#<Excon::Connection:96f25f8 @data={:chunk_size=>1048576, :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.25.3"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :uri_parser=>URI, :write_timeout=>60, :host=>"s3-eu-central-1.amazonaws.com", :path=>"/", :port=>"443", :query=>nil, :scheme=>"https", :user=>nil, :password=>nil, :instrumentor=>Excon::StandardInstrumentor} @socket_key="https://s3-eu-central-1.amazonaws.com:443">, :stack=>#<Excon::Middleware::ResponseParser:0x000000096efd58 @stack=#<Excon::Middleware::Expects:0x000000096efda8 @stack=#<Excon::Middleware::Idempotent:0x000000096efdd0 @stack=#<Excon::Middleware::Instrumentor:0x000000096efdf8 @stack=#<Excon::Middleware::Mock:0x000000096efe70 @stack=#<Excon::Connection:96f25f8 @data={:chunk_size=>1048576, :connect_timeout=>60, :debug_request=>false, :debug_response=>false, :headers=>{"User-Agent"=>"excon/0.25.3"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :uri_parser=>URI, :write_timeout=>60, :host=>"s3-eu-central-1.amazonaws.com", :path=>"/", :port=>"443", :query=>nil, :scheme=>"https", :user=>nil, :password=>nil, :instrumentor=>Excon::StandardInstrumentor} @socket_key="https://s3-eu-central-1.amazonaws.com:443">>>>>>}

**Comment by Pequi-eu** [comment]
UPDATE:
I created a new bucket on the same region as my EC2 (eu-west-1) and it seems to work. Before I had my EC2 on eu-west-1 and my S3 on eu-central-1.

So I still do not understand the bug, but it is probably an Amazon one. I just now have pb to upload photos but will try to correct it, and after that, I will post a tuto!

**Comment by Pequi-eu** [comment]
All is working now!

To sum up:

1/ Create you S3 in the same region as your EC2
2/ Add in config.yml
- FOG_DIRECTORY: bucket_name
- FOG_REGION: eu-west-1 (or other)
- FOG_PROVIDER: AWS
- ASSET_SYNC_GZIP_COMPRESSION: true

3/ Add in asset_sync.rb
- fog_region = app_config.FOG_REGION
- config.fog_region = fog_region.get

@SharetribeTeam, @rap1ds : I think it could be interesting to put those parameters directly in the Sharetribe code.

For all, I made a tuto in two parts (right now in French, if I have time I will translate it)
- Step 1: http://www.pequi.eu/installation-de-sharetribe-sur-amazon-web-services-aws-etape-1-configuration-daws/
- Step 2: http://www.pequi.eu/installation-de-sharetribe-sur-amazon-web-services-aws-etape-2-parametrage-de-sharetribe/

I still have some bugs with "Can not find new transaction path to listing_id: X,..." but this is another issue.

**Comment by bingxie** [comment]
Thanks, this could be very useful. I used google translate to read. :)
