### ISSUE TITLE
Could not host in Azure cloud server

### ISSUE THREAD

**Issue by appcodr** [sharetribe/sharetribe#1150]
Hi, I hosted sharetribe in a Azure VM (Ubuntu 12.04). I was able to successfully setup everything but when I access the page from outside of the VM(i.e from laptop host) it gives error

Here is what i see in the terminal in the server
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2015-04-14 03:09:20] INFO  WEBrick 1.3.1
[2015-04-14 03:09:20] INFO  ruby 2.1.2 (2014-05-08) [x86_64-linux]
[2015-04-14 03:09:20] INFO  WEBrick::HTTPServer#start: pid=41735 port=3000
source=rack-timeout id=20312f012f025a1914933f7835581efb timeout=23000ms state=ready
Started GET "/" for *.*.*.* at 2015-04-14 03:09:21 +0000
Processing by HomepageController#index as 
Redirected to http://www.[redirectwebsite].com/

Filter chain halted as :fetch_community rendered or redirected
Completed 302 Found in 25.2ms (ActiveRecord: 3.9ms)
x.x.x.x GET / 302 Found HomepageController#index HTML 25.2 (DB 3.9, View 0.0) {} {}
source=rack-timeout id=b5b57508225d0ef47c8bc145665d60e8 timeout=23000ms service=321ms state=completed

I was trying with [myserver].cloudapp.net:3000 and it redirected to lajek.com. Is there something that Im missing? (I am new to Rails)

**Comment by appcodr** [comment]
This is very similar to this issue 
https://github.com/sharetribe/sharetribe/issues/631

But I cannot find that dashboard_subdomains setting anymore as it is removed..

**Comment by rap1ds** [comment]
I'm not familiar with Azure VM, so I can not give any tips regarding that environment.

I suggest you to check that your `config.yml` domain is setup correctly and the `community.ident` is correctly set.

Hope that helps.
