### ISSUE TITLE
Adding Payment processors

### ISSUE THREAD

**Issue by Vanhal** [sharetribe/sharetribe#1155]
Hi there, less of an issue and more of a feature request,

I was attempting to add stripe connect (https://stripe.com/docs/connect) as a payment processor instead of brain tree in the community but with the way that it is set up at the moment  references to either braintree or paypal are hard coded all over the place.

Might it be an idea to abstract out the entire payment processors as modules?
Alternatively add stripe as a payment option.

**Comment by pauldionbrooks** [comment]
I have not had a look at it yet, and replacing the whole module might be
the best option. Have you looked at the Dwolla API (
https://developers.dwolla.com/ )?  Seems like it would be most practical to
have a payments module that would support any, or even ALL payment
processors...

Or even multiple modules (http://www.silverearth.com/)?

Anxious to follow this conversation.

**Comment by rap1ds** [comment]
Hi! 

See #889 . @Kusti has explained the current situation there quite well.

Abstracting the payment gateways is definitely on the list of things to do in the future.

**Comment by valeda** [comment]
Any updates on stipe connect ?
