### ISSUE TITLE
NoMethodError in ListingsController#create

### ISSUE THREAD

**Issue by rkukuczka** [sharetribe/sharetribe#1170]
NoMethodError in ListingsController#create

undefined method `collect' for nil:NilClass
Rails.root: /Users/rafal/Documents/dev/PRD-EcoHub/Modules/Repos/Bitbucket/EcoHub4/sharetribe_2

Application Trace | Framework Trace | Full Trace
app/controllers/listings_controller.rb:236:in `create'
config/initializers/oneline_detailed_logging.rb:31:in `block (2 levels) in <top (required)>'
config/initializers/oneline_detailed_logging.rb:30:in `block in <top (required)>'
lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"JOcYRP6I37ecHE0nGMUbVnivRcYtLFvpVdNpznC9bLA=",
 "listing"=>{"title"=>"test",
 "price"=>"4",
 "currency"=>"USD",
 "description"=>"test listing",
 "valid_until(1i)"=>"2015",
 "valid_until(2i)"=>"7",
 "valid_until(3i)"=>"21",
 "origin"=>"Berlin",
 "origin_loc_attributes"=>{"address"=>"",
 "google_address"=>"",
 "latitude"=>"",
 "longitude"=>"",
 "location_type"=>"origin_loc"},
 "visibility"=>"this_community",
 "privacy"=>"public",
 "current_community_id"=>"1",
 "category_id"=>"1",
 "listing_shape_id"=>"1"},
 "button"=>"",
 "locale"=>"en"}

**Comment by RileySpiller** [comment]
That particular line has to do with getting the images from the listing. I'd double check any install steps that deal with images in general.

**Comment by rap1ds** [comment]
Are you using S3? Have you configured S3 bucket correctly? Is the image successfully uploaded to your S3 bucket?

Can you reproduce the issue? Please add the exact steps to reproduce the error to the issue description. You can use the issue template https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md Thanks!

**Comment by rap1ds** [comment]
Inactive. Closing.
