### ISSUE TITLE
switch market place from selling to renting

### ISSUE THREAD

**Issue by jigartank** [sharetribe/sharetribe#1191]
Hello,

I've setup sharetribe on ec2 instance. During initial configuration I set the marketplace to selling instead of renting.
Is there a way I can change it now ?
Please suggest.

**Comment by rap1ds** [comment]
Hi!

We are about to add a new page to the admin site which allows you to edit the order types (selling, renting, requesting etc.). That will be available next week.

**Comment by jigartank** [comment]
ok thanks.

I'll await that update.
