### ISSUE TITLE
Login fails on fresh sharetribe install

### ISSUE THREAD

**Issue by mparramont** [sharetribe/sharetribe#1192]
I just installed sharetribe on EC2, you can see it working [here](http://54.191.173.8:8080/en).

I can create users and they show on the database, but I can't log in with any of them.
When I log in, it seems that it logs the user successfully, and then the user is redirected to `app/controllers/community_memberships_controller.rb` where it checks again if the user is logged in, and there it is not logged in anymore.

I can reproduce it on a fresh development install of sharetribe as well.

Any idea why this could be happening? Thanks!

**Comment by math29** [comment]
Did you try to access to your subdomain ? 
What did you use to allow accessing site on the 8080 port ?

**Comment by rap1ds** [comment]
Thanks for reporting the issue! This is a bug in the code. The app doesn't work well if you are running it from an IP address and not using a domain name. The cookies get mixed somehow up and that's why the login doesn't work.

If you are able to reproduce the issue, could you please add the exact steps to the issue description? You can use the issue template, https://github.com/sharetribe/sharetribe/blob/master/ISSUE_TEMPLATE.md Thanks!

Quick solution for your issue is to setup a DNS name, and change the `domain` configuration in `config.yml` to match the DNS name.

However, I think that this is something that should be fixed on the code side as well.

**Comment by mparramont** [comment]
I'm not using Sharetribe anymore, leaving this open because it looks like a real bug.

**Comment by movstox** [comment]
Guys, when running fresh install from IP, I was able to login via Firefox. However, Chrome or Chromium doesn't work that well.

**Comment by JahBrewski** [comment]
I'm having the same experience as @movstox -- Can login via Firefox, bug not Chrome.

**Comment by JerryChr** [comment]
Just finished the setup and got the exact same bug - and as @movstox and @JahBrewski it also works in FireFox but not in Chrome.

**Comment by Amerlander** [comment]
I have the same problem. But in Chrome and Firefox as well.

The server shows an CSRF-Tokken-Error:

```
INFO source=rack-timeout id=e423989497fec827cb6b87e0b3cb38e7 timeout=23000ms state=ready
DEBUG source=rack-timeout id=e423989497fec827cb6b87e0b3cb38e7 timeout=23000ms service=0ms state=active
WARN {"request_uuid":"8a6967be627148fcab02ff6443c79789","tag":"controller","free":"WARNING: Can't verify CSRF token authenticity"}
INFO {"method":"POST","path":"/de/sessions","format":"html","controller":"sessions","action":"create","status":302,"duration":154.78,"view":0.0,"db":22.81,"location":"http://username.rasalhague.uberspace.de/de/community_memberships/new","params":{"utf8":"✓","authenticity_token":"W2Pcvc8cfrBnh0Is9s/P59feUL2xH5EvGDZ7po4SAGM=","person":{"login":"Nutzer","password":"[FILTERED]"},"button":"","locale":"de"},"host":"username.rasalhague.uberspace.de","community_id":1,"current_user_id":"bHflgGL5Sr5yaauLqaDi7j","request_uuid":"8a6967be627148fcab02ff6443c79789"}
INFO source=rack-timeout id=e423989497fec827cb6b87e0b3cb38e7 timeout=23000ms service=176ms state=completed
INFO source=rack-timeout id=ab3cae408701e7e4822bfd8b0185791a timeout=23000ms state=ready
DEBUG source=rack-timeout id=ab3cae408701e7e4822bfd8b0185791a timeout=23000ms service=0ms state=active
INFO {"method":"GET","path":"/de/community_memberships/new","format":"html","controller":"community_memberships","action":"new","status":302,"duration":16.75,"view":0.0,"db":1.25,"location":"http://username.rasalhague.uberspace.de/de/login","params":{"locale":"de"},"host":"username.rasalhague.uberspace.de","community_id":1,"current_user_id":"","request_uuid":"ea602b681a7d91063041ec24b34c907a"}
INFO source=rack-timeout id=ab3cae408701e7e4822bfd8b0185791a timeout=23000ms service=39ms state=completed
INFO source=rack-timeout id=1371b5dac9868028f65244b3f8cb7ebf timeout=23000ms state=ready
DEBUG source=rack-timeout id=1371b5dac9868028f65244b3f8cb7ebf timeout=23000ms service=0ms state=active
INFO {"method":"GET","path":"/de/login","format":"html","controller":"sessions","action":"new","status":200,"duration":47.42,"view":33.73,"db":1.96,"params":{"locale":"de"},"host":"username.rasalhague.uberspace.de","community_id":1,"current_user_id":"","request_uuid":"93d3d05146933f3189da4ac11eb92213"}
INFO source=rack-timeout id=1371b5dac9868028f65244b3f8cb7ebf timeout=23000ms service=65ms state=completed
```

**Comment by bipashant** [comment]
I felt the same issues many times. I need to use incognito mode to solve this but even it doesn't works some time

**Comment by rap1ds** [comment]
@Amerlander @bipashant Thanks for reporting! To make it easier to debug, could you please tell me:

1. What's the host of the server you using (for @Amerlander I can see that it's nutzername.rasalhague.uberspace.de, what's yours @bipashant ?)
2. What's the value of the `domain` configuration in `config.yml`?
3. What's the value of `ident` and `domain` in `communities` table for the marketplace you are using?

Also, if you are able to list the exact steps to reproduce the issue, that would be helpful and highly appreciated.

**Comment by Amerlander** [comment]
Hey, thank you for reply!

1. yes, its nutzername.rasalhague.uberspace.de (in fact the first part is different, but its my username, so I replaced it)
2. `domain: "nutzername.rasalhague.uberspace.de"`
3. ident is `handcrafted-life-holidays` and domain is `nutzername.rasalhague.uberspace.de`

I wasnt able to reproduce it on my VirtualMachine till now, there it works all the time.
But on Uberspace I reproduce it every time and I dont know why, the steps are the same like in my VM. If you want I can give you access to an Uberspace Account for testing.

**Comment by thiyagarajan** [comment]
Hey, My website is http://www.mistersafer.com/ and login not working in Chrome but working fine in FireFix. 

help appreciated

**Comment by blacktea3937** [comment]
facing the same issue here. Login in chrome always fails.

**Comment by rap1ds** [comment]
@thiyagarajan @blacktea3937 Make sure you are using a host name, not an IP, and that the host name you use matches your configurations (the domain value in the config.yml). If you use an IP address (as @thiyagarajan is doing) the login will fail.

**Comment by blacktea3937** [comment]
Thanks @rap1ds , but if this is the case, does it mean that during the process of development, if the IP is not assigned a hostname, there is no way to test the login functions?

**Comment by aivils** [comment]
I have same issue. I add single line in the /etc/hosts

```
127.0.0.1 sharetribe.me
```

and i add according line in the config.yml

```
  domain: "sharetribe.me"
```

I test my site on localhost and it works when i access site via sharetribe.me:3000. Dot in the domain name is crucial!!!

@blacktea3937 and others  can replace IP address in /etc/hosts with right one. 127.0.0.1 is just a special case. Any IP can be used.

**Comment by woto** [comment]
Confirming, got same issue with login until has added correct lines in /etc/hosts

**Comment by rap1ds** [comment]
Instead of adding the host to /etc/hosts, you can also use the domain http://lvh.me:3000 as suggested in the installation instructions.

lvh.me redirects to localhost

**Comment by rincona22** [comment]
Hi @rap1ds. I follow all steps from installation instruction but login still fails. I haven't been able to set up config.yml using the domain http://lvh.me:3000. May you please show me a detailed example? 
![captura de pantalla 2016-03-24 a las 1 42 39 a m](https://cloud.githubusercontent.com/assets/17840927/14010279/cc10e67a-f161-11e5-9f10-4b2626de24f1.png)

Thank you for your help

**Comment by rap1ds** [comment]
Hi @rincona22 . You configurations look good. So now if you go to http://lvh.me:3000 you should be able to login. If not, try to clean up your browser cookies. If that doesn't help, then there might be some other bug I'm not aware of. Could you post more details about the issue you are facing? What's the Sharetribe version you are using? Can you see any error messages?

**Comment by rincona22** [comment]
hi @rap1ds . Thank you for your reply. Here a screenshot of http://lvh.me:3000 (in Spanish)
![captura de pantalla 2016-03-24 a las 2 24 28 a m](https://cloud.githubusercontent.com/assets/17840927/14010956/17042b8c-f168-11e5-8832-d3b1bd3819d7.png)
But if I use http://localhost:3000/ loads correctly home . Here a screenshot
![captura de pantalla 2016-03-24 a las 2 25 15 a m](https://cloud.githubusercontent.com/assets/17840927/14010974/53956d2c-f168-11e5-93ef-0201fce4fcdd.png)
I am trying to login as admin to explore customization options, but after the following screen:
![captura de pantalla 2016-03-24 a las 2 25 42 a m](https://cloud.githubusercontent.com/assets/17840927/14011045/2c35906c-f169-11e5-8bd9-7088e48313a7.png)

It goes back to homescreen without login. In fact as @mparramont said, it seems it logs in and immediately out. Here logs from rails server: 
[log.txt](https://github.com/sharetribe/sharetribe/files/187404/log.txt)

Once again, thank you for your help.

**Comment by rap1ds** [comment]
@rincona22 Thanks for the screenshots! The login (and the whole application) definitely doesn't work if the `domain` configuration in `config.yml` (or `config.defaults.yml`) doesn't match to the domain you are actually using. Your application is configured to be in `lvh.me`, but you are using `localhost`. So that's the issue.

I'd try to first figure out why lvh.me is not working.

**Comment by rincona22** [comment]
@rap1ds  thank you for your time and help. It is working with localhost. Let me know if you figured out why lvh.me does not work.

**Comment by bipashant** [comment]
@rincona22  Another option is you can also register your own domain in host file and use it.
but there will be lots of hassle if you use url like `localhost:3000` .

**Comment by karibuTW** [comment]
Hello guys,
I am having the same issue actually.
It works fine in Firefox, but not with Chrome.

I have set the domain in my config.yml and in the database (domain/use domain)
I have also added 1 line in my /etc/hosts with 127.0.0.1 mydomain.tld but cannot make it work.

Any suggestions?

**Comment by zinovyev** [comment]
I've got the same error too. Can not log in using Chrome, but in Firefox it works fine.

**Comment by karibuTW** [comment]
In my case, the issue came from the HTTPS connection. Using HTTP, no issue, but if I force SSL connection, then I face this issue. I was not able to solve that point..
I have only put the HTTPS optional in my case. It works, but it is not perfect.

Probably some issue with the redirection / cookies or so.

PS: I use let's encrypt SSL certificate

**Comment by zinovyev** [comment]
I have this issue when using HTTP with the source code from from master branch.

**Comment by zinovyev** [comment]
Ah. That's was my inadvertence. I've forgot to set the `X-Forwarded-Host` in my Nginx configuration.
