### ISSUE TITLE
confirmation email problem 

### ISSUE THREAD

**Issue by khohck** [sharetribe/sharetribe#1193]
Hi 

I've setup a domain name (eg : test1.com) and the confirmation email that I get for the url 
is always test1.test1.com/en/people/confirmation?

my config.yml :
# NOTE: Do not include http(s) here, or subdomains, just the top level domain, like "sharetribe.com" for example
  domain: "test1.com"

How do I fix this to get the confirmation email to work properly.

Thanks much !

**Comment by RileySpiller** [comment]
I'm having the same issue. Seeking the answer now also.

**Comment by RileySpiller** [comment]
I was able to fix it by putting "www.test1.com" in the `domain` field of the `communities` database. However I'm not sure this is how you're supposed manage this.

**Comment by khohck** [comment]
I ended up fixing my dns forwarder.:(

I'm starting my server this way :
nohup rails server -e production &

is there a better way to start and stop this process ?

I realise the upload images stop working after 1 day and the emails stop sending out too .
Does any one have the same issues ?

TIA
