### ISSUE TITLE
sharetribe running on linux kept crashing

### ISSUE THREAD

**Issue by khohck** [sharetribe/sharetribe#1222]
The latest ver of sharetribe on linux keep crashing.

The email stop working.
The image upload stop working too.

I had to restart the process everyday.

Please help.

**Comment by khohck** [comment]
tail -f production.log 
DalliError: No server available
DalliError: No server available
source=rack-timeout id=95e270c97adc13a0873a62b8b608cbdc timeout=23000ms service=2ms state=completed
source=rack-timeout id=e47947b27126e04c5191de1ea7527147 timeout=23000ms state=ready
DalliError: No server available
DalliError: No server available
DalliError: No server available

**Comment by ovan** [comment]
@khohck Is this new behavior? Has some older version of Sharetribe worked in your setup? The error you see, DalliError: No server available suggests there's no connection with a memcached server. Do you have a working memcached setup? We changed the failover settings a bit just this week so I'm wondering if this is related.

**Comment by khohck** [comment]
I just setup shatetribe 2 weeks back following the setup instructions provided. Is memcache required or mandatory ?

Do u have the steps to disable memcache in sharetribe, if not how do i go about setting up memcache and getting this to work w my setup.

Thanks & appreciate your reply.

**Comment by ovan** [comment]
Yes, memcached is required with the default production configuration. You can alter the environment configurations to use e.g. memory store with rails cache but in that case make sure to run only one instance since you're not using a shared cache. More instructions about general rails caching and configuration e.g. here: http://guides.rubyonrails.org/caching_with_rails.html#configuration

**Comment by khohck** [comment]
Hi 

I'm new to this.
Could you elaborate how do I go about altering memory store with rails cache.

thanks

**Comment by Sultan91** [comment]
> tail -f production.log
> DalliError: No server available
> DalliError: No server available
> source=rack-timeout id=95e270c97adc13a0873a62b8b608cbdc timeout=23000ms service=2ms state=completed
> source=rack-timeout id=e47947b27126e04c5191de1ea7527147 timeout=23000ms state=ready
> DalliError: No server available
> DalliError: No server available
> DalliError: No server available

`apt-get install memcached`
