### ISSUE TITLE
Error when requesting a free listing

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#1310]
I've just updated the sharetribe to the latest commit, and now i am getting this error in a free listing:

NoMethodError - undefined method `person_transactions_path' for #<TransactionsController:0x0000010eafccd8>:
  app/controllers/transactions_controller.rb:358:in `render_free'
  app/controllers/transactions_controller.rb:36:in `block in new'
  app/services/result.rb:52:in `on_success'
  app/controllers/transactions_controller.rb:29:in `new'

I don't know if it's an existent bug, i will try to fix it, but if you know some, would be helpful

thanks

**Comment by rap1ds** [comment]
Did you find out anything? This sounds something that may be a bug in the code.

**Comment by rap1ds** [comment]
Closing this as inactive.
