### ISSUE TITLE
Design part not working

### ISSUE THREAD

**Issue by pablorodriguezgonzalez** [sharetribe/sharetribe#1318]
Hello!

I'm testing Sharetribe to see if it fits our needs, but I'm facing some problem when changing something like logo, colors, etc, in admin as isn't working at all and the server stops.

I'm using Debian 7, Ruby 2.1.2 and the rails server throws this just after upload the logo and click "Save": (example.com it's ommited)

[2015-07-04 09:44:48] INFO  WEBrick::HTTPServer#start: pid=19982 port=3000
INFO source=rack-timeout id=ea305f5430e6bfdab43e6d81a836c3c6 timeout=23000ms state=ready
DEBUG Cache read: http://example.com:3000/en/admin/communities/1/edit_look_and_feel?
DEBUG Dalli::Server#connect 127.0.0.1:11211
DEBUG source=rack-timeout id=ea305f5430e6bfdab43e6d81a836c3c6 timeout=23000ms service=6ms state=active
INFO 127.0.0.1:11211 failed (count: 0)
ERROR DalliError: No server available
DEBUG Cache read: /translation_service/community/1
DEBUG Dalli::Server#connect 127.0.0.1:11211
INFO 127.0.0.1:11211 failed (count: 1)
WARN 127.0.0.1:11211 is down
ERROR DalliError: No server available
DEBUG Cache generate: /translation_service/community/1
DEBUG Cache write: /translation_service/community/1
DEBUG down_retry_delay not reached for 127.0.0.1:11211 (0.988 seconds left)
ERROR DalliError: No server available

but others like colors appears to be saved, and nothing changes too :-)

DalliError is because of memcached, but still isn't being updated and server face some problems.

Any help would be appreciated, thanks in advance.

**Comment by bingxie** [comment]
Did you start the delayed_job like this: rake jobs:work.

**Comment by pablorodriguezgonzalez** [comment]
Yes bingxie, with production parameter:

rake RAILS_ENV=production jobs:work

**Comment by malachaifrazier** [comment]
What ENV are you using? Any logs showing up?

**Comment by pablorodriguezgonzalez** [comment]
Hello malachaifrazier,

Debian 7, Ruby 2.1.2 and default server that comes to serve the pages, plus MariaDB; I don't know where to find another logs except the one I've put, can you help with that?

Best.

**Comment by rap1ds** [comment]
The stack trace you posted isn't very helpful in this case.

Can you see any logs from the worker? What do you mean by "the server stops"? Does it crash or how does it stop? Freeze? Are you using S3? Have you configured S3 properly? Are you able to reproduce the issue? Can you describe the exact steps to reproduce the issue? You can use the issue template: https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md

**Comment by rap1ds** [comment]
Inactive. Closing.
