### ISSUE TITLE
rake assets:precompile not working.

### ISSUE THREAD

**Issue by yo-gen** [sharetribe/sharetribe#1329]
I am trying to deploy sharetribe on the cloud9 ide. When i use rake assets:precompile, memory limit is hit and the process is getting killed. I am using 512MB ram, with 1GB disk space. I do not currently wish to increase my memory size. Is there some workaround?

The error messages - 

Digest::Digest is deprecated; use Digest
/usr/local/rvm/rubies/ruby-2.1.2/bin/ruby /usr/local/rvm/gems/ruby-2.1.2/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
Digest::Digest is deprecated; use Digest
AssetSync: using /home/ubuntu/workspace/config/initializers/asset_sync.rb

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

INFO Compiled jquery.js  (3ms)  (pid 850)
INFO Compiled jquery-ui-1.9.2.custom.js  (0ms)  (pid 850)
INFO Compiled jquery_ujs.js  (0ms)  (pid 850)
INFO Compiled jquery.form.js  (1ms)  (pid 850)
INFO Compiled jquery.validate.js  (1ms)  (pid 850)
INFO Compiled jquery.pageless.js  (0ms)  (pid 850)
INFO Compiled jquery.autosize-min.js  (0ms)  (pid 850)
INFO Compiled jquery.lightbox_me.js  (2ms)  (pid 850)
INFO Compiled jquery.transit.min.js  (0ms)  (pid 850)
INFO Compiled jquery.placeholder.js  (0ms)  (pid 850)
INFO Compiled jquery.ui.widget.js  (100ms)  (pid 850)
INFO Compiled load-image.min.js  (0ms)  (pid 850)
INFO Compiled canvas-to-blob.min.js  (0ms)  (pid 850)
INFO Compiled jquery.fileupload.js  (1ms)  (pid 850)
INFO Compiled jquery.fileupload-process.js  (0ms)  (pid 850)
INFO Compiled jquery.fileupload-validate.js  (0ms)  (pid 850)
INFO Compiled jquery.fileupload-image.js  (0ms)  (pid 850)
INFO Compiled selectize-standalone.js  (1ms)  (pid 850)
INFO Compiled datepicker/bootstrap-datepicker.js  (1ms)  (pid 850)
INFO Compiled jquery.iframe-transport.js  (0ms)  (pid 850)
INFO Compiled fastclick.js  (0ms)  (pid 850)
INFO Compiled relocate.js  (0ms)  (pid 850)
INFO Compiled minwidth.js  (0ms)  (pid 850)
INFO Compiled infobubble.js  (0ms)  (pid 850)
INFO Compiled sharetribe_common.js  (0ms)  (pid 850)
INFO Compiled Bacon.js  (2ms)  (pid 850)
INFO Compiled Bacon.jquery.min.js  (0ms)  (pid 850)
INFO Compiled lodash.min.js  (1ms)  (pid 850)
INFO Compiled utils.js  (0ms)  (pid 850)
INFO Compiled kassi.js  (1ms)  (pid 850)
INFO Compiled googlemaps.js  (0ms)  (pid 850)
INFO Compiled map_label.js  (0ms)  (pid 850)
INFO Compiled homepage.js  (0ms)  (pid 850)
INFO Compiled order_manager.js  (0ms)  (pid 850)
INFO Compiled ajax_status.js  (0ms)  (pid 850)
INFO Compiled admin/expiration_notice.js  (0ms)  (pid 850)
INFO Compiled admin/custom_fields.js  (0ms)  (pid 850)
INFO Compiled admin/categories.js  (0ms)  (pid 850)
INFO Compiled admin/manage_members.js  (0ms)  (pid 850)
INFO Compiled admin/menu_links.js  (0ms)  (pid 850)
INFO Compiled admin/community_customizations.js  (0ms)  (pid 850)
INFO Compiled admin/listing_shapes.js  (0ms)  (pid 850)
INFO Compiled admin/settings.js  (0ms)  (pid 850)
INFO Compiled payment_math.js  (0ms)  (pid 850)
INFO Compiled dropdown.js  (0ms)  (pid 850)
INFO Compiled jquery.nouislider.js  (0ms)  (pid 850)
INFO Compiled range_filter.js  (0ms)  (pid 850)
INFO Compiled translations.js  (0ms)  (pid 850)
INFO Compiled image_uploader.js  (0ms)  (pid 850)
INFO Compiled image_carousel.js  (0ms)  (pid 850)
INFO Compiled thumbnail_stripe.js  (0ms)  (pid 850)
INFO Compiled listing.js  (0ms)  (pid 850)
INFO Compiled listing_images.js  (0ms)  (pid 850)
INFO Compiled datepicker.js  (0ms)  (pid 850)
INFO Compiled follow.js  (0ms)  (pid 850)
INFO Compiled paypal_account_settings.js  (0ms)  (pid 850)
INFO Compiled transaction.js  (0ms)  (pid 850)
INFO Compiled listing_form.js  (0ms)  (pid 850)
INFO Compiled application.js  (423ms)  (pid 850)
rake aborted!
ExecJS::RuntimeError: Killed

  (in /home/ubuntu/workspace/app/assets/javascripts/application.js)/usr/local/rvm/gems/ruby-2.1.2/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:142:in `exec_runtime'
/usr/local/rvm/gems/ruby-2.1.2/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:28:in `block in exec'
/usr/local/rvm/gems/ruby-2.1.2/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:41:in `compile_to_tempfile'
/usr/local/rvm/gems/ruby-2.1.2/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:27:in `exec'
/usr/local/rvm/gems/ruby-2.1.2/gems/uglifier-1.3.0/lib/uglifier.rb:100:in `compile'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/compressors.rb:74:in `compress'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/processing.rb:265:in `block in js_compressor='
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/processor.rb:29:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/processor.rb:29:in `evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/context.rb:193:in `block in evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/bundled_asset.rb:26:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:19:in `block in compile'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:219:in `block in each_logical_path'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each_entry'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:204:in `block in each_file'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each_file'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.2.3/lib/sprockets/base.rb:217:in `each_logical_path'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:18:in `compile'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/assets.rake:56:in `internal_precompile'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/usr/local/rvm/rubies/ruby-2.1.2/bin/ruby ...]
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-3.2.21/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

**Comment by math29** [comment]
I have exactly the same problem ! Did you find any thing about that ? :)

**Comment by rap1ds** [comment]
I'm not familiar with cloud9 IDE, so I can not give any tips regarding that environment.

Did you btw. ran the `rake assets:precompile` on your local development machine or on the cloud9 machine?

How did you come up that it's a memory issue? I couldn't find any mentioning about memory in the stack trace. Did I miss something?

**Comment by math29** [comment]
For my mind I had this error with the S3 of AWS because of a CORS error of my part.

**Comment by yo-gen** [comment]
I could understand that i am facing a memory issue, because cloud9 ide has an interface where i can view current memory usage. As soon as I tried precompile assets, the memory usage peaked, and the process got killed. 
However I have started using Koding and my production server also has enough memory, so I no longer face this issue. Thanks anyways :)
