### ISSUE TITLE
Non-US can use Braintree payment gateway 

### ISSUE THREAD

**Issue by vshnusuman** [sharetribe/sharetribe#1330]
We're planning to use Sharetribe open source code and do the required customization. I just read out in the payment section that to start with Braintree you need to have a legal business in The United States. So Non-US can not use it? 
If no, then can we integrate PayPal using open source code? for that I have my eCommerce developer and he will integrate PayPal or Stripe.
Please let me know what is the best way to resolve above problem.
Thank you.

**Comment by yo-gen** [comment]
edit the word sue to use in your issue. That gave me a mini heart-attack :stuck_out_tongue_winking_eye:

**Comment by vshnusuman** [comment]
haha @yo-gen just corrected!

**Comment by Hermi999** [comment]
Have a look at https://www.braintreepayments.com/faq question "Is Braintree available in my country?":
... Braintree is available for merchants in the United States, Canada, Australia, Europe, Singapore, Hong Kong, Malaysia and New Zealand. In legal terms, you have to be domiciled in a supported country....

**Comment by math29** [comment]
Hi !
I'm in the same case than you @vshnusuman , and looking for enabling the breantree solution in Sharetribe. My company is located in Europe.
Some news about that ? :)

**Comment by vshnusuman** [comment]
Hi @math29 
As far as I collected the information, You have to remove existing PayPal or Braintree files and then integrate either PayPal or Braintree or Stripe from scratch as per your requirements. I am doing this.
But still, I am not fully sure if there is another alternate so DO confirm at your end.
Thanks,
Vishnu

**Comment by math29** [comment]
Re @vshnusuman ,
I come back to you just to say that I used my custom Braintree developed solution and it works very well ;)
Thanks for your answer
Math

**Comment by vshnusuman** [comment]
Hey @math29 
That's great to know that you achieved your goal.
cheers!
Vishnu

**Comment by delblues** [comment]
Hi @math29,

I,m trying to use sharetribe fomr Brazil, but I dont know how to integrate some payment gateway here, as long Braintree is not supported here. Could you help me with this custom solution in this case? 

@rap1ds  can you also help with this? Is it posible to integrate sharetribe with others payment gateways, as ?  

thanks
