### ISSUE TITLE
INBOX view - Fatal error

### ISSUE THREAD

**Issue by ptzool** [sharetribe/sharetribe#1375]
Hi,

I sent a message for a test user and when I watch the message (http://domain.tld3000/en/testuser/inbox) I get the following message. 

What is the problem?

```
FATAL 
ArgumentError (argument out of range):
  app/utils/time_utils.rb:12:in `utc_str_to_time'
  app/utils/entity_utils.rb:141:in `block in <module:EntityUtils>'
  app/utils/entity_utils.rb:237:in `call'
  app/utils/entity_utils.rb:237:in `block in transform'
  app/utils/entity_utils.rb:236:in `each'
  app/utils/entity_utils.rb:236:in `reduce'
  app/utils/entity_utils.rb:236:in `transform'
  app/utils/entity_utils.rb:243:in `block in transform_all'
  app/utils/entity_utils.rb:242:in `each'
  app/utils/entity_utils.rb:242:in `reduce'
  app/utils/entity_utils.rb:242:in `transform_all'
  app/utils/entity_utils.rb:263:in `transform_and_validate'
  app/utils/entity_utils.rb:370:in `with_result'
  app/utils/entity_utils.rb:325:in `build'
  app/services/marketplace_service/inbox.rb:150:in `block in query_inbox_data'
  app/services/marketplace_service/inbox.rb:142:in `map'
  app/services/marketplace_service/inbox.rb:142:in `query_inbox_data'
  app/services/marketplace_service/inbox.rb:45:in `inbox_data'
  app/controllers/inboxes_controller.rb:14:in `show'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
```

**Comment by rap1ds** [comment]
Thanks for the report!

We haven't seen this issue before, so it's hard to tell what's the problem. Could you provide some additional information about the issue? What did you do exactly? Are you able to reproduce the issue? Can you describe exact steps to reproduce it?

Thanks!

**Comment by ptzool** [comment]
Hi,

I found a workaround. I commented out this line [:last_activity_at, :utc_str_to_time, :mandatory] in app/services/marketplace_service/inbox.rb. 

The problem is the next function (utc_str_to_time) I think.

Regards,

Zoli

**Comment by rap1ds** [comment]
Ookey... well commenting out the like is definitely a workaround, not a fix 😊 There's a good reason why that line of code exists there 😉

I'm still interested to hear what we're the steps that you did before this error occured?

We've seen the error with the `last_activity_at` a couple of times, and usually it occured because you have started a new transaction which doesn't contain any activity, i.e. message, payment, etc. This shouldn't happen normally, but may happen due to some bug.

**Comment by rap1ds** [comment]
Inactive. Closing the ticket.

**Comment by JahBrewski** [comment]
Hmm. I'm getting this bug as well.
