### ISSUE TITLE
Login with Facebook always uses the port 3000

### ISSUE THREAD

**Issue by congkinh** [sharetribe/sharetribe#1394]
Hi,

I deployed a version of sharetribe in production mode with integrating Facebook. I use nginx for reverse proxy from 80 (443 later) to 3000. However, when I logged in with my Facebook test account, the redirect_uri was using the port 3000 instead of 80. Could anyone of you tell me how to fix it? The following pattern was received by logging in with Facebook:
```
:3000/people/auth/facebook/callback?code=
```

Best regards,
Kinh

**Comment by ptzool** [comment]
Did you change the redirect URL on Facebook developer page? (Valid OAuth redirect URIs)

**Comment by congkinh** [comment]
Hi @ptzool,
 
Yesterday, I let it be empty. I didn't configure anything for this. So, port 3000 was somehow fixed in code itself.

I changed Valid OAuth redirect URIs on Facebook  with `http://example.com/people/auth/facebook/callback` (I supposed that mydomain was `example.com`). However, I still received the `redirect_uri` with port 3000 from URL. But, it didn't work while I was using this redirect_uri. It said that there was invalid configuration.

**Comment by rap1ds** [comment]
What's the value for `domain` in `config.yml`?

**Comment by congkinh** [comment]
Hi @rap1ds,

I used the port 80. I already tested for both domain:80 and domain (without port), the redirect_uri was the same in both cases.

**Comment by congkinh** [comment]
Hi all,

I found out that this issue came from OmniAuth. Actually, I don't know how to solve it in general. But in my case, I just added the following line:
```
OmniAuth.config.full_host = "https://www" + APP_CONFIG.domain
```
just after the line 156 in the file https://github.com/sharetribe/sharetribe/blob/master/config/application.rb.

If I were a Rails developer, I would check whether the current URL is using HTTPS or not.

**Comment by rap1ds** [comment]
Hi @congkinh 

This sounds interesting. It could be a bug in our code. However, I would need a little bit more information to debug this further.

Can you provide exact steps how to reproduce the issues? That would be helpful.

You can also use the Issue Template, it's here: https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md

**Comment by congkinh** [comment]
Hi @rap1ds,

The following information would be helpful for you:

##### Sharetribe Version:
8fb1611a0d561c5ac1c76e9660170d13a63e974f


##### Environment:

Debian 7 and Amazon S3

##### Server mode:

Production

##### Description:

Signing in with Facebook account always redirects to the 3000 port.

##### Steps To Reproduce:
- Used a reverse proxy (nginx) to map from HTTPS (outside) to the port 3000 (inside)
- Created a Facebook application:
     + Activated Web OAuth Login & Client OAuth Login
     + Filled in `App Domains`
     + Didn't fill in `redirect_uri`
- Deployed `Sharetribe`
- Signed in with a Facebook account

##### Expected Result:

I was expected to be able to continue using HTTPS after signing in with a Facebook account.

##### Actual Result:

The `redirect_uri` contained the 3000 port. That meant the URL after signing in with a Facebook account contained the port 3000. In other words, it meant I couldn't continue using HTTPS.

##### Additional information

**Comment by rap1ds** [comment]
@congkinh Thanks for the information! Right now I don't have time to dig into this issue, but I'll leave the issue open since it looks like something that maybe is a bug (or at least unexpected behaviour) in the code.

**Comment by rap1ds** [comment]
Closing as inactive
