### ISSUE TITLE
Download Images

### ISSUE THREAD

**Issue by math29** [sharetribe/sharetribe#1405]
Hi everybody,

I installed sharetribe on a AWS EC2/RDS/S3 server. Everythings works except the image downloading.
When I try to download an image it goes to 100% and then let me see : "Erreur lors de l'envoi d'image" = "Error during the image sending". 
I have this error that appear : 

INFO source=rack-timeout id=0d36edf7ec746925608e1e8b1a643772 timeout=23000ms state=ready
DEBUG Cache read: http://try-my-home.trymyhome.xyz:3000/fr/listing_images/add_from_url?
DEBUG Dalli::Server#connect 127.0.0.1:11211
INFO 127.0.0.1:11211 failed (count: 4)
DEBUG 127.0.0.1:11211 is still down (for 336.670 seconds now)
ERROR DalliError: No server available
DEBUG source=rack-timeout id=0d36edf7ec746925608e1e8b1a643772 timeout=23000ms service=1ms state=active
DEBUG Cache read: /translation_service/community/1
DEBUG down_retry_delay not reached for 127.0.0.1:11211 (0.943 seconds left)
ERROR DalliError: No server available
DEBUG Cache generate: /translation_service/community/1
DEBUG Cache write: /translation_service/community/1
DEBUG down_retry_delay not reached for 127.0.0.1:11211 (0.940 seconds left)
ERROR DalliError: No server available
here
INFO {"method":"PUT","path":"/fr/listing_images/add_from_url","format":"*/*","controller":"listing_images","action":"add_from_url","status":500,"error":"SystemExit: here","duration":47.27,"params":{"filename":"IMG_LOGO_400x400.jpg","path":"https://trymyhome.s3.amazonaws.com/uploads/listing-images/2015/8/20150819T1353Z-a85c6065557a4d4b76361ce349c06269/1/img_logo_400x400.jpg","locale":"fr"},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}
DEBUG ** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? true         
  API key set? false
FATAL 
SystemExit (here):
  app/controllers/listing_images_controller.rb:79:in `abort'
  app/controllers/listing_images_controller.rb:79:in `new_image'
  app/controllers/listing_images_controller.rb:68:in `add_image'
  app/controllers/listing_images_controller.rb:29:in `add_from_url'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

INFO {"method":"PUT","path":"/500","format":"*/*","controller":"listing_images","action":"add_from_url","status":500,"duration":6.58,"view":1.75,"db":2.07,"params":{"filename":"IMG_LOGO_400x400.jpg","path":"https://trymyhome.s3.amazonaws.com/uploads/listing-images/2015/8/20150819T1353Z-a85c6065557a4d4b76361ce349c06269/1/img_logo_400x400.jpg","locale":"fr"},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}
INFO source=rack-timeout id=0d36edf7ec746925608e1e8b1a643772 timeout=23000ms service=115ms state=completed

Did someone have the same problem ? :)

**Comment by math29** [comment]
Images are sent to the S3 and listing_images are created, this is just the "downloading" step which set the differents fields of listing_image (like name, size etc...) that don't works.
I checked 3 times my production configuration ...
Any ideas ? :)

**Comment by rap1ds** [comment]
Do you have a worker running? The line 79 in `listing_images_controller` trying to save the Delayed Job description to the database and apparently it fails.

**Comment by math29** [comment]
Yes I start it with : 
`bundle exec rake RAILS_ENV=production jobs:work`
after starting sphinx.

The worker do this kind of action when Sharetribe send emails : 
`[Worker(host:ip-172-31-28-95 pid:27061)] Starting job worker
DEBUG Cache read: /translation_service/community/1
DEBUG Dalli::Server#connect 127.0.0.1:11211
INFO 127.0.0.1:11211 failed (count: 0)
ERROR DalliError: No server available
DEBUG Cache generate: /translation_service/community/1
DEBUG Cache write: /translation_service/community/1
DEBUG Dalli::Server#connect 127.0.0.1:11211
INFO 127.0.0.1:11211 failed (count: 1)
WARN 127.0.0.1:11211 is down
ERROR DalliError: No server available
INFO 
Sent mail to mathieu.allain29@gmail.com (48.5ms)
[Worker(host:ip-172-31-28-95 pid:27061)] SendWelcomeEmail completed after 3.9977
[Worker(host:ip-172-31-28-95 pid:27061)] 1 jobs processed at 0.2456 j/s, 0 failed ...`

But no action when I download images ! :o

**Comment by math29** [comment]
Ok my bad, my code was doing this.
Thanks again and really sorry about the inconvenience !
