### ISSUE TITLE
`process_in_background': undefined method `[]=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by 419371274** [sharetribe/sharetribe#1425]
##### Sharetribe Version:
git rev-parse HEAD
933409d23b917c3d34ffaef918c91cd6dae9e75c
##### Environment:
ubuntu14.04

##### Server mode:

either development or production mode didn't work
this exapmle i use the production mode 
##### Description:
i follow  the instruction of Installation every step except for" gem install mailcatcher",the other  steps works  fine

##### Steps To Reproduce:
bundle exec rake RAILS_ENV=production db:schema:load
bundle exec rake RAILS_ENV=production ts:index
bundle exec rake RAILS_ENV=production ts:start
bundle exec rake assets:precompile
bundle exec rake RAILS_ENV=production jobs:work
bundle exec rails server -e production
##### Expected Result:
http://0.0.0.0:3000 can be visited
##### Actual Result:
server  Exit
##### Additional information
ubuntu@stone:~/sharetribe$ bundle exec rails server -e production
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:315: warning: Insecure world writable dir /usr/local/lib/ruby/gems/2.1.0 in PATH, mode 040777
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:315: warning: Insecure world writable dir /usr/local/lib/ruby/gems/2.1.0 in PATH, mode 040777
=> Booting WEBrick
=> Rails 3.2.21 application starting in production on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
INFO Connecting to database specified by database.yml
Exiting
/usr/local/lib/ruby/gems/2.1.0/gems/delayed_paperclip-2.9.1/lib/delayed_paperclip.rb:52:in `process_in_background': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /home/ubuntu/sharetribe/app/models/community.rb:205:in `<class:Community>'
	from /home/ubuntu/sharetribe/app/models/community.rb:105:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:359:in `require_or_load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:502:in `load_missing_constant'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:192:in `block in const_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `const_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:514:in `load_missing_constant'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:192:in `block in const_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `const_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:230:in `block in constantize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:229:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:229:in `constantize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:260:in `safe_constantize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/core_ext/string/inflections.rb:66:in `safe_constantize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:152:in `_default_wrap_model'
	from /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:169:in `_set_wrapper_defaults'
	from /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:133:in `inherited'
	from /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-3.2.21/lib/abstract_controller/railties/routes_helpers.rb:7:in `block (2 levels) in with'
	from /usr/local/lib/ruby/gems/2.1.0/gems/actionpack-3.2.21/lib/action_controller/railties/paths.rb:7:in `block (2 levels) in with'
	from /home/ubuntu/sharetribe/app/controllers/admin/communities_controller.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:359:in `require_or_load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:313:in `depend_on'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:225:in `require_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:443:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:443:in `block in eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:441:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:441:in `eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/ubuntu/sharetribe/config/environment.rb:17:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/ubuntu/sharetribe/config.ru:3:in `block in <main>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from /home/ubuntu/sharetribe/config.ru:in `new'
	from /home/ubuntu/sharetribe/config.ru:in `<main>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/server.rb:200:in `app'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by rap1ds** [comment]
Please use the Issue Template. Sheer stacktrace is not very helpful.

https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md

**Comment by rap1ds** [comment]
Not enough information. Closing.
