### ISSUE TITLE
listings images disappeared on listings of people page after git pull 

### ISSUE THREAD

**Issue by ptzool** [sharetribe/sharetribe#1430]
Hi,

After when I updated the sharetribe (git pull), the images of listings disappeared on listings of people page. 

For example: 
https://porteka.com/bubilla

But when I open a listing page I see the images.

What is the problem, could anybody help me?

Regrads,

Zool

**Comment by ptzool** [comment]
Fixed: https://github.com/sharetribe/sharetribe/commit/94773c6cec0156e8bc845e79d1effa78d7407d0e

**Comment by rap1ds** [comment]
Sorry about that :( Did some pretty bad commits today :(
