### ISSUE TITLE
Image upload issues

### ISSUE THREAD

**Issue by yo-gen** [sharetribe/sharetribe#1439]
We have set up sharetribe in development environment. But the image upload while posting or editing a listing is not working properly. It fails most of the time. I suppose it is some Paperclip issue, or , an issue with the delayed job worker. 
Did anybody face this previously..?

**Comment by rap1ds** [comment]
Hi @yo-gen !

Could you elaborate a little bit more? Can you use the issue template? https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md

Are you using S3 or local filesystem? Do you have workers up and running? Does it fail always or "most of the time" (i.e. works every now and then)?

**Comment by rap1ds** [comment]
More information needed. Inactive, closing.
