### ISSUE TITLE
Setting up Postmark for ShareTribe in Heroku

### ISSUE THREAD

**Issue by levina-duivesteijn** [sharetribe/sharetribe#1441]
Firstly - thanks a lot for an amazing template! I'm a real newby to Ruby, but managed to install it last weekend thanks to your guides - much appreciated! Just dealing with the last challenges now:

I deployed sharetribe via heroku and don't get the email service working. I added postmark as a heroku add-on, filled out my config file and re-deployed. Do I need to do anything else..?

##### Description: 
My app doesn't connect to Postmark to send the emails. I created a Postmark account, confirmed my sender address and got my Postmark API code. 

I added the following details in the config.yml file:

mail_delivery_method: smtp.postmarkapp.com
  smtp_email_address: "hello@mydomain.com"
  smtp_email_port: 25
  smtp_email_user_name: "my-api-code"
  smtp_email_password: "my-api-code"
  smtp_email_domain: "mydomain.com"
  postmark_api_key: "my-api-code"

In MySQLWorkbench 2, it does show a date for 'confirmation_sent_at', but in Postmark is shows that no emails were sent.

Did I set anything incorrectly? Do I need to do anything else?

##### Additional information: I'm very new to this so step-by-step instruction are much appreciated! :D

Thanks a lot,

Levina

**Comment by gnomet** [comment]
Hi!

Thanks for contacting! I haven't actually realized that the Postmark support is still in the code, as we've been using Amazon SES as our mail service for long time now. We should probably actually remove that code, as we can't easily guarantee the functionality of multiple email services. And at this moment we unfortunately don't have the resources to start debugging Postmark issues, so my recommendation is that probably easiest option would be to use Amazon SES as mail service, as that we use now with the core team and that should be better tested.

Also, if someone else in the open source community has been using Postmark and has tips about that, I hope those to be shared here.

But for the sake of simplicity, I think Postmark code should be removed as we can't guarantee it works. If someone is currently using it, please let me know!

**Comment by gnomet** [comment]
I will close the issue because it's a deprecated feature that we will remove soon. However, feel free to continue the discussion here if needed.
