### ISSUE TITLE
Sharetribe css not loading in chrome

### ISSUE THREAD

**Issue by jaceylab** [sharetribe/sharetribe#1444]
We have just successfully installed Sharetribe 4.5.5 in Amazon AWS. The pages are loading fine in IE and Firefox and we are able to sign up and use the website. However, when we open the same site in Chrome, only text shows up and the css won't load.

When we run "inspect element" in Chrome, it shows various errors which seem to be pointing to a css file and a modernizr.js file:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

assets/application-0b12969e03d375764905c3283393cbb5.css
assets/modernizr.min-7bd6b3739389a2d0a06bc21116527b6a.js

Uncaught ReferenceError: Modernizr is not defined
Uncaught ReferenceError: $ is not defined

Has anyone encountered this issue and resolved it?

Thanks in advance.

**Comment by rap1ds** [comment]
Hi! Thanks for reporting the issue. Could you give some more details about it? Have you run rake assets:precompile? Are you using Amazon S3 to host the assets? Can you attach a screenshot of the Chrome web inspector and the errors you are seeing?

**Comment by rap1ds** [comment]
Inactive. Closing.

**Comment by mouddai** [comment]
I have the same issue,when we open the site in Chrome, only text shows up and the css won't load.

When we run "inspect element" in Chrome, it shows various errors:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://spootfood.lvh.me:3000/images/profile_image/thumb/missing.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://spootfood.lvh.me:3000/javascripts/application.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://spootfood.lvh.me:3000/stylesheets/application.css Failed to load resource: the server responded with a status of 404 (Not Found)
edit_welcome_email:42 Uncaught ReferenceError: Modernizr is not defined
edit_welcome_email:447 Uncaught TypeError: Cannot set property 'jsonTranslations' of undefined
edit_welcome_email:477 Uncaught ReferenceError: $ is not defined
edit_welcome_email:483 Uncaught ReferenceError: $ is not defined
edit_welcome_email:489 Uncaught ReferenceError: $ is not defined
http://spootfood.lvh.me:3000/images/profile_image/thumb/missing.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://spootfood.lvh.me:3000/stylesheets/application.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by dargonar** [comment]
Hi

I have the same error

application-341396a….js:40 Uncaught Error: Cannot find module "!!./../../css-loader/index.js!./../../sass-loader/index.js!./styles.scss"
    at application-341396a….js:40
    at Object.<anonymous> (application-341396a….js:40)
    at t (application-341396a….js:2)
    at Object.<anonymous> (application-341396a….js:40)
    at t (application-341396a….js:2)
    at Object.<anonymous> (application-341396a….js:40)
    at t (application-341396a….js:2)
    at Object.<anonymous> (application-341396a….js:40)
    at t (application-341396a….js:2)
    at Object.<anonymous> (application-341396a….js:40)
(anonymous) @ application-341396a….js:40
(anonymous) @ application-341396a….js:40
t @ application-341396a….js:2
(anonymous) @ application-341396a….js:40
t @ application-341396a….js:2
(anonymous) @ application-341396a….js:40
t @ application-341396a….js:2
(anonymous) @ application-341396a….js:40
t @ application-341396a….js:2
(anonymous) @ application-341396a….js:40
t @ application-341396a….js:2
(anonymous) @ application-341396a….js:3
t @ application-341396a….js:2
(anonymous) @ application-341396a….js:3
t @ application-341396a….js:2
window.webpackJsonp @ application-341396a….js:2
(anonymous) @ application-341396a….js:3
edit:599 Uncaught TypeError: Cannot set property 'jsonTranslations' of undefined
    at edit:599
(anonymous) @ edit:599
edit:631 Uncaught ReferenceError: $ is not defined
    at edit:631
(anonymous) @ edit:631
edit:640 Uncaught ReferenceError: ST is not defined
    at edit:640
(anonymous) @ edit:640
edit:651 Uncaught ReferenceError: $ is not defined
    at edit:651
(anonymous) @ edit:651
application-341396a….js:8 Uncaught Error: ReactOnRails encountered an error while rendering component: OnboardingTopBar.Original message: Could not find component registered with name OnboardingTopBar. Registered component names include [  ]. Maybe you forgot to register the component?
    at Object.get (application-341396a….js:8)
    at Object.getComponent (application-341396a….js:3)
    at Object.i [as default] (application-341396a….js:8)
    at d (application-341396a….js:8)
    at a (application-341396a….js:8)
    at s (application-341396a….js:8)
    at p (application-341396a….js:8)
    at HTMLDocument.<anonymous> (application-341396a….js:8)

Hosting: AWS
URL: http://mercado-ecoin.waba.co.in

**Comment by jkowens** [comment]
@dargonar did you find a resolution to that issue? I'm seeing the same thing.

**Comment by jkowens** [comment]
Downgrading to node 6.9.5 fixed this issue for me.

**Comment by jkowens** [comment]
Actually, discovered that the real resolution was just to run:

```
rm -rf node_modules
rm -rf client/node_modules
npm install
```

Apparently I had initially installed dependencies with a newer version of node and this was creating some type of conflict.
