### ISSUE TITLE
Bug with deploying code on my own

### ISSUE THREAD

**Issue by congkinh** [sharetribe/sharetribe#1449]
Hi,

I took code from github and deployed it on my own. However, I got something like the following image.

<img width="629" alt="screen shot 2015-09-27 at 16 51 04" src="https://cloud.githubusercontent.com/assets/1632776/10123348/f9db4d54-6537-11e5-83d3-ced9ebbe8f8b.png">

Could someone tell me how to fix this? Thanks in advance!

**Comment by rap1ds** [comment]
Hi @congkinh 

You see that popup because your "plan" has expired. This is something that is related to our hosted version.

You can fix it running the following command in rails console:

```ruby
PlanService::API::Api.plans.create(community_id: <your community id here>, plan: { plan_level: PlanService::Levels::SCALE, expires_at: nil })
```

That will create a "scale" plan that will not expire ever.
