### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#1455]
Hi,

I've just configured sharetribe in my VPS, i've did this lots of time without any issue, i followed all the instructions and my market place is up and running.
It's running in a Red Hat distribution.
Everything is running fine, i've started the take tasks with:
bundle exec rake RAILS_ENV=production ts:start
bundle exec rake jobs:work RAILS_ENV=production

But when i add any image to any listing, i am getting a forever "image processing", i am monitoring the logs and everything is fine

Image Magick is installed, also sphinx, the job log, without any problem, any ideas?

thanks

INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh1.jpg[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh1.jpg[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh1.jpg[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh1.jpg[0]'
INFO Command :: convert '/tmp/image20150928-26213-18rpnh1.jpg[0]' -auto-orient -resize "1600x1600>" '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q'
INFO Command :: file -b --mime '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q'
INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: convert '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]' -auto-orient -resize "240x" -crop "240x160+0+98" +repage '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-1agro3w'
INFO Command :: file -b --mime '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-1agro3w'
INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: convert '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]' -auto-orient -resize "360x" -crop "360x270+0+132" +repage '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-y7473w'
INFO Command :: file -b --mime '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-y7473w'
INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: convert '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]' -auto-orient -resize "120x" -crop "120x120+0+29" +repage '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-7lgtft'
INFO Command :: file -b --mime '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-7lgtft'
INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: convert '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]' -auto-orient -resize "660x440>" '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-13wih27'
INFO Command :: file -b --mime '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-13wih27'
INFO Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: identify -format %m '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]'
INFO Command :: convert '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph[0]' -auto-orient -resize "150x" -crop "150x100+0+61" +repage '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-1p5039a'
INFO Command :: file -b --mime '/tmp/image20150928-26213-18rpnh120150928-26213-1jo806q20150928-26213-8c81ph20150928-26213-1p5039a'
INFO [paperclip] deleting /var/www/sharetribe/public/system/images/18/original/image.jpg

**Comment by rap1ds** [comment]
Hi @eltonokada 

Are you using Amazon S3 for the images? Can you see from the Web Inspector what's the response the image status poller gets? The status poller should be doing Ajax requests frequently. How about the server logs? Does the server receive the status poller requests?

**Comment by rap1ds** [comment]
Inactive. Closing.

**Comment by manishkongari** [comment]
Processing Uploaded Image   does not display image in development
