### ISSUE TITLE
Image upload form is gone

### ISSUE THREAD

**Issue by ptzool** [sharetribe/sharetribe#1482]
Hi,

After, when I upgraded the system the image upload form is gone.

Regards,

Zoli
![image_upload](https://cloud.githubusercontent.com/assets/350709/10409891/e2fc0b98-6f30-11e5-90ab-d16acda6e2d3.png)

**Comment by rap1ds** [comment]
Hi @ptzool 

Thanks for reporing! Have you tried to recompile the stylesheet? You can trigger the stylesheet compilation by going to the Design page and changing the colors.

**Comment by ptzool** [comment]
Hi rap1ds,

Sorry, I don't precompile assets... Everything works.:)

Regrads,

Zoli

**Comment by rap1ds** [comment]
No worries!
