### ISSUE TITLE
numeric_field_value_spec.rb:74 test fails

### ISSUE THREAD

**Issue by ArnisL** [sharetribe/sharetribe#1493]
```
Failure/Error: NumericFieldValue.search_many(with_many.compact).count.should == expected_count
  expected: 1
       got: 0 (using ==)
# ./spec/models/numeric_field_value_spec.rb:68:in `test_search'
# ./spec/models/numeric_field_value_spec.rb:74:in `block (3 levels) in <top (required)>'
```

If i change numeric_value data type to integer in migration:  
20140227102627_add_numeric_value_to_custom_field_values.rb

and schema (because migrations are broken), then rebuild db and sphinx indexes -  test passes

```
diff --git a/db/migrate/20140227102627_add_numeric_value_to_custom_field_values.rb b/db/migrate/20140227102627_add_numeric_value_to_custom_field_values.rb
index bec12fb..043638b 100644
--- a/db/migrate/20140227102627_add_numeric_value_to_custom_field_values.rb
+++ b/db/migrate/20140227102627_add_numeric_value_to_custom_field_values.rb
@@ -1,5 +1,5 @@
 class AddNumericValueToCustomFieldValues < ActiveRecord::Migration
   def change
-    add_column :custom_field_values, :numeric_value, :float, :after => :text_value
+    add_column :custom_field_values, :numeric_value, :integer, :after => :text_value
   end
 end
diff --git a/db/schema.rb b/db/schema.rb
index c33c385..a8374fa 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -349,7 +349,7 @@ ActiveRecord::Schema.define(:version => 20151008130725) do
     t.integer  "custom_field_id"
     t.integer  "listing_id"
     t.text     "text_value"
-    t.float    "numeric_value"
+    t.integer  "numeric_value"
     t.datetime "date_value"
     t.datetime "created_at",                        :null => false
     t.datetime "updated_at",                        :null => false
```

is that a correct way to handle this?

or there could be areas where there's necessity for numeric_value to be float?

**Comment by rap1ds** [comment]
Hi @ArnisL 

Thanks for reporting the issue!

I'm pretty sure that this is not the correct way to handle the error. We have a checkbox in the UI, "Allow decimals" for numeric custom fields, so we definitely want to keep the float type.

My guess is that the tests passed, because you rebuilt the sphinx indexes, which were probably broken for some reason and thus the search didn't return any results.

I'm pretty confident that this is not a bug in Sharetribe code, so I'll close the issue. However, if you find any additional information, feel free to post them here and I'll reopen the issue if needed.

**Comment by ArnisL** [comment]
>We have a checkbox in the UI, "Allow decimals" for numeric custom fields, so we definitely want to keep the float type.

thought so...

>My guess is that the tests passed, because you rebuilt the sphinx indexes, which were probably broken for some reason and thus the search didn't return any results.

can assure that that's untrue

during same test run - debugged and searched successfully by range on custom_field_id field

spec:
spec/models/numeric_field_value_spec.rb:74

breakpoint:
app/models/custom_field_values/numeric_field_value.rb:73

```
search(with: { custom_field_id: 0..500 }) # => all hits as expected
search(with: { numeric_value: 0..500}) # => no hits

# rebuilt indexes, same result
search(with: { numeric_value: 0..500}) # => no hits

# changed numeric_value to integer, rebuilt indexes
search(with: { numeric_value: 0..500}) # => all hits as expected
```

my current best bet is on "different sphinx version something something"

**Comment by rap1ds** [comment]
@ArnisL Thanks for additional information! I'll reopen the ticket. It feels that there might be something wrong.

What was the exact command you used to rebuild the index? Was it `rake ts:index`?

Btw. what's your Sphinx version? Mine is:

```bash
> searchd -h
Sphinx 2.2.4-id64-release (r4806)
Copyright (c) 2001-2014, Andrew Aksyonoff
Copyright (c) 2008-2014, Sphinx Technologies Inc (http://sphinxsearch.com)
```

**Comment by ArnisL** [comment]
```
Sphinx 2.0.4-id64-release (r3135)
```

will upgrade sphinx and see if that helps

**Comment by ArnisL** [comment]
upgrading sphinx did the trick

```
Sphinx 2.2.10-id64-release (2c212e0)
```

works as well with this version

**Comment by rap1ds** [comment]
@ArnisL Ok! Good to know that upgrading helped! Thanks for informing about this!
