### ISSUE TITLE
Pressing Follow on the page of another person gives error

### ISSUE THREAD

**Issue by FistOfTheNorthStar** [sharetribe/sharetribe#1502]
The follow functionality works, but error is displayed after the follow button is pressed. I'm not sure if this is due to my configuration or an actual bug.

Request goes to domain/en/username/followers

In the development environment locally it renders:

<< @current_user 12 respond_to do |format| 13 format.html { redirect_to :back } 14 format.js { render :partial => "people/follow_button", :locals => { :person =>

And this is the output
DEBUG   FollowerRelationship Exists (0.4ms)  SELECT 1 AS one FROM `follower_relationships` WHERE (`follower_relationships`.`follower_id` = BINARY 'cGcUfYz3yr5yabeedZE5MI' AND `follower_relationships`.`person_id` = 'dqDEvYy48r5ya3eedZE5MI') LIMIT 1
DEBUG    (6.2ms)  ROLLBACK
ERROR Could not log "process_action.action_controller" event. ArgumentError: wrong number of arguments (0 for 1)
DEBUG ** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? false         
  API key set? false
FATAL 
ActiveRecord::RecordInvalid - Validation failed: Follower has already been taken:
  activerecord (3.2.21) lib/active_record/validations.rb:56:in `save!'
  activerecord (3.2.21) lib/active_record/attribute_methods/dirty.rb:33:in `save!'
  activerecord (3.2.21) lib/active_record/transactions.rb:264:in `block in save!'
  activerecord (3.2.21) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  activerecord (3.2.21) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (3.2.21) lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
  activerecord (3.2.21) lib/active_record/transactions.rb:264:in `save!'
  activerecord (3.2.21) lib/active_record/associations/has_many_through_association.rb:85:in `save_through_record'
  activerecord (3.2.21) lib/active_record/associations/has_many_through_association.rb:52:in `insert_record'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:496:in `block (2 levels) in concat_records'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:344:in `add_to_target'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:495:in `block in concat_records'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:493:in `concat_records'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:134:in `block in concat'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:149:in `block in transaction'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  activerecord (3.2.21) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:148:in `transaction'
  activerecord (3.2.21) lib/active_record/associations/collection_association.rb:134:in `concat'
  activerecord (3.2.21) lib/active_record/associations/has_many_through_association.rb:38:in `concat'
  activerecord (3.2.21) lib/active_record/associations/collection_proxy.rb:118:in `<<'
  app/controllers/followers_controller.rb:11:in `create'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:645:in `_run__1977139859591418727__process_action__3034296783731766836__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/mapper.rb:43:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__4463603891686228648__call__170864138492232702__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  lograge (0.3.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:18:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-livereload (0.3.15) lib/rack/livereload.rb:23:in `_call'
  rack-livereload (0.3.15) lib/rack/livereload.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/deflater.rb:13:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
/Users/kak/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/kak/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/kak/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread

**Comment by FistOfTheNorthStar** [comment]
In the production env. it just renders in the place of the follow button, but the following functionality still works:
Page not found.

**Comment by rap1ds** [comment]
Hi! (and sorry for some delay)

Thanks for reporting this issue. I think that this may be a bug in the code.

Are you able to list the steps how to reproduce this? I tried to, but I couldn't.

**Comment by FistOfTheNorthStar** [comment]
I fixed this some time ago by changing the mutual index of person_id and follower_id.

**Comment by carlosgrgr** [comment]
Hi!

I have same problem but can not fix it.How did you change the mutual index of person_id and follower_id?

Thank you.
