### ISSUE TITLE
Unable to change Cover photo under design menu

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1510]
Hello I'm unable to change image such as cover photo, Small cover photo under the ADMIN-> Design.After clicking the save setting it just display ` Stylesheet is recompiling. Please, reload the page after a while.` but nothing changes.
When I see in the database, Field is updated with new file name and Images also get uploaded in the server.
Here is the stack of log.

Delayed::Job.last.last_error

`undefined method `[]' for nil:NilClass\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_paperclip-2.9.1/lib/delayed_paperclip/attachment.rb:54:in `delayed_only_process'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_paperclip-2.9.1/lib/delayed_paperclip/attachment.rb:62:in `process_delayed!'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_paperclip-2.9.1/lib/delayed_paperclip.rb:36:in `process_job'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_paperclip-2.9.1/lib/delayed_paperclip/jobs/delayed_job.rb:30:in `perform'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/backend/base.rb:95:in `block in invoke_job'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `block in initialize'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `execute'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:38:in `run_callbacks'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/backend/base.rb:92:in `invoke_job'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:203:in `block (2 levels) in run'\n/Users/iMac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'\n/Users/iMac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `call'\n/Users/iMac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `timeout'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:203:in `block in run'\n/Users/iMac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:202:in `run'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:259:in `block in reserve_and_run_one_job'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `block in initialize'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `execute'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:38:in `run_callbacks'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:259:in `reserve_and_run_one_job'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:187:in `block in work_off'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:186:in `times'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:186:in `work_off'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:151:in `block (4 levels) in start'\n/Users/iMac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:150:in `block (3 levels) in start'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `block in initialize'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `execute'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:38:in `run_callbacks'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:149:in `block (2 levels) in start'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:148:in `loop'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:148:in `block in start'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/plugins/clear_locks.rb:7:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:78:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:60:in `block in initialize'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:78:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:78:in `block in add'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:65:in `execute'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/lifecycle.rb:38:in `run_callbacks'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/worker.rb:147:in `start'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/delayed_job-3.0.5/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'\n/Users/iMac/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'\n/Users/iMac/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'\n/Users/iMac/.rvm/gems/ruby-2.1.2/bin/rake:23:in `load'\n/Users/iMac/.rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'\n/Users/iMac/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'\n/Users/iMac/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'`

Is there anything I need to do before setting up the system?

**Comment by rap1ds** [comment]
Hi!

The best advice I can give is to go and check that the delayed jobs and running on the background. In addition, make sure that ImageMagick is installed and working properly.

To me it sounds that this is not an issue in Sharetribe code, thus I'm going to close the ticket. It's probably an issue with your development environment.

If you find out the reason and if you have any suggestions how to improve the installation steps, feel free to send a comment in this thread!
