### ISSUE TITLE
how can i integrate paypal with sharetribe open source

### ISSUE THREAD

**Issue by shakti2601** [sharetribe/sharetribe#1532]
tell me how to do this

**Comment by rap1ds** [comment]
Hi there!

Have you already looked previously posted Issue about the subject. There are quite many issues which explain the situation and give hints how to build your own implementation, if that's what you are after:

* https://github.com/sharetribe/sharetribe/issues/1462
* https://github.com/sharetribe/sharetribe/issues/1395
* https://github.com/sharetribe/sharetribe/issues/1324
* https://github.com/sharetribe/sharetribe/issues/1155
