### ISSUE TITLE
Is it possible to remove delayed job and make to work as normal on my application 

### ISSUE THREAD

**Issue by manishkongari** [sharetribe/sharetribe#1563]
Is it possible to remove delayed job and make to work as normal on my application as my shared web hosting site5 does not allow daemonize

**Comment by rap1ds** [comment]
In order to run Sharetribe properly you have to be able to run at least 1 background job worker. We have some time consuming operations (e.g. image processing) that we definitely do not want to do during the HTTP request cycle, so that's why the background worker is required.
