### ISSUE TITLE
HTTPS protocol missing on new message email

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1566]
Hello, 
I've a fresh copy of sharetribe on production server.I installed SSL certificates to use https rather than http.
Everything is working fine, but When buyer send the message to seller during transaction, I'm receiving email containing the View message link but link is without `https`.
I'm sure I've followed all the process during installation as in documentation and more importantly https://github.com/sharetribe/sharetribe#setting-your-domain

I also changed `always_use_ssl: true` in the `config.default.yml` .

Is there anything I need to do to fix the problem.This is really urgent.
Thank you :)

## Update 1
Actually I want to have link as `https://kickmarket.eu/en/buyer/messages/6?ref=email_about_new_messages#message6`
but i'm getting `http://kickmarket.eu/en/buyer/messages/6?ref=email_about_new_messages#message6`.

**Comment by rap1ds** [comment]
@bipashant Thanks for reporting the issue!

This looks something that is probably a bug in the code.

Btw. instead of modifying the `config.default.yml` file, I'd suggest you to add a new file `config.yml`. This file overrides settings in `config.default.yml` values.

**Comment by bipashant** [comment]
Thanks a lot @rap1ds

**Comment by bipashant** [comment]
Hope You guys have a quick fix it. It's really both urgent and  important for me. Would you please suggest me some solution If there is any quick hack, so that I don't need to hardcode every url in the link. 
Or Is it will be the possible solution using  @community.full_url method instead of @community.full_domain in mailers parts?

**Comment by voyera** [comment]
This is a bit of a "hack" but couldn't you instruct your web server to redirect any http traffic to https ? This issue would now become a bit of a non-issue.

**Comment by bipashant** [comment]
Ya, You right,I'm doing same thing, but my concern is my client is for asking https link in their email.
