### ISSUE TITLE
Using Paypal API calling account as receiver

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1601]
Hello, I'm trying to integrate Paypal in sharetribe. I've changed existing `BillingType`: `ChannelInitiatedBilling`  to `MerchantInitiatedBillingSingleAgreement` and run the following command in the console to enable `Payments` menu under the Settings.

``` ruby 
PaymentSettings.create(community_id: 1, active: true, payment_gateway: "paypal", payment_process: "preauthorize", commission_from_seller: 3, minimum_price_cents: 50, minimum_transaction_fee_cents: 12, confirmation_after_days: 1)
```

Then I added my API credentials in the `config.yml`  and added my own checkout method in controller. I'm trying to integrate `adaptive checkout` using https://github.com/jpablobr/active_paypal_adaptive_payment .Then I tried to connect Paypal from the `Payments` menu so that I can use this email later while making checkout. I've only one account in Paypal using which I obtained the API credentials. After clicking connect to Paypal button, I got redirect to Paypal login page.
After entering my login credentials, I got the following error

> You are logging into the account of the API caller of this transaction. Please change your login information and try again.

I don't know what is wrong. Is it possible to use the API calling account as receiver.

**Comment by vuonghominh** [comment]
How did you resolve this issue?
Appreciate your assistance!

**Comment by bipashant** [comment]
@vuonghominh 
Seems we can not use the `API calling account as receiver.`
So at first I logged in as a different email address, 
Then after the registration, I changed the saved email address with the API calling account email.
This sounds weird but I did this to prevent the necessity of two paypal account in future.
I asked my client to register with different account then After registration, I reset it with the Original account.
Thanks

**Comment by delblues** [comment]
Hello, @bipashant  
Did you have success in this integration? I supposed you are working with the open source solution of sharetribe (as well I am too). Could you help me with that?  
Thanks

**Comment by bipashant** [comment]
@delblues  Would you please see my last answer, It was just a trick by the way :(

**Comment by delblues** [comment]
@bipashant 
I read, but I'm afraid I didn't get it at all. I'm investigating about using paypal with the open source version of sharetribe and I found your discussion here. I think it's possible, besides some people say it is not.  It's seems you get it, right? 
If yes, Can you please help me with a brief checklist (could be some bullets) of what should I do to activate paypal with open source version of sharetribe?

thanks a lot cheers
