### ISSUE TITLE
Braintree configuration fail

### ISSUE THREAD

**Issue by thonythony** [sharetribe/sharetribe#1613]
##### Sharetribe Version:

a07dfdcf0340c29ff4d2123e7ffab0a56b88ff6b

##### Environment:

_debian_

##### Server mode:

_production mode_

##### Description:

_Following the instructions from README.md, I can't configure the braintree gateways_

##### Steps To Reproduce:

_I create a new row in the table sharetribe_production.payment_gateways with the following data : community_id (1), braintree_environment (production), braintree_merchant_id (I copy/paste from braintree website), braintree_master_merchant_id (I don't know this information, I tested with the same value of braintree_merchant_id, and I leave blank), braintree_public_key (I copy/paste from braintree website), braintree_private_key  (I copy/paste from braintree website), braintree_client_side_encryption_key  (I copy/paste from braintree website)_

##### Actual Result:

_The server returns an error 500 when I attempt to visit a page_

``App 2635 stdout: FATAL 
App 2635 stdout: NoMethodError (undefined method `gateway_type' for #<PaymentGateway:0x000000096a5618>):
App 2635 stdout:   app/services/marketplace_service/community.rb:31:in `block in payment_type'
App 2635 stdout:   app/services/marketplace_service/community.rb:27:in `payment_type'
App 2635 stdout:   app/models/community.rb:518:in `payments_in_use?'
App 2635 stdout:   app/models/community.rb:528:in `testimonials_in_use'
App 2635 stdout:   app/controllers/homepage_controller.rb:81:in `block in index'
App 2635 stdout:   app/services/result.rb:52:in `call'
App 2635 stdout:   app/services/result.rb:52:in `on_success'
App 2635 stdout:   app/controllers/homepage_controller.rb:74:in `index'
App 2635 stdout:   lib/rack_middleware/custom_domain_cookie.rb:20:in `call'``

##### Additional information

_Where can I find the braintree_master_merchant_id ? There is another steps in order to configure braintree in sharetribe ?_

**Comment by thonythony** [comment]
I still have this issue... Anyone can help me please ?

**Comment by brakon** [comment]
anyone?

**Comment by brakon** [comment]
You need to set the payment_gateways.type column to be "BraintreePaymentGateway"

**Comment by rap1ds** [comment]
Hi @thonythony and sorry for late response.

Did you try changing the payment_gateways.type column as @brakon suggested?

Last time when I checked (and that was long ago) the master merchant id was shown in the Braintree dashboard.

We don't currently offer Braintree for our sharetribe.com hosted solution customers and we may remove (on completely rewrite) the Braintree support in the future.

**Comment by thonythony** [comment]
After searching for a long time, I found some issues in the sharetribe repo about the removal of Braintree support. So I given up this solution.
Thank you @brakon for your help and thank you @rap1ds for your reply. 
I close this issue.
