### ISSUE TITLE
which version of Rails of Sharetribe is compatible with?

### ISSUE THREAD

**Issue by blacktea3937** [sharetribe/sharetribe#1619]
Hi, just want to find out which version of Rails of Sharetribe is compatible with?

thanks!

**Comment by voyera** [comment]
From the gemfile...

ruby '2.1.2'
gem 'rails', '3.2.21'

But I do know they are working on a version compatible with Rails 4 :)

**Comment by blacktea3937** [comment]
i see. Thank you @voyera
