### ISSUE TITLE
No jobs are added in the database

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1632]
Hi
I'm having problem with delayed jobs.Let me explain the scenario,

I've deployed sharetribe on three different server.One is Integration, one for Staging and other for Production. Production is existing server, and is live since 4 months.Now I want to have different server for Staging and Integration but with same existing data as in production.So I dumped database from production and imported it into other server.Everything other than delayed job is working fine.

On uploading images for new listing, I got "image Uploading Failed" after upload percentage reached to 100% .On running `bundle exec rake RAILS_ENV=integration jobs:work` I got `[Worker(host:INT01 pid:9082)] Starting job worker` but it doesn't perform any job while uploading new images.In addition to this I checked `Delayed::Job.all` in console but got `nil`. no jobs are added in the database. 
I went through https://github.com/collectiveidea/delayed_job/wiki/Common-problems#no-jobs-are-added-in-the-database but It doesn't make any sense on me. I can't figured out what should I do.

Any suggestion will be appreciated. Thank you

**Comment by rap1ds** [comment]
Hi, sorry for late response.

Are you using S3 to host your images? Are you sharing the same S3 bucket with your production, integration and staging servers? Are you using the same database for production, integration and staging, or just the same data dump but different database servers?

**Comment by bipashant** [comment]
Yes, I'm having the same exact code in all environment.I'm using different DB server for different environment.

**Comment by rap1ds** [comment]
Based on the "Image Uploading Failed" error message, it feels to me that the uploading it self has failed for some reason. It might be that it's not yet in the phase where delayed job description is created but the uploading has failed before. One thing I would do at least is to double check your S3 configurations. Are you able to save any other images, such as profile image?

**Comment by bipashant** [comment]
No I'm not able to upload any images.Okay, I'm closing this issue now.Seems it is something wrong from side. Thank you very much for your time. Yes to Brotherhood :+1:
