### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by emilnikkhah** [sharetribe/sharetribe#1633]
Hi 
I have a question about the SEO. I have been having a site live in 4 month now and still dont show up on google. 
How is the SEO working with this? 
Thanks

**Comment by bipashant** [comment]
@emilnikkhah, I think you're correct :)
The best forum for this kind of questions is our Flowdock chat(https://www.flowdock.com/invitations/de227bdbe48d24c31a6b749933d3b4eca82e307c), however :)

**Comment by emilnikkhah** [comment]
Thanks
