### ISSUE TITLE
Karma Based Marketplace

### ISSUE THREAD

**Issue by drorm** [sharetribe/sharetribe#1637]
I installed Sharetribe (Good installation instructions), and am trying different options.

I'd like to create a marketplace where people can trade their used cloths and other items based on karma. This would be similar to stackoverflow where you accrue Karma points for answering questions except that your Karma would increase the more things or services you give away and decrease as you get things and use services. It wouldn't necessary be a one to one relationship.

 Looking at "Order Types", I see 'giving things away",  "Selling" and even a way to create a your custom template, but I suspect that I'd have to use some custom code, maybe based on https://github.com/twitter/activerecord-reputation-system. Is that something that you folks are thinking about or would be interested in?

**Comment by rap1ds** [comment]
Hi! 

Currently we don't support karma based marketplaces, so yes, you need to build this with some custom code.

Our main focus is on adding new payment gateways (in addition to Braintree and PayPal). Karma/virtual money marketplaces are not in our roadmap right now. However, every now and then people ask about this, so it's possible that someday we'll implement it.

**Comment by parasneo** [comment]
@rap1ds I am also looking for similar feature set where integrating a virtual currency wallet into the Sharetribe framework. 

Essentially, we would want to allow members that are selling something on the platform to be able to buy using a virtual currency.

Once the transaction goes through the virtual currency would be automatically taken from the buyers users account and deposited into the sellers account.

Let me know.
