### ISSUE TITLE
Braintree configuration missing/broken

### ISSUE THREAD

**Issue by brakon** [sharetribe/sharetribe#1646]
While running sharetribe I wanted to enable Braintree payments, which in the documentation it mentions it just needs to have the Braintree merchant_id, master_merchant_id, public_key, private_key and client_side_encryption_key.

But it seems this is not the case, since the payment configuration doesnt display in the admin ui when this data is added.

By checking the queries being done by the application I saw that it was missing the community_id and type columns, which I set to: "1" and "BraintreePaymentGateway" correspondingly.

But there is still no option to configure payments in the admin section.
And now there is no Order Types option in the admin section either.

Any idea on how to resolve this?

**Comment by brakon** [comment]
Seems the initial account is not even marked as "is_admin" and I had to update the database manually.

Either way, products on the site still have a "buy" button that doesnt send them to a checkout page, but instead a "message" page

**Comment by rap1ds** [comment]
Hi @brakon 

Order types are not supported with Braintree. That's why there's no order types tab showing.

Have a look at your `transaction_processes` table. You should see there a process `none`. `none` marks for non-monetary transaction. In addition to that, you should add another row with `process` `preauthorize`. After that you need to change your `listing_shapes` table to use the newly created `preauthorize` process, so you need to add the correct transaction_process_id there.

I hope this helps!

**Comment by brakon** [comment]
thanks @rap1ds I tried what you mentioned but still the buy button sends me to a message screen.

When I access my account it does say
{code}
"Your payout details
Account status: pending
Your account is pending for approval. "
{code}

I would think this is the reason my sample product doesn't go to a checkout page (since I created the product before enabling braintree).

Is the account approval done by Braintree by communicating to the webhook shown in the Sharetribe Braintree Payment Admin page? Also, do I have to give a valid routing and account number even though I'm currently just using a braintree sandbox credentials?

**Comment by rap1ds** [comment]
Yep, exactly as you said. Approval is done by Braintree and sent to the webhook. Sandbox is fine for testing.

**Comment by brakon** [comment]
I configured the webhook in braintree and its working now :) I can create test accounts, and post "billable"  test items.

Thanks for the help!

This would be useful in the documentation, I could send a MR with the additions to the documentation.

**Comment by rap1ds** [comment]
@brakon Good to hear that you got it working!

If you are able to send a PR that adds instructions to README, that would be awesome!
