### ISSUE TITLE
Quick survey: Which payment gateway do you use?

### ISSUE THREAD

**Issue by rap1ds** [sharetribe/sharetribe#1657]
Hi all Sharetribe Open Source users!

This is a quick survey to get some idea about the popularity of different payment gateways.

**1) Which payment gateway do you use?**

  a) None
  b) Braintree
  c) You have implemented integration to some other gateway, which one?

**2) In ideal world, which payment gateway would you like to use?**

Thanks for your answer!

Mikko,
Sharetribe

**Comment by bipashant** [comment]
Hi Mikko, 
I'm a freelancer working more than 1 year in customizing the sharetribe.Most of the jobs I've done is adding the Paypal as Payment Gateway.

With Best regards,
Bibek Sharma

**Comment by FistOfTheNorthStar** [comment]
1. Braintree
2. Gold coins, no but seriously they all have their goods and bads.

**Comment by Clem-J** [comment]
I have implemented Lemonway getway

**Comment by santiagogsanchez** [comment]
1. None.
2. PayPal

**Comment by brakon** [comment]
Braintree!

**Comment by top1select** [comment]
1. Stripe
2. Stripe and PayPal

**Comment by vbklv** [comment]
1. Mangopay
2. It doesn't matter as long as there are many tasty transactions

**Comment by pcm211** [comment]
CC Payment Gateway

**Comment by priviterag** [comment]
Braintree

**Comment by amicheals** [comment]
would love to use payeezy.js from first data

**Comment by amicheals** [comment]
with the payeezy.js you won't have to worry about pci

**Comment by shoaibmalik786** [comment]
Hi Mikko,
I realized during last one year that most of the guys asked to integrate stripe connect and paypal.

Thanks

**Comment by infiniteschema** [comment]
Stripe Connect!

**Comment by clehner** [comment]
Is the source for any of these alternative payment integrations (in particular Stripe Connect and PayPal) available?

**Comment by shoaibmalik786** [comment]
Hi I have integrated the stripe connect with sharetribe project, for more
info you can contact me over my email
shoaib2109@gmail.com

Thanks
Shoaib Malik

**Comment by rap1ds** [comment]
Thank you everyone for answering!

**Comment by wesleyguirra** [comment]
Hi I'm looking for help to implement payment gateway in sharetribe someone can help me with it? I've read the forum, but not found something that can bootstrap me on this task. @vbklv @pcm211 @Clem-J

**Comment by pcm211** [comment]
@wesleyguirra ... This question is very region specific ... The APIs are very customized with every payment gateway. What exactly have you been able to achieve and what exactly do you require

**Comment by pcm211** [comment]
Sharetribe has a complex Payment system for paypal implemented for a start ...keeping in mind the multiple marketplaces it hosts .... as SHARETRIBE.... :)

Firstly, we actually dont need such a complex system for implementing a single marketplace. 

You can mail me on vivek.bardia@gmail.com to discuss it in detail ..... Ill try to help you out understanding what you require

**Comment by vins2k** [comment]
Hi 
Is any Indian payment gateway supported on Sharetribe?
Thanks

**Comment by thomasmalbaux** [comment]
Hi there!

Right now, Sharetribe Go supports PayPal as a payment gateway available for transactions within India. This is available in the hosted version however in the open-source version, you'd have to get the approvals from PayPal to confirm the integration, which is something quite challenging to do.

Another possibility is for you to add your own payment gateway, on your own servers. Don't hesitate to discuss this with other open-source users at https://www.sharetribe.com/community/!

**Comment by 218labs** [comment]
PayPal & Stripe

**Comment by computersciencejunction** [comment]
We Generally Use **[Razorpay Payment Gateway](https://www.computersciencejunction.in/2021/07/12/razorpay-payment-gateway/)** Best Gateway used in India in 2021
