### ISSUE TITLE
Mercury Editor not working

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#1680]
I am not able to edit any page that is using the mercury editor.
I am not using the Rails 4.1 version as it has lots of bugs.

**Comment by rap1ds** [comment]
Hi! Thanks for reporting the issue!

Could you tell me a bit more about the issue? I tried it on my local machine and didn't see any issue. Also, the Mercury editor works fine on sharetribe.com. 

Could provide clear, exact and precise steps how to reproduce the issue. We are not able to provide any help if we are not able to reproduce it ourselves.

Rails 4.1 is still in an unmerged branch #1678 . You should not use it.

**Comment by eltonokada** [comment]
Hi, thanks for the answer and for testing.
I've uploaded the code from commit: 1b0ee57784bf371b9d1f64306c85f21b4fca7016 to a server in Digital Ocean, followed the instructions to install the marketplace, and when i try to edit About page the editor is not loading, just reloading the page.

In production i am not seeing any error in console, but in dev yes:

WebSocket connection to 'ws://warmshopping.lvh.me:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Thank you so much

**Comment by eltonokada** [comment]
Sorry, just found the error, was in my code

**Comment by rap1ds** [comment]
Good that you found the reason.
