### ISSUE TITLE
assets not loading, request_uuid ... 

### ISSUE THREAD

**Issue by tee-vee** [sharetribe/sharetribe#1706]
Hi, 

- running sharetribe on linux / mysql 
- RAILS_ENV=production
  (did not set up development/test instance on this box)

- sharetribe starts perfectly fine and pages load okay except my favorite logo (top left) and font-awesome assets don't load (search magnifying glass?)
- I'm fully aware that serving static content / assets off ruby/rails is a bad idea; i'll fix this later. 
  (Would appreciate a quick hint as to configuring sharetribe where its assets is on an httpd server, and which files are needed?) 
- I noticed a pattern in my log files - successful entries have values for "host" and "request_uuid" - like this: `{"method":"GET","path":"/en/signup","format":"html","controller":"people","action":"new","status":200,"duration":50.69,"view":31.29,"db":9.84,"params":{"locale":"en"},"host":"test.webserver.com","community_id":1,"current_user_id":"","request_uuid":"cec1a324-187a-4831-916d-c1428efabb55"}`

- however, those assets that won't load are followed with a log entry like this - note the null "host" and "request_uuid":
`{"method":"GET","path":"/system/wide_logos/1/header_highres/sbux7b_zpse57e6454.png","format":"png","controller":"errors","action":"not_found","status":404,"duration":9.08,"view":1.68,"db":3.87,"params":{"1453123185":null,"path":"system/wide_logos/1/header_highres/sbux7b_zpse57e6454","format":"png"},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}`

- and `{"method":"GET","path":"/assets/fontawesome-webfont.woff","format":null,"controller":"errors","action":"not_found","status":404,"duration":7.49,"view":1.82,"db":2.26,"params":{"v":"3.0.1","path":"assets/fontawesome-webfont","format":"woff"},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}
`

Yet the physical files do exist on the filesystem. So I don't get it ... 

Would be very grateful for any advice. 

Thanks!
-D

**Comment by rap1ds** [comment]
@tee-vee Thanks for reporting the issue.

I was able to reproduce it with a fresh install when I started `rails server` in production environment.
