### ISSUE TITLE
Rails server is running, but cannot connect through 3000

### ISSUE THREAD

**Issue by top1select** [sharetribe/sharetribe#1725]
Hello, 

I was unable to start development environment anymore, production is no problem.

  `bundle exec rails server` 

seems to be starting fine:

`[root@ip sharetribe]# bundle exec rails server
=> Booting WEBrick
=> Rails 4.2.5.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-02-10 21:39:02] INFO  WEBrick 1.3.1
[2016-02-10 21:39:02] INFO  ruby 2.1.2 (2014-05-08) [x86_64-linux]
[2016-02-10 21:39:02] INFO  WEBrick::HTTPServer#start: pid=2833 port=3000`

However, when I try connecting to localhost:3000 , 0.0.0.0:3000 , 127.0.0.1:3000 in browsers and they all cannot establish a connection to the server. wget  also not working.

`wget http://0.0.0.0:3000
wget http://127.0.0.1:3000
wget http://localhost:3000`

Some things to clarify:

I was able to connect to localhost just yesterday,

it seems like it suddenly stopped working after I merged to the lasted master branch as of today.

Please help!!

**Comment by michelboaventura** [comment]
What is the output of ```ping localhost```?

And ```netstat -a | grep 3000``` (with the server running)?

**Comment by top1select** [comment]
ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.018 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.029 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.029 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.029 ms

netstat -a | grep 3000

has nothing when server is started:


[2016-02-10 22:36:34] INFO  WEBrick 1.3.1
[2016-02-10 22:36:34] INFO  ruby 2.1.2 (2014-05-08) [x86_64-linux]
[2016-02-10 22:36:34] INFO  WEBrick::HTTPServer#start: pid=9284 port=3000

**Comment by top1select** [comment]
This worked for me:

rails s -b 0.0.0.0 -p 3000

**Comment by emads3** [comment]
> 
> 
> This trick worked for me:
> 
> rails s -b 0.0.0.0 -p 3000
> 
> Can't access ports assigned to Rails 4.2, but 4.04 works fine
> [http://serverfault.com/questions/625841/cant-access-ports-assigned-to-rails-4-2-but-4-04-works-fine]

YOU SAVED MY ASS

**Comment by parmardhaval48107** [comment]
> This trick worked for me:
> 
> rails s -b 0.0.0.0 -p 3000
> 
> Can't access ports assigned to Rails 4.2, but 4.04 works fine
> [http://serverfault.com/questions/625841/cant-access-ports-assigned-to-rails-4-2-but-4-04-works-fine]

I tried this but it doesn't work for me when I enter the URL 0.0.0.0:3000 into the browser it does nothing.

**Comment by swikars1** [comment]
I'm facing same issue using ruby 2.7.1 with rails 6.1.1

**Comment by iamdhavalparmar** [comment]
Check the ruby and rails version in your machine and in the gem file of your project. In my case, the versions of the ruby and rails were different in my machine and in the gem file.

**Comment by swikars1** [comment]
The issue occurred in wsl2 but is not possible to perfectly replicate it, it has happened to me 3 times in 5 days and only gets fixed after a complete windows reboot.

**Comment by juls0730** [comment]
> The issue occurred in wsl2 but is not possible to perfectly replicate it, it has happened to me 3 times in 5 days and only gets fixed after a complete windows reboot.

I have the exact same problem
