### ISSUE TITLE
Pageless issue, can also be reproduced on maggieskidsmarket.com

### ISSUE THREAD

**Issue by top1select** [sharetribe/sharetribe#1733]
Hello,

FYI, this issue can also be reproduced on https://www.maggieskidsmarket.com/

This is what happened:

When you are on homepage with grid view (home-fluid-thumbnail-grid-narrow), then scroll all the way down, say beyond 5 pages, then click a listing, go into the detail page, then return to homepage(click go back button), it restarts at the first/second page, instead of staying at the 5th page. 

I tried this on desktop and smart phone, both are like this.

Could you please take a look?

Thanks a lot.

**Comment by rap1ds** [comment]
Hi @top1select 

Thanks for reporting the issue.

This is indeed an annoying issue. It's definitely a very bad user experience. However, it's also a damn difficult issue to solve well. Even the big players (Facebook, Twitter, e.g.) have some difficulties implementing this. You can try this, go to Facebook/Twitter, scroll down to load more posts, click a link (that doesn't open to a new tab) and then hit the browser Back button. They try to load all the posts and move the scroll position to the correct positioning, but it's not perfect.

We are not planning to put effort on this right now. We are planning to do some bigger improvements to the whole frontpage layout and at the same time we try to find some solution for this issue.
