### ISSUE TITLE
Flowdock channel is not in use at the moment

### ISSUE THREAD

**Issue by rap1ds** [sharetribe/sharetribe#1734]
Hi all! Our Flowdock developer chatroom is not in use at the moment.

We are soon setting up a new chatroom and/or forum and we will inform you when this is done.

**Comment by mooreds** [comment]
Have you considered a slack channel?  Not open source, but free.

**Comment by rap1ds** [comment]
We have now a new community forum 🎉 See the issue #1806 for more details!

https://www.sharetribe.com/community/
