### ISSUE TITLE
Invalid Flowdock invitation link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by apaatsio** [sharetribe/sharetribe#1751]
In CONTRIBUTING.md there is a link to https://www.flowdock.com/invitations/de227bdbe48d24c31a6b749933d3b4eca82e307c but following that link goes to a page that says "Invitation could not be found"

**Comment by rap1ds** [comment]
Sorry about that. The Flowdock channel is not in use at the moment. We're setting up a new communication channel at the moment.
