### ISSUE TITLE
Warnings for REMOVED_LOCALES already defined

### ISSUE THREAD

**Issue by vbklv** [sharetribe/sharetribe#1757]
##### Sharetribe Version:

80a0a888

##### Environment:

OSX

##### Server mode:

Development

##### Description:

There is a warning on every sql update every:

DEBUG   SQL (0.9ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = ...
/sharetribe/config/routes.rb:52: warning: already initialized constant REMOVED_LOCALES
/sharetribe/config/routes.rb:52: warning: previous definition of REMOVED_LOCALES was here
DEBUG   SQL (0.9ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` =

##### Steps To Reproduce:

rake jobs:work

**Comment by rap1ds** [comment]
Thanks for the report!

This is only a warning, so it doesn't brake anything or cause any issues. However, I agree it's kinda annoying.

If someone wants to fix this, I'm happy to accept the pull request!
