### ISSUE TITLE
Sphinx doesn't work well

### ISSUE THREAD

**Issue by ptzool** [sharetribe/sharetribe#1758]
##### Sharetribe Version:
The newest version of sharetribe (commit: 11307) REV-PARSE: 2d8d8a23a02d968ff7d62eaa6b31ff47e0947fbd

##### Environment:
Own server.

##### Server mode:
Production

##### Description:
I upgraded the system to the newest version of sharetribe, everything was fine but when i checked the search I realized it didn't work well. If the search string contains for example 'éáúűüö' etc. characters the search result didn't give anything. 

I made the following steps when I finished the upgrade:
bundle exec rake RAILS_ENV=production ts:index
bundle exec rake RAILS_ENV=production ts:start

Does anybody meet this problem?

Thx,

Regards,

Zoli

**Comment by rap1ds** [comment]
Thanks for the report.

@mporkola @Gnito @ovan What do you think, could this be related to the new search?

**Comment by sktoiva** [comment]
I couldn't reproduce the issue on my local installation. However, this reminds me on an issue we had a while back where searches failed with those characters. It was related to Thinking Sphinx adding SQL command `SET NAMES utf8` as part of the indexing process if the database connection settings have encoding set to utf8. It should normally be default in Rails, but with e.g. Heroku it should be at the end of db uri:  mysql2://username:password@host/database?encoding=utf8.

The other option is to have it in the index definitions like this: `set_property :utf8? => true`. We use the latter method like this: https://github.com/sharetribe/sharetribe/blob/master/app/indices/listing_index.rb#L7

This is a bit of a long shot if you have set up the database with `rake db:schema:load`, and are using unmodified index files, but maybe this information gives you some clues on how to debug the issue: .e.g. check database configuration and connection settings. 

Another thing you could try is to rebuild the indexes completely with `bundle exec rake RAILS_ENV=production ts:rebuild`

**Comment by ptzool** [comment]
Hi,

I cheked my DB encoding settings and everthing is utf8. I ran `ts:rebuild` and after it I noticed following things. 

I got this message and I don't unterstand some lines in message. For example

skipping non-plain index 'custom_field_value'...
skipping non-plain index 'listing'...


```
indexing index 'custom_field_value_core'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.004 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'custom_field_value_delta'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.001 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'listing_core'...
collected 728 docs, 0.4 MB
collected 0 attr values
sorted 0.0 Mvalues, 100.0% done
sorted 1.2 Mhits, 100.0% done
total 728 docs, 355961 bytes
total 0.698 sec, 509313 bytes/sec, 1041.63 docs/sec
indexing index 'listing_delta'...
collected 0 docs, 0.0 MB
collected 0 attr values
sorted 0.0 Mvalues, 100.0% done
total 0 docs, 0 bytes
total 0.002 sec, 0 bytes/sec, 0.00 docs/sec
skipping non-plain index 'custom_field_value'...
skipping non-plain index 'listing'...
total 10 reads, 0.003 sec, 728.7 kb/call avg, 0.3 msec/call avg
total 44 writes, 0.018 sec, 314.1 kb/call avg, 0.4 msec/call avg
Started searchd successfully (pid: 22072).
```

**Comment by sktoiva** [comment]
That 

```
skipping non-plain index 'custom_field_value'...
skipping non-plain index 'listing'...
```

is perfectly normal and doesn't unfortunately help here. It just means, that e.g. index `listing` is a distributed index that contains both `listing_core` and `listing_delta` and is therefore skipped as there is nothing to index directly. And as you can see `listing_core` is indexing 728 docs:

```
indexing index 'listing_core'...
collected 728 docs, 0.4 MB
```

I assume that this `rebuild` didn't help?

**Comment by ptzool** [comment]
Unfortunately, no

**Comment by sktoiva** [comment]
We probably figured it out.

In the newest Sharetribe version there is a patch level update to Thinking Sphinx gem, and apparently there is some work in 3.1.x versions to make it work with Sphinx v2.2. It seems that something in this upgrade breaks some of the compatibility between the gem and Sphinx. Upgrading Sphinx to newest version fixed the exact same issue in one of our local machines.

Could you try upgrading Sphinx, rebuild indexes and report if that works?

**Comment by ptzool** [comment]
Hi,

I upgraded sphinx to `Sphinx 2.2.10-id64-release (2c212e0)` but I have same problem.:(

**Comment by gnomet** [comment]
Sorry to hear that, we hoped that it would have been the reason as it was the fixing move to get it working on our machines locally. Now it's harder to debug the issue at this end as we can't seem to reproduce the same issue with Sphinx 2.2.10..

Just a thought that even though rebuild command should start and stop sphinx, you could try to ensure that all sphinx daemons are stopped ( by looking at process list if there's any "searchd" process active) and quit all and then start again. As said, it probably won't differ from the effect of rebuild, but currently the only thought coming to mind..

**Comment by ptzool** [comment]
It works well after upgrade. https://github.com/sharetribe/sharetribe/commit/bbf5acaa05c29fa2dbce92c929da97e73a6be85b
