### ISSUE TITLE
Cannot save profile settings

### ISSUE THREAD

**Issue by indy-guide** [sharetribe/sharetribe#1788]
##### Description: Some user get an error message when they add their profile info and try to save it.
He already tried different up-to-date browsers, different profile pictures, and also on his mobile. He’s been trying now for more than a week. 

Error message is:
“Network Error (tcp_error) 

A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.”

##### Steps To Reproduce:
0. Sign up
1. Edit and complete profile settings (about me, profile picture)
2. Click save

Expected result: Confirmation: 'Information updated'

Actual result: Error message: “Network Error (tcp_error) 

A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.”

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by rap1ds** [comment]
Hi @indy-guide ! Thanks for reporting the issue!

First, try to update to the latest release 5.4.0. We had a bug in the code (misconfiguration) which made the image processing to happen in the request and not in the background as it should. That made the requests longer and prone to timeouts.

So please try 5.4.0 and see if it helps.

**Comment by rap1ds** [comment]
Inactive. Closing.
