### ISSUE TITLE
What is Zappy?

### ISSUE THREAD

**Issue by brakon** [sharetribe/sharetribe#1797]
From what I see its supposed to be a scala client to query zappos, am I missing something?

**Comment by rap1ds** [comment]
Hi! Thanks for asking. See [this comment](https://github.com/sharetribe/sharetribe/pull/1713#issuecomment-185733542)

**Comment by xuanus** [comment]
@rap1ds May I ask what is Discovery service? What is searchpage_v1? Thank you.
