### ISSUE TITLE
image upload fails due to UndefinedConversionError

### ISSUE THREAD

**Issue by mooreds** [sharetribe/sharetribe#1801]
##### Sharetribe Version:

71b506b1d9975e71c390c3ffded1c4cd43ea2f47

##### Environment:

ubuntu/trusty64 under vagrant

##### Server mode:

Development

##### Description:

Uploading listing images 

##### Steps To Reproduce:

1. bundle exec rails server  -b 0.0.0.0
1. add a listing as an admin user (using microsoft edge and google chrome)
1. try to upload an image

##### Expected Result:

See image upload succeeded

##### Actual Result:

See "Image upload failed" in the image section

##### Debugging information

Log message in the server console: 

```
DEBUG ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false
DEBUG ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false
FATAL
Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8):
  lib/sharetribe_logger.rb:16:in `info'
  app/controllers/listing_images_controller.rb:80:in `new_image'
  app/controllers/listing_images_controller.rb:66:in `add_image'
  app/controllers/listing_images_controller.rb:37:in `add_from_file'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'


FATAL
Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8):
  lib/sharetribe_logger.rb:16:in `info'
  app/controllers/listing_images_controller.rb:80:in `new_image'
  app/controllers/listing_images_controller.rb:66:in `add_image'
  app/controllers/listing_images_controller.rb:37:in `add_from_file'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

```

Imagemagick was installed via apt-get: `sudo apt-get install imagemagick --fix-missing `

```
vagrant@vagrant-ubuntu-trusty-64:~/sharetribe$ convert -version
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP
```

**Comment by mooreds** [comment]
Found this SO question: https://stackoverflow.com/questions/13909812/error-ruby-on-rails-encodingundefinedconversionerror-in-coursescontrollerat but it wasn't clear to me exactly how the file gets uploaded.

**Comment by rap1ds** [comment]
Thanks for the bug report!

I guess you are using local file system to store the files (not S3), is that right?

Can you try to open the `listing_images_controller.rb` and comment out the line 80? It seems that the logging is failing and commenting out the line that does to logging may help. I guess the logger is trying to dump the uploaded image to the log stream and that is failing.

**Comment by mooreds** [comment]
@rap1ds Thank you!

It seems this was a combination of errors, mostly mine.

I commented out that line which you suggested.  This let me see that the job was getting into the delayed_job queue, but still gave me a `image processing` default image.

Then I re-read fantastic install docs and realized I needed to run `bundle exec rake jobs:work` in a different window.  After I did that things worked flawlessly, and I was able to upload images.

However, I just tried uncommenting that line and the image upload still fails.  Is there something special I have to do to enable logging?  (Obviously turning off logging for the whole application is something I'd like to avoid.)

This: https://github.com/airbrake/airbrake/issues/399  is what turns up when I google the airbrake message just above the stacktrace (below):
```
DEBUG ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false
DEBUG ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false
FATAL
Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8):
  lib/sharetribe_logger.rb:16:in `info'
  app/controllers/listing_images_controller.rb:80:in `new_image'
  app/controllers/listing_images_controller.rb:66:in `add_image'
  app/controllers/listing_images_controller.rb:37:in `add_from_file'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'


FATAL
Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8):
  lib/sharetribe_logger.rb:16:in `info'
  app/controllers/listing_images_controller.rb:80:in `new_image'
  app/controllers/listing_images_controller.rb:66:in `add_image'
  app/controllers/listing_images_controller.rb:37:in `add_from_file'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

```

Is it an encoding error of some kind?

**Comment by mooreds** [comment]
Oh yes, I am using the local file system.  I expect to use s3 in production, but for local development I thought the local file system was appropriate.

**Comment by mooreds** [comment]
Ah, sorry, I just re-read your comment.  In your opinion is it safe to modify the logging statement so it doesn't try to dump the image to the log file?

**Comment by ankurj77** [comment]
I also got the same error. The way I fixed the issue was to add a dependency in Gemfile:
gem 'activesupport-json_encoder'

This fixed the issue without commenting out the line 80 in listing image controller.
