### ISSUE TITLE
S3 Bucket NOT Working .... Earlier issues are outdated as Sharetribe Version Upgraded &  AWS addressing has probably changed

### ISSUE THREAD

**Issue by pcm211** [sharetribe/sharetribe#1817]
##### Sharetribe Version:
Stable
##### Environment:
Production: AWS EC2, RDS, S3

##### Server mode:
All Envts 
##### Description:

This is an issue with the code in assets_synce.rb, config.yml/config.defaults.yml ... compatibility... and ease of working.

i have deployed sharetribe in production envt , MADE IAM USER and added it to a GROUP which has access to S3 assets, and have overwritten defaults of config file to add the foll:

  Default bucket
  s3_bucket_name:  <bucket name as seen on S3 Website>
  s3_upload_bucket_name: <bucket name as seen on S3 Website>
  
  AWS keys
  aws_access_key_id: xxx
  aws_secret_access_key: "+xxxx"
  
The assets DO NOT SYNC ....due to ... a default suffix value attaching itself to the bucket names while calling from the working website GET/ in ....  s3.amazonaws.com ...... which cannot be changed or overridden ....APPARENTLY

![Uploading ASSETS SYNC 1.png…]()

 ##### Steps To Reproduce:

Have a working sharetribe production envt ready for launch 

1. add aws bucket names (both) -- they claim to be region independent as shown in aws documentation
2. Add IAM User to IAM group with S3 priviledges
3. Run the envt
4. Inspect element from a browser (chrome) for seeing the behaviour of images moving

Expected result: both S3 buckets should hold its appropriate assets

Actual result: no bucket is accessed ....  and hold its expected image

PS : if you do not have a bucket created .... in s3 then Paperclip creates the bucket and access it ....wierd but an interim solution... till not corrected

##### Additional information

use a browser and inspect the element .... on clicking the upload image <select file> the 0% does not change and browser gives the above following problem.

Probably the issue is a paperclip merge issue which i am not able to identify and smoothly integrate with the code ;clumsy solutions can be tried

EASY REFERENCES
http://www.rubydoc.info/gems/paperclip/Paperclip/Storage
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
(only one region probably allows small adderssing)

**Comment by pcm211** [comment]
![assets sync 1](https://cloud.githubusercontent.com/assets/13811638/13713227/ef10125e-e7ed-11e5-840b-87bbe0b42ab7.png)

**Comment by rap1ds** [comment]
Hi @pcm211 Thanks for reporting the issue.

What's the exact Sharetribe version you are using? You can see this from VERSION file. We haven't been using AssetSync for a while.

(Btw. now that you mentioned it, the asset_sync.rb file should be removed. It's not used anymore)

**Comment by pcm211** [comment]
hi @rap1ds , 

i am using the latest version 5.6.0 ... 

there is another issue related to this (probably)... which is on changing the look and feel of the sharetribe page ...  the icons dissapear and only boxes and lines appear (placeholders) where there were icons.......  other logo , favicon, desktop pic etc are refleted less the icons (fonts-awesome) which should have been uploaded to s3 ...but is not sent to s3 bucket....  initially which should have been the case ....


![font loading problem](https://cloud.githubusercontent.com/assets/13811638/13742517/2c939c16-ea02-11e5-9b80-315bd1b27fb9.png)

**Comment by rap1ds** [comment]
@pcm211 Ok, thanks for details.

AssetSync has been removed long ago, so it's expected behaviour that no assets are synced to the S3 bucket. That's why I'm now closing this issue.

If you still have some other issue than AssetSync, feel free to open a new issue with exact steps how to reproduce.
