### ISSUE TITLE
fontawesome-webfont missing after upgrade

### ISSUE THREAD

**Issue by ptzool** [sharetribe/sharetribe#1824]
##### Sharetribe Version:

bbf5acaa05c29fa2dbce92c929da97e73a6be85b
##### Environment:

Own server with S3 assets
##### Server mode:

Production
##### Steps To Reproduce:

I upgraded sharetribe to https://github.com/sharetribe/sharetribe/commit/bbf5acaa05c29fa2dbce92c929da97e73a6be85b and after it the system doesn't find fontawesome-webfont on S3. 
![sharetribe](https://cloud.githubusercontent.com/assets/350709/13791029/7fcf3ffe-eaeb-11e5-8946-bd3e0281ecba.png)

I ran the following commands:

```
bundle install
RAILS_ENV=production rake db:migrate
RAILS_ENV=production rake sharetribe:generate_customization_stylesheets_immediately
rake assets:precompile
```

**Comment by pcm211** [comment]
copy your local assets to s3 bucket... partial bucket working is not allowed....in code

in the assets folder (S3) bucket ... add the font-awesome folder from the local server you are working on ....

Its bit of a hack ....but wrks fine

**Comment by rap1ds** [comment]
@ptzool Thanks for reporting.

What was the version from which you updated?

**Comment by ptzool** [comment]
From 5.5.0

**Comment by rap1ds** [comment]
Sometime ago we made a change and got rid of the `asset-sync` gem which was responsible for syncing the static assets to S3. So nowadays the recommended way is to use CDN to serve assets: 

README:

> It is not recommended to serve static assets from a Rails server in production. Instead, you should use a CDN (Content Delivery Network) service, such as Amazon CloudFront. To serve the assets from the CDN service, you need to change the `asset_host` configuration in the the config/config.yml file to point your CDN distribution.

There was also a bug that fixed for 5.5.0 https://github.com/sharetribe/sharetribe/pull/1756

**Comment by pcm211** [comment]
![image](https://cloud.githubusercontent.com/assets/13811638/13978784/bd1cf022-f0f9-11e5-8ea5-894b4a820d0d.png)


the problem is supposedly that its got this wierd versioning thing in the end which is not available even in the local assets .... or some script check parameter which it needs to execute .. preloading .. and fails finally to load ... most of the icons ..... (*.ttf?v=3.0.1 & *.woff?v=3.0.1)

https://xxxx.cloudfront.net/assets/fontawesome-webfont-f845c8a28aff5fe61489393eeacb1435.ttf?v=3.0.1
https://xxxx.cloudfront.net/assets/fontawesome-webfont-9602ffa0a8cbb7c6a7b51e733014a836.woff?v=3.0.1

PROPOSED SOLUTION : Fix this by just adding the following line to theme's stylesheet: 
@import url("https://xxx.yyyy.com/font-awesome/3.0.1/css/font-awesome.min.css");

That seemed to fix the problem without needing to hack the plugin code or copy plugin template files into my theme folder.

**Comment by niiamon** [comment]
@pcm211 which stylesheet is this?

**Comment by mooreds** [comment]
I saw this same behavior not when I upgraded, but when I customized the cover images and favicon.

This is with 5.6.0, slightly customised, on heroku.

Will try some of these fixes and report back.

**Comment by thefoodcorridor** [comment]
@rap1ds: "Sometime ago we made a change and got rid of the  asset-sync  gem which was responsible for syncing the static assets to S3. So nowadays the recommended way is to use CDN to serve assets."

What is the suggested method for getting the assets up to s3 or the CDN?  It seems like `asset-sync` is the best way to do so, but is there another recommended solution?

**Comment by pcm211** [comment]
@niiamon  works for all

**Comment by rap1ds** [comment]
Can someone verify that #1850 fixes the issue?

**Comment by mooreds** [comment]
@rap1ds I cherry picked your commit: d6d2312ce7ef5b4b41fac5b0d22042314e2634b3

and see this issue:

http://cdn.hostname/stylesheets/font-awesome.min.css is 404ing

However, http://cdn.hostname/assets/application-11b52adadf1e65dc38d27fef209374f5.css is found.

Is there perhaps an issue with not generating the SHA-1 for the font css?

**Comment by rap1ds** [comment]
@mooreds You're right. Sorry, I didn't test this well. `The font-awesome.min.css` was missing from the `precompile` array. I added it there now.

@mooreds Can you test the branch again and see if that fixed the issue?

I tested this locally and it seemed to work both in production and in development mode.

(Btw. you may need to `rm -rf public/assets` after running `RAILS_ENV=production rake assets:precompile`)

**Comment by mooreds** [comment]
@rap1ds I cherry picked your new commit: 02d2444cbd37272c44e4033eab93d1a22b625ee8

And am now seeing the css file being picked up.

The icons are still not working, however.

In firefox, I see this error message:

```
11:12:08.608 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cdn.myhostname.com/assets/fontawesome-webfont-1915930f1472653f6c46ed363f6efb63.woff?v=3.0.1. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>
11:12:08.609 downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source: http://cdn.myhostname.com/assets/fontawesome-webfont-1915930f1472653f6c46ed363f6efb63.woff?v=3.0.11 font-awesome.min-521b63c0cf985c8af2162da650a878f6.css:22:14
```

In Chrome, I see a similar message:

```
Font from origin 'http://cdn.myhostname.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://app.myhostname.com' is therefore not allowed access.
util.js:220 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
```

This SO answer seemed to fix the issue: http://stackoverflow.com/questions/22487079/phusion-passenger-heroku-cloudfront-cors-configuration but I'm still struggling with getting the fonts to be served with the correct CORS headers.

**Comment by mooreds** [comment]
I was able to get the correct CORS headers set through a custom nginx.conf file, as outlined here: http://stackoverflow.com/questions/25945419/how-do-i-configure-access-control-allow-origin-with-rails-and-nginx/25977267#25977267 

(make sure you grab the latest version of the config file using `heroku bash` and put the access control headers ahead of `<%= include_passenger_internal_template('rails_asset_pipeline.erb', 8, false) %>`).

**Comment by pcm211** [comment]
@rap1ds I have checked ...  The issue of automatic uploading of fonts and icons still remains ....although .now manualy uploading to buckets eliminates the problem of fonts and icons not being found .... This is a gr8 interim achievement though

**Comment by dwidoo** [comment]
@pcm211 Hey I tried to follow your advice and inserted the `@import url` line. Then I can see this line in html source code, but css seems to not be used since fonts are still missing...
Any idea?

**Comment by pcm211** [comment]
there was a problem of compiling the assets ....  at least if you blindly followed the instl instructions of README.md   ...... Now this has been identified as many were facing problems and has been rectified 
and closes this long impending issue :)

$ RAILS_ENV=production rake assets:precompile

Ref Pull Request #2440

**Comment by rap1ds** [comment]
In version 5.9.0 we got rid of css compilation step (thanks @bladealslayer!). That changed fixed also this issue.
