### ISSUE TITLE
Can't run tests, fails with "cannot load such file -- rails_helper"

### ISSUE THREAD

**Issue by mooreds** [sharetribe/sharetribe#1833]
##### Sharetribe Version:

efae2f0d50382660c77d1783a07204f2efdc8126

(I'm making some changes, so that may not be in the GH repo.)

##### Environment:

Ubuntu trusty/64 on vagrant

##### Server mode:

Development

##### Description:

Trying to run the tests, and unable to do so.

##### Steps To Reproduce:

Follow instructions here: https://github.com/sharetribe/sharetribe#running-tests

When you get to step 4, the error messages displayed below occur.

Expected result: Tests run

Actual result: See stack traces below

See link below for fix as well.

##### Additional information

```
vagrant@vagrant-ubuntu-trusty-64:~/sharetribe$ zeus test
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- rails_helper (LoadError)

```

```
vagrant@vagrant-ubuntu-trusty-64:~/sharetribe$ rspec spec
/home/vagrant/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- rails_helper (LoadError)
```

Needed to follow the instructions here: http://stackoverflow.com/a/25804049 but I didn't overwrite `spec/spec_helper.rb`

**Comment by mooreds** [comment]
I merged in master two days ago, if that helps with the versioning at all.

**Comment by mooreds** [comment]
I guess I'd just modify the docs to suggest the rake action.

**Comment by rap1ds** [comment]
I wasn't able to reproduce the issue. I'm on latest master (cdd9e9f), in the root directory of Sharetribe and  both `zeus rspec` and `rspec spec` commands work without any issues.

Is the stacktrace really that short or did you shorten it?

Btw. have you updated your `rspec` or `rspec-rails`? Can you post the versions of these gems from the Gemfile.lock?

**Comment by mooreds** [comment]
I did shorten it.  Hmmm.  I wonder if I had screwed something up.  Since the workaround was fine, and I'm a rails newbie, it is possible I didn't do something.  

Here's the versions of rspec:

```
vagrant@vagrant-ubuntu-trusty-64:~/sharetribe$ grep rspec Gemfile Gemfile.lock
Gemfile:  gem 'guard-rspec', "~> 4.3.1", require: false
Gemfile:  gem "rspec-rails", "~>3.0"
Gemfile.lock:    guard-rspec (4.3.1)
Gemfile.lock:      rspec (>= 2.14, < 4.0)
Gemfile.lock:    rspec (3.4.0)
Gemfile.lock:      rspec-core (~> 3.4.0)
Gemfile.lock:      rspec-expectations (~> 3.4.0)
Gemfile.lock:      rspec-mocks (~> 3.4.0)
Gemfile.lock:    rspec-core (3.4.2)
Gemfile.lock:      rspec-support (~> 3.4.0)
Gemfile.lock:    rspec-expectations (3.4.0)
Gemfile.lock:      rspec-support (~> 3.4.0)
Gemfile.lock:    rspec-mocks (3.4.1)
Gemfile.lock:      rspec-support (~> 3.4.0)
Gemfile.lock:    rspec-rails (3.4.2)
Gemfile.lock:      rspec-core (~> 3.4.0)
Gemfile.lock:      rspec-expectations (~> 3.4.0)
Gemfile.lock:      rspec-mocks (~> 3.4.0)
Gemfile.lock:      rspec-support (~> 3.4.0)
Gemfile.lock:    rspec-support (3.4.1)
Gemfile.lock:  guard-rspec (~> 4.3.1)
Gemfile.lock:  rspec-rails (~> 3.0)

```

I will just close this out, and if it pops up again for me or someone else, will try to provide more details.
