### ISSUE TITLE
S3 process not well documented

### ISSUE THREAD

**Issue by thefoodcorridor** [sharetribe/sharetribe#1840]
##### Sharetribe Version:

5.6.0

##### Environment:

n/a

##### Server mode:

n/a

##### Description:

S3 setup process is not well documented and should be.

##### Steps To Reproduce:

n/a

##### Additional information

n/a

**Comment by thefoodcorridor** [comment]
I have documented this and will send a PR.

**Comment by mooreds** [comment]
I noticed that the desire for documentation was mentioned here: https://github.com/sharetribe/sharetribe/issues/1568

**Comment by mooreds** [comment]
(Note that this is the first time I've ever used `git rebase`.  I read the contributing document, but please let me know if I missed anything.

**Comment by rap1ds** [comment]
Thanks for reporting the issue. This was fix by #1841
