### ISSUE TITLE
New products are not indexed in development environment

### ISSUE THREAD

**Issue by ankurj77** [sharetribe/sharetribe#1842]
##### Sharetribe Version:
Sharetribe v5.6.0 - d1ea5a4e9bf2cabaa2e6af259969d0c29998c307

##### Environment:
Google Cloud Server - Ubuntu
Linux 3.19.0-56-generic #62~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

##### Server mode:
Development Mode

##### Description:
When I add new products from admin or any other account, those are not available in the search or filters. When I manually update the index, then they come up.

##### Steps To Reproduce:
1. Add new product
2. Search for it - any word in title or description
3. Apply appropriate filter and try to find the product.

Expected result: The new product should appear in search or filter

Actual result: The new product is not found unless manually indexed.

##### Additional information
Manual indexing command -> bundle exec rake ts:index

**Comment by mooreds** [comment]
Were you running the delayed job worker in your dev environment?

**Comment by ankurj77** [comment]
@mooreds I am running the delayed job worker and web server using a nohup script from home directory of sharetribe:

nohup bundle exec rake jobs:work >> log/delayed-jobs-worker.log 2>&1 &
nohup bundle exec rails server -b 0.0.0.0 > log/web-server.log 2>&1 &

**Comment by ankurj77** [comment]
If I manually index using command "bundle exec rake ts:index", then the newly added products are added to the index, but I would like this to be automatic.

**Comment by ankurj77** [comment]
Surprisingly I was fixing an earlier issue which seems to have fixed this issue as well, not sure why!

https://github.com/sharetribe/sharetribe/issues/1834

**Comment by mooreds** [comment]
Huh.  OK.  Not sure why that fixed the issue. :
