### ISSUE TITLE
Zappy search failing

### ISSUE THREAD

**Issue by brakon** [sharetribe/sharetribe#1854]
##### Sharetribe Version:

a564fb7736dc169ccd91d25ecaf205571865c2dd

##### Environment:

Ubuntu

##### Server mode:

Development

##### Description:

Zappy search failing

##### Steps To Reproduce:

I had to update the config.yml to have external_search_in_use set to true so that the admin/settings/search preferences section shows up.

After setting search to location, the autocomplete shows as expected but once I search I get an error on app/services/listing_index_service/search/zappy_adapter.rb
    undefined method `+' for nil:NilClass
     line 36 res = @conn.get do |req|

I would guess its related to it needing 
API_KEY = APP_CONFIG.external_search_apikey
SEARCH_URL = APP_CONFIG.external_search_url

**Comment by mporkola** [comment]
Hi @brakon, "Zappy" is our custom search service, and we currently have it in use only in our hosted service. As you can't use it in open source installations, the location search functionality is not available in our open source version. We're considering open sourcing our search service, but right now there's unfortunately no supported way to have location search in open source Sharetribe. We're sorry about that, but the situation might change in the future depending on our roadmap priorities.

**Comment by xuanus** [comment]
@mporkola when do you think the search service will be pushed to open source? Thanks!

**Comment by sktoiva** [comment]
Hi @xuanus, as you might have noticed we just published Harmony - our availability managament backend: https://github.com/sharetribe/harmony. 

The timeline for publishing our search service is still open.  There's still some amount of documentation to finish before we can publish the service. Plus, open sourcing Harmony might teach us a bit more about the open sourcing process and what is needed for things to go smoothly.

Sorry that we cannot give you a definite timeline. But well keep the community posted when we decide to move forward with the search api open sourcing.
