### ISSUE TITLE
Multiple Listings from the same geo sensed location showing up but not able to browse

### ISSUE THREAD

**Issue by pcm211** [sharetribe/sharetribe#1871]
##### Sharetribe Version:

Stable 5.6.0 & Master

##### Environment:

Ubuntu, AWS, S3, RDS

##### Server mode:

Production

##### Description:

When multiple listings are made from a same geo location the listings when seen in map view are seen as the number ; but on the clicking the location icon generated ... it is not possible to browse the multiple listings from the geo place. 

Only one listing is seen 

##### Steps To Reproduce:

Post multiple listings without by automatically generated geo location

Expected result: A forward and back arrow /marker for browsing to see multiple listings posted from the same place

Actual result: Only one result is seen although multiple listings are shown

##### Additional information

![1](https://cloud.githubusercontent.com/assets/13811638/14274745/d5eb4d92-fb30-11e5-8711-feee8412e9e3.png)

Map View

![1](https://cloud.githubusercontent.com/assets/13811638/14274833/5ee20bcc-fb31-11e5-9b64-fe093449636a.png)

On Clicking : No Arrow for mov etc

**Comment by rap1ds** [comment]
@pcm211 Thanks for reporting. Can you check if #1876 fixes the issue?
