### ISSUE TITLE
Location search not working

### ISSUE THREAD

**Issue by shoaibmalik786** [sharetribe/sharetribe#1914]
Hi
How can i enable location search in my marketplace.
I saw the feature_flags table and when i created a record in this table with feature: :location_search , it is still not searching by location.
Please help, Thanks in advance. :+1:

**Comment by sktoiva** [comment]
Hi @shoaibmalik786,

The location search is currently only available in our hosted platform. It uses our, still private and in-development, search platform. So, unfortunately, for os-users this option is not yet available. 

However, this situation is changing in the future as we get the platform ready with better documentation and publish it as open source.

**Comment by alamkanfi** [comment]
Do you have an idea when the sharetribe's location search functionality will be open sourced? Will it be similar to the excelent geocoder gem?

**Comment by rap1ds** [comment]
@alamkanfi Please see this topic in the Community Forum: https://www.sharetribe.com/community/t/will-the-new-improved-search-function-on-sharetribe-com-come-to-the-open-source-version/107/3

**Comment by emish23** [comment]
Hey, is there any update ?

**Comment by funahasf** [comment]
Does incompatibility of the location search in the open source also affect location input in each listing? In creating a new listing in my open source marketplace, typing anything doesn't get accepted in location input either clicking on the map.

**Comment by sainineeraj** [comment]
any updates to search capability in open source?

**Comment by aivils** [comment]
https://github.com/sharetribe/sharetribe/pull/3256 Please apply manually and ask author what is required to run it.
