### ISSUE TITLE
Sharetribe community url is 404ing

### ISSUE THREAD

**Issue by mooreds** [sharetribe/sharetribe#1965]
https://www.sharetribe.com/community shows 'not found' right now.

**Comment by mooreds** [comment]
![sharetribe-community](https://cloud.githubusercontent.com/assets/91825/14835685/48df1746-0bc8-11e6-930d-252237df6d1e.png)

**Comment by rap1ds** [comment]
Thanks for reporting! We have contacted the hosting provider. I hope they fix this soon.

**Comment by rap1ds** [comment]
Community Forum is now back online again. Sorry for the inconvenience.
