### ISSUE TITLE
JS client errors

### ISSUE THREAD

**Issue by clehner** [sharetribe/sharetribe#2042]
On page load I get errors in the console, e.g.:

```
[Error] TypeError: SyntheticEvent.augmentClass is not a function. (In 'SyntheticEvent.augmentClass(SyntheticCompositionEvent, CompositionEventInterface)', 'SyntheticEvent.augmentClass' is undefined)
[Error] TypeError: undefined is not an object (anonymous function)
[Error] ReferenceError: Can't find variable: $ Global Code (localhost:1194)
[Error] ReferenceError: Can't find variable: $ Global Code (localhost:1204)
[Error] ReferenceError: Can't find variable: $ Global Code (localhost:1208)
```

I have followed the instructions in the README. Assets are built, but looks like jQuery is
missing or something. Advice?

Debian testing, ruby 2.3.1, sharetribe@86eed984d42b88c62eb791b55e6c5d03740d2c8e, env=production

**Comment by rap1ds** [comment]
I have seen something similar in development environment, but never in production env. This might have something to do with React on Rails (or not... just guessing).

In development environment restarting the server fixes the issue.

@Gnito @mporkola @kpuputti any ideas?

**Comment by clehner** [comment]
I'd like to try resetting some state or doing something to fix this behavior but am not sure what to do.

The errors do not appear in Firefox or Chromium, but do in the Webkit-based browsers that I have tried.

**Comment by kpuputti** [comment]
@clehner Are you still seeing these errors?

**Comment by clehner** [comment]
@kpuputti I still see the errors in Webkit-based browsers (epiphany, surf). I have been working around it by using Chromium instead.

**Comment by jgillich** [comment]
I'm also getting this excat error in my own React app (I don't use sharetribe). The [React TodoMVC](http://todomvc.com/examples/react/) works fine in Epiphany, so this might or might not be an upstream issue..

**Comment by kpuputti** [comment]
I think jQuery missing is just a result of an error happening before jQuery could be downloaded.

SyntheticEvent is part of React's [event system](https://facebook.github.io/react/docs/events.html) and we have the latest React updated in the master branch. Could you test if you still get this error with master? Thanks.

**Comment by mporkola** [comment]
Closed as inactive.

**Comment by oksurf** [comment]
I seem to only git it in a WebKit browser, Firefox and Chrome are fine.

**Comment by imsurinder90** [comment]
I get below error:

`TypeError: SyntheticEvent.call is not a function. `

when the React based app is run using Webkit browser and is built(webpack) with the non-production mode.
I get no error when the app is run in production(`flag -p`) mode.

However, I have opened an issue in [React](https://github.com/facebook/react/issues/10582).
