### ISSUE TITLE
Error: Cannot find module "./app/startup/serverRegistration" (ExecJS::ProgramError)

### ISSUE THREAD

**Issue by wolfieorama** [sharetribe/sharetribe#2043]
##### Sharetribe Version:
86eed984d42b88c62eb791b55e6c5d03740d2c8e

##### Environment:

Linux ubuntu 14.04 64 bit
##### Server mode:

development 
##### Description:

when running the procfiles i am getting the following error:

 `webpackMissingModule ((execjs):79:43): Error: Cannot find module "./app/startup/serverRegistration" (ExecJS::ProgramError)`

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

1. step 13 and 14 of installation 

##### Additional information

my log below:

john@john-Lenovo-G40-30:~/sharetribe$ foreman start -f Procfile.static
07:59:20 rails.1               | started with pid 8649
07:59:20 rails-client-assets.1 | started with pid 8650
07:59:20 rails-server-assets.1 | started with pid 8652
07:59:22 rails-client-assets.1 | 
07:59:22 rails-client-assets.1 | > @ build:dev:client /home/john/sharetribe/client
07:59:22 rails-client-assets.1 | > webpack -w --config webpack.client.rails.build.config.js
07:59:22 rails-client-assets.1 | 
07:59:22 rails-server-assets.1 | 
07:59:22 rails-server-assets.1 | > @ build:dev:server /home/john/sharetribe/client
07:59:22 rails-server-assets.1 | > webpack -w --config webpack.server.rails.build.config.js
07:59:22 rails-server-assets.1 | 
07:59:26 rails-client-assets.1 | Webpack dev build for Rails
07:59:32 rails.1               | => Booting WEBrick
07:59:32 rails.1               | => Rails 4.2.5.2 application starting in development on http://0.0.0.0:3000
07:59:32 rails.1               | => Run `rails server -h` for more startup options
07:59:32 rails.1               | => Ctrl-C to shutdown server
07:59:32 rails.1               | ERROR when compiling base_js_code! See file tmp/base_js_code.js to correlate line numbers of error. Error is
07:59:32 rails.1               | 
07:59:32 rails.1               | Error: Cannot find module "./app/startup/serverRegistration"
07:59:32 rails.1               | 
07:59:32 rails.1               | webpackMissingModule ((execjs):79:43)
07:59:32 rails.1               | Object.<anonymous> ((execjs):79:114)
07:59:32 rails.1               | __webpack_require__ ((execjs):51:30)
07:59:32 rails.1               | (execjs):71:18
07:59:32 rails.1               | (execjs):74:10
07:59:32 rails.1               | /home/john/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
07:59:32 rails.1               | /home/john/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
07:59:32 rails.1               | /home/john/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'

**Comment by mporkola** [comment]
Hi, unfortunately I was unable to reproduce the error so I can't say for sure if this works. This branch will ensure that the React dependencies are built before Rails tries to access them: https://github.com/sharetribe/sharetribe/pull/2046

You can also try to run the Webpack build manually before starting the Rails server:
```bash
cd client && npm run build:client && npm run build:server
```

Let me know if this helps!

**Comment by rap1ds** [comment]
If the problem persist, you might want to try do some cleanup.

Running `rake tmp:clear assets:clobber` and removing `tmp/base_js_code.js` will remove all the previous files compiled by Webpack.

**Comment by ppope** [comment]
I had the same issue, but @mporkola's suggestion fixed it.
