### ISSUE TITLE
MySQL crashes on negative community_id value

### ISSUE THREAD

**Issue by vbklv** [sharetribe/sharetribe#2049]
##### Sharetribe Version:

980d4384f91b15756d44c96b8881b2ab15e8331f

##### Environment:

OSX / EngineYard

##### Server mode:

Development

##### Description:

Somehow in 'listings' and 'people' tables there were records with 'community_id' = -1.
This caused the MySQL server to crash both locally and on development EngineYard/AWS instance.

##### Steps To Reproduce:

Update from 5.6.0 to 5.7.1

##### Additional information

N/A

**Comment by sktoiva** [comment]
Could you please provide more information? What kind of error did you encounter? Log extracts might be helpful. What is your MySQL version? 

The schema of the `listings` and `people` table should define for the `community_id`column a type `INT`that supports negative values.

**Comment by rap1ds** [comment]
Closing as inactive.
