### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by JerryChr** [sharetribe/sharetribe#2074]
##### Sharetribe Version:
5.7.1

##### Environment:
Ubuntu 14.04

##### Server mode:
Development

##### Description:
Issue is that one of the dependencies is only for darwin(Mac OS), the name of that dependency is: fsevents

Error log:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

##### Steps To Reproduce:
1. Setup Ubuntu 14.04 and try to follow the install documention..  
2. When you get to NPM install, not all dependencies will install.
3. See error output in description.

**Comment by JerryChr** [comment]
Found this after creating the issue: https://www.sharetribe.com/community/t/help-webpack-and-react/151/4 - will comment in there if I find more issues related to this.

**Comment by kpuputti** [comment]
Thanks for reporting. I'm glad the community forum post helped. :)

I'll close this now, feel free to reopen if the problem persists (or open a new issue if something else comes up).
