### ISSUE TITLE
ForbiddenAttributesError on setting Braintree Payment API keys

### ISSUE THREAD

**Issue by clehner** [sharetribe/sharetribe#2082]
When I attempt to create a transaction I get an error:
```
Jun 02 21:08:37 gsn bundle[11037]: {"method":"GET","path":"/en/transactions/new","format":"html","controller":"transactions","action":"new","status":500,"error":"ArgumentError: Cannot find new transaction path to listing_id: 238200, payment_gateway: , payment_process: {:id=>58167, :community_id=>18532, :author_is_seller=>true, :process=>:preauthorize}, booking: false","duration":108.05,"view":0.0,"db":30.42,"params":{"utf8":"✓","listing_id":"238200","locale":"en"},"host":"gsn.celehner.com","community_id":18532,"current_user_id":"qBFawj_sEwbV5sOZEh1IQQ","request_uuid":"45da8ca0-d6ca-48fa-812f-f20fc509fa7f"}
Jun 02 21:08:37 gsn bundle[11037]: ArgumentError (Cannot find new transaction path to listing_id: 238200, payment_gateway: , payment_process: {:id=>58167, :community_id=>18532, :author_is_seller=>true, :process=>:preauthorize}, booking: false):
Jun 02 21:08:37 gsn bundle[11037]: app/controllers/transactions_controller.rb:47:in `block in new'
Jun 02 21:08:37 gsn bundle[11037]: app/services/result.rb:52:in `on_success'
Jun 02 21:08:37 gsn bundle[11037]: app/controllers/transactions_controller.rb:29:in `new'
Jun 02 21:08:37 gsn bundle[11037]: lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
Jun 02 21:08:37 gsn bundle[11037]: {"method":"GET","path":"/500","format":"html","controller":"errors","action":"server_error","status":500,"duration":89.87,"view":3.55,"db":1.34,"params":{"utf8":"✓","listing_id":"238200","locale":"en"},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}
```

running be726387f2ccae84e8d26557f9ddf9c5c3ed7560, production mode. debian testing.

The setup I did is basically as follows:

1. Set up sharetribe according to the readme.
1. Import SQL dump from hosted sharetribe.
1. Insert row in `payment_gateways` with braintree sandbox credentials.
1. Update payment method in `payment_settings` table to be `braintree`

Now when I click the request button on a listing to create a transaction, I get an error "Marketplace temporarily unavailable" in the browser, and the stack trace as above. I notice in the stack trace `payment_gateway:` is empty, which makes me think the payment gateway is not set up properly. Also, I can't find in the web UI any links to configure the braintree payment method in the admin settings or in the user settings. Is there an additional step to setting up the braintree payment gateway that I am missing?

**Comment by rap1ds** [comment]
Indeed, the `payment_gateway` seems to be empty. One possible reason for that is that the listing was created before you configured the payment gateway. Other possible reason is that the gateway is not properly configured.

First thing that you should do is to make yourself a "super admin". Open the `people` table in the database, search your own user account and set the `admin` column value to `true`. Then go to the admin panel. Now you should see a link to configure Braintree. After you have configured the gateway properly, try to create a new listing and see if the payments work with the new listing. If they do, then you can try with the old listing. If the old listing fails, you may need to do some manual migrations.

I hope this helps!

(I'm closing this issue because this doesn't seem to be a bug in the Sharetribe code. However, feel free to continue the discussion in this thread. For future reference: The [community forum](https://www.sharetribe.com/community/) is the best place to ask installation help and support for open source issues)

**Comment by clehner** [comment]
Thank you @rap1ds. Setting is_admin to 1 in people caused the 'Braintree Payment API keys' to appear. Does using that form take the place of the instructions in the readme to `create a new row in the payment gateways table with your Braintree merchant_id, master_merchant_id, public_key, private_key and
client_side_encryption_key`?

After submitting the Braintree Payment API keys form, I get "Page not found". Log output (creds removed) is as follows:
```
Jun 03 15:02:02 gsn bundle[11037]: {"method":"POST","path":"/en/admin/communities/18532/payment_gateways","format":"html","controller":"admin/communities","action":"create_payment_gateway","status":500,"error":"ActiveModel::ForbiddenAttributesError: ActiveModel::ForbiddenAttributesError","duration":44.93,"view":0.0,"db":5.46,"params":{"utf8":"✓","authenticity_token":"********","payment_gateway":{"braintree_environment":"sandbox","braintree_public_key":"****************","braintree_private_key":"********","braintree_merchant_id":"gpbxsq5nb2k3xxbq","braintree_master_merchant_id":"****************","braintree_client_side_encryption_key":"******"},"community":{"commission_from_seller":"0"},"button":"","locale":"en","id":"18532"},"host":"gsn.celehner.com","community_id":18532,"current_user_id":"qBFawj_sEwbV5sOZEh1IQQ","request_uuid":"b2e3bb46-86ce-45bd-bf03-802c9bde4755"}
Jun 03 15:02:02 gsn bundle[11037]: ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
Jun 03 15:02:02 gsn bundle[11037]: app/controllers/admin/communities_controller.rb:184:in `create_payment_gateway'
Jun 03 15:02:02 gsn bundle[11037]: lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
Jun 03 15:02:03 gsn bundle[11037]: {"method":"POST","path":"/500","format":"html","controller":"errors","action":"not_found","status":404,"duration":28.0,"view":14.64,"db":1.37,"params":{"utf8":"✓","authenticity_token":"********","payment_gateway":{"braintree_environment":"sandbox","braintree_public_key":"********","braintree_private_key":"********","braintree_merchant_id":"********","braintree_master_merchant_id":"****************","braintree_client_side_encryption_key":"********"},"community":{"commission_from_seller":"0"},"button":"","locale":"en","id":"18532","path":"500"},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}
```

Do you have any idea what might be causing that ForbiddenAttributesError?

**Comment by usmanasif** [comment]
@clehner  In admin/Communities_controller#update_payment_gateway

line 234 (in my case)
braintree_params = params[:payment_gateway]

replace it with 

braintree_params = params.require(:payment_gateway).permit(
                                                              :braintree_environment,
                                                              :braintree_public_key,
                                                              :braintree_private_key,
                                                              :braintree_merchant_id,
                                                              :braintree_master_merchant_id,
                                                              :braintree_client_side_encryption_key
                                                              )

Hopefully attributes error will be settled.

**Comment by clehner** [comment]
@usmanasif after making that change and restarting the server, I still get the ForbiddenAttributesError

**Comment by buildmydream** [comment]
You'll have to do the same in 'admin/Communities_controller#create_payment_gateway' as well. Replace it with the following:
def create_payment_gateway
    braintree_params = params.require(:payment_gateway).permit(
        :braintree_environment,
        :braintree_public_key,
        :braintree_private_key,
        :braintree_merchant_id,
        :braintree_master_merchant_id,
        :braintree_client_side_encryption_key
    )
    @current_community.payment_gateway = BraintreePaymentGateway.create(braintree_params.merge(community: @current_community))
    update_payment_gateway
  end

**Comment by rap1ds** [comment]
If you @buildmydream or @usmanasif are able to make a PR that fixes this issue, that would be awesome!

**Comment by kpuputti** [comment]
Just noting here that we are currently working on removing Braintree support from the platform:

https://www.sharetribe.com/community/t/braintree-integration-will-be-removed-from-sharetribe/225

**Comment by rap1ds** [comment]
As @kpuputti pointed out, we're working on removing Braintree so I'll close this issue.

**Comment by woakes070048** [comment]
Is it still possable to use this. I am in the US

**Comment by rap1ds** [comment]
@woakes070048 Version [5.9.0](https://github.com/sharetribe/sharetribe/releases/tag/v5.9.0) is the last version that has Braintree integration. You can use that version if you want to.

**Comment by woakes070048** [comment]
@rap1ds I like the new version would you think it would be hard to port it to the latest version.

**Comment by rap1ds** [comment]
@woakes070048 It might be quite tricky 😕 But that's hard to estimate without trying...
