### ISSUE TITLE
JS errors in development: TypeError: Cannot read property 'assign' of undefined

### ISSUE THREAD

**Issue by rap1ds** [sharetribe/sharetribe#2087]
##### Sharetribe Version:

master branch, commit [b209e16ac8834ea65eee4ed4e81ebef5246eda34](https://github.com/sharetribe/sharetribe/commit/b209e16ac8834ea65eee4ed4e81ebef5246eda34)

##### Environment:

Mac OSX

##### Server mode:

development

##### Description:

In certain situations JavaScript error `TypeError: Cannot read property 'assign' of undefined` happens. Because of this error, jQuery is unable to load resulting the page to be broken. Dynamic elements, such as menus are broken.

Here's a screenshot from the line where the error happens:

![screen shot 2016-06-06 at 10 06 48](https://cloud.githubusercontent.com/assets/429876/15814299/749f59a6-2bce-11e6-8ee7-f08d5b6a55dc.png)

Here's a screenshot of the console errors:

![screen shot 2016-06-06 at 10 05 42](https://cloud.githubusercontent.com/assets/429876/15814281/43ccf626-2bce-11e6-805b-376e6631df8b.png)

##### Steps To Reproduce:

1. Start Rails server with foreman

  ```foreman start -f Procfile.static```

1. Make sure that the JavaScript loaded properly and dynamic elements such as menu work
1. Make a whitespace change to any React related JavaScript file (e.g. add a new line). This will trigger a new JavaScript build, but it will NOT build app-bundle.js file (apparently webpack is smart enough to notice that the change was only a whitespace change):

   ```
10:02:05 rails-client-assets.1 | Hash: 10b8a8916155bc580ce2
10:02:05 rails-client-assets.1 | Version: webpack 1.13.0
10:02:05 rails-client-assets.1 | Time: 925ms
10:02:05 rails-client-assets.1 |            Asset     Size  Chunks             Chunk Names
10:02:05 rails-client-assets.1 | vendor-bundle.js  1.05 MB       1  [emitted]  vendor
10:02:05 rails-client-assets.1 |   app-bundle.css  8.25 kB       0  [emitted]  app
10:02:05 rails-client-assets.1 |     + 691 hidden modules
   ```

1. Refresh browser

Expected result: JavaScript loads properly, menu works

Actual result: JavaScript loading fails

##### Additional information

Instead of making a whitespace change, if you make a "real" change, e.g. add a `fuubar` function, webpack will build also the `app-bundle.js` and the error goes away.

Steps:

1. Add the following function to any React related JavaScript file:

  ```
  function fuubar() {
    console.log("foobar");
  }
  ```

1. Now you should see that a new build is triggered:

  ```
10:17:46 rails-server-assets.1 | Hash: 037fc29ea1876f55cedc
10:17:46 rails-server-assets.1 | Version: webpack 1.13.0
10:17:46 rails-server-assets.1 | Time: 881ms
10:17:46 rails-server-assets.1 |            Asset     Size  Chunks             Chunk Names
10:17:46 rails-server-assets.1 | server-bundle.js  1.96 MB       0  [emitted]  main
10:17:46 rails-server-assets.1 |     + 635 hidden modules
10:17:47 rails-client-assets.1 | Hash: abd6dee35f7e6e5a577e
10:17:47 rails-client-assets.1 | Version: webpack 1.13.0
10:17:47 rails-client-assets.1 | Time: 1721ms
10:17:47 rails-client-assets.1 |            Asset     Size  Chunks             Chunk Names
10:17:47 rails-client-assets.1 |    app-bundle.js  3.79 MB       0  [emitted]  app
10:17:47 rails-client-assets.1 | vendor-bundle.js  1.05 MB       1  [emitted]  vendor
10:17:47 rails-client-assets.1 |   app-bundle.css  8.25 kB       0  [emitted]  app
10:17:47 rails-client-assets.1 |     + 691 hidden modules
  ```

1. Refresh browser

Expected result: JavaScript loads properly, menu works

Actual result: JavaScript loads properly, menu works

**Comment by kpuputti** [comment]
This is also reproducible when using the `Procfile.hot` startup file and making a change in a CSS file.

**Comment by sktoiva** [comment]
Also reproducible by just restarting at least with `Procfile.static`. Meaning, working, running service with `Procfile.static` is shut down with `ctrl+c` and restarted with `foreman start -f Procfile.static` results in the same error.

**Comment by jareware** [comment]
I'm rooting for you guys!

**Comment by rap1ds** [comment]
Workaround:

Comment out the line 24 (babel-polyfill) in `webpack.client.base.config.js` : 

```js
    // See use of 'vendor' in the CommonsChunkPlugin inclusion below.
    vendor: [
      // 'babel-polyfill',
      'es5-shim/es5-shim',
      'es5-shim/es5-sham',
    ],

```

**Comment by orignMaster** [comment]
Please help me understand this properly. This only happens in development and not in production?

**Comment by rap1ds** [comment]
@orignMaster I'd love to help you to understand this properly 😊 The problem is that we don't fully understand this ourselves, otherwise it would've been fixed already, since this is pretty damn annoying bug.

Anyway, it seems that this is somehow related to webpack build during the development, so it's not happening in production.

**Comment by delblues** [comment]
@rap1ds this solutions works great. thanks @bladealslayer for pointing this here.

we would not to expect this on production env right?

**Comment by rap1ds** [comment]
@delblues Noup, should not happen in production.

**Comment by kpuputti** [comment]
This was a weird one.

My hypothesis: Webpack is apparently quite clever with detecting whitespace changes that don't require a full rebuild, but somehow different kinds of changes triggered partial builds that were missing libraries or broken otherwise.

Commening out [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) removed the [core-js](https://github.com/zloirock/core-js) polyfills from the build (breaking the bundle for older browsers like IE11). Since we needed only some of those polyfills, I tried to include only them in the build, but no matter what polyfill was included from core-js, the same issue came up.

I ended up switching to [es6-shim](https://github.com/paulmillr/es6-shim) which also enabled removing the separate [es6-promise](https://github.com/stefanpenner/es6-promise) polyfill since es6-shim already includes a Promise polyfill.

In the end I cannot reproduce the issue anymore and the application.js build is 10KB smaller, so that's nice. :)

Feel free to reopen this issue if the bug resurfaces.

**Comment by rap1ds** [comment]
@kpuputti Cooool! Seems to work!
