### ISSUE TITLE
Change market place from selling to rental type

### ISSUE THREAD

**Issue by ersandeepdh** [sharetribe/sharetribe#2137]
I've setup sharetribe on my server, But by mistake during setup I set the market place to selling. But instead I need it to be of type : rental.
Is there a way to do so without installing the entire thing again ? Any thoughts will help.
Thanks in Advance!

**Comment by rap1ds** [comment]
Sure! The "Selling" type is just a template for settings that we use when you create a new marketplace. It will set you an Order Type with title "Selling". All the order type settings can be changed afterwards. Go to Admin > Order Types and create a new Order Type with title "Renting" and select pricing unit "day", and that's basically it.

Btw. for support questions like this (i.e. not bug reports) the best place to ask is our Community Forum https://www.sharetribe.com/community/. Our intention is to keep Github Issues only for code issues.
