### ISSUE TITLE
Cannot find module '../features'

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2141]
I have installed the sharestribe on my machine (Mac os)
I got the error "Cannot find module '../features'" when doing "foreman start -f Procfile.static" in step 12
there's no features.js. So when including the node package, the error occured due to lack of features.js
I need the quick help.

**Comment by kpuputti** [comment]
Thanks for the report! Could you paste the full error output for context? Your version of Sharetribe and Node.js would also be helpful.

**Comment by Joaz** [comment]
I'm having the same issue with current git HEAD and nodejs v6.2.2

`$ rbenv exec foreman start -f Procfile.static 
17:05:04 rails.1               | started with pid 12525
17:05:04 rails-client-assets.1 | started with pid 12526
17:05:04 rails-server-assets.1 | started with pid 12528
17:05:04 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
17:05:04 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
17:05:04 rails.1               | app/assets/webpack/server-bundle.js found
17:05:04 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
17:05:04 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
17:05:04 rails-server-assets.1 | client/app/routes/routes.js found
17:05:05 rails-server-assets.1 | 
17:05:05 rails-server-assets.1 | > @ build:dev:server /home/jglauche/work/jasmin/sharetribe/client
17:05:05 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
17:05:05 rails-server-assets.1 | 
17:05:05 rails-client-assets.1 | 
17:05:05 rails-client-assets.1 | > @ build:dev:client /home/jglauche/work/jasmin/sharetribe/client
17:05:05 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
17:05:05 rails-client-assets.1 | 
17:05:06 rails-client-assets.1 | module.js:442
17:05:06 rails-client-assets.1 |     throw err;
17:05:06 rails-client-assets.1 |     ^
17:05:06 rails-client-assets.1 | 
17:05:06 rails-client-assets.1 | Error: Cannot find module '../features'
17:05:06 rails-client-assets.1 |     at Function.Module._resolveFilename (module.js:440:15)
17:05:06 rails-client-assets.1 |     at Function.Module._load (module.js:388:25)
17:05:06 rails-client-assets.1 |     at Module.require (module.js:468:17)
17:05:06 rails-client-assets.1 |     at require (internal/module.js:20:19)
17:05:06 rails-client-assets.1 |     at Object.<anonymous> (/home/jglauche/work/jasmin/sharetribe/client/node_modules/caniuse-api/dist/index.js:19:32)
17:05:06 rails-client-assets.1 |     at Module._compile (module.js:541:32)
17:05:06 rails-client-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
17:05:06 rails-client-assets.1 |     at Module.load (module.js:458:32)
17:05:06 rails-client-assets.1 |     at tryModuleLoad (module.js:417:12)
17:05:06 rails-client-assets.1 |     at Function.Module._load (module.js:409:3)
17:05:06 rails-client-assets.1 | 
17:05:06 rails-client-assets.1 | npm ERR! Linux 4.4.0-24-generic
17:05:06 rails-client-assets.1 | npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:dev:client"
17:05:06 rails-client-assets.1 | npm ERR! node v6.2.2
17:05:06 rails-client-assets.1 | npm ERR! npm  v3.9.5
17:05:06 rails-client-assets.1 | npm ERR! code ELIFECYCLE
17:05:06 rails-client-assets.1 | npm ERR! @ build:dev:client: `webpack -w --config webpack.client.config.js`
17:05:06 rails-client-assets.1 | npm ERR! Exit status 1
17:05:06 rails-client-assets.1 | npm ERR! 
17:05:06 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'webpack -w --config webpack.client.config.js'.
17:05:06 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
17:05:06 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
17:05:06 rails-client-assets.1 | npm ERR! not with npm itself.
17:05:06 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
17:05:06 rails-client-assets.1 | npm ERR!     webpack -w --config webpack.client.config.js
17:05:06 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
17:05:06 rails-client-assets.1 | npm ERR!     npm bugs 
17:05:06 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
17:05:06 rails-client-assets.1 | npm ERR!     npm owner ls 
17:05:06 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
17:05:06 rails-client-assets.1 | 
17:05:06 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
17:05:06 rails-client-assets.1 | npm ERR!     /home/jglauche/work/jasmin/sharetribe/client/npm-debug.log
17:05:06 rails-client-assets.1 | exited with code 1
17:05:06 system                | sending SIGTERM to all processes
17:05:07 rails.1               | terminated by SIGTERM
17:05:07 rails-server-assets.1 | terminated by SIGTERM
`

**Comment by Joaz** [comment]
To add, doing so in the latest version, commit 7bcbce3cc03cb80260fa080381ffa8bee1bf732c works.

**Comment by ppope** [comment]
Same issue! I'm on the latest commit.

```
$ git rev-parse --short HEAD
166854a

$ node --version 
v6.2.2

$ npm --version
3.10.2

$ foreman start -f Procfile.static
17:45:52 storybook.1           | started with pid 5386
17:45:52 rails-client-assets.1 | started with pid 5387
17:45:52 rails-server-assets.1 | started with pid 5389
17:45:52 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
17:45:52 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
17:45:53 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
17:45:53 rails-server-assets.1 | client/app/routes/routes.js found
17:45:54 rails-server-assets.1 | 
17:45:54 rails-server-assets.1 | > @ build:dev:server /home/ubuntu/sharetribe/client
17:45:54 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
17:45:54 rails-server-assets.1 | 
17:45:54 rails-client-assets.1 | 
17:45:54 rails-client-assets.1 | > @ build:dev:client /home/ubuntu/sharetribe/client
17:45:54 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
17:45:54 rails-client-assets.1 | 
17:45:54 storybook.1           | 
17:45:54 storybook.1           | > @ styleguide /home/ubuntu/sharetribe/client
17:45:54 storybook.1           | > start-storybook -p 9001
17:45:54 storybook.1           | 
17:45:55 rails-client-assets.1 | module.js:442
17:45:55 rails-client-assets.1 |     throw err;
17:45:55 rails-client-assets.1 |     ^
17:45:55 rails-client-assets.1 | 
17:45:55 rails-client-assets.1 | Error: Cannot find module '../features'
17:45:55 rails-client-assets.1 |     at Function.Module._resolveFilename (module.js:440:15)
17:45:55 rails-client-assets.1 |     at Function.Module._load (module.js:388:25)
17:45:55 rails-client-assets.1 |     at Module.require (module.js:468:17)
17:45:55 rails-client-assets.1 |     at require (internal/module.js:20:19)
17:45:55 rails-client-assets.1 |     at Object.<anonymous> (/home/ubuntu/sharetribe/client/node_modules/caniuse-api/dist/index.js:19:32)
17:45:55 rails-client-assets.1 |     at Module._compile (module.js:541:32)
17:45:55 rails-client-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
17:45:55 rails-client-assets.1 |     at Module.load (module.js:458:32)
17:45:55 rails-client-assets.1 |     at tryModuleLoad (module.js:417:12)
17:45:55 rails-client-assets.1 |     at Function.Module._load (module.js:409:3)
17:45:55 rails-client-assets.1 | 
17:45:55 rails-client-assets.1 | npm ERR! Linux 3.13.0-74-generic
17:45:55 rails-client-assets.1 | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dev:client"
17:45:55 rails-client-assets.1 | npm ERR! node v6.2.2
17:45:55 rails-client-assets.1 | npm ERR! npm  v3.10.2
17:45:55 rails-client-assets.1 | npm ERR! code ELIFECYCLE
17:45:55 rails-client-assets.1 | npm ERR! @ build:dev:client: `webpack -w --config webpack.client.config.js`
17:45:55 rails-client-assets.1 | npm ERR! Exit status 1
17:45:55 rails-client-assets.1 | npm ERR! 
17:45:55 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'webpack -w --config webpack.client.config.js'.
17:45:55 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
17:45:55 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
17:45:55 rails-client-assets.1 | npm ERR! not with npm itself.
17:45:55 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
17:45:55 rails-client-assets.1 | npm ERR!     webpack -w --config webpack.client.config.js
17:45:55 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
17:45:55 rails-client-assets.1 | npm ERR!     npm bugs 
17:45:55 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
17:45:55 rails-client-assets.1 | npm ERR!     npm owner ls 
17:45:55 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
17:45:55 rails-client-assets.1 | 
17:45:55 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
17:45:55 rails-client-assets.1 | npm ERR!     /home/ubuntu/sharetribe/client/npm-debug.log
17:45:55 rails-client-assets.1 | exited with code 1
17:45:55 system                | sending SIGTERM to all processes
17:45:55 storybook.1           | terminated by SIGTERM
17:45:55 rails-server-assets.1 | terminated by SIGTERM
```

Let me know what else I can provide.

**Comment by bladealslayer** [comment]
Try deleting `node_modules` and `client/node_module` and run `npm install` again. Make sure to use Node.js version 6.1.0. We haven't tested with other node versions.

**Comment by sureshblp71** [comment]
I am getting save issue I have node version - v6.2.1


00:08:43 rails-client-assets.1 | > @ build:dev:client /home/vishal/myapps/sharetribe/client
00:08:43 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
00:08:43 rails-client-assets.1 | 
00:08:44 rails-client-assets.1 | module.js:442
00:08:44 rails-client-assets.1 |     throw err;
00:08:44 rails-client-assets.1 |     ^
00:08:44 rails-client-assets.1 | 
00:08:44 rails-client-assets.1 | Error: Cannot find module '../features'
00:08:44 rails-client-assets.1 |     at Function.Module._resolveFilename (module.js:440:15)
00:08:44 rails-client-assets.1 |     at Function.Module._load (module.js:388:25)
00:08:44 rails-client-assets.1 |     at Module.require (module.js:468:17)
00:08:44 rails-client-assets.1 |     at require (internal/module.js:20:19)
00:08:44 rails-client-assets.1 |     at Object.<anonymous> (/home/vishal/myapps/sharetribe/client/node_modules/caniuse-api/dist/index.js:19:32)
00:08:44 rails-client-assets.1 |     at Module._compile (module.js:541:32)
00:08:44 rails-client-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
00:08:44 rails-client-assets.1 |     at Module.load (module.js:458:32)
00:08:44 rails-client-assets.1 |     at tryModuleLoad (module.js:417:12)
00:08:44 rails-client-assets.1 |     at Function.Module._load (module.js:409:3)

**Comment by bladealslayer** [comment]
Try with node version 6.1.0. Remember to delete `node_modules` and `client/node_modules` and run `npm install` again when you change the node version.

**Comment by shoaibmalik786** [comment]
Hi @bladealslayer - I am getting this error while doing npm install and rake assets:precompile
please suggest what do i need to do
npm install

> undefined postinstall /home/deployer/apps/rentiron
> cd client && npm install

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/home/deployer/.nvm/versions/node/v6.1.0/bin/node" "/home/deployer/.nvm/versions/node/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn

npm ERR! spawn ENOMEM
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Killed

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/home/deployer/.nvm/versions/node/v6.1.0/bin/node" "/home/deployer/.nvm/versions/node/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! undefined postinstall: `cd client && npm install`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the undefined postinstall script 'cd client && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/deployer/apps/rentiron/npm-debug.log

I have deleted the node_modules and client/node_modules
