### ISSUE TITLE
Asset is not being served from local.

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2176]
Sharetribe is too buggy. App version is 5.7.1. I have compiled that in digital ocean. But the asset is not served from local. Asset's basic uri is always pointing s3. Such is the case for awesomefont.

**Comment by bladealslayer** [comment]
Have you set `asset_host` to be your Sharetribe installation hostname? You can do that either in `config.yml` or by setting environment variable `asset_host`.

Example: `asset_host: www.example.com`

**Comment by llvc** [comment]
I cloned the last version and the phenomena got out. Thanks.
