### ISSUE TITLE
sharetribe doesn't support environment.

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2177]
I have used environment for s3 bucket in config.yml. <%=  ENV['S3_SECRET_KEY'] =>    but the value is not taken. and It shows error in that point.

**Comment by bladealslayer** [comment]
@llvc ERB pre-processing of the configuration YAML files is not available by default in Rails and we don't support that.

However, our configuration loader supports overwriting any value in `config.defaults.yml` by simply setting environment variable with the same name (not capitalised). For example, if you want to set `aws_access_key_id` and start a rails server in shell:

```bash
export aws_access_key_id=THE_KEY_ID
# start your rails server
```

**Comment by llvc** [comment]
Can I write like <%= ENV['S3_SECRET_KEY'] => in config.yml?

**Comment by rap1ds** [comment]
@llvc As @bladealslayer said, you don't need to do `<%= ENV['S3_SECRET_KEY'] %>`. Just set the environment variable with the same name than the config you want to override. And no, to my understanding you can't do `<%= ENV['S3_SECRET_KEY'] %>` in `config.yml`

**Comment by llvc** [comment]
Thanks. That is fixed. I have configured the environment variable in .rbenv-vars file
