### ISSUE TITLE
Google map is not displayed

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2186]
Hello, folks
My store doesn't display google map. It is deployed on digital ocean. When loading the web page, I got "Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error"
I want to fix this asap.

![screen shot 2016-06-29 at 5 35 41 am](https://cloud.githubusercontent.com/assets/12979715/16439766/b75301f4-3dbb-11e6-9356-f87e84ea8187.png)

**Comment by kpuputti** [comment]
Thanks for reporting.

You should generate a "browser key" following Google's [instructions](https://support.google.com/cloud/answer/6158862) and add it to the `google_maps_key` column in the `communities` table.

If there are errors about referrers, your API key domain restrictions are most likely wrong: https://support.google.com/cloud/answer/6310037

Let me know if this helps!

**Comment by llvc** [comment]
Thanks. That is fixed
