### ISSUE TITLE
How to support AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2187]
I am using S3 in Frankfurt. when uploading image, I got "AWS4-HMAC-SHA256 is not supported."
How should I configure this?

**Comment by bladealslayer** [comment]
We use `paperclip` for image upload to S3 and its default configuration doesn't set the S3 request signature to version 4. S3 in Frankfurt region requires version 4. See this related `paperclip` issue https://github.com/thoughtbot/paperclip/issues/1691. We're happily accepting contributions to Sharetribe to support that.

As a workaround, you can use Ireland (eu-west-1) region.

**Comment by bladealslayer** [comment]
If there's more interest in this, please discuss in https://www.sharetribe.com/community/.

**Comment by bladealslayer** [comment]
Should be resolved with #2539
