### ISSUE TITLE
delayed job worker doesn't work for image upload

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2194]
I was trying to upload a list. but it failed. 
**Test case**
1) I run "bundle exec rake RAILS_ENV=production jobs:work"
2) visit my store and login 
3) press a button "Post a new listing"
4) Scroll down to image upload and do the upload action.
Here the progress is never proceeded from 0%.
And the delay job is not triggered. I think it should be triggered for image uploading.

**Comment by llvc** [comment]
Fixed this
I set the domain and use_domain column in communities table.

**Comment by gdvwrmd** [comment]
Do you have the appropiate commands? I always get the syntax wrong and its driving me crazy...
