### ISSUE TITLE
MYSQL2 fails to install / Bundle 

### ISSUE THREAD

**Issue by hundhest** [sharetribe/sharetribe#2226]
##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:

Codeanywhere

##### Server mode:

Ubuntu

##### Description:

Fails to bundle install 

##### Steps To Reproduce:

Bundle install

An error occurred while installing mysql2 (0.3.20), and Bundler cannot continue.

**Comment by bladealslayer** [comment]
You probably lack MySQL client development headers (package `libmysqlclient-dev` on Ubuntu). If that doesn't help, please give some more details. What's the exact error from `mysql2` gem?

**Comment by bladealslayer** [comment]
Is this resolved @hundhest?
