### ISSUE TITLE
Unable to rebuild/index new filter in Sphinx

### ISSUE THREAD

**Issue by mstumpf818** [sharetribe/sharetribe#2334]
##### Sharetribe Version:

git rev-parse HEAD = 74f91070a05047bca645e5c5eb29998daac31b25

##### Environment:

Mac OS X 10.11.6

##### Server mode:

development

##### Description:

Sphinx will not build indexes after a new filter/field is added in the admin panel

##### Steps To Reproduce:

1. Set up dev environment according to: https://github.com/sharetribe/sharetribe/blob/master/README.md
2. Create new checkbox filter in Sharetribe admin panel
3. Create product with an option selected for checkbox filter
4. Go to product grid and apply the new filter

Expected result: Indexes should be rebuilt and product grid should sort/filter accordingly

Actual result: Cannot access product grid with query filters applied and cannot index or rebuild using Sphinx

##### Additional information

bundle exec rake ts:index

Generating configuration to /Users/mstumpf/Work/dev.eivey.com/config/development.sphinx.conf
DEBUG   SQL (0.7ms)  DELETE FROM `delayed_jobs` WHERE (handler LIKE ('--- !ruby/object:ThinkingSphinx::Deltas::%') AND locked_at IS NULL AND locked_by IS NULL AND failed_at IS NULL)
Sphinx 2.2.10-id64-release (2c212e0)
Copyright (c) 2001-2015, Andrew Aksyonoff
Copyright (c) 2008-2015, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/Users/mstumpf/Work/dev.eivey.com/config/development.sphinx.conf'...
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
indexing index 'custom_field_value_core'...
ERROR: index 'custom_field_value_core': sql_connect: SSL connection error: SSL is required but the server doesn't support it (DSN=mysql://sharetribe_dev:***@localhost:3306/sharetribe_development).
total 0 docs, 0 bytes
total 0.008 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'custom_field_value_delta'...
ERROR: index 'custom_field_value_delta': sql_connect: SSL connection error: SSL is required but the server doesn't support it (DSN=mysql://sharetribe_dev:***@localhost:3306/sharetribe_development).
total 0 docs, 0 bytes
total 0.000 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'listing_core'...
ERROR: index 'listing_core': sql_connect: SSL connection error: SSL is required but the server doesn't support it (DSN=mysql://sharetribe_dev:***@localhost:3306/sharetribe_development).
total 0 docs, 0 bytes
total 0.000 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'listing_delta'...
ERROR: index 'listing_delta': sql_connect: SSL connection error: SSL is required but the server doesn't support it (DSN=mysql://sharetribe_dev:***@localhost:3306/sharetribe_development).
total 0 docs, 0 bytes
total 0.000 sec, 0 bytes/sec, 0.00 docs/sec
skipping non-plain index 'custom_field_value'...
skipping non-plain index 'listing'...
total 0 reads, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
total 0 writes, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg

<img width="1364" alt="screen shot 2016-07-27 at 15 21 04" src="https://cloud.githubusercontent.com/assets/11161484/17189078/ea04feb4-540d-11e6-96ce-0ab85de96ff9.png">
<img width="1417" alt="screen shot 2016-07-27 at 15 21 09" src="https://cloud.githubusercontent.com/assets/11161484/17189077/ea03bf86-540d-11e6-9871-2208dc67e62b.png">

**Comment by bladealslayer** [comment]
You are probably running MySQL 5.7, which changes how SSL connections are handled / enforced. Sharetribe uses MySQL 5.6, but if you still want to use 5.7, you can remove the lines `mysql_ssl_ca: ...` in `config/thinking_sphinx.yml`.

**Comment by mstumpf818** [comment]
@bladealslayer thank you for your help

**Comment by mstumpf818** [comment]
@bladealslayer shouldn't the readme be updated with the specific version number?

**Comment by bladealslayer** [comment]
@mstumpf818 yes it should :) I'll do that.
