### ISSUE TITLE
I can't enable Landing Page feature at 5.7.1

### ISSUE THREAD

**Issue by delblues** [sharetribe/sharetribe#2339]
Hi,

I can't find the `clp_static_enabled` option at the file `config.yml` in the sharetribe version 5.7.1, as related in this article: https://github.com/sharetribe/sharetribe/blob/master/docs/landing-page.md.
I'm working locally, in development mode, believe this could be some issue, as long I did delete any file from this folder.

cheers

**Comment by bladealslayer** [comment]
The `config.yml` file is your local copy and is not inversion control. It's typically a copy of our defaults `config.default.yml`. You have to manually update it. See the `config.defaults.yml` for reference.

**Comment by delblues** [comment]
thanks @bladealslayer for yout response, but I also checked this file and I could't find this option in this version. I double checked on the repository, and I can't find this option too: https://github.com/sharetribe/sharetribe/blob/v5.7.1/config/config.defaults.yml 

T've tried to copy those parameters from the 5.8.0 code `config.defaults.yml` file but it also did not work form me. Im really not being able to activate de landing page in the 5.7.1 version.

**Comment by bladealslayer** [comment]
@delblues sorry, I didn't pay attention to the version number you mentioned. You can't enable landing page for v5.7.1 because it was released with v5.8.0 :)

**Comment by delblues** [comment]
@bladealslayer  thanks for clarify this!
