### ISSUE TITLE
Payment gateway does not appear after adding row in database

### ISSUE THREAD

**Issue by mstumpf818** [sharetribe/sharetribe#2344]
##### Sharetribe Version:

git rev-parse HEAD = 74f91070a05047bca645e5c5eb29998daac31b25

##### Environment:

Mac OS X 10.11.6

##### Server mode:

production

##### Description:

I entered the Braintree credentials as per the ReadMe [here](https://github.com/sharetribe/sharetribe/blob/master/README.md):

`Sharetribe's open source version supports payments using Braintree Marketplace. To enable payments with Braintree, you need to have a legal business in the United States. You can sign up for Braintree here. Once that's done, create a new row in the payment gateways table with your Braintree merchant_id, master_merchant_id, public_key, private_key and client_side_encryption_key.`

After stopping the jobs worker and the production server and starting both again I still didn't have an option to use the payment gateway as a regular user.  My only option was to message the seller after clicking the "buy" button.

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

1. Set up production environment from master
2. Enter braintree credentials as new row in database
3. Create a product with price and shipping price as user 1
4. Sign out as user 1
5. Create new user account as user 2
6. Click "buy" on user 1's product

Expected result: User should be directed to payment gateway

Actual result: User was presented with messaging system

**Comment by mstumpf818** [comment]
Is there a way to see what payment gateways are loaded in the system?   I couldn't find anything in the admin panel

Also, I used a Braintree sandbox account.  Would that be a problem?  Shouldn't the payment gateway still appear on the frontend?

**Comment by mstumpf818** [comment]
answer was found here: https://github.com/sharetribe/sharetribe/issues/2082

`First thing that you should do is to make yourself a "super admin". Open the people table in the database, search your own user account and set the admin column value to true. Then go to the admin panel. Now you should see a link to configure Braintree. After you have configured the gateway properly, try to create a new listing and see if the payments work with the new listing. If they do, then you can try with the old listing. If the old listing fails, you may need to do some manual migrations.`

**Comment by mstumpf818** [comment]
After configuring a super admin user and setting the braintree credentials in the admin panel instead of the database, I restarted the server and the job worker and created a new posting but I am still only offered a conversation option; no payment gateway appears.

**Comment by gnomet** [comment]
@mstumpf818 Thanks for the efforts for finding out the answer yourself, and I'm glad you gotten forward!

If Braintree is enabled correctly it shouldn't allow you to post new listings before setting the payment receiving details correctly. So something might still be missing..

Do you see the personal payment settings page (with braintree logo) if you click on your name  in upper bar (preferably when logged in with normal user account) and click settings? There should be "Payments" link below "Notifications" on the left. And that should take you to a page where you can enter your account info etc.

Having a sandbox BT account should not bother anything at this point. It should allow you to test things.

I apologize of our limited resources and documentation regarding Braintree. The core team currently doesn't use Braintree anymore, so things are not clear in our minds either at the moment. Actually at some point we probably try to remove BT support from the main repository, and make it a more community managed thing to keep up the BT support option. But for the time being, the code is still in main repo and we try to offer help where we can.

**Comment by mstumpf818** [comment]
@gnomet Thank you for your help.  I've read up on the Braintree support and how it's going to be removed in the future so I appreciate your input here.

When I logged in as a regular user, I do not see the Payments link under Notifications.  What can I do to diagnose the issue since I do see the Braintree option under the site admin panel?

**Comment by gnomet** [comment]
@mstumpf818 ok, pretty interesting that you see it in admin panel, but users don't see it in their settings..

One thing that could be double checked in the DB is that the payment_gateways seems to have a good looking row (everything before "checkout"stuff is filled), and check especially that the type column has "BraintreePaymentGateway" and that the community_id matches with the id of the right row in the communities table.

Based on your earlier messages it sounds like this probably is the case already, but good to check, as that is the thing checked in the code that determines if the payment settings should be shown to users..

Another way to check that the association is correct would be in Rails console to run:

`Community.last.payment_gateway`

(or if you have created multiple rows in the communities table use Community.find(ID_OF_THE_CORRECT_COMMUNITY) instead of Community.last)

That should print out something starting with BraintreePaymentGateway.

I'm not sure if these will help, but probably the best things that come to mind now.. Let me know if the settings look correct on those tests?

**Comment by mstumpf818** [comment]
@gnomet Ah, I figured out that I had configured Braintree in my production db and not the dev one.  After doing that I was able to see the payments field in the user's settings.

When trying to create a user's braintree account I got a Braintree::AuthenticationError message.  Does that mean the issue is with the payment gateway configuration or the user's configuration?  (I put in sample data for the user and sandbox credentials for the gateway.)

Also, I got the following message when I tried to run the Rails command.  What is the proper way of doing getting that information?
```
Mikes-MacBook-Pro:shop mstumpf$ bundle exec rake Community.last.payment_gateway
rake aborted!
Don't know how to build task 'Community.last.payment_gateway' (see --tasks)
```

**Comment by gnomet** [comment]
Hi @mstumpf818,

It sounds that you found the issue for which the Community.last.payment_gateway idea was for. But in case you want to get to the Rails console, where you can run such commands, the command to get there would be just `rails console` and then you can type quit to exit the console.

Unfortunately I don't immediately remember about the Braintree::AuthenticationError, and we don't have any more easy testing setup for that, but to me it sounds like the most probable cause would be that the (sandbox) credentials you've put in the Braintree configuration are not getting accepted in authentication.

So maybe good to double check the credentials and make sure you are able to log in with those to the Braintree control panel. Do you already have a production account credentials for Braintree also?

**Comment by mstumpf818** [comment]
@gnomet thank you for your help
