### ISSUE TITLE
Image upload not working (Broken images)

### ISSUE THREAD

**Issue by angelg95** [sharetribe/sharetribe#2347]
We are using the latest Sharetribe version (we have downloaded from official Github repo).
We are trying to setup Sharetribe in a AWS EC2 Ubuntu server. At the moment, we are running in Production mode. We are also using Puma as our web server (in case that's helpful). We are currently using Ruby 2.3.1 and Node 6.1 (as specified in the installation steps).

Once someone uploads an image (listing or profile), it appears broken. Sharetribe tries to display the resized or modified version, ie: /system/images/0ylBlOqk_M5--RCrW6CO3g/thumb/3_box.png?1470004670

Funny thing is when I go to /system/images/0ylBlOqk_M5--RCrW6CO3g/, I can see the original folder with the uploaded files, somehow it's failing to resize the image. At first I suspected it was related to Imagemagick, but I verified it was working and correctly configured.

I'm a being dazzled and don't know where else to look. Any help would be appreciated.

Thank you!

**Comment by bladealslayer** [comment]
Are you running a worker process? The worker is responsible for resizing uploaded images. You normally start the worker with

```
$ bundle exec rake jobs:work
```

as described in the `README.md`

**Comment by lrojas94** [comment]
Hi, so, I tried your recommenation @bladealslayer , and sure enough, it was the workers issue. However, I'm running the instance in AWS EC2, and I put my workers in the background using &. They seem to fall asleep or something after a while. Is this normal?

**Comment by bladealslayer** [comment]
You shouldn't be starting background processes in your shell for production use. You can use some process manager like `supervisord` or write an `upstart` script to start the worker. That way, it would get restarted if it dies.

**Comment by dwidoo** [comment]
I am also interested in an example of a 'upstart' script to start the `delayed_job` worker at boot. 
@bladealslayer do we also need an 'upstart' script for Sphinx?

**Comment by bladealslayer** [comment]
@dwidoo actually, using `foreman` and a Procfile is also probably ok option. Haven't used that in production though yet, so can't comment on how stable it is.

The challenge with the Sphinx job and upstart would be that the job starts sphinx daemon in background, while upstart works best with foreground processes. You could probably get around that with some tweaking. Sorry, I don't have a ready example.

**Comment by dwidoo** [comment]
for `delayed_job` , I added `gem "daemons"` to my Gemfile and ran `RAILS_ENV=production script/delayed_job start` and now I don't need to run `RAILS_ENV=production bundle exec rake jobs:work`

**Comment by pcm211** [comment]
@bladealslayer ... what is the best option for starting the production envt ...(with phusionpassenger/nginx)
as classically we would love to have the fwg cmds run on boot 

1)  RAILS_ENV=production bundle exec rake ts:index  ---#once
2)  RAILS_ENV=production bundle exec rake ts:start -----#once

3) RAILS_ENV=production bundle exec rake jobs:work -- #persistent

which is the best soln ?
put cmd 1&2 in the ec2 user data/ bash script
cmd 3 in supervisored/upstart/daemons
