### ISSUE TITLE
User Signup and Email SMTP Delivery Broken.

### ISSUE THREAD

**Issue by lrojas94** [sharetribe/sharetribe#2355]
##### Sharetribe Version: ####
6811104b620530fe3f6e52844d00a4d80240451c
##### Environment: ####
Amazon EC2 (AWS) 

##### Server mode: ####
Production
##### Description: ####
* After user signup, redirection to /en/people/ returns 404 (not found).
* Email SMTP setup is not working.

##### Steps To Reproduce: ####

* For user signup:
Simply signup with any user email or so. I see the form has a redirect to /en/people/ which is not found. I checked the routes and there seem to be routes like /people/(:id), but no empty /people/ so, not sure what's going on here.

* For Email SMTP setup:
Add any SMTP provider to the config.yml or config.defaults.yml. So far, I've tried with gmail, outlook and mailchimp with no luck.

UPDATE:
It seems that the user signup problem is strictly related to the SMTP issue. As for the SMTP, still debugging here and there. I believe it might be my mistake, but will leave this out in case anyone comes up with an idea

**Comment by lrojas94** [comment]
Something useful to add to the docs:

* If Email setup is NOT working, user signup will **NOT** work either.

**Comment by Aero-geek** [comment]
@lrojas94  Did you manage to figure out the issue with the smtp settings?
