### ISSUE TITLE
Stripe Integration [Again]

### ISSUE THREAD

**Issue by murdoch** [sharetribe/sharetribe#2382]
I realise it's probably a pain for you guys to have to keep answering questions about Stripe integration, but after reading all of the closed issues on this subject I still can't figure out whether it's possible.

I ask because there is a freelance job available that requires Stripe to be intregrated with Sharetribe, and I don't want to undertake the work if it's something that can't be done as I'll likely not get paid if that's the case.

So I guess I have three questions: 
- Can Stripe be integrated into the open source version of Sharetribe?
- Does the company need to be based in USA (which is the case when integrating with Braintree)?
- Do we need to be hosted on Sharetribe.com or can we use Heroku/Openshift/SomethingElseThat'sBasedInEurope

Thanks I know it's annoying when people ask stupid questions like this, but I don't want to undertake any freelance work that can't be completed.

**Comment by dwidoo** [comment]
- Yes it can be integrated
- No company can be based in 25 countries [list here](https://stripe.com/global)
- Code is open source (thank you Sharetribe team) , you can host it wherever you want 
So yes you can integrate Stripe.
I have read [here](http://support.sharetribe.com/forums/240322-sharetribe-development-ideas/suggestions/6790422-integrate-with-stripe) that @Kusti (Sharetribe's CEO) thinks that MangoPay would be more interesting (escrow, e-wallets features...) than Stripe

**Comment by hansgtbrd** [comment]
Hi Murdoch, 

can you keep us in the loop on this? We'd be very interested in Stripe integration, and might be willing to chip in, or chip in for open-source adapation. We think this is a key feature that is missing from Sharetribe right now, and likely very very popular. 

http://support.sharetribe.com/forums/240322-sharetribe-development-ideas/suggestions/6790422-integrate-with-stripe

Cheers, 
Hans

**Comment by dwidoo** [comment]
Hey
@mooreds is working on building stripe connect into the open source version of sharetribe.
If you are interested, please either comment here, or sign up for the mailing list that he'd use to announce it: [http://eepurl.com/caicLf6](http://eepurl.com/caicLf6)

**Comment by delblues** [comment]
HI, @dwidoo and @mooreds , I would be part of this list for the stripe integration, I'm fully interested in that. This link above is no t working. tks

**Comment by mooreds** [comment]
@delblues, sorry, this is the correct link: http://eepurl.com/caicLf 

(no 6 at the end).

**Comment by hansgtbrd** [comment]
guys, this sounds awesome. We would be totally up for that. What is the
timeline? Even a ballpark would be great, whether this is fall 2016, spring
2017 or later.

**Comment by mooreds** [comment]
@hansgtbrd I'm not getting much of a response (I thought I'd get more than two email signups) so I am re-considering whether to keep working on this or not.

**Comment by dwidoo** [comment]
@mooreds Dan maybe you could communicate your project here: [http://support.sharetribe.com/forums/240322-sharetribe-development-ideas/suggestions/6790422-integrate-with-stripe](url)
163 people are waiting for this

**Comment by mooreds** [comment]
@dwidoo thanks!  I posted a comment there.

**Comment by hansgtbrd** [comment]
I would really think that the main issue is that people don't know about
this idea -- but Stripe is really needed, so pumping the idea out via some
channels might help!

**Comment by woakes070048** [comment]
@mooreds I just subscribed to the list. It would be a great intergration that is need for a self hosted version.

**Comment by hansgtbrd** [comment]
I agree, I think we need to tell more people about this great option...

**Comment by shoaibmalik786** [comment]
Hi Guys
I have integrated the stripe connect Standalone and Managed account both. Please get back to me if you want me to integrate it for you :)

Thanks

**Comment by woakes070048** [comment]
@shoaibmalik786 I could be interested in the code. How much would it cost?

**Comment by shoaibmalik786** [comment]
@woakes070048 - Please inbox me. My emails is shoaib2109@gmail.com

**Comment by mooreds** [comment]
Hi folks, 

Unfortunately, I wasn't able to make time to work on the stripe integration, and have been pulled off to other projects.  I don't expect to release this integration anytime soon.  I've updated the mailing list signup to reflect that.  

Hopefully @shoaibmalik786 can helps some folks out.

**Comment by shoaibmalik786** [comment]
Hey Guys
If you need my services, you can contact to me :)

Thanks
Shoaib

**Comment by woakes070048** [comment]
I would like to try and integrate with killbill.io. I have done it with php
but dont know ruby that well yet

**Comment by shoaibmalik786** [comment]
You decided to go with braintree, right?

**Comment by woakes070048** [comment]
Well i have version 5.8 or 5.9 running with braintree but if i could have
an integration with killbill then it allow for many payment gateways. Im
just wondering if you think you could do it.

**Comment by vivek2007** [comment]
@team I would like to integrate stripe and will commit, shall I do it ?

**Comment by woakes070048** [comment]
@vivek2007 if you are willing to develop it i would use it but i cant speak for everyone

**Comment by vivek2007** [comment]
@woakes070048, Ok thank you I will integrate and will do it

**Comment by woakes070048** [comment]
@vivek2007 thanks please keep me posted!

**Comment by vivek2007** [comment]
@woakes070048, make sure I will update you, once it will done.

**Comment by hansgtbrd** [comment]
indeed, we would also be interested...

**Comment by jarvisjohnson** [comment]
Hey guys - I've got Stripe Connect integrated [here](https://github.com/jarvisjohnson/sharetribe-stripe-connect).

This has been a big work in progress and will continue to be  - happy for anyone to use and would love for anyone to contribute to the code.

It's pretty basic at this point, and not as complex as Sharetribe's Paypal implementation.

It is using the 'standalone' version of Stripe Connect, meaning that sellers on your app will be given access to a Stripe Dashboard, as opposed to taking all actions from within the app.

Would be awesome to get the complete 'managed' version integrated - allowing complete white-labeling of Stripe Connect within your app.

**Comment by woakes070048** [comment]
@jarvisjohnson I will spin up a docker instance and start testing and using it for one of my projects. I have been using cocorico but sharetribe is a great platform. Thanks for doing the integration.

**Comment by hansgtbrd** [comment]
This is super, we plan to test this out soon.

**Comment by jarvisjohnson** [comment]
FYI guys - working on some issues people have found in the implementation.  I'll update here when fixed. Cheers

**Comment by jarvisjohnson** [comment]
Righto - all sorted with those issues now :)

**Comment by lbanovsky** [comment]
@jarvisjohnson I am trying to set up the stripe payments but I am not sure with some of the settings. In order to get the 'Stripe Client Id' I assume I have to go to 'Connect' section under my account at Stripe and fill the platform settings details. How should typically the 'Website URL' and mainly 'Redirect URIs' look like? Thanks

**Comment by jarvisjohnson** [comment]
Hey @lbanovsky  - Stripe just changed the dashboard around a bit the past couple of weeks, so I'll update the docs.

You should have a Client ID in your Stripe account, as well as testing + live secret and public keys, which you put in depending if you want real transactions or not.

[Client ID](https://dashboard.stripe.com/account/applications/settings); [Keys](https://dashboard.stripe.com/account/apikeys)

I didn't actually write about the redirect url in the readme; my mistake  - I'll update.  

The redirect url is where Stripe sends uses back to after the have connected their Stripe account.  

It should be the full site url + /connect/confirm 

Here are examples:

Site URL: https://mysite.com
Redirect URI: https://mysite.com/connect/confirm

Hope that helps :)

**Comment by hansgtbrd** [comment]
can anyone share experience on how this works?

PayPal remains the biggest problem for us, for our Sharetribe installation,
so would be extremely helpful to hear how this is working for people.

Thanks,
Hans

**Comment by thomasmalbaux** [comment]
Finally (you've waited for it for a long time!), **Stripe is available in Sharetribe marketplaces** and is, of course, **available in the open-source version too**!

Just update to the latest master branch to enjoy it. 

You can also look at the collections of articles in Sharetribe's Help Center to understand a bit more how it works: https://help.sharetribe.com/payments-and-transactions/online-payments-with-stripe/guide-to-getting-started-with-stripe-online-payments
