### ISSUE TITLE
foreman start error in development

### ISSUE THREAD

**Issue by anbublacky** [sharetribe/sharetribe#2436]
##### Sharetribe Version:

e5a04ab8fc6628bf33d453482433f4a096b356092
##### Environment:

Ubuntu 14 in dev, 16.04 in production
##### Server mode:

Development and production also
##### Description:

Getting different error in different environment
##### Steps To Reproduce:

foreman start -f Procfile.static

gives  me the following error in development

Webpack dev build for Rails
Server JS bundle missing after waiting for 30 seconds: 'app/assets/webpack/server-bundle.js'
exited with code 1
##### Additional information

In production i did follow this tutorial https://github.com/asm-products/lancrapp/blob/master/docs/vps-deployment.md

 ActionView::Template::Error (ERROR in SERVER PRERENDERING
App 6284 stdout: Encountered error: "ReferenceError: ReactOnRails is not defined"
App 6284 stdout: when prerendering OnboardingTopBar with props: {"progress":28.57142857142857,"next_step":"slogan_and_description"}
App 6284 stdout: js_code was:
App 6284 stdout: (function() {
App 6284 stdout:   var railsContext = {"href":"http://x.x.x.x/","location":"/","scheme":"http","host":"x.x.x.x","port":80,"pathname":"/","search":null,"i18nLocale":"en","i18nDefaultLocale":"en","httpAcceptLanguage":"en-US,en;q=0.8","marketplaceId":2,"loggedInUsername":"loveb","marketplace_color1":"#4a90e2","marketplace_color2":"#2ab865","serverSide":true};
App 6284 stdout: 
App 6284 stdout:   var props = {"progress":28.57142857142857,"next_step":"slogan_and_description"};
App 6284 stdout:   return ReactOnRails.serverRenderReactComponent({
App 6284 stdout:     name: 'OnboardingTopBar',
App 6284 stdout:     domNodeId: 'OnboardingTopBar-react-component-0',
App 6284 stdout:     props: props,
App 6284 stdout:     trace: false,
App 6284 stdout:     railsContext: railsContext
App 6284 stdout:   });
App 6284 stdout: })()

**Comment by kpuputti** [comment]
Thanks for reporting!

Does this happen every time? Are your packages up to date, i.e. have you ran `bundle install` and `npm install`?

**Comment by kpuputti** [comment]
@anbublacky What version are you running? The git hash you provided isn't found in our repo:

```bash
> git show e5a04ab8fc6628bf33d453482433f4a096b356092
fatal: ambiguous argument 'e5a04ab8fc6628bf33d453482433f4a096b356092': unknown revision or path not in the working tree.
```

**Comment by 1c7** [comment]
same here!

**Comment by 1c7** [comment]
check if you have install Webpack.
and check your Nodejs version > 6.1.0 shoule be fine.

and then restart your machine, run that foreman command again.

this method work for me.

**Comment by rap1ds** [comment]
Closing as inactive.
