### ISSUE TITLE
Installing Sphinx -with-mysql forces installation of MySQL 5.7

### ISSUE THREAD

**Issue by dwidoo** [sharetribe/sharetribe#2444]
##### Environment:

Mac OS X

##### Server mode:

Dev mode

##### Description:

Installing Sphinx -with-mysql forces installation of MySQL 5.7 but Sharetribe recommends installation of MySQL 5.6 on the README.md

Any tip please?

**Comment by pcm211** [comment]
hi try the fwg

Install the older version of mysql.

# Find older mysql versions
brew search mysql  

# Install older mysql version
brew install homebrew/versions/mysql56

# Start agent for older version of mysql (including on login)
ln -sfv /usr/local/opt/mysql56/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql56.plist

Then to switch to the older version.

# Unlink current mysql version
brew unlink mysql 

# Check older mysql version
ls /usr/local/Cellar/mysql56 # => 5.6.27

# Link the older version
brew switch mysql56 5.6.27

**Comment by rap1ds** [comment]
@dwidoo If you're not having any issues with the MySQL 5.7, just go with it. I'm pretty sure that everything works well with 5.7. We're probably at some point updating our database to 5.7 and then updating also the README.md
