### ISSUE TITLE
db:migrate doesn't work from 5.9.0 to 5.10.0 or 5.11.0

### ISSUE THREAD

**Issue by thecrabnebula** [sharetribe/sharetribe#2451]
bundle exec rake db:migrate does not update the database to the schema required by 5.10.0 or 5.11.0.

If I create a brand new database with 5.11.0 and initialise it with bundle exec rake db:schema:load it works, but if I use the database from 5.9.0 and try bundle exec rake db:migrate it doesn't.

**Comment by rap1ds** [comment]
Thanks for reporting!

Can you give a bit more information about the error you are seeing? What's the error? What's the stacktrace? What do you mean when you say "does not update". What happens?

**Comment by thecrabnebula** [comment]
When I compare the database tables available before and after I run db:migrate, there is no difference. Sharetribe 5.11.0 fails because the database structure has somehow changed, yet bundle exec db:migrate does not change the 5.9.0 database tables. For instance, there are several tables that have been deleted when I compare the database from 5.9.0 with a newly created one from 5.11.0.
If this could be fixed so the migrate makes the 5.9.0 exactly like the 5.11.0, any errors I am now experiencing running 5.11.0 with a 5.9.0 database structure are likely irrelevant.

**Comment by rap1ds** [comment]
Have you checked the `rake db:migrate:status` to make sure that all migrations have been run?

I'm also interested to know the exact steps you did when you upgraded from 5.9.0 to 5.11.0. Did you ran something like this? :

```
v5.9.0 > git checkout v5.10.0
v5.10.0 > rake db:migrate
v5.10.0 > git checkout v5.11.0
v5.11.0 > rake db:migrate
```

**Comment by thecrabnebula** [comment]
Thanks for your quick reply.

5.10.0 is broken in the development environment and doesn't work for other reasons, so I was hoping that 5.11.0 would work.
I'll try a gradual schema migration from 5.9->5.10->5.11, but this should be in the 5.11 schema anyway.

**Comment by thecrabnebula** [comment]
The incremental migration fixed it, thanks.
Cheers
