### ISSUE TITLE
Working good with node 6.2.2 in v5.9.0

### ISSUE THREAD

**Issue by delblues** [sharetribe/sharetribe#2464]
Guys, just to report that I'm working nice with v5.9.0 and node 6.2.2 in development env, just to let you know. I remember that there were a lot of issues with node and the new versions of sharetribe, forcing to use node 6.1.

i hope it helps in something

**Comment by kpuputti** [comment]
Thanks for the info!

We will probably update the version once the v6 becomes LTS: https://github.com/nodejs/LTS#lts_schedule
