### ISSUE TITLE
problem with google location search!

### ISSUE THREAD

**Issue by DinhThienLapDia** [sharetribe/sharetribe#2485]
Hello,

 i deployed sharetribe to my host (OS: ubuntu 16.04 LTS), everything is ok but the location search is not working. i tried to change the value of column main_search to 'location' in marketplace_configrations table but still not work, after reviewing the html code of home page, i can see controller still render search_bar not location_bar then i forced to change index.haml to location_bar but the function initializeLocationSearch() did not work again (but there is a javascript tag with this function)

What is the problem?

**Comment by kpuputti** [comment]
Hi @DinhThienLapDia !

Did you check the browser Developer tools console if there are any errors? Is the Google Maps script loaded?

![screen shot 2016-08-31 at 12 56 01](https://cloud.githubusercontent.com/assets/53923/18124304/55ad620a-6f7a-11e6-846c-ca50245c5b01.png)

There could also be a problem with the Google Maps API key, is there a warning/error related to that?

**Comment by kpuputti** [comment]
Never mind the potential Google Maps errors, I just realised that the new search backend that has the location search isn't open sourced yet. Therefore changing the main_search just breaks things in the current open source version.

You can follow updated for open sourcing the new search backend in the community forum thread:

https://www.sharetribe.com/community/t/will-the-new-improved-search-function-on-sharetribe-com-come-to-the-open-source-version/107

**Comment by DinhThienLapDia** [comment]
@kpuputti Thank you for reply 
After a short working, i can see that the problem in my case is with ZappyAdapter search.
