### ISSUE TITLE
Unable to run Sharetribe on local machine

### ISSUE THREAD

**Issue by 1c7** [sharetribe/sharetribe#2508]
##### Sharetribe Version:

c5f3d7c88486634cb25036e4a759ced6a2918918

##### Environment:
Ubuntu 16.04 LTS

##### Server mode:
development mode

##### Description:
```
foreman start -f Procfile.static
```
not working as expect

##### Steps To Reproduce:
Run  
```
foreman start -f Procfile.static
```

##### Additional information

```Bash
$ nodejs -v
v6.5.0

$ npm -v
3.10.3

$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

$ rails -v
Rails 4.2.7.1

```

## Error Message
```
a@ubuntu:~/Desktop/sharetribe$ foreman start -f Procfile.static
16:28:22 rails.1               | started with pid 43575
16:28:22 rails-client-assets.1 | started with pid 43576
16:28:22 rails-server-assets.1 | started with pid 43577
16:28:23 rails-client-assets.1 | Exporting routes...
16:28:23 rails-server-assets.1 | Exporting translations...
16:28:23 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
16:28:54 rails.1               | Server JS bundle missing after waiting for 30 seconds: 'app/assets/webpack/server-bundle.js'
16:28:55 rails.1               | exited with code 1
16:28:55 system                | sending SIGTERM to all processes
16:28:55 rails-client-assets.1 | terminated by SIGTERM
16:28:55 rails-server-assets.1 | terminated by SIGTERM
```
![image](https://cloud.githubusercontent.com/assets/1804755/18266910/638e01c0-744f-11e6-9a21-42fdaa097d41.png)

How to fix the problem? How can I run Sharetribe at my local Ubuntu 16.04 Machine?
Thank you!

**Comment by 1c7** [comment]
I think the problem relate to "Server JS bundle missing after waiting for 30 s ............"
I am not familiar with webpack(and foreman), I am still reading tutorial about both of them.

**Comment by 1c7** [comment]
`rails s -b 0.0.0.0`


<br/>
![image](https://cloud.githubusercontent.com/assets/1804755/18269490/d51fca7a-745a-11e6-9a87-bbf5ee4fd8d1.png)
<br/>
seem work, 
But I don't think this is correct way to do it.
otherwise you guys would write this into document.

**Comment by 1c7** [comment]
I think Node js version 6.5 probably is the problem?
I should use 6.1 exactly as the document saids?
I am using n to switching version, 
![image](https://cloud.githubusercontent.com/assets/1804755/18275385/59d7274a-7479-11e6-95f9-7b32c0605808.png)

I would get back once I got result.

**Comment by 1c7** [comment]
![image](https://cloud.githubusercontent.com/assets/1804755/18300186/7de37ea6-74f9-11e6-90ef-c5ef82210468.png)
![image](https://cloud.githubusercontent.com/assets/1804755/18300187/810d4e5e-74f9-11e6-81ea-ab01727f05b6.png)

Seem like It work now.
I didn't do anything special. I just restart my machine.
(still using nodejs 6.5.0 here.)

**Comment by 1c7** [comment]
## Conclusion
1. try restart your machine
2. try to run `bundle install` and `npm install` one more time
3. try to reopen your terminal
4. run both
```
foreman start -f Procfile.client-static
foreman start -f Procfile.static
```
and then close them,   
run `foreman start -f Procfile.client-static` or  `foreman start -f Procfile.static` again

**Comment by akhildave** [comment]
@1c7  Thank you 👍

**Comment by 1c7** [comment]
@skhildave you are welcome

**Comment by yaalsys** [comment]
Hi, 

I'm facing issue with formen start.  It keep running in the terminal which means this command didn't end.  Should I run this in background?


21:56:03 rails-client-assets.1 | started with pid 2766
21:56:03 rails-server-assets.1 | started with pid 2767
21:56:03 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
21:56:03 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
21:56:03 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
21:56:03 rails-server-assets.1 | client/app/routes/routes.js found
21:56:04 rails-server-assets.1 |
21:56:04 rails-server-assets.1 | > @ build:dev:server /home/ubuntu/sharetribe/client
21:56:04 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
21:56:04 rails-server-assets.1 |
21:56:04 rails-client-assets.1 |
21:56:04 rails-client-assets.1 | > @ build:dev:client /home/ubuntu/sharetribe/client
21:56:04 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
21:56:04 rails-client-assets.1 |
21:56:05 rails-server-assets.1 |
21:56:05 rails-server-assets.1 | > @ ensure-node-version /home/ubuntu/sharetribe/client
21:56:05 rails-server-assets.1 | > check-node-version --package
21:56:05 rails-server-assets.1 |
21:56:05 rails-client-assets.1 |
21:56:05 rails-client-assets.1 | > @ ensure-node-version /home/ubuntu/sharetribe/client
21:56:05 rails-client-assets.1 | > check-node-version --package
21:56:05 rails-client-assets.1 |
21:56:06 rails-client-assets.1 | node: v6.9.1
21:56:06 rails-server-assets.1 | node: v6.9.1
21:56:06 rails-server-assets.1 | npm: v3.10.8
21:56:06 rails-client-assets.1 | npm: v3.10.8
21:56:07 rails-client-assets.1 | Webpack dev build for Rails
21:58:12 rails-server-assets.1 | Hash: dd1959c5202b3e7c0513
21:58:12 rails-server-assets.1 | Version: webpack 1.13.2
21:58:12 rails-server-assets.1 | Time: 125544ms
21:58:12 rails-server-assets.1 |            Asset     Size  Chunks             Chunk Names
21:58:12 rails-server-assets.1 | server-bundle.js  2.97 MB       0  [emitted]  main
21:58:12 rails-server-assets.1 |    [0] multi main 40 bytes {0} [built]
21:58:12 rails-server-assets.1 |  [604] ./app/i18n/all.js 342 kB {0} [optional] [built]
21:58:12 rails-server-assets.1 |  [607] ./app/routes/routes.js 138 kB {0} [optional] [built]
21:58:12 rails-server-assets.1 |     + 773 hidden modules
21:59:25 rails-client-assets.1 | Hash: e719786ebfaf927849ce
21:59:25 rails-client-assets.1 | Version: webpack 1.13.2
21:59:25 rails-client-assets.1 | Time: 197159ms
21:59:25 rails-client-assets.1 |            Asset     Size  Chunks             Chunk Names
21:59:25 rails-client-assets.1 |    app-bundle.js  6.29 MB       0  [emitted]  app
21:59:25 rails-client-assets.1 | vendor-bundle.js   403 kB       1  [emitted]  vendor
21:59:25 rails-client-assets.1 |   app-bundle.css  64.1 kB       0  [emitted]  app
21:59:25 rails-client-assets.1 |    [0] multi app 28 bytes {0} [built]
21:59:25 rails-client-assets.1 |    [0] multi vendor 40 bytes {1} [built]
21:59:25 rails-client-assets.1 |  [289] ./app/routes/routes.js 138 kB {0} [optional] [built]
21:59:25 rails-client-assets.1 |     + 479 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 4 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules
21:59:25 rails-client-assets.1 | Child extract-text-webpack-plugin:
21:59:25 rails-client-assets.1 |         + 2 hidden modules

**Comment by 1c7** [comment]
@yaalsys  if you need run this in background, you can search about "Tmux".
great tool.
