### ISSUE TITLE
Hard coded path to missing image

### ISSUE THREAD

**Issue by thomassnielsen** [sharetribe/sharetribe#2513]
##### Sharetribe Version:

At least all 5.x.x releases

##### Environment:

All

##### Server mode:

All

##### Description:

The asset `ajax-loader-grey.gif` is hard coded to `https://s3.amazonaws.com/sharetribe/assets/ajax-loader-grey.gif` several places, a file which is no longer available.

##### Steps To Reproduce:

See [this search](https://github.com/sharetribe/sharetribe/search?utf8=%E2%9C%93&q=https%3A%2F%2Fs3.amazonaws.com%2Fsharetribe%2Fassets%2Fajax-loader-grey.gif) for everywhere where this path is hard coded. Try to open [this link](https://s3.amazonaws.com/sharetribe/assets/ajax-loader-grey.gif) to see that the asset is no longer hosted there.

##### Additional information

Suggested fix: Use dynamic path for this asset, everywhere it is used.

Possible temporary fix: Figure out why the asset is no longer available at the hard coded location and make it available again.

**Comment by mporkola** [comment]
Thanks for the report! Apparently we accidentally changed the file permission in S3, but it's now fixed. We're planning some bigger changes to the front page, and hardcoded paths will be probably gone after it's done.
