### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by jimix974** [sharetribe/sharetribe#2516]
Hello
I find a similar problem on issues but I try node 6.1, 6.2, and 6.5

I have the same error: 

npm WARN lifecycle undefined~postinstall: cannot run in wd %s %s (wd=%s) undefined cd client && npm install /sharetribe

How could I fix this problem please?

Thanks a lot

**Comment by rap1ds** [comment]
Thanks for reporting. In order to help you, we need some information. What's your Sharetribe version? What's your environment? (Windows/MacOsx/Linux) What's the full stacktrace? It's recommended to use the issue template.

The message you are showing seems to be only warning (WARN), not an error. What's the issue this is causing?

**Comment by jimix974** [comment]
excuse me for my let answer.

I suppose there is a pb with npm because on step 12 (start the development server), when I run "foreman start -f Procfile.static"

I have some error about npm and node



`08:48:22 rails-client-assets.1 | module.js:440
08:48:22 rails-client-assets.1 |     throw err;
08:48:22 rails-client-assets.1 |     ^
08:48:22 rails-client-assets.1 | 
08:48:22 rails-client-assets.1 | Error: Cannot find module '../features'
08:48:22 rails-client-assets.1 |     at Function.Module._resolveFilename (module.js:438:15)
08:48:22 rails-client-assets.1 |     at Function.Module._load (module.js:386:25)
08:48:22 rails-client-assets.1 |     at Module.require (module.js:466:17)
08:48:22 rails-client-assets.1 |     at require (internal/module.js:20:19)
08:48:22 rails-client-assets.1 |     at Object.<anonymous> (/home/jimix/sharetribe/client/node_modules/caniuse-api/dist/index.js:19:32)
08:48:22 rails-client-assets.1 |     at Module._compile (module.js:541:32)
08:48:22 rails-client-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
08:48:22 rails-client-assets.1 |     at Module.load (module.js:456:32)
08:48:22 rails-client-assets.1 |     at tryModuleLoad (module.js:415:12)
08:48:22 rails-client-assets.1 |     at Function.Module._load (module.js:407:3)
08:48:22 rails-client-assets.1 | 
08:48:22 rails-client-assets.1 | npm ERR! Linux 4.4.0-21-generic
08:48:22 rails-client-assets.1 | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dev:client"
08:48:22 rails-client-assets.1 | npm ERR! node v6.1.0
08:48:22 rails-client-assets.1 | npm ERR! npm  v3.8.6
08:48:22 rails-client-assets.1 | npm ERR! code ELIFECYCLE
08:48:22 rails-client-assets.1 | npm ERR! @ build:dev:client: `webpack -w --config webpack.client.config.js`
08:48:22 rails-client-assets.1 | npm ERR! Exit status 1
08:48:22 rails-client-assets.1 | npm ERR! 
08:48:22 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'webpack -w --config webpack.client.config.js'.
08:48:22 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
08:48:22 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
08:48:22 rails-client-assets.1 | npm ERR! not with npm itself.
08:48:22 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
08:48:22 rails-client-assets.1 | npm ERR!     webpack -w --config webpack.client.config.js
08:48:22 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
08:48:22 rails-client-assets.1 | npm ERR!     npm bugs 
08:48:22 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
08:48:22 rails-client-assets.1 | npm ERR!     npm owner ls 
08:48:22 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
08:48:22 rails-client-assets.1 | 
08:48:22 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
08:48:22 rails-client-assets.1 | npm ERR!     /home/jimix/sharetribe/client/npm-debug.log
08:48:22 rails-client-assets.1 | exited with code 1
08:48:22 system                | sending SIGTERM to all processes
08:48:23 rails.1               | terminated by SIGTERM
08:48:23 rails-server-assets.1 | terminated by SIGTERM
`

**Comment by rap1ds** [comment]
Thanks for additional information! 

I can spot two errors in the stacktrace.

1. `08:48:19 rails-server-assets.1 | Mysql2::Error: Access denied for user 'jimix'@'localhost' to database 'sharetribe_development'`

Rails is unable to access MySQL database in `localhost` using the user `jimix`. This means that there's a problem in your MySQL database or Rails database configurations. Make sure your database is up and running and a user `jimix` exists there. Also, check that the configurations in `config/database.yml` match with your database configurations.

2. `08:48:22 rails-client-assets.1 | Error: Cannot find module '../features'`

This one is not that obvious. It may be that fixing the MySQL issue will fix also this. If not, try to clean install npm as instructed here: https://github.com/sharetribe/sharetribe/issues/2141

I hope this helps you forward!

**Comment by jimix974** [comment]
It's ok for me for this step ..
I have another problem to start production environment, I open another issue.
Thanks a lot for your help

**Comment by mannixgb** [comment]
I'm having a similar issue (I get the same warning when I do npm install) and when I run "foreman start -f Procfile.static" I get a lot of NPM errors:

`
npm ERR! @ build:dev:server: 'webpack -w --config webpack.server.config.js'
npm ERR! @ build:dev:client: 'webpack -w --config webpack.client.config.js'
npm ERR!      npm owner ls
npm ERR! webpack -w --config webpack.server.config.js
npm ERR! webpack -w --config webpack.client.config.js
`

I haven't been able to find a solution to this specific issue, but the results look very similar to the one's in this thread along with a few others with a lot of NPM errors. What am I doing wrong?

**Comment by jimix974** [comment]
rap1ds give us the solution to clean the npm install

**Comment by rap1ds** [comment]
@jimix974 I already pointed you to the issue that has a comment which instructs how to do clean install, but here it is again: https://github.com/sharetribe/sharetribe/issues/2141#issuecomment-230491442

**Comment by mannixgb** [comment]
@rap1ds Any idea if I'm still getting this error after cleaning my NPM install? I'm using Node JS 6.1.0

**Comment by rap1ds** [comment]
@mannixgb Can you post the full error stacktrace?

**Comment by mannixgb** [comment]
@rap1ds Sure! 
root@tradezer:/var/www/html/sharetribe# node -v
v6.1.0
root@tradezer:/var/www/html/sharetribe# npm install
normalizeTree             ��� ����������������������������������������������������������������������������������������������normalizeTree ��� install   ��� ��������������������������������������������������������������������������������������������cloneCurrentTree ��� loadSh ��� ��������������������������������������������������������������������������������������������npm WARN lifecycle undefined~postinstall: cannot run in wd %s %s (wd=%s) undefined cd client && npm install /var/www/html/sharetribe
root@tradezer:/var/www/html/sharetribe# foreman start -f Procfile.static
19:20:35 rails.1               | started with pid 6650
19:20:35 rails-client-assets.1 | started with pid 6651
19:20:35 rails-server-assets.1 | started with pid 6653
19:20:35 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
19:20:35 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
19:20:35 rails.1               | app/assets/webpack/server-bundle.js found
19:20:35 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
19:20:35 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
19:20:35 rails-server-assets.1 | client/app/routes/routes.js found
19:20:37 rails-server-assets.1 | 
19:20:37 rails-server-assets.1 | > @ build:dev:server /var/www/html/sharetribe/client
19:20:37 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
19:20:37 rails-server-assets.1 | 
19:20:37 rails-client-assets.1 | 
19:20:37 rails-client-assets.1 | > @ build:dev:client /var/www/html/sharetribe/client
19:20:37 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
19:20:37 rails-client-assets.1 | 
19:20:38 rails-client-assets.1 | module.js:440
19:20:38 rails-client-assets.1 |     throw err;
19:20:38 rails-client-assets.1 |     ^
19:20:38 rails-client-assets.1 | 
19:20:38 rails-client-assets.1 | Error: Cannot find module '../features'
19:20:38 rails-client-assets.1 |     at Function.Module._resolveFilename (module.js:438:15)
19:20:38 rails-client-assets.1 |     at Function.Module._load (module.js:386:25)
19:20:38 rails-client-assets.1 |     at Module.require (module.js:466:17)
19:20:38 rails-client-assets.1 |     at require (internal/module.js:20:19)
19:20:38 rails-client-assets.1 |     at Object.<anonymous> (/var/www/html/sharetribe/client/node_modules/caniuse-api/dist/index.js:19:32)
19:20:38 rails-client-assets.1 |     at Module._compile (module.js:541:32)
19:20:38 rails-client-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
19:20:38 rails-client-assets.1 |     at Module.load (module.js:456:32)
19:20:38 rails-client-assets.1 |     at tryModuleLoad (module.js:415:12)
19:20:38 rails-client-assets.1 |     at Function.Module._load (module.js:407:3)
19:20:38 rails-client-assets.1 | 
19:20:38 rails-client-assets.1 | npm ERR! Linux 4.4.0-36-generic
19:20:38 rails-client-assets.1 | npm ERR! argv "/root/.nvm/versions/node/v6.1.0/bin/node" "/root/.nvm/versions/node/v6.1.0/bin/npm" "run" "build:dev:client"
19:20:38 rails-client-assets.1 | npm ERR! node v6.1.0
19:20:38 rails-client-assets.1 | npm ERR! npm  v3.8.6
19:20:38 rails-client-assets.1 | npm ERR! code ELIFECYCLE
19:20:38 rails-client-assets.1 | npm ERR! @ build:dev:client: `webpack -w --config webpack.client.config.js`
19:20:38 rails-client-assets.1 | npm ERR! Exit status 1
19:20:38 rails-client-assets.1 | npm ERR! 
19:20:38 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'webpack -w --config webpack.client.config.js'.
19:20:38 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
19:20:38 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
19:20:38 rails-client-assets.1 | npm ERR! not with npm itself.
19:20:38 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
19:20:38 rails-client-assets.1 | npm ERR!     webpack -w --config webpack.client.config.js
19:20:38 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
19:20:38 rails-client-assets.1 | npm ERR!     npm bugs 
19:20:38 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
19:20:38 rails-client-assets.1 | npm ERR!     npm owner ls 
19:20:38 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
19:20:38 rails-client-assets.1 | 
19:20:38 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
19:20:38 rails-client-assets.1 | npm ERR!     /var/www/html/sharetribe/client/npm-debug.log
19:20:38 rails-client-assets.1 | exited with code 1
19:20:38 system                | sending SIGTERM to all processes
19:20:38 rails.1               | terminated by SIGTERM
19:20:39 rails-server-assets.1 | terminated by SIGTERM

**Comment by rap1ds** [comment]
@mannixgb And what Sharetribe version are you using?

To be honest, I don't have a lot of ideas how to fix this. Seems that most people have solved the issue by installing correct node versions and then doing a clean install as instructed here: https://github.com/sharetribe/sharetribe/issues/2141#issuecomment-230491442 . If that's not working for you, then I don't know what to do...

Still couple questions that may or may not be helpful:

- What's your OS?
- Have you done any modifications?
- Can you reproduce this issue with a clean Sharetribe installation from the master branch?
