### ISSUE TITLE
session.rb file in sharetribe/app/models/session.rb seem like a useless file?

### ISSUE THREAD

**Issue by 1c7** [sharetribe/sharetribe#2645]
the content is 
```ruby
class Session

end
```

seem like a useless file. maybe you guys should delete this file?
😄

**Comment by rap1ds** [comment]
Yeah it's meant to be a model to provide access to `sessions` table and it should actually inherit from `ActiveRecord::Base`. Happy to merge a PR.

**Comment by 1c7** [comment]
ok, I would send a PR
