### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by asakk046** [sharetribe/sharetribe#2659]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:

_What's your environment? Mac OS X
_What's your node version? Run the following commands and copy the result here:_
 node v0.12.4
 npm  v2.10.1

##### Server mode:

development 
##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_ type in: npm install
1. _Step 2_ Get error

Expected result: _What was the expected result after running the steps above?_

Actual result: _What was the actual result after running the steps above?_

##### Additional information

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ postinstall: `cd client && npm install`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the @ postinstall script 'cd client && npm install'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

**Comment by rap1ds** [comment]
README.md: "Version 6.1 is currently used and we don't guarantee everything works with other versions. If you need multiple versions of Node, consider using n or nvm."
