### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rajm** [sharetribe/sharetribe#2712]
sharetribe/config/available_locales.rb:95: syntax error, unexpected ':', expecting end-of-input
default: &default_settings

when i run>bundle exec rake db:create db:structure:load to create the db tables it gives this error in available_locales.rb file

**Comment by rap1ds** [comment]
Can't reproduce. Please edit the issue to use the issue template and provide all the information in the template.

**Comment by rajm** [comment]
the branches were mixed i hope, i got it solved. Thanks
