### ISSUE TITLE
Can I put a "Tech Stack" Section in readme.md?

### ISSUE THREAD

**Issue by 1c7** [sharetribe/sharetribe#2780]
content as following:

## Tech Stack
- Ruby 2.3.1  
- Ruby on Rails 4.2.7  
- MySQL  5.7
- React + jQuery
- Node.js 6.9
- "what you see is what you get" Editor [Mercury](http://jejacks0n.github.io/mercury/)  
- Deploy: Custom Script (not using Mina or Cap3)  
- Server: Heroku
- Image Hosting: Amazon S3  
- Background job: delayed_job
- Gem: 
    -  devise | for Email/Username Signup/Login
    -  omniauth-facebook | Third party login: Facebook
    -  haml | easier to write HTML
    -  mysql2 | because sharetribe using mysql
    -  paperclip | image upload
    -  passenger | rails server
    -  react_on_rails
    -  factory_girl, capybara, rspec-rails, cucumber-rails, selenium-webdriver | for test

please correct me if any info in this is wrong 😄 

I just think this is easier for developer to understand Sharetribe.
Can I send a PR ?  or you guys can just copy & paste this into readme.

Thanks, have a nice day.

**Comment by rap1ds** [comment]
Go ahead and send a PR. I agree, this will make it easier someone reading the README to understand what's under the hood of Sharetribe.

**Comment by 1c7** [comment]
@rap1ds Thanks
