### ISSUE TITLE
delayed_job memory leak?

### ISSUE THREAD

**Issue by 1c7** [sharetribe/sharetribe#2797]
##### Sharetribe Version:
6.1.0

##### Environment:
Ubuntu 14.04

## The Problem
After running `bundle exec rake jobs:work`
This delay job would slowly take up all the memory the server have, and cause server down.
I have to manual restart server at Cloud Provider website (I am using Azure from Microsoft)

## How did you guys solve this problem ?
I am thinking about migrate from `delayed_job` to`sidekiq`

**Comment by rap1ds** [comment]
Ping @bladealslayer have you noticed any memory leaks in our production workers?

**Comment by bladealslayer** [comment]
No, I haven't, but ours get restarted once per day automatically anyway (by Heroku). @1c7 have you tried setting the ImageMagick-related memory limits? Maybe it's not memory leak, but memory spikes during image processing?

You can try setting these environment variables in the process that starts the workers:

```
MAGICK_MAP_LIMIT=64MiB
MAGICK_MEMORY_LIMIT=256MiB
MAGICK_TIME_LIMIT=30
```

**Comment by 1c7** [comment]
@bladealslayer Thank you, I would try your setting.

**Comment by 1c7** [comment]
https://github.com/collectiveidea/delayed_job/issues/823
According to this issue from delayed_job Github repo, I think it's not Image process problem, 
But I would try your solution anyway.  

Thanks again

**Comment by 1c7** [comment]
haven't test. I just decide migrate to sidekiq
