### ISSUE TITLE
Errro on e-mail confirmation when opening a account.

### ISSUE THREAD

**Issue by leofreitasusa** [sharetribe/sharetribe#2801]
Hello everyone.
I am facing a problem when creating a new account on the website.
The confirmation link comes with a subdomain on it, and it doesn't work.

My domain is outletdebeleza .com . br

And i got a e-mail like this:

http://**test-market**.outletdebeleza.com.br/pt-BR/people/confirmation?confirmation_token=%2F92EWlBPoSWiEPET 

With test-market before my domain. 

What do i have o do to fix it?

Thanks,

**Comment by rap1ds** [comment]
Hi! Thanks for reporting.

Have you read the instructions how to setup custom domain? https://github.com/sharetribe/sharetribe#setting-your-domain

If that doesn't help, please have a look at the [ISSUE_TEMPLATE.md](https://github.com/sharetribe/sharetribe/blob/master/ISSUE_TEMPLATE.md) and edit your issue to contain all the information asked in the issue template. We need to know the exact version of Sharetribe you are running and exact steps how to reproduce the issue.

**Comment by rap1ds** [comment]
Closing, inactive.
