### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by shoaibmalik786** [sharetribe/sharetribe#2813]
Hello Team
I am having issue while trying to signup with facebook, getting this error on clicking fb button
<script type='text/javascript' charset='utf-8'>top.location.href = 'https://www.facebook.com/v2.8/dialog/oauth?client_id=650287128462028&redirect_uri=http%3A%2F%lvh.me:30002Fpeople%2Fauth%2Ffacebook%2Fcallback&response_type=code&scope=public_profile%2Cemail&state=31ab941ece74e6d8ea028e67f5285362f9896b59ecb526cd';</script>

Any idea?

Thanks

**Comment by rap1ds** [comment]
Hi, thanks for reporting! Please tell us the exact Sharetribe version you are using and exact steps how we can reproduce the issue. Have a look at the ISSUE_TEMPLATE.md, it's a good template for filing issue reports with all the necessary information.

**Comment by shoaibmalik786** [comment]
Hi @rap1ds 
I am using the latest version of sharetribe and v2.8 of facebook sdk.

Thanks

**Comment by rap1ds** [comment]
Hi @shoaibmalik786 and thanks for the answer.

We haven't heard of any issues with Facebook signup from our sharetribe.com customers and I haven't seen this while doing development on my local machine. Do you have any additional information that would help us to reproduce the issue? We're not able to help that much without first being able to reproduce the issue.

**Comment by shoaibmalik786** [comment]
Hi i am able to fix the issue actually there was an issue with nginx
configuration. You can close this issue.
Thanks

**Comment by kwigley** [comment]
@shoaibmalik786 mind sharing what you had to change in nginx config? Having the same issue, thanks.

**Comment by mecjack** [comment]
Having the same issue, could you please tell me how you fixed it?
