### ISSUE TITLE
Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'description' can't have a default value

### ISSUE THREAD

**Issue by prakash-subramani** [sharetribe/sharetribe#2823]
##### Environment: Mac OS X

Node version: v6.3.1
npm version: 3.10.3

##### Description:

While running `rake db:migrate` it will gives following error

`Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'description' can't have a default value: ALTER TABLE `items` ADD `description` text DEFAULT ''/Users/prakash/.rvm/gems/ruby-2.3.1@global/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/Users/prakash/.rvm/gems/ruby-2.3.1@global/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/Users/prakash/.rvm/gems/ruby-2.3.1@global/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/Users/prakash/.rvm/gems/ruby-2.3.1@global/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
`

Any help?

**Comment by rap1ds** [comment]
Thanks for reporting!

Since you are running `rake db:migrate`, I assume you are upgrading your Sharetribe version and not doing a clean install, am I right? If you do clean install, run `rake db:structure:load` instead as instructed in the [installation instructions](https://github.com/sharetribe/sharetribe#setting-up-the-development-environment) From which version are you upgrading?

**Comment by prakash-subramani** [comment]
yeah `rake db:structure:load`  resolved my problem. Thanks

**Comment by johnsonyeap** [comment]
@prakash-subramani, did you manage to run the following command to generate schema.rb file?
```
bundle exec rake db:migrate
```

#2844

**Comment by ramesh2007** [comment]
Iam getting same error here while run the rake db:migrate

If I tried to reload there is no schema and structure

/home/vivek/Documents/matchtrials/db/structure.sql doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /home/vivek/Documents/matchtrials/config/application.rb to limit the frameworks that will be loaded.
