### ISSUE TITLE
Delayed job: Can't allocate memory

### ISSUE THREAD

**Issue by kaiyum2012** [sharetribe/sharetribe#2828]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version: 6.1.0
f4c11e349499c2e93ea6aead5f0e64df73bca086

##### Environment: digitalocean

```
> node -v 6.9.0
> npm -v 3.10.8
```

##### Description:
Signup and invite email not working with sendmail or smtp (Gmail). forget password and test email working fine! I have tested with skip_email_confirmation : true/false in config.yml file. while true and send confirmation it won't work.

**Comment by rap1ds** [comment]
Hi! Thanks for reporting.

It seems that the version you are using is not found from Sharetribe repository. https://github.com/sharetribe/sharetribe/commit/f4c11e349499c2e93ea6aead5f0e64df73bca086 leads to page not found. So apparently you have done your own edits to your installation.

Are you able to reproduce this with a fresh Sharetribe installation? What's to commit hash of a version in Sharetribe repo where this is reproducable?

Are you sure you have workers running on the background?

**Comment by kaiyum2012** [comment]
sorry. its `6cc767763d657e36bc98128832d066770f958b9c` 

And now it's working after running Delayed_job.

Now the issue is Delayed job get killed at some random time. 

I am using this `script/delayed_job start` in the development environment.  How to prevent it to get killed or closed at random time.

deployed_job.rb

```
require 'delayed_job'

class DelayedJobLoggerPlugin < Delayed::Plugin

  callbacks do |lifecycle|

    lifecycle.around(:invoke_job) do |job, &block|
      logger.info "Running job", :running, job_to_hash(job)
      begin
        block.call(job)
        logger.info "Job success", :success, job_to_hash(job)
      rescue Exception => e
        # log and reraise
        logger.info "Job error: #{e.inspect}", :error, job_to_hash(job)
        raise e
      end
    end
  end

  def self.job_to_hash(job)
    payload = job.payload_object # Usually the Struct, but can be a PerformableObject also

    case payload
    when Struct
      {job_name: payload.class.name, args: payload.to_h }
    when Delayed::PerformableMethod
      {job_name: "#{payload.object.to_s}.#{payload.method_name.to_s}", args: payload.args.to_s}
    else
      {payload: payload.inspect}
    end
  end

  def self.logger
    @logger ||= SharetribeLogger.new(:delayed_job)
  end
end

Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.max_attempts = 3
Delayed::Worker.max_run_time = APP_CONFIG.delayed_job_max_run_time.to_i.seconds
Delayed::Worker.default_priority = 5
Delayed::Worker.default_queue_name = "default"
Delayed::Worker.plugins << DelayedJobLoggerPlugin
```

Thanks in advance.

**Comment by kaiyum2012** [comment]
@rap1ds  I am using monit to monitor delayed_job and from database log, I came to know, the paperclip is facing an issue. 


![screenshot_67](https://cloud.githubusercontent.com/assets/5669573/21452882/0176f092-c930-11e6-8c47-238d54016b04.png)
![screenshot_68](https://cloud.githubusercontent.com/assets/5669573/21452881/01769e4e-c930-11e6-8bf2-429c85462973.png)




I found this link: [fighting-paperclip-errno-enomem-error](http://blog.sundaycoding.com/blog/2014/02/05/fighting-paperclip-errno-enomem-error/ )


my concern is, **1 GB RAM is enough**? Thanks for your precise support.

**Comment by pcm211** [comment]
@kaiyum2012 have swap introduced to your system .... wud exponentially help you

**Comment by kaiyum2012** [comment]
Thanks hopefully it will help.

**Comment by rap1ds** [comment]
@kaiyum2012 Thanks for digging this up. The article you posted [fighting-paperclip-errno-enomem-error](http://blog.sundaycoding.com/blog/2014/02/05/fighting-paperclip-errno-enomem-error/) seems interesting! 

@bladealslayer is this something we should have a closer look?

**Comment by kaiyum2012** [comment]
@rap1ds thanks I will surely check it. Once again thanks for your support.

**Comment by bladealslayer** [comment]
@kaiyum2012 try setting ImageMagick resource limits (via environment variables):

```
MAGICK_MAP_LIMIT=64MiB
MAGICK_MEMORY_LIMIT=128MiB
MAGICK_TIME_LIMIT=60
```

See https://www.imagemagick.org/script/resources.php for details.

**Comment by kaiyum2012** [comment]
@bladealslayer thanks. I have tried this solution I think. I will again look for it. hope it will work.

**Comment by rap1ds** [comment]
Closing, inactive.
