### ISSUE TITLE
New payment gateway/ provision

### ISSUE THREAD

**Issue by delblues** [sharetribe/sharetribe#2830]
Hello there,
I'm trying to understand how sharetribe works with the objective to implement an new payment gateway for the solution, but it's being very hard to understand some things in the code. I read all the information available here, and at the github issues forum, but I'm not able to find nothing straightforward - unless a lot of tips which drove me until here.

I would like to ask help for the community to clarify some points bellow:

how to provision a new gateway after set the new gateway/new api in transaction process;
how start the app with my new gateway as default;
how to turn on the review and testimonials to be showed after the payment occurs with new payment settings;
All of this is tied with paypal, and setting the Fakepal does not work for me, so, It's hard to emulate how the sharetribe works and to have the experience of how the payment flows.

Some of the sharetribe members already mentioned that the new code for transaction services/payment gateway is going to be rewritten in Clojure, so, I assume that a lot of this is going to be changed.

Thanks anyway.

**Comment by rap1ds** [comment]
Inactive. Closing.

**Comment by wesleyguirra** [comment]
I have the same issue.

**Comment by thomasmalbaux** [comment]
@wesleyguirra Don't hesitate to discuss this with other open-source users (some of them already implemented a new gateway) at https://www.sharetribe.com/community/
