### ISSUE TITLE
db:migrate cannot be executed successfully - Unable to annotate

### ISSUE THREAD

**Issue by johnsonyeap** [sharetribe/sharetribe#2844]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:
Release v6.1.0

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

6cc767763d657e36bc98128832d066770f958b9c

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_

Ubuntu 14.04 LTS

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
v6.9.2
> npm -v
3.10.9
```

##### Server mode:

_Are you running in development or production mode?_

Development mode

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

After completing the steps for "Setting up the development environment", I tried to execute "bundle exec rake db:migrate" to generate schema.rb. However, it fails immediately. 

```
DEBUG   ActiveRecord::SchemaMigration Load (0.3ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
DEBUG   ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`  ORDER BY version
Unable to annotate app/models/listing_image_s3_options_js_adapter.rb: Unable to autoload constant ListingImageS3OptionsJsAdapter, expected /home/sponavitus/workspace/sharetribe/app/models/listing_image_s3_options_js_adapter.rb to define it
/home/sponavitus/workspace/sharetribe/app/models/listing_image_js_adapter.rb:2: warning: already initialized constant ListingImageJSAdapter::ASPECT_RATIO
/home/sponavitus/workspace/sharetribe/app/models/listing_image_js_adapter.rb:2: warning: previous definition of ASPECT_RATIO was here
Unable to annotate app/models/listing_image_js_adapter.rb: Unable to autoload constant ListingImageJsAdapter, expected /home/sponavitus/workspace/sharetribe/app/models/listing_image_js_adapter.rb to define it
Nothing to annotate.
```

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
Following "Setting up the development environment" - Step 1 to 12.
1. _Step 2_
Run "bundle exec rake db:migrate"

Expected result: _What was the expected result after running the steps above?_

Database migrations is complete successfully without any errors. schema.rb is generated.

Actual result: _What was the actual result after running the steps above?_

Error is prompted. schema.rb is not generated.

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by rap1ds** [comment]
Hi @johnsonyeap !

There's no error in the output you pasted. There are only debug messages and warning but no errors. We are not using `schema.rb`, but instead we use [structure.sql](https://github.com/sharetribe/sharetribe/blob/master/db/structure.sql). Running `rake db:migrate` will update the `structure.sql` but it will NOT create `schema.rb`. That's expected behaviour.
