### ISSUE TITLE
How to use environment variables in config.defaults.yml?

### ISSUE THREAD

**Issue by johnsonyeap** [sharetribe/sharetribe#2846]
```
smtp_email_password: <%= ENV['SENDGRID_PASSWORD'] %>
```
Failed to setup for the ```APP_CONFIG.smtp_email_password```

**Comment by rap1ds** [comment]
First of all, you should not change the `config.defaults.yml` file. You should either:

* Change the `config.yml` file, e.g.

  ```
  smtp_email_password: "your_secret_password"`
  ```

* Set environment variable `smtp_email_password` in your environment. E.g. `export smtp_email_password` and then start your rails server

* Start the rails server with the environment variable included in the command, e.g. `smtp_email_password=your_secret_password rails s`
