### ISSUE TITLE
delayed_jobs error due to order of Gemfile

### ISSUE THREAD

**Issue by jarvisjohnson** [sharetribe/sharetribe#2855]
##### Sharetribe Version:
bec5732dec9fd83c0ca9a77f5e279910b3904d5c

##### Environment:

Heroku

```
> node -v
v6.9.1
> npm -v
3.10.8
```

##### Server mode:

production

##### Description:

delayed_jobs error due to order of Gemfile

##### Steps To Reproduce:

1. Deploy to Heroku
2. `heroku run bundle exec rake jobs:work`
3. `heroku logs -t`

##### Actual result: Error returned

```
Jan 18 10:07:58 closet-raid-production app/worker.1:  ** [NewRelic][01/18/17 18:07:58 +0000 37dc9a47-2e6a-427b-976a-05c98b0ea12d (4)] WARN : ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':conditions=>"failed_at is not NULL"}) FROM `delayed_jobs`' at line 1: SELECT COUNT({:conditions=>"failed_at is not NULL"}) FROM `delayed_jobs 
```

##### Additional information

Solution is [mentioned in the delayed_job repo](https://github.com/collectiveidea/delayed_job#rails-4x) - the protected_attributes gem, it must appear before delayed_job in your gemfile.

Just need to move those gems around  :)

**Comment by rap1ds** [comment]
Hi! Thanks for the bug report!

Are you able to reproduce this is a non-Heroku environment? I'm asking this because I have never seen this issue myself, even though we've used delayed_jobs in Rails 4 for a long time.

**Comment by rap1ds** [comment]
Closing, inactive
