### ISSUE TITLE
Server is terminated with nmp run ERR

### ISSUE THREAD

**Issue by wegain123456** [sharetribe/sharetribe#2856]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:6.1.0

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._
"6cc767763d657e36bc98128832d066770f958b9c: command not found"

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_
Ubuntu 16.04 x64 on DigitalOcean

_What's your node version? Run the following commands and copy the result here:_

```
> node -v   6.9.0
> npm -v    4.1.1
```

##### Server mode:

_Are you running in development or production mode?_ development

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_  follow the installation guide below https://github.com/sharetribe/sharetribe/blob/master/README.md#installation

1. _Step 2_  start the server with foreman start -f Procfile.static
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_  no server termination

Actual result: _What was the actual result after running the steps above?_  get ERR message below.

##### Additional information

~/sharetribe$ foreman start -f Procfile.static
05:24:40 rails.1               | started with pid 2126
05:24:40 rails-client-assets.1 | started with pid 2127
05:24:40 rails-server-assets.1 | started with pid 2129
05:24:40 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
05:24:40 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
05:24:40 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
05:24:40 rails.1               | app/assets/webpack/server-bundle.js found
05:24:40 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
05:24:40 rails-server-assets.1 | client/app/routes/routes.js found
05:24:43 rails-server-assets.1 | 
05:24:43 rails-server-assets.1 | > @ build:dev:server /home/dev/sharetribe/client
05:24:43 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
05:24:43 rails-server-assets.1 | 
05:24:43 rails-client-assets.1 | 
05:24:43 rails-client-assets.1 | > @ build:dev:client /home/dev/sharetribe/client
05:24:43 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
05:24:43 rails-client-assets.1 | 
05:24:47 rails-server-assets.1 | 
05:24:47 rails-client-assets.1 | 
05:24:47 rails-server-assets.1 | > @ ensure-node-version /home/dev/sharetribe/client
05:24:47 rails-client-assets.1 | > @ ensure-node-version /home/dev/sharetribe/client
05:24:47 rails-server-assets.1 | > check-node-version --package
05:24:47 rails-client-assets.1 | > check-node-version --package
05:24:47 rails-server-assets.1 | 
05:24:47 rails-client-assets.1 | 
05:24:49 rails-client-assets.1 | node: v6.9.0
05:24:49 rails-server-assets.1 | node: v6.9.0
05:24:49 rails-client-assets.1 | npm: v4.1.1
05:24:49 rails-server-assets.1 | npm: v4.1.1
05:24:53 rails-client-assets.1 | Webpack dev build for Rails
05:25:41 rails.1               | [2017-01-20 05:25:41] INFO  WEBrick 1.3.1
05:25:41 rails.1               | [2017-01-20 05:25:41] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
05:25:41 rails.1               | [2017-01-20 05:25:41] INFO  WEBrick::HTTPServer#start: pid=2133 port=3000
05:26:25 rails-client-assets.1 | Killed
05:26:25 rails-client-assets.1 | 
05:26:25 rails-client-assets.1 | npm ERR! Linux 4.4.0-59-generic
05:26:25 rails-client-assets.1 | npm ERR! argv "/home/dev/.nvm/versions/node/v6.9.0/bin/node" "/home/dev/.nvm/versions/node/v6.9.0/bin/npm" "run" "build:dev:client"
05:26:25 rails-client-assets.1 | npm ERR! node v6.9.0
05:26:25 rails-client-assets.1 | npm ERR! npm  v4.1.1
05:26:25 rails-client-assets.1 | npm ERR! code ELIFECYCLE
05:26:25 rails-client-assets.1 | npm ERR! @ build:dev:client: `npm run ensure-node-version && webpack -w --config webpack.client.config.js`
05:26:25 rails-client-assets.1 | npm ERR! Exit status 137
05:26:25 rails-client-assets.1 | npm ERR! 
05:26:25 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'npm run ensure-node-version && webpack -w --config webpack.client.config.js'.
05:26:25 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
05:26:25 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
05:26:25 rails-client-assets.1 | npm ERR! not with npm itself.
05:26:25 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
05:26:25 rails-client-assets.1 | npm ERR!     npm run ensure-node-version && webpack -w --config webpack.client.config.js
05:26:25 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
05:26:25 rails-client-assets.1 | npm ERR!     npm bugs 
05:26:25 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
05:26:25 rails-client-assets.1 | npm ERR!     npm owner ls 
05:26:25 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
05:26:25 rails-client-assets.1 | 
05:26:25 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
05:26:25 rails-client-assets.1 | npm ERR!     /home/dev/sharetribe/client/npm-debug.log
05:26:26 rails-client-assets.1 | exited with code 1
05:26:26 system                | sending SIGTERM to all processes
05:26:26 rails.1               | terminated by SIGTERM
05:26:26 rails-server-assets.1 | terminated by SIGTERM

**Comment by kpuputti** [comment]
Thanks for the report!

I cannot see anything specific in your error output, but can you run `npm install` in the `client/` directory, and run these commands separately to see what fails:

    npm run ensure-node-version

and

    ./node_modules/.bin/webpack --config webpack.client.config.js

**Comment by rap1ds** [comment]
Closing, inactive.

**Comment by funahasf** [comment]
The same problem in the same environment.
I ran the suggested command above,
and here is the output.
Any thought? Thanks for help!

~/sharetribe/client# `npm install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-dom-factories@1.0.0 requires a peer of react@^15.5.4 but none was installed.

~/sharetribe/client# `npm run ensure-node-version`

> @ ensure-node-version /root/sharetribe/client
> check-node-version --package

node: v6.9.5
npm: v3.10.10

~/sharetribe/client# `./node_modules/.bin/webpack --config webpack.client.config.js`
Webpack dev build for Rails
Hash: 37ad5ce20d972e226d9b
Version: webpack 1.13.3
Time: 24350ms
           Asset     Size  Chunks             Chunk Names
   app-bundle.js  8.72 MB       0  [emitted]  app
vendor-bundle.js   408 kB       1  [emitted]  vendor
  app-bundle.css  74.9 kB       0  [emitted]  app
   [0] multi app 28 bytes {0} [built]
   [0] multi vendor 40 bytes {1} [built]
 [295] ./app/routes/routes.js 139 kB {0} [optional] [built]
    + 703 hidden modules

ERROR in ENOENT: no such file or directory, scandir '/root/sharetribe/client/node_modules/node-sass/vendor'
 @ ./~/react-dates/css/styles.scss 4:14-97
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

**Comment by Sultan91** [comment]
Same problem
