### ISSUE TITLE
Not able to display a custom logo

### ISSUE THREAD

**Issue by facundofarias** [sharetribe/sharetribe#2890]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Environment:

_What's your environment?_ macOS Sierra
_What's your node version? Run the following commands and copy the result here:_

```
> node -v
v7.7.1
> npm -v
4.1.2
```

##### Steps To Reproduce:
1. Enable the landing page feature,
2. Upload a new custom logo,
3. Refresh the landing page. 

Expected result: The new logo gets shown on the lading page.
Actual result:
![image](https://cloud.githubusercontent.com/assets/2700564/23671530/e0facbce-036b-11e7-8b30-eea05c754a4b.png)

##### Additional information

The logo seems to be in the database:
![image](https://cloud.githubusercontent.com/assets/2700564/23671557/f9532cf2-036b-11e7-86ec-5511cd8c8754.png)

But, when rendering, it fails:
![image](https://cloud.githubusercontent.com/assets/2700564/23671575/0fba7cfc-036c-11e7-8f63-ea2bd2d35e84.png)

**Comment by mohdsameer** [comment]
Please make sure that you have run delayed job :)

**Comment by facundofarias** [comment]
Yes, that was the issue 👍
