### ISSUE TITLE
Japanese Search

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#2903]
Hi,

I've configured the open source version in my server, and i am using Japanese as one of the languages, it seems that the search isn't working, i believe it's something on Sphinx, can you help me to configure Sphinx, as it should work on the hosted version?

Thanks!

**Comment by sktoiva** [comment]
Hi @eltonokada,

Please, use the Issue template when posting new issues. 

What steps have you taken? Is the sphinx installed according to instructions with mysql integration? Is it indexed and have you started the sphinx daemon?

There is also a file https://github.com/sharetribe/sharetribe/blob/master/config/thinking_sphinx.yml that defines how utf8 characters are handled in Sphinx searches. To my knowledge it should contain also definitions to Japanese. More information here: http://sphinxsearch.com/wiki/doku.php?id=charset_tables

**Comment by rap1ds** [comment]
Inactive. Closing.
