### ISSUE TITLE
Google map marker limited to 144 in number

### ISSUE THREAD

**Issue by jolly17** [sharetribe/sharetribe#2904]
We have more than 800 listings on our platform but google map only shows 144 markers all the time.

##### Sharetribe Version:

5.6.0

##### Environment:

Google cloud hosted on Linux OS.

##### Server mode:

production

##### Description:

I am facing an issue with map markers. They are limited to 144 in number for my website. Sharetribe suggests that the limit is 2000, is there anything I need to do to increase that limit to 2000?

##### Steps To Reproduce:

You can see the view live on: https://secondcry.com/en?view=map whereas you can see no. of listings on the site is more than 800 (https://secondcry.com/en?page=34&view=grid) - 34 pages, 24 listings on each.

Else, you can create 150+ listing entries with proper address on your local system and reproduce the issue.

Expected result: Map view should show 150 markers.

Actual result: Map view will show you only 144 markers.

(https://cloud.githubusercontent.com/assets/24221367/24031991/b002ecac-0b0b-11e7-8c35-1f293f83dbc3.png)

##### Additional information

We were told in our previous issue that we should get the map api from google and use that instead of open user api. so we did this using this code: https://github.com/sharetribe/sharetribe/pull/2172/files
It resolved the [object object] error, but the above issue persists.

**Comment by rap1ds** [comment]
Hi and thanks for reporting the issue!

I haven't seen this issue before and in fact, this is not happening in sharetribe.com. Here's an example site with 700+ listings on the map: https://aalto.sharetribe.com/?view=map

Are you sure there are more than 144 listings on your marketplace **with location added**? You should do a SQL query and select all open listings with proper location, to get the number you'd expect to see on the map.

I saw that your marketplace has a lot of modifications (looks great btw!). Can you reproduce this issue with fresh installation of unmodified Sharetribe version 6.2.0?

**Comment by jolly17** [comment]
Yes, I have checked that most of the listings have location added and in fact I can add a new listing with proper location which will show up on map but the count will remain as 144, so some other listing gets overwritten somehow.. All listings have a map on their listing page which proves that location is saved correctly for all of them.

As you rightly pointed out, we have done lot of modification so it is not possible to update the sharetribe to its latest version and to reproduce this issue with fresh installation of unmodified Sharetribe version 6.2.0 will not help because we would not know which files have been changed in the latest issue.

Can you please check with your development team if this was fixed in any of the later versions?

**Comment by jolly17** [comment]
So, just now I updated one of my listing which was not showing up on map previously and it appeared now, but still the total marker count is 144. 
![after](https://cloud.githubusercontent.com/assets/24221367/24033933/3effcf7a-0b15-11e7-93c8-fe00fe00c4c3.png)
![before](https://cloud.githubusercontent.com/assets/24221367/24033934/3f028dc8-0b15-11e7-85cc-1fe2f989aafc.png)

**Comment by cyclelifehq** [comment]
There is a configuration variable in "config.defaults.yml" - map_listings_limit: 150. Try changing that.

**Comment by jolly17** [comment]
Awesome, it worked! Thanks cyclelikehq :)
