### ISSUE TITLE
Getting "Detail update failed" error when upload image.

### ISSUE THREAD

**Issue by loydsmohan** [sharetribe/sharetribe#2907]
I am getting "Detail update failed" red box error when upload image.  I have started rake job:work. it is also started with pid, then it is hanging .

Note: It is working fine in my local system at development mode.

##### Environment:

Production environment, vps, ubuntu

_What's your node version? Run the following commands and copy the result here:_

> node -v
v6.9.5
> npm -v  
3.10.10

##### Server mode:

Production

##### Description:

According to the user manual i did not use following steps in production mode,
foreman start -f Procfile.static
foreman start -f Procfile.hot

##### Steps To Reproduce:
![screenshot from 2017 03 17 21 20 38 png png image 1366 x 768 pixels scaled 87](https://cloud.githubusercontent.com/assets/6448054/24051856/789e88c2-0b59-11e7-86d9-11fd77981ff7.png)

**Comment by sktoiva** [comment]
Hi @loydsmohan,

The output from the workers looks correct. It is meant to be left running. From that output, it also looks like that there are no delayed jobs to be processed.

However, the error message "Detail update failed" comes from the server and the cause might be visible in the server logs. I'd suggest you start looking from the server logs what causes the failure.

I'm guessing you are trying to upload some kind of image for the marketplace. The code responsible for the error message is in here: https://github.com/sharetribe/sharetribe/blob/master/app/controllers/admin/communities_controller.rb#L404

**Comment by rap1ds** [comment]
Inactive. Closing.
