### ISSUE TITLE
Npm install not working

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#2908]
Having this error when running NPM install on my AWS instance:

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.2/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! undefined postinstall: `cd client && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the undefined postinstall script 'cd client && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sharetribe-altspc/npm-debug.log

##### Sharetribe Version:
V6.1.0

##### Environment:

AWS - Ubuntu 16.04

> node -v 6.9.2
> npm -v 3.10.9

tried with:

node -v 6.9.5
npm -v 3.10.10

##### Server mode:
production

##### Steps To Reproduce:

clone the repo
install the gems
npm install

**Comment by sktoiva** [comment]
Hi @eltonokada,

Is that the whole error message? There's a similar issue from a while back (with older Node version) that might help:  https://github.com/sharetribe/sharetribe/issues/2161 There I guess the error was related on the method Node was installed on Ubuntu.

You can also try to circumvent the issue by running `cd client` and `npm install` manually.

**Comment by rap1ds** [comment]
Inactive. Closing.

**Comment by sainineeraj** [comment]
I tried doing cd client and rerun but got a new error. I am using a lightsail ubuntu image

```
npm WARN deprecated babel-preset-es2015@6.18.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated postcss-cssnext@2.8.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm ERR! Linux 4.4.0-1052-aws
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.8.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.8.0/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn

npm ERR! spawn ENOMEM
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Killed
```

**Comment by zenikk** [comment]
ENOMEM tells that your server just does not have enough resources for nodejs.
You should switch to instance with more RAM, say 4GB :)

**Comment by sainineeraj** [comment]
Yes, thank you, I figured it after posting here, Had to upgrade to 2 GB and it worked

**Comment by mouazq** [comment]
Same here:

```


> undefined postinstall /home/mq/Documents/bookswap-beta/booksswapper
> cd client && npm install

/home/mq/Documents/bookswap-beta/booksswapper/client
├─┬ babel-core@6.18.2
│ └─┬ babel-register@6.26.0
│   └── babel-core@6.26.3 
├── UNMET PEER DEPENDENCY react@15.4.1
└── UNMET PEER DEPENDENCY react-dom@15.4.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-form@2.15.0 requires a peer of react@^15.6.1 || 16 but none was installed.
npm WARN react-form@2.15.0 requires a peer of react-dom@^15.6.1 || 16 but none was installed.
```
