### ISSUE TITLE
Facebook login is not working

### ISSUE THREAD

**Issue by mohdsameer** [sharetribe/sharetribe#2916]
##### Environment: production

My facebook login stopped working suddenly, I am getting this error
Could not authorize you from Facebook because "Login error".

Please consider my request.

Thanks

**Comment by sktoiva** [comment]
Hi @mohdsameer,

Could you please provide a little bit more information? E.g. logs would be helpful.

**Comment by mohdsameer** [comment]
Hi @sktoiva 
Here are the logs
INFO {"method":"GET","path":"/people/auth/facebook/setup","format":"html","controller":"sessions","action":"facebook_setup","status":404,"duration":1741.53,"view":0.74,"db":2.75,"params":{"code":"AQC56DkuUKk1E0RqeYYmdvN-8EBmQ4r47bjH7jWqgR_hZ7UPiof7uBsE6D0KlCDRBTkFLsPFEAADfrqJ_Dq7Vc787ydLME0-NmmqdvUk3efznjtYU8dfwpiYiFfqMPBO0REpWFwGK7nDKENwHHzHRXyR2yhHCY1yLGk7uGgFBop5JPDp6lVMCaTAs4Q5B0ORtnP7MSFBghJPkXHX04Py39o2Dej0soQITYdI0epOstpDjvR1OTegWp21b8ZHSpMV3GJBacAArxlZV9j-mtOZ78NtQDlkT1w7YHh_TN6C3cdUFyXuEulpSelw4_y5eDZ7GvVjPF2niXgaETdQY_T-uFYH","state":"1b4f4af1b421d8df8f9059f4cc6f551233bfc88613d418d7","provider":"facebook"},"host":"sharingexchange.lvh.me","community_id":1,"current_user_id":"","request_uuid":"ac9e776f-2f3f-4c7f-9d8a-2eddec4d5536"}
INFO {"method":"GET","path":"/people/auth/facebook/setup","format":"html","controller":"sessions","action":"facebook_setup","status":404,"duration":1741.53,"view":0.74,"db":2.75,"params":{"code":"AQC56DkuUKk1E0RqeYYmdvN-8EBmQ4r47bjH7jWqgR_hZ7UPiof7uBsE6D0KlCDRBTkFLsPFEAADfrqJ_Dq7Vc787ydLME0-NmmqdvUk3efznjtYU8dfwpiYiFfqMPBO0REpWFwGK7nDKENwHHzHRXyR2yhHCY1yLGk7uGgFBop5JPDp6lVMCaTAs4Q5B0ORtnP7MSFBghJPkXHX04Py39o2Dej0soQITYdI0epOstpDjvR1OTegWp21b8ZHSpMV3GJBacAArxlZV9j-mtOZ78NtQDlkT1w7YHh_TN6C3cdUFyXuEulpSelw4_y5eDZ7GvVjPF2niXgaETdQY_T-uFYH","state":"1b4f4af1b421d8df8f9059f4cc6f551233bfc88613d418d7","provider":"facebook"},"host":"sharingexchange.lvh.me","community_id":1,"current_user_id":"","request_uuid":"ac9e776f-2f3f-4c7f-9d8a-2eddec4d5536"}
I, [2017-03-30T12:18:26.735793 #14461]  INFO -- omniauth: (facebook) Callback phase initiated.
E, [2017-03-30T12:18:27.988406 #14461] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"access_token":"EAARvUZBlgqnYBABRYJEtCQnFYQ5cBsbBnvYdxHsTkrQt0E7x4wdng7b2d1iZCZAvB47og0IFurGDZB39B5LqgcLSPy2grMNsXwZBKdY0hkRTaLDJVEFaQulBVg6JpT6iflOljbEYQLc4EHFbOYY3kOchHmB6rbvYZD","token_type":"bearer","expires_in":5122720}
DEBUG   CACHE (0.0ms)  SELECT COUNT(*) FROM `communities`
DEBUG   CACHE (0.0ms)  SELECT  `community_customizations`.* FROM `community_customizations` WHERE `community_customizations`.`community_id` = 1 AND `community_customizations`.`locale` = 'en'  ORDER BY `community_customizations`.`id` ASC LIMIT 1  [["community_id", 1], ["locale", :en]]
DEBUG   CACHE (0.0ms)  SELECT  `community_customizations`.* FROM `community_customizations` WHERE `community_customizations`.`community_id` = 1 AND `community_customizations`.`locale` = 'en'  ORDER BY `community_customizations`.`id` ASC LIMIT 1  [["community_id", 1], ["locale", "en"]]
DEBUG    (0.7ms)  SELECT COUNT(*) AS count_all, `delayed_jobs`.`priority` AS delayed_jobs_priority FROM `delayed_jobs` WHERE (attempts < 3 AND run_at < '2017-03-30 06:48:28.000711') GROUP BY `delayed_jobs`.`priority`
INFO {"method":"GET","path":"/people/auth/facebook/callback","format":"html","controller":null,"action":null,"status":302,"duration":18.71,"view":0.0,"db":0.78,"location":"http://sharingexchange.lvh.me:3000/s","params":{"code":"AQC56DkuUKk1E0RqeYYmdvN-8EBmQ4r47bjH7jWqgR_hZ7UPiof7uBsE6D0KlCDRBTkFLsPFEAADfrqJ_Dq7Vc787ydLME0-NmmqdvUk3efznjtYU8dfwpiYiFfqMPBO0REpWFwGK7nDKENwHHzHRXyR2yhHCY1yLGk7uGgFBop5JPDp6lVMCaTAs4Q5B0ORtnP7MSFBghJPkXHX04Py39o2Dej0soQITYdI0epOstpDjvR1OTegWp21b8ZHSpMV3GJBacAArxlZV9j-mtOZ78NtQDlkT1w7YHh_TN6C3cdUFyXuEulpSelw4_y5eDZ7GvVjPF2niXgaETdQY_T-uFYH","state":"1b4f4af1b421d8df8f9059f4cc6f551233bfc88613d418d7"},"host":"sharingexchange.lvh.me","community_id":1,"current_user_id":"","request_uuid":"ac9e776f-2f3f-4c7f-9d8a-2eddec4d5536"}
INFO {"method":"GET","path":"/people/auth/facebook/callback","format":"html","controller":null,"action":null,"status":302,"duration":18.71,"view":0.0,"db":0.78,"location":"http://sharingexchange.lvh.me:3000/s","params":{"code":"AQC56DkuUKk1E0RqeYYmdvN-8EBmQ4r47bjH7jWqgR_hZ7UPiof7uBsE6D0KlCDRBTkFLsPFEAADfrqJ_Dq7Vc787ydLME0-NmmqdvUk3efznjtYU8dfwpiYiFfqMPBO0REpWFwGK7nDKENwHHzHRXyR2yhHCY1yLGk7uGgFBop5JPDp6lVMCaTAs4Q5B0ORtnP7MSFBghJPkXHX04Py39o2Dej0soQITYdI0epOstpDjvR1OTegWp21b8ZHSpMV3GJBacAArxlZV9j-mtOZ78NtQDlkT1w7YHh_TN6C3cdUFyXuEulpSelw4_y5eDZ7GvVjPF2niXgaETdQY_T-uFYH","state":"1b4f4af1b421d8df8f9059f4cc6f551233bfc88613d418d7"},"host":"sharingexchange.lvh.me","community_id":1,"current_user_id":"","request_uuid":"ac9e776f-2f3f-4c7f-9d8a-2eddec4d5536"}

**Whenever i am trying to login with fb, it is redirecting me to the failure action of sessions controller.**

**Comment by sktoiva** [comment]
Ok, the error is there:

E, [2017-03-30T12:18:27.988406 #14461] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error

Potential cause is actually invalid credentials or one other is that the Facebook app is in sandbox mode which will probably cause this error for any other than developer account. 

Also, googling with that specific error might provide some additional information. 

I would also be interested in the actual steps to reproduce this. You said in your original post that the authentication stopped working suddenly. Did you change something?

**Comment by mohdsameer** [comment]
It also stopped here on production hengerdeling.no
I haven't changed anything there, it was working fine 2 days ago.

Thanks

**Comment by sktoiva** [comment]
I tried to reproduce it, but I couldn't. I hope that the error message or the couple of potential solutions provide a clue for what is the reason.

I'll leave this open for a while still and I'm happy to help if you find out more information.

**Comment by mohdsameer** [comment]
closing this as i had to change my fb api keys.

**Comment by invinc** [comment]
@mohdsameer  I am getting same error as you.
How did you fix this error?
What do you mean "I had to change my fb api keys"?

Looking forward your answer.
