### ISSUE TITLE
Click on Inbox = "Marketplace temporarily unavailable" message

### ISSUE THREAD

**Issue by strainly** [sharetribe/sharetribe#2931]
Sharetribe v6.2.0 (just installed)
Running on DigitalOcean _Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Server mode:

Production mode

##### Description:

When implementing https://github.com/sharetribe/sharetribe/pull/2853/commits/8ffb86376f30170b97fcdd5c858dd4c1a3d759ec

After a transaction is completed, both members who completed the transactions can no longer access their Inbox and land on a page with "Marketplace temporarily unavailable" message

![image](https://cloud.githubusercontent.com/assets/25166070/24986282/46b48456-1fc7-11e7-9357-d70fc1c44bb5.png)

##### Steps To Reproduce:

implement https://github.com/sharetribe/sharetribe/pull/2853/commits/8ffb86376f30170b97fcdd5c858dd4c1a3d759ec

1. Submit request or Buy to a member
2. Accept request
3. Even before leaving feedback, the Inbox is no longer accessible

**Comment by jkadry** [comment]
+1 here. Same issue.

**Comment by slavabrodskiy** [comment]
has it ever been resolved?
