### ISSUE TITLE
Webpack Killed

### ISSUE THREAD

**Issue by deviprasad97** [sharetribe/sharetribe#2934]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._
##### Environment:
Ubuntu 16.04
Amazon EC2

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
> npm -v
```
node -v :6.9.1
npm -v :3.10.8
##### Server mode:
Production
_Are you running in development or production mode?_

##### Description:
Webpack dev build for Rails KILLED

##### Steps To Reproduce:
In clients folder
 RAILS_ENV=production bundle exec rake assets:precompile
Webserver is running but CSS and Images are not loading as Webpack commands fails
Terminal error log:
(in /home/ubuntu/sharetribe)
/var/lib/gems/2.3.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/configuration/default_source.rb:675: warning: key :disable_mongo is duplicated and overwritten on line 987
cd client && npm run build:client

> @ build:client /home/ubuntu/sharetribe/client
> npm run ensure-node-version && webpack --config webpack.client.config.js

> @ ensure-node-version /home/ubuntu/sharetribe/client
> check-node-version --package

node: v6.9.1
npm: v3.10.8
Webpack dev build for Rails
Asset ["step3_coverPhoto.jpg"] is copied to /home/ubuntu/sharetribe/public/webpack/step3_coverPhoto-875d69d62fde8885b67184f8cdc5ac45.jpg
Asset ["step6_addListing.jpg"] is copied to /home/ubuntu/sharetribe/public/webpack/step6_addListing-95c1db46186bcf7e7e93366347b92103.jpg
Asset ["step2_sloganDescription.jpg"] is copied to /home/ubuntu/sharetribe/public/webpack/step2_sloganDescription-a83c0c2cb462753018c9650b1215c4f9.jpg
Asset ["step4_fieldsFilters.jpg"] is copied to /home/ubuntu/sharetribe/public/webpack/step4_fieldsFilters-4203c725b71275066cab9884795775f0.jpg
Killed

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/npm" "run" "build:client"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ build:client: `npm run ensure-node-version && webpack --config webpack.client.config.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the @ build:client script 'npm run ensure-node-version && webpack --config webpack.client.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ensure-node-version && webpack --config webpack.client.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/sharetribe/client/npm-debug.log
rake aborted!
Command failed with status (1): [cd client && npm run build:client...]
/home/ubuntu/sharetribe/lib/tasks/assets.rake:21:in `block (2 levels) in <top (required)>'
Tasks: TOP => assets:precompile => assets:compile_environment => assets:webpack
(See full trace by running task with --trace)

**Comment by deviprasad97** [comment]
Solved. The problem was with the swap file size of the Virtual Machine. Because of insufficient storage, the npm install never finished installing all the commands and this lead to the error mentioned above. If you are on AWS and using micro ec2 then you might face this problem

**Comment by santoshgistto** [comment]
this is happening in local machine also, is there any solution?

**Comment by deviprasad97** [comment]
Can you please provide more informtion.
