### ISSUE TITLE
Project Sharetribe -- Feedback & Critical Update Mailing List

### ISSUE THREAD

**Issue by pcm211** [sharetribe/sharetribe#2936]
With over 15000 commits we have gone a long way developing this ... We now require the actual feedback and the real & live running sites as proof of pudding of this project so that we can exponentially grow further. To implement the above we had started a community too but with fewer results than expected. 

We could build this concept by including a small option during initial configuration/registration of the site to send an email with the site link so that critical updates could be mailed to the admin by the community forum and we also get to know the site which is running sharetribe platform... which can be displayed in our community --place

**Comment by delblues** [comment]
I'm working for a quite long time to launch a new project with the OS sharetribe platform, I hope soon I will be able to share the link. As a feedback, I have learned a lot with the open source solution. I really appreciate all the support you guys had with this and would like to give this honest feedback and I wish you guys continue with the project. And, I really would like to opt in in this mailing list for the future critical updates (delblues@gmail.com). Thanks sharetribe team.

**Comment by thomasmalbaux** [comment]
Thanks all, good to hear about your projects.

Don't hesitate to share them in the Sharetribe Community Forum, [there is a dedicated thread for that](https://www.sharetribe.com/community/t/marketplace-showroom-are-you-hosting-an-open-source-sharetribe-marketplace-advertise-it-here/51/20)!
