### ISSUE TITLE
script/prepare-assets.sh failing when executed

### ISSUE THREAD

**Issue by acloudiator** [sharetribe/sharetribe#2940]
##### Sharetribe Version:
a593b604f328c4c04c07b15e2e9f69bb3c60978a

##### Environment:
_What's your environment?_
Running it on a container, image based on Ruby:2.3.1

_What's your node version? Run the following commands and copy the result here:_
```
Node v6.9.1
Npm 3.10.8
```

##### Server mode:
_Are you running in development or production mode?_
Development

##### Description:
script/prepare-assets.sh failing when executed.

##### Steps To Reproduce:
1. _Use the docker file from sharetribe/Dockerfile and download it locally_
2. _change to the directory where the docker file has been download and build it. "docker build ."_
3. _You'll encounter an error before this script failure, since the directory is missing and unable to copy "customfileloader" to the container. I've fixed that in my Dockerfile _
4. _Once you pass the above step, it will try to execute the "script/prepare-assets.sh" and will fail with the below error._

-----------------------
root@22987e5f19c0:/opt/app# script/prepare-assets.sh
cd client && npm run build:client

> @ build:client /opt/app/client
> npm run ensure-node-version && webpack --config webpack.client.config.js

> @ ensure-node-version /opt/app/client
> check-node-version --package

sh: 1: check-node-version: not found

npm ERR! Linux 4.8.7-300.fc25.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ensure-node-version"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ ensure-node-version: `check-node-version --package`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ ensure-node-version script 'check-node-version --package'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     check-node-version --package
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/client/npm-debug.log

npm ERR! Linux 4.8.7-300.fc25.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ build:client: `npm run ensure-node-version && webpack --config webpack.client.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:client script 'npm run ensure-node-version && webpack --config webpack.client.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ensure-node-version && webpack --config webpack.client.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/client/npm-debug.log
rake aborted!
Command failed with status (1): [cd client && npm run build:client...]
/opt/app/lib/tasks/assets.rake:21:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/bundle/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bundle/bin/bundle:22:in `load'
/usr/local/bundle/bin/bundle:22:in `<main>'
Tasks: TOP => assets:precompile => assets:compile_environment => assets:webpack
(See full trace by running task with --trace)
--------------

Expected result: _It should pass successfully and create the docker container_

Actual result: _Getting failed with the above error_

##### Additional information

_Attaching the modified Dockerfile, in case you need it
[Dockerfile.zip](https://github.com/sharetribe/sharetribe/files/938931/Dockerfile.zip)

_

**Comment by rap1ds** [comment]
Hmhm... so the main issue seems to be that `npm` is unable to find `check-node-version` package. This package should be installed when `npm install` is run. I can't say why it's not found by `npm`. @bladealslayer do you have any ideas?

**Comment by bladealslayer** [comment]
@acloudiator In your steps to reproduce you say download only the Dockerfile. Are you doing that? You need the entire sharetribe repository cloned to be able to build the image correctly, not just the Dockerfile. When building the docker image form a freshly cloned repo, I can't reproduce the issue. Are you still experiencing this?

Please, so the following:

* Clone a fresh copy of sharetribe repo
* Run `docker build --pull --no-cache -t sharetribe:latest` in the repo root
* If you still get errors, post the entire build output here.

**Comment by acloudiator** [comment]
Thanks @bladealslayer and @rap1ds !! 
Seems like something was broken and stayed in my cache. "--no-cache" resolved my issue.

**Comment by acloudiator** [comment]
Quick question, is this docker image production ready or for development purpose?

**Comment by bladealslayer** [comment]
@acloudiator it is production-ready, but does not support running sphinx search, so you can't have fully-functional installation without modifying the image yet.
