### ISSUE TITLE
Not able to post listing

### ISSUE THREAD

**Issue by storein** [sharetribe/sharetribe#2950]
I am getting this error when I am trying to post on my site
The price is negotiable. This is the first post on this site. Yeee Contact me to know more

**Comment by rap1ds** [comment]
Thanks for reporting the issue!

We need a bit more information about the issue before we are able to comment or act on it. Please consider using the [Issue template](./ISSUE_TEMPLATE.md). We need to know at least the Sharetribe version you are running on, git SHA of the commit, environment and most importantly **the exact steps to reproduce the issue.**

We'll keep waiting for the additional information.

**Comment by rap1ds** [comment]
Inactive. Closing.
