### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by thefoodcorridor** [sharetribe/sharetribe#2955]
Hi folks,

Was wondering if there were any plans to upgrade this app to rails 5?

Rails 5.1 was just released http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/ 

So I was wondering.

Thanks!
Dan

**Comment by rap1ds** [comment]
No plans yet. But you're right, since 5.1. was released, we should start thinking about the upgrade at some point. Hopefully sooner than later.

**Comment by sktoiva** [comment]
We have started working on Rails 5 upgrade. Progress can be seen here: #2976

**Comment by rap1ds** [comment]
Rails 5 upgrade is already merged to master. New version will be released soon.
