### ISSUE TITLE
Any feedback on React on Rails?

### ISSUE THREAD

**Issue by justin808** [sharetribe/sharetribe#2961]
Any feedback on https://github.com/shakacode/react_on_rails?

I'm looking for some help to:

* Migrate to 8.0.0-beta.2 with no configuration changes. Should just work.
* Migrate to 8.0.0-beta.2 with changes to use webpacker_lite. See https://github.com/shakacode/react-webpack-rails-tutorial/pull/387 for an example of upgrading.

Any other feedback?

**Comment by rap1ds** [comment]
In active. Closing.
