### ISSUE TITLE
NPM bug

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#2967]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:
Not sure

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:
Digital Ocean - Ubuntu
_What's your environment? Mac OS X, Heroku, or something else?_

_What's your node version? Run the following commands and copy the result here:_

node v6.9.1
npm  v3.10.8
##### Server mode:
Production

##### Description:
Can't build the assets the error is:

 missing script: ensure-node-version

##### Steps To Reproduce:
bundle exec rake assets:precompile RAILS_ENV=production

**Comment by rap1ds** [comment]
Thanks for reporting the issue!

We need a bit more information about the issue before we are able to comment or act on it. We need to know at least the Sharetribe version you are running on, git SHA of the commit and most importantly **the exact steps to reproduce the issue.** By running `bundle exec rake assets:precompile RAILS_ENV=production`, I can't reproduce the issue.

We'll keep waiting for the additional information.

**Comment by rap1ds** [comment]
I'm now closing this because issue has been inactive for more than two weeks. 

Feel free to post any additional information to this thread. We'll revisit the issue again if there are new information available later.
