### ISSUE TITLE
There is no "go back to listing view" button in listing detail view

### ISSUE THREAD

**Issue by xuanus** [sharetribe/sharetribe#2985]
Go back to listing view button is very useful on mobile device.

##### Sharetribe Version:
sharetribe.com paid version

##### Environment:
_What's your environment? iPhone 7 Plus

##### Server mode:
sharetribe.com paid version

##### Steps To Reproduce:

1. open an account in Sharetribe.com
2. log in to Sharetribe.com
3. create several listings
4. visiting [yoursite].sharetribe.com on mobile device
5. click on one of the listings
6. go into listing detail view
7. looking for "go back to listing view" button

Expected result: There is a go back button

Actual result:  
On Android, there is physical "go back" button. It is fine for Android users.
On iOS, there is no physical "go back" button, have to find the "go back" button in browser. Not good user experience.

**Comment by rap1ds** [comment]
Hi, thanks for the feature request!

At the moment we are not planning to add a "go back to listing view" button to the listing details view. Browsers' have their own Back buttons and we're relying on them, and not duplicating the Back functionality on the website.

User experience is of course very subjective, but as an iPhone user I do use Safari's Back button often and I find it working ok.
