### ISSUE TITLE
Server is terminated with nmp run ERR 2

### ISSUE THREAD

**Issue by funahasf** [sharetribe/sharetribe#3004]
Server gets terminated with nmp run ERR.

##### Sharetribe Version:
6.4.0
~/sharetribe# `git rev-parse HEAD`
63cf22673ba74fe0ffc3b1f28f21bf8c2d97310f

##### Environment:
Ubuntu 16.04.2 LTS x64 on DigitalOcean

> node -v   6.9.5
> npm -v    3.10.10

##### Server mode:
development mode

##### Description:
Server is terminated with nmp run ERR.
The issue looks very similar to #2856.
I add below the result of `foreman start -f Procfile.static`
as well as command commented in #2856,
`npm install` in the `client/` directory
`npm run ensure-node-version`
and
`./node_modules/.bin/webpack --config webpack.client.config.js`
Thank you for any help!

##### Additional information
~/sharetribe# `foreman start -f Procfile.static`
02:51:09 rails.1               | started with pid 23054
02:51:09 rails-client-assets.1 | started with pid 23055
02:51:09 rails-server-assets.1 | started with pid 23057
02:51:09 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
02:51:09 rails.1               | app/assets/webpack/server-bundle.js found
02:51:09 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
02:51:09 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
02:51:09 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
02:51:09 rails-server-assets.1 | client/app/routes/routes.js found
02:51:12 rails-server-assets.1 | 
02:51:12 rails-server-assets.1 | > @ build:dev:server /root/sharetribe/client
02:51:12 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
02:51:12 rails-server-assets.1 | 
02:51:12 rails-client-assets.1 | 
02:51:12 rails-client-assets.1 | > @ build:dev:client /root/sharetribe/client
02:51:12 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
02:51:12 rails-client-assets.1 | 
02:51:15 rails-server-assets.1 | 
02:51:15 rails-server-assets.1 | > @ ensure-node-version /root/sharetribe/client
02:51:15 rails-server-assets.1 | > check-node-version --package
02:51:15 rails-server-assets.1 | 
02:51:15 rails-client-assets.1 | 
02:51:15 rails-client-assets.1 | > @ ensure-node-version /root/sharetribe/client
02:51:15 rails-client-assets.1 | > check-node-version --package
02:51:15 rails-client-assets.1 | 
02:51:17 rails-server-assets.1 | node: v6.9.5
02:51:17 rails-server-assets.1 | npm: v3.10.10
02:51:17 rails-client-assets.1 | node: v6.9.5
02:51:17 rails-client-assets.1 | npm: v3.10.10
02:51:21 rails-client-assets.1 | Webpack dev build for Rails
02:51:57 rails.1               | [2017-06-28 02:51:57] INFO  WEBrick 1.3.1
02:51:57 rails.1               | [2017-06-28 02:51:57] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
02:51:57 rails.1               | [2017-06-28 02:51:57] INFO  WEBrick::HTTPServer#start: pid=23061 port=3000
02:52:37 rails-client-assets.1 | Killed
02:52:37 rails-client-assets.1 | 
02:52:37 rails-client-assets.1 | npm ERR! Linux 4.4.0-79-generic
02:52:37 rails-client-assets.1 | npm ERR! argv "/root/.nvm/versions/node/v6.9.5/bin/node" "/root/.nvm/versions/node/v6.9.5/bin/npm" "run" "build:dev:client"
02:52:37 rails-client-assets.1 | npm ERR! node v6.9.5
02:52:37 rails-client-assets.1 | npm ERR! npm  v3.10.10
02:52:37 rails-client-assets.1 | npm ERR! code ELIFECYCLE
02:52:37 rails-client-assets.1 | npm ERR! @ build:dev:client: `npm run ensure-node-version && webpack -w --config webpack.client.config.js`
02:52:37 rails-client-assets.1 | npm ERR! Exit status 137
02:52:37 rails-client-assets.1 | npm ERR! 
02:52:37 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'npm run ensure-node-version && webpack -w --config webpack.client.config.js'.
02:52:37 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
02:52:37 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
02:52:37 rails-client-assets.1 | npm ERR! not with npm itself.
02:52:37 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
02:52:37 rails-client-assets.1 | npm ERR!     npm run ensure-node-version && webpack -w --config webpack.client.config.js
02:52:37 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
02:52:37 rails-client-assets.1 | npm ERR!     npm bugs 
02:52:37 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
02:52:37 rails-client-assets.1 | npm ERR!     npm owner ls 
02:52:37 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
02:52:37 rails-client-assets.1 | 
02:52:37 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
02:52:37 rails-client-assets.1 | npm ERR!     /root/sharetribe/client/npm-debug.log
02:52:38 rails-client-assets.1 | exited with code 1
02:52:38 system                | sending SIGTERM to all processes
02:52:38 rails.1               | terminated by SIGTERM
02:52:38 rails-server-assets.1 | terminated by SIGTERM

~/sharetribe/client# `npm install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-dom-factories@1.0.0 requires a peer of react@^15.5.4 but none was installed.

~/sharetribe/client# `npm run ensure-node-version`

    @ ensure-node-version /root/sharetribe/client
    check-node-version --package

node: v6.9.5
npm: v3.10.10

~/sharetribe/client# `./node_modules/.bin/webpack --config webpack.client.config.js`
Webpack dev build for Rails
Hash: 37ad5ce20d972e226d9b
Version: webpack 1.13.3
Time: 24350ms
Asset Size Chunks Chunk Names
app-bundle.js 8.72 MB 0 [emitted] app
vendor-bundle.js 408 kB 1 [emitted] vendor
app-bundle.css 74.9 kB 0 [emitted] app
[0] multi app 28 bytes {0} [built]
[0] multi vendor 40 bytes {1} [built]
[295] ./app/routes/routes.js 139 kB {0} [optional] [built]
+ 703 hidden modules

ERROR in ENOENT: no such file or directory, scandir '/root/sharetribe/client/node_modules/node-sass/vendor'
@ ./~/react-dates/css/styles.scss 4:14-97
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 4 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules
Child extract-text-webpack-plugin:
+ 2 hidden modules

**Comment by bladealslayer** [comment]
@funahasf did you try what @kpuputti suggested in #2856 ? I don't see any error besides `npm run ensure-node-version && webpack -w --config webpack.client.config.js`

**Comment by funahasf** [comment]
If I didn't misunderstand your comment, I tried what suggested in #2856, as shown above.
I tried deleting `node_modules` and `client/node_modules`, and ran again `npm install`. 
I got the same result with above.
Since It didn't work in `/sharetribe` with a WARN below, I installed in `/sharetribe/client` directory.

~/sharetribe# `npm install`
> npm WARN lifecycle undefined~postinstall: cannot run in wd %s %s (wd=%s) undefined cd client && npm install /root/sharetribe

**Comment by bladealslayer** [comment]
Sorry, can't reproduce this. There's a new release coming soon with Rails 5, which has updated node version too. Maybe you won't encounter the issue there. If you want to try this before the official release, check the current `master` branch.

**Comment by funahasf** [comment]
ok, I'll give a shot on that. Thank you for your help.

**Comment by funahasf** [comment]
I ended up installing all modules one by one manually on client directory. I found some modules in "devDependencies" in package.jason file that I couldn't successfully installed even manually, but all modules listed in "dependencies" were fine. The system is running fine in production mode.
