### ISSUE TITLE
Marketcluster bug

### ISSUE THREAD

**Issue by evanshabsove** [sharetribe/sharetribe#3015]
Hey I don't know if this is the best spot for this, and the issue may be non existent now since you recently updated sharetribe, but I noticed a bug when a group of listings were not perfectly at the same address. The problem was that the statement that checked if the markers were in the same position, not within the bounds of a cluster. On my version of Sharetribe the statement looked like
```
  for (var i = 1, marker; marker = markers[i]; i++) {
    if (!marker.getPosition().equals(position)) sameLocation = false;
  }
```

a quick change to 

```
  for (var i = 1, marker; marker = markers[i]; i++) {
    if (!this.cluster_.bounds_.contains(marker.getPosition())) sameLocation = false;
  }
```

Fixed the problem. 

Again not sure if this has already been fixed in an updated version of Sharetribe. I took a look at the new marketcluster.js file and saw the code was fairly different. 

Thanks!

**Comment by bladealslayer** [comment]
I'm going to close this, as it doesn't seem to be confirmed issue with current version.
