### ISSUE TITLE
Can you please update your tutorial? make it more detailed?

### ISSUE THREAD

**Issue by alexlizogub** [sharetribe/sharetribe#3073]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
> npm -v
```

##### Server mode:

_Are you running in development or production mode?_

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_

Actual result: _What was the actual result after running the steps above?_

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment]
Hi Alex!

Thanks for the suggestion. One difficult thing is that there are many hosting solutions and providers and at this time we can't describe the installation process for all of them.

However don't hesitate to discuss this with others open-source users in the [Sharetribe Open-Source Community forum](https://www.sharetribe.com/community/): this is the best place to get help from people who maybe are using the same setup than you.

Hopefully this helps.

**Comment by karibuTW** [comment]
I've tested again my tutorial and it seems to be working
https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04/

But Sharetribe is evolving fast. It might not be working anymore in few months haha.
