### ISSUE TITLE
Renew 

### ISSUE THREAD

**Issue by alexlizogub** [sharetribe/sharetribe#3076]
Hi! I'm trying to install Sharetribe following instructions from readme, but seems like they don't make any more sense. E.g. - You install ruby 2.3.1 as it's said that run "bundle install" and it gives you "Your Ruby version is 2.3.1, but your Gemfile specified 2.3.4

Thanks!

**Comment by valdis** [comment]
Thanks for pointing this out. 
We have updated Sharetribe to use ruby 2.3.4 but that is not yet reflected in the README. Will updated the documentation.

**Comment by thomasmalbaux** [comment]
Again, thanks for reporting, Alex!

We've now updated the [Readme file](https://github.com/sharetribe/sharetribe/blob/master/README.md) to reflect that Ruby 2.3.4 is the current version. You can also learn more about this [in the latest release information](https://github.com/sharetribe/sharetribe/releases/tag/v7.1.0).
