### ISSUE TITLE
Didn't receive admin confirmation email.

### ISSUE THREAD

**Issue by alexlizogub** [sharetribe/sharetribe#3081]
Sharetribe Version: 7.1 (current)
Environment: 8099a972d0eef3ad306405f23db65b75f32f874a  Ubuntu 16.04

```
> node -v 7.8.0
> npm -v 4.2.0
```

Server mode: production

Description:

I didn't receive administrator confirmation email after I have entered my info in ipadress:3000
So I can't really do anything 

Just followed steps from github 1-5 and "how to setup production.." 

How to fix it? what's wrong? 

Is it ok that I can connect to ipadress:3000 only when I enter "bundle exec rails server -e production" 
and it works until I close the ssh terminal?

**Comment by thomasmalbaux** [comment]
Hello there.

Did you configure your mail delivery method in your config.yml file?
You can have a look at this in the example config file at https://github.com/sharetribe/sharetribe/blob/master/config/config.defaults.yml#L166

As soon as you configure this, it should then work smoothly.

If you face some difficulties to configure your SMTP or make sure that your sendmail command works, don't hesitate to ask help from other open-source users in Sharetribe's Community forum at https://www.sharetribe.com/community/

Hopefully this helps.

**Comment by alexlizogub** [comment]
Hello,
I have installed sendmail and added
 ` mail_delivery_method: sendmail`
to config/config.yml file 
If I run `ps -e | grep sendmail`
Output is:  `1662 ?        00:00:00 sendmail-mta`

Tried with smtp - does not work too. 

Any suggestions?

**Comment by thomasmalbaux** [comment]
Thanks for those details!

Unfortunately this doesn't ring a bell. We don't offer support for the open-source version but don't hesitate to post this in [the Community forum](https://www.sharetribe.com/community/), this is the best place to get help from other open-source users!
