### ISSUE TITLE
Basic Details update failed problem. (Re-open #3012)

### ISSUE THREAD

**Issue by terrence0488** [sharetribe/sharetribe#3082]
Please re-open the Issue #3012 
A few other people are having the similar issue too.

here I'm quoting my reply to #3012 
> Any updates??
> Having the same problem here.
> Using:
>   Ubuntu 16.04 x64
>   in Production mode
>   Sharetribe version 7.1
>   node 7.8.0
>   npm 4.2.0
> 
> No error from server side log. After clicking the "Save Setting" button, server output showing a PATCH request with status 302. But the red bar "Detail update failed." just won't go away.
> 
> Similar to @YASSERKOT, I see this exact same error on the exact same page 
> ![screenshot](https://user-images.githubusercontent.com/19874315/28314304-433617f6-6bba-11e7-84cc-b3ec78bf8198.png "screenshot")
> 
> I also realize that there are a bunch of error from the browser console:
> ![screenshot](http://hostthenpost.org/uploads/f0b44c89d860250421b9824e0a3ead04.png "screenshot")
> 
> not sure if it's something related.

**Comment by jkadry** [comment]
Looks like you're running the wrong node version: 7.8.0

You should use NPM to install the correct node version: 6.9
Install npm first. Instructions here: https://www.npmjs.com/get-npm

Then use a node version manager like NVM (https://github.com/creationix/nvm) and use this command:
`nvm use 6.9`

**Comment by terrence0488** [comment]
Hi, @jkadry,
I am using nvm.
Before I tried with Node7.8, I was using Node6.9 and the exact same thing happen.

Here is what I did in the first attempt:

1. nvm to switch to node 6.9.5
2. did a npm install.
... did everything in the middle ...
3. nvm switch to node 7.8 (the next step will complain if you don't do this).
4. RAILS_ENV=production NODE_ENV=production bundle exec rake assets:precompile
5. nvm switch back to node 6.9.5
6. run the server.

And then, the "Details update failed" red bar appears. 
I check and [CHANGELOG ](https://github.com/sharetribe/sharetribe/blob/master/CHANGELOG.md)and realize the in v7.0.0 - 2017-08-08, Sharetribe has updated to Node7.8, somehow the readme never updated. It was quite confusing. But nevermind, let's go back to zero and do it all again with Node7.8

Here is what I did in the second attempt:

1. nvm install Node7.8.0
2. did a npm install
3. everything else
4. run the server.

The Red Bar of "Details update failed" appears again. Sigh... :(

Hope somebody can help to get through this.
If you need anything, please let me know. Happy to provide you with all level of details.

by the way, I have been following very closely to the guide in README, other than the database that I'm using, which is the latest stable version of MariaDB 10.2.

**Comment by jkadry** [comment]
Is it working on development or test environments?
Try these commands:
`nvm install 6.9`
`npm use 6.9`

run server

**Comment by terrence0488** [comment]
[Update]

Problem Solved.
I spin up a server and retry everything from zero.
And for the whole process, I was using Node 7.8.0 all the way.
Everything went well this time. 

I realize I have done something stupid the first few times.
When I clone the Git, I did not checkout the latest branch (I guess this is the reason I failed).
This is because I was following the guide from this website https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04/

So, hopefully for people who are following the same guide and ended up in the same s***
Remember
- Checkout "latest" branch.
- use Node 7.8.0 all the way. 

I will close this now.
Thanks @jkadry for trying to help.

**Comment by thomasmalbaux** [comment]
Thanks a lot for sharing those details and the solution, good to hear that it works now!

**Comment by sophy17** [comment]
Hello 
I have the some problem with  Sharetribe version 7.1

Any updates??
Having the same problem here.
Using:
Ubuntu 16.04 x64
in Production mode
Sharetribe version 7.1
node 7.8.0
npm 4.2.0

how can check and find a solution to this problem 
witing for your help 
thanks

**Comment by sophy17** [comment]
![probconfigbasics](https://user-images.githubusercontent.com/32310976/32148416-e9f2c25a-bcf6-11e7-98ba-17e605c5bc90.png)

Hello 
here the different steep for my instlation 



sudo apt-get update
sudo apt-get upgrade

sudo apt-get install git-core curl
git clone git://github.com/sharetribe/sharetribe.git
cd sharetribe

### Need 7.8 version
sudo apt-get install build-essential libssl-dev curl imagemagick
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh -o install_nvm.sh
bash install_nvm.sh
source ~/.profile
nvm ls-remote  ### It will display the list of available nodejs version.
We want the 7.8.0, so run:
nvm install 7.8.0
nvm use 7.8.0

sudo apt-get install mysql-server   (and set the password, toor in my case)
mysql -u root -p
CREATE DATABASE sharetribe_production CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT all privileges ON sharetribe_production.* TO 'sharetribe'@'localhost' IDENTIFIED BY 'PASSWORD';
exit

cp config/database.example.yml config/database.yml
nano config/database.yml     to replace Username and Password. Remove # ADD DATABASE PASSWORD and set the user/pass we just created in the production

sudo apt-get install libmysqlclient20 libodbc1 libpq5
wget http://sphinxsearch.com/files/sphinxsearch_2.2.11-release-1~xenial_amd64.deb
sudo dpkg -i sphinxsearch_2.2.11-release-1~xenial_amd64.deb

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install 2.3.4
rvm rubygems current
rvm use 2.3.4


change this parameters in the confg file: config.default.yml
domain:"domain.com:3000"


sudo apt-get install libxslt-dev libxml2-dev -y
sudo apt-get install libmysqlclient-dev -y
gem install bundler
bundle install

npm install

rake secret  : This command will generate a the secret_key_base, copy this value in the file config.yml
nano config/config.yml and add:

production:
  secret_key_base: e41a2728874df4e3019c4d861ae0c567b213810043ee1556dd9aadfa1acd$
  
 Save the file

RAILS_ENV=production bundle exec rake db:create
RAILS_ENV=production bundle exec rake db:structure:load
RAILS_ENV=production bundle exec rake ts:index
RAILS_ENV=production bundle exec rake ts:start
RAILS_ENV=production NODE_ENV=production bundle exec rake assets:precompile



pour lancer sharetribe, open  new window
cd sharetribe
source ~/.rvm/scripts/rvm
RAILS_ENV=production bundle exec rake jobs:work

et dans une nouvelle fenetre
source ~/.rvm/scripts/rvm
bundle exec rails server -e production

And access to sharetribe instance through IP:3000

CAN YOU help me 
i have this error 
![capture d ecran 2017-10-29 a 22 16 37](https://user-images.githubusercontent.com/32310976/32148414-e2a89d80-bcf6-11e7-839b-1ce289ccd448.png)

**Comment by karibuTW** [comment]
Thanks terrence0488 for sharing the issues with my tuto. It was indeed outdated. I have revised  it to use latest branch, use node 7.8 etc...

Should be okay now.

**Comment by sophy17** [comment]
Hello terrence0488, karibuTW 

i try to re install evrythink and i have the some probleme 
i do the following commande to get the latest branch

sudo apt-get install git-core curl
git clone git://github.com/sharetribe/sharetribe.git
cd sharetribe
git checkout latest

### Need 7.8 version
sudo apt-get install build-essential libssl-dev curl imagemagick
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh -o install_nvm.sh
bash install_nvm.sh
source ~/.profile
nvm ls-remote  ### It will display the list of available nodejs version.
We want the 7.8.0, so run:
nvm install 7.8.0
nvm use 7.8.0


Can you help me 
thanks

**Comment by bhanunischal** [comment]
I am also facing the same problem, installed Sharetibe on 15-02-2018 using the latest package and getting same error.
Can someone help me installing latest branch?

Thanks
