### ISSUE TITLE
FATAL  ActionView:: Template::Error - couldn't find file 'vendor-bundle' with type 'application/javascript' Checked in these paths: 

### ISSUE THREAD

**Issue by SonamJagetia** [sharetribe/sharetribe#3092]
Environment : Mac OS X, 

_What's your node version? Run the following commands and copy the result here:_

```
> node -6.11.4
> npm -5.3.0

I installed the sharetribe in my machine and reached to this level
![screen shot 2017-10-06 at 6 18 43 pm](https://user-images.githubusercontent.com/25615436/31282913-96587568-aad1-11e7-853d-dfc1a78f5d30.png)

After that page when I fill the details, I got these errors, Would you please suggest me the further steps
![screen shot 2017-10-06 at 6 17 06 pm](https://user-images.githubusercontent.com/25615436/31282939-ac3625ce-aad1-11e7-9e5e-5a746415d4c4.png)


Step 10 : 
sharetribe sonamvjagetia$ foreman start -f Procfile.static
19:53:52 rails.1               | started with pid 12784
19:53:52 rails-client-assets.1 | started with pid 12785
19:53:52 rails-server-assets.1 | started with pid 12786
19:53:52 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
19:53:52 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
19:53:52 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
19:53:52 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
19:53:52 rails-server-assets.1 | client/app/routes/routes.js found
19:53:53 rails-client-assets.1 | 
19:53:53 rails-server-assets.1 | 
19:53:53 rails-client-assets.1 | > @ build:dev:client /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-server-assets.1 | > @ build:dev:server /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
19:53:53 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
19:53:53 rails-client-assets.1 | 
19:53:53 rails-server-assets.1 | 
19:53:53 rails-server-assets.1 | 
19:53:53 rails-server-assets.1 | > @ ensure-node-version /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-server-assets.1 | > check-node-version --package
19:53:53 rails-server-assets.1 | 
19:53:53 rails-client-assets.1 | 
19:53:53 rails-client-assets.1 | > @ ensure-node-version /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-client-assets.1 | > check-node-version --package
19:53:53 rails-client-assets.1 | 
19:53:54 rails-server-assets.1 | node: v6.11.4
19:53:54 rails-server-assets.1 | npm: v5.3.0
19:53:54 rails-server-assets.1 | Error: Wanted node version "7.8" (>=7.8.0 <7.9.0)
19:53:54 rails-server-assets.1 | Error: Wanted npm version "4.2.0" (4.2.0)
19:53:54 rails-server-assets.1 | To install node, run `nvm install 7.8` or check https://nodejs.org/
19:53:54 rails-server-assets.1 | To install npm, run `npm install -g npm@4.2.0`
19:53:54 rails-client-assets.1 | node: v6.11.4
19:53:54 rails-client-assets.1 | npm: v5.3.0
19:53:54 rails-client-assets.1 | Error: Wanted node version "7.8" (>=7.8.0 <7.9.0)
19:53:54 rails-client-assets.1 | Error: Wanted npm version "4.2.0" (4.2.0)
19:53:54 rails-client-assets.1 | To install node, run `nvm install 7.8` or check https://nodejs.org/
19:53:54 rails-client-assets.1 | To install npm, run `npm install -g npm@4.2.0`
19:53:54 rails-server-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-server-assets.1 | npm ERR! errno 1
19:53:54 rails-server-assets.1 | npm ERR! @ ensure-node-version: `check-node-version --package`
19:53:54 rails-server-assets.1 | npm ERR! Exit status 1
19:53:54 rails-server-assets.1 | npm ERR! 
19:53:54 rails-server-assets.1 | npm ERR! Failed at the @ ensure-node-version script.
19:53:54 rails-server-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-server-assets.1 | 
19:53:54 rails-server-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-server-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_102Z-debug.log
19:53:54 rails-client-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-client-assets.1 | npm ERR! errno 1
19:53:54 rails-client-assets.1 | npm ERR! @ ensure-node-version: `check-node-version --package`
19:53:54 rails-client-assets.1 | npm ERR! Exit status 1
19:53:54 rails-client-assets.1 | npm ERR! 
19:53:54 rails-client-assets.1 | npm ERR! Failed at the @ ensure-node-version script.
19:53:54 rails-client-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-client-assets.1 | 
19:53:54 rails-client-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-client-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_117Z-debug.log
19:53:54 rails-server-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-server-assets.1 | npm ERR! errno 1
19:53:54 rails-server-assets.1 | npm ERR! @ build:dev:server: `npm run ensure-node-version && webpack -w --config webpack.server.config.js`
19:53:54 rails-server-assets.1 | npm ERR! Exit status 1
19:53:54 rails-server-assets.1 | npm ERR! 
19:53:54 rails-server-assets.1 | npm ERR! Failed at the @ build:dev:server script.
19:53:54 rails-server-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-server-assets.1 | 
19:53:54 rails-server-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-server-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_137Z-debug.log
19:53:54 rails-client-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-client-assets.1 | npm ERR! errno 1
19:53:54 rails-client-assets.1 | npm ERR! @ build:dev:client: `npm run ensure-node-version && webpack -w --config webpack.client.config.js`
19:53:54 rails-client-assets.1 | npm ERR! Exit status 1
19:53:54 rails-client-assets.1 | npm ERR! 
19:53:54 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script.
19:53:54 rails-client-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-client-assets.1 | 
19:53:54 rails-client-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-client-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_144Z-debug.log
19:53:54 rails-server-assets.1 | exited with code 1
19:53:54 system                | sending SIGTERM to all processes
19:53:54 rails-client-assets.1 | exited with code 1
19:53:54 rails.1               | terminated by SIGTERM

**Comment by aniketstiwari** [comment]
I have resolve this issue
1) curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
If everything went well, open new Terminal window/tab.List what versions of Node are currently installed (probably none)
2) nvm ls
3) nvm install v6.11.3

Refer this link https://gist.github.com/d2s/372b5943bce17b964a79

**Comment by aniketstiwari** [comment]
close #3092

**Comment by vivek2007** [comment]
root@ubuntu-2gb-nyc3-01:/home/rails/rails_projects/sharetribe# foreman start -f Procfile.static
13:32:07 rails.1               | started with pid 29955
13:32:07 rails-client-assets.1 | started with pid 29957
13:32:07 rails-server-assets.1 | started with pid 29959
13:32:07 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
13:32:07 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
13:32:07 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
13:32:07 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
13:32:07 rails-server-assets.1 | client/app/routes/routes.js found
13:32:08 rails-client-assets.1 | 
13:32:08 rails-client-assets.1 | > @ build:dev:client /home/rails/rails_projects/sharetribe/client
13:32:08 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
13:32:08 rails-client-assets.1 | 
13:32:08 rails-server-assets.1 | 
13:32:08 rails-server-assets.1 | > @ build:dev:server /home/rails/rails_projects/sharetribe/client
13:32:08 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
13:32:08 rails-server-assets.1 | 
13:32:09 rails-client-assets.1 | 
13:32:09 rails-client-assets.1 | > @ ensure-node-version /home/rails/rails_projects/sharetribe/client
13:32:09 rails-client-assets.1 | > check-node-version --package
13:32:09 rails-client-assets.1 | 
13:32:09 rails-server-assets.1 | 
13:32:09 rails-server-assets.1 | > @ ensure-node-version /home/rails/rails_projects/sharetribe/client
13:32:09 rails-server-assets.1 | > check-node-version --package
13:32:09 rails-server-assets.1 | 
13:32:09 rails-server-assets.1 | node: v7.8.0
13:32:09 rails-server-assets.1 | npm: v4.2.0
13:32:09 rails-server-assets.1 | sh: 1: webpack: not found
13:32:09 rails-server-assets.1 | 
13:32:09 rails-server-assets.1 | npm ERR! Linux 4.4.0-97-generic
13:32:09 rails-server-assets.1 | npm ERR! argv "/root/.nvm/v7.8.0/bin/node" "/root/.nvm/v7.8.0/bin/npm" "run" "build:dev:server"
13:32:09 rails-server-assets.1 | npm ERR! node v7.8.0
13:32:09 rails-server-assets.1 | npm ERR! npm  v4.2.0
13:32:09 rails-server-assets.1 | npm ERR! file sh
13:32:09 rails-server-assets.1 | npm ERR! code ELIFECYCLE
13:32:09 rails-server-assets.1 | npm ERR! errno ENOENT
13:32:09 rails-server-assets.1 | npm ERR! syscall spawn
13:32:09 rails-server-assets.1 | npm ERR! @ build:dev:server: `npm run ensure-node-version && webpack -w --config webpack.server.config.js`
13:32:09 rails-server-assets.1 | npm ERR! spawn ENOENT
13:32:09 rails-server-assets.1 | npm ERR! 
13:32:09 rails-server-assets.1 | npm ERR! Failed at the @ build:dev:server script 'npm run ensure-node-version && webpack -w --config webpack.server.config.js'.
13:32:09 rails-server-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
13:32:09 rails-server-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
13:32:09 rails-server-assets.1 | npm ERR! not with npm itself.
13:32:09 rails-server-assets.1 | npm ERR! Tell the author that this fails on your system:
13:32:09 rails-server-assets.1 | npm ERR!     npm run ensure-node-version && webpack -w --config webpack.server.config.js
13:32:09 rails-server-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
13:32:09 rails-server-assets.1 | npm ERR!     npm bugs 
13:32:09 rails-server-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
13:32:09 rails-client-assets.1 | node: v7.8.0
13:32:09 rails-server-assets.1 | npm ERR!     npm owner ls 
13:32:09 rails-server-assets.1 | npm ERR! There is likely additional logging output above.
13:32:09 rails-client-assets.1 | npm: v4.2.0
13:32:09 rails-client-assets.1 | sh: 1: webpack: not found
13:32:09 rails-client-assets.1 | 
13:32:09 rails-server-assets.1 | 
13:32:09 rails-server-assets.1 | npm ERR! Please include the following file with any support request:
13:32:09 rails-server-assets.1 | npm ERR!     /root/.npm/_logs/2017-10-16T13_32_09_560Z-debug.log
13:32:09 rails-client-assets.1 | npm ERR! Linux 4.4.0-97-generic
13:32:09 rails-client-assets.1 | npm ERR! argv "/root/.nvm/v7.8.0/bin/node" "/root/.nvm/v7.8.0/bin/npm" "run" "build:dev:client"
13:32:09 rails-client-assets.1 | npm ERR! node v7.8.0
13:32:09 rails-client-assets.1 | npm ERR! npm  v4.2.0
13:32:09 rails-client-assets.1 | npm ERR! file sh
13:32:09 rails-client-assets.1 | npm ERR! code ELIFECYCLE
13:32:09 rails-client-assets.1 | npm ERR! errno ENOENT
13:32:09 rails-client-assets.1 | npm ERR! syscall spawn
13:32:09 rails-client-assets.1 | npm ERR! @ build:dev:client: `npm run ensure-node-version && webpack -w --config webpack.client.config.js`
13:32:09 rails-client-assets.1 | npm ERR! spawn ENOENT
13:32:09 rails-client-assets.1 | npm ERR! 
13:32:09 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script 'npm run ensure-node-version && webpack -w --config webpack.client.config.js'.
13:32:09 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
13:32:09 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
13:32:09 rails-client-assets.1 | npm ERR! not with npm itself.
13:32:09 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
13:32:09 rails-client-assets.1 | npm ERR!     npm run ensure-node-version && webpack -w --config webpack.client.config.js
13:32:09 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
13:32:09 rails-client-assets.1 | npm ERR!     npm bugs 
13:32:09 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
13:32:09 rails-client-assets.1 | npm ERR!     npm owner ls 
13:32:09 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
13:32:09 rails-server-assets.1 | exited with code 1
13:32:09 system                | sending SIGTERM to all processes
13:32:09 rails.1               | terminated by SIGTERM
13:32:09 rails-client-assets.1 | terminated by SIGTERM
