### ISSUE TITLE
Need seed data?

### ISSUE THREAD

**Issue by brandonhilkert** [sharetribe/sharetribe#3103]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Description:

When I first installed everything, I was prompted to create a user and a community, which worked. Inside the community, I wanted to setup Stripe for payments, but I didn't have an option in the left admin nav menu for "Payments". I poke around the code enough to realize it seemed to need a record in the `payment_settings` table referencing `stripe`, so I added that and then payment showed up all of a sudden.

This doesn't feel right, so is there some seed data I'm missing which would allow me not to have to create these records by hand?

Also, I'm looking to enable availability. And like above, I dove around the code enough to realize there's a record in the `transaction_processes` table with an attribute of `process` set to `none`. If I change that to `preauthorize`, I get the option to edit the availability in the shape. This, too, doesn't feel right by editing these records manually. Am I missing something by not being able to do this from the UI?

**Comment by nnlugovoy** [comment]
one fast way for me was to invoke int_api with curl for proper setup 

```curl -H 'Content-Type: application/json' -d @marketplace.json http://localhost:3000/int_api/create_trial_marketplace
```
where in file marketplace.json you place your initial community data:
```json
{   
  "admin_email" : "admin@example.com",
  "admin_first_name": "Admin",
  "admin_last_name": "Admin",
  "admin_password": "password",
  "marketplace_country": "US",
  "marketplace_language": "en",
  "marketplace_name": "New Marketplace",
  "marketplace_type": "product"
}

```

**Comment by brandonhilkert** [comment]
I didn't know about this API. It looks like if you fill the community form out, it [merges `none` as the payment process](https://github.com/sharetribe/sharetribe/blob/master/app/controllers/communities_controller.rb#L29) and from that `int_api`, [merges `preauthorize` as the `payment_process`](https://github.com/sharetribe/sharetribe/blob/master/app/controllers/int_api/marketplaces_controller.rb#L24).

It'd be awesome to have that piece documented. It seems like a necessary bit for those that do want to accept payment. 

Any thoughts on `transaction_processes`? Does modifying `process` by hand seem like the appropriate way to make booking work?

**Comment by thomasmalbaux** [comment]
Hey there!

Indeed the upgrade to 7.2.0 was supposed to enable Stripe automatically, but the conditions were a bit too strict and some manual steps can be required.

We've now updated the Readme file to share the commands you should run, and clarified a bit the encryption key instructions.
You can find them at https://github.com/sharetribe/sharetribe/blob/master/README.md#enable-stripe

Availability management will then be possible too, as this feature can be used only if the online payment system is configured.

Keep up the good work!
