### ISSUE TITLE
Search is currently unavailable. Try searching again soon.

### ISSUE THREAD

**Issue by MatChar** [sharetribe/sharetribe#3119]
##### Sharetribe Version:

1806bc5dec418f4309a8f77a1371467fa568b49b

##### Environment:

AWS EC2 Ubuntu 16.04
node v6.9.5
npm 3.10.10

##### Server mode:

Production

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

Hello, 

i just installed Sharetribe OS and it is working great except the location search and the filters who both say : 

Search is currently unavailable. Try searching again soon.

My website is this one : 

ec2-52-56-45-231.eu-west-2.compute.amazonaws "." com/en/

I don't really know how to fix this :(

Help will be very welcomed, thanks in advance ! :)

**Comment by thomasmalbaux** [comment]
Hey there!

Right now, the components for the location search are not available yet in the open-source version, so relying on the regular keyword search is the best way to move forward.

Don't hesitate to discuss the setup with other open-source users on Sharetribe's Community forum at https://www.sharetribe.com/community/
You can also learn more about open-sourcing the location search at https://www.sharetribe.com/community/t/will-the-new-improved-search-function-on-sharetribe-com-come-to-the-open-source-version/107

**Comment by MatChar** [comment]
Thanks Thomas ! :)
