### ISSUE TITLE
"Detail update failed" when modifying admin panel - Basic details

### ISSUE THREAD

**Issue by karibuTW** [sharetribe/sharetribe#3132]
Hi guys,

I'm using the following tutorial on a fresh machine:
https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04/
[How to install Sharetribe for Ubuntu 16.04](https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04/)

and I am facing some errors.

When I try to update the "Basic details" of the admin panel, I got the error "Detail update failed"

In the log I found the 
```
127.0.0.1:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused
DalliError: No server available
```
type of error, as shared in some others unsolved issues.

I am using Ubuntu 16.04, node 7,8, Ruby 2.3.4, Webrick 1.3.1 and a dedicated subdomain (buy.freedif.org, that I have configured in the database as per official doc) and the machine is from AWS EC2.

Do you see any reason for this? Missing piece in the tutorial? Incorrect conf?

PS: Right after the installation and starting the prod mode, when navigating to IP:3000 to launch the installation/configuration panel (admin username, password,..), the styles were probably not set as you can see in below screen. (Not sure if it is connected)
![image](https://user-images.githubusercontent.com/7557855/32333003-65da8a04-c019-11e7-8a35-66cab980a366.png)

Thank you

**Comment by karibuTW** [comment]
Hi guys,
I've tried in a different machine, (Virtuall Machine and a dedicated server) and I did not got this issue. (The window the setup the marketplace is the same, like if they were missing some styles).
But I can save with no issues. (I still have the DalliError, but i guess it is not related then).

I can only reproduce this with the amazon's EC2. You could try to replicate using their free instance.

Anything special with EC2? Some additional configuration required?

Thank you

**Comment by thomasmalbaux** [comment]
Thanks for reporting! Indeed it seems that the configuration with EC2 requires some specific settings.

Unfortunately we don't offer support for this however don't hesitate to browse our Community forum at https://www.sharetribe.com/community/c/os-users and possibly open a new thread there: other open-source users might be able to help you, some may have encountered a similar situation already.

Hopefully this helps.

**Comment by karibuTW** [comment]
Thanks for confirming

**Comment by mswap** [comment]
karibuTW ,

Did you find any solution to this problem?
