### ISSUE TITLE
Stripe setup

### ISSUE THREAD

**Issue by iBicha** [sharetribe/sharetribe#3135]
Should Stripe setup details be added to the README in the [Payments](https://github.com/sharetribe/sharetribe#payments) section?

**Comment by thomasmalbaux** [comment]
Indeed! So far we didn't because Stripe was part of the unreleased features but version 7.2.0 has now been published and we've added a few details in the Payments sections of the readme file. 

Thanks!

**Comment by karibuTW** [comment]
Big thanks for this.
I think there is a typo/missing word in the payments section:
Stripe API keys are encrypted and you should the app_encryption_key
by 
**Stripe API keys are encrypted and you should use the app_encryption_key** ?

But actually I didn't get it how to enable/use Stripe in the opensource version as I don't have the Payment settings in the admin panel of my 7.2 version.
Can we revise a bit the README in this case?

Thanks
