### ISSUE TITLE
Stripe money is not refunded when order is canceled

### ISSUE THREAD

**Issue by xuanus** [sharetribe/sharetribe#3146]
Steps:
1. buyer sends an order request
2. seller accepts the order
3. buyer cancels the order

Actual result: 
4. Stripe money is not refunded when order is canceled

Expected result:
4. seller accepts the cancelation
5. Stripe money is refunded or partially refunded

**Comment by thomasmalbaux** [comment]
Hey there,

thanks for sharing your experience! Indeed right now we don't offer a refund feature: refunds should happen from the Stripe dashboard.

You can learn more at https://help.sharetribe.com/payments-and-transactions/online-payments-with-stripe/can-providers-issue-refunds-with-stripe
