### ISSUE TITLE
S3 signature issue

### ISSUE THREAD

**Issue by ali-hassan** [sharetribe/sharetribe#3160]
<Error
>
<Code
>
InvalidArgument
</Code
>
<Message
>
Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.
</Message
>
<ArgumentName
>
Authorization
</ArgumentName
>
<ArgumentValue
>
null
</ArgumentValue
>
<RequestId
>
67BF68D8EA92C08D
</RequestId
>
<HostId
>
3r7STAtrPEw9cbwe3gzE0GBr/lco/gmnpojE8xFo7MjFUa0hmNAuDTCNu1BGb1j4/NxzyJ/wMJg=
</HostId
>
</Error>
Getting this issue on uploading files at s3

_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
> npm -v
```

##### Server mode:

_Are you running in development or production mode?_

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_

Actual result: _What was the actual result after running the steps above?_

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment]
Hi there!

Sounds like your S3 configuration, maybe the part about your access and secret keys, is not correct yet.

Did you follow closely all the instructions at https://github.com/sharetribe/sharetribe/blob/master/README.md#setting-up-s3, especially step 6?

**Comment by ali-hassan** [comment]
That was not the issue issue was related region I fixed it BTW thanks for your answer.

**Comment by thomasmalbaux** [comment]
Thanks for the update! Good to hear that it has been fixed.
