### ISSUE TITLE
Login/registration not working on Chrome

### ISSUE THREAD

**Issue by karibuTW** [sharetribe/sharetribe#3167]
Hello guys,
I've installed Sharetribe on a VPS few days ago and the login/registration does not work with Chrome. It works well with Firefox tho.

If I use the domain name with the port 3000, it works in this case. But not without.

I have updated by /etc/hosts to have 127.0.0.1 mydomain.tld and even my hostname, on top of the Domain and Use Domain field in communities table.
Yet, no improvement.

Any idea of what could be wrong?

Thank you

**Comment by thomasmalbaux** [comment]
Hey there, thanks for reporting!

Indeed, there might be something wrong in your configuration.

Unfortunately we are not able to offer support for such specific setup but don't hesitate to discuss it in the Community forum at https://www.sharetribe.com/community/: other Sharetribe open-source users may have experienced something similar and would be able to help!
