### ISSUE TITLE
Stripe not enabled?

### ISSUE THREAD

**Issue by karibuTW** [sharetribe/sharetribe#3172]
Hi guys,

Stripe is supposed to be enabled since the version 7.2, however I am not able to see that from my side.
Do we need to do something else in the configuration to enable it?

Last, you may want to revise the README payment section to correct the typo
Stripe API keys are encrypted and you should the app_encryption_key
by
Stripe API keys are encrypted and you should setup the app_encryption_key ?

Thank you

**Comment by karibuTW** [comment]
So it seems we need to modify the database to enable Stripe or Paypal. (Limited doc on this tho)
Can we have it enabled per default or have something in the admin to enable/disable it?

However, the API keys for Stripe are not being accepted.
Any issue with the key pattern?

Adding this in the config.yml doesn't help
  stripe_private_key_pattern: "\\Ask_test_.{24}\\z"
  stripe_publishable_key_pattern: "\\Apk_test_.{24}\\z"

**Comment by vasaf** [comment]
Hey,

In your config.yml add this:

stripe_private_key_pattern: "sk_(test|live)_.{24}"
stripe_publishable_key_pattern: "pk_(test|live)_.{24}"
app_encryption_key: "2617463e32b65ec6645b3cb661f9686f2ab608c18ac930ee1295a1c1170504ed"

Now open up rails console.. (bundle exec rails c)

Now run both these to enable stripe payments:

TransactionService::API::Api.processes.create(community_id: 1, process: :preauthorize, author_is_seller: true)

TransactionService::API::Api.settings.provision(community_id: 1, payment_gateway: :stripe, payment_process: :preauthorize, active: true)

That should enable stripe payments in the Admin Dashboard for you.

**Comment by thomasmalbaux** [comment]
Indeed the upgrade to 7.2.0 was supposed to enable Stripe automatically, but the conditions were a bit too strict and some manual steps can be required.

We've now updated the Readme file to share the commands you should run, and clarified a bit the encryption key instructions.
You can find them at https://github.com/sharetribe/sharetribe/blob/master/README.md#enable-stripe

It's true that it isn't perfect, as the updated instructions are in the master branch but not in the Release 7.2.0. The work in progress prevents us to do a new release right now but following the instructions at https://github.com/sharetribe/sharetribe/blob/master/README.md#enable-stripe will work for the time being!
