### ISSUE TITLE
Sharetribe 7.2.0 Admin Manage Users Error

### ISSUE THREAD

**Issue by webprobox** [sharetribe/sharetribe#3193]
After new install Manage Users in Admin is working fine, Then I connected my account to Facebook and second user registered on the site. After second user registered in Admin after clicking on Manage Users I get Marketplace temporarily unavailable page. 

##### Sharetribe Version:

7.2.0

##### Environment:

Ubuntu 16.0.4

```
> node -v  7.8.0
> npm -v   4.2.0
```

##### Server mode:

Production

##### Description:

Manage users link in Admin goes to Marketplace temporarily unavailable page after second user registers. Both users also used Facebook to login after registering by email. 

I had this issue since my very first install but I assumed it was gone because link is accessible while there is only one user. 

Link becomes inaccessible after second user registers. Both users also used Facebook to login after registering with emails.

**Comment by thomasmalbaux** [comment]
Hi there!

Thanks for reporting. Sounds strange indeed. 
I'm not able to reproduce this, and it sounds quite related to your setup and possibly addition of custom languages.

I noticed that you've posted the issue already in Sharetribe's Community forum at https://www.sharetribe.com/community/t/sharetribe-7-2-manage-users-marketplace-temporarily-unavailable/883, hopefully someone with a similar experience will be able to help there.
