### ISSUE TITLE
Email confirmation not sent

### ISSUE THREAD

**Issue by ChechoCdls** [sharetribe/sharetribe#3202]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version: 
Latest

##### Environment:

My VPS CentOS

_What's your node version? Run the following commands and copy the result here:_

```
> node -v 7.8.0
> npm -v 
```

##### Server mode:
Production

##### Description:

I have installed sharetribe in producton mode, but no sent mails confirmation, in the console does not throw errors, or that means that the email is sent, but also does not arrive, I know what the problem may be.

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_

Actual result: _What was the actual result after running the steps above?_

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment]
Hi there!

Unfortunately we don't offer support for such specific installation.

You might want to double check your email setup in your `config.yml` file and can also discuss this with other open-source users in [Sharetribe's Community forum](https://www.sharetribe.com/community/c/os-users), possibly other people with a similar configuration may be able to share their experience!
