### ISSUE TITLE
can't edit sender email and name on installation

### ISSUE THREAD

**Issue by BruhKofi** [sharetribe/sharetribe#3203]
I installed sharetribe on the digital ocean and initially used gmail settings to test the emailing. Now I am trying to edit and change to custom domain and there is no option to edit or reverify the email address on the dashboard. thoughts anyone?

**Comment by thomasmalbaux** [comment]
Hey there!

What Sharetribe release do you use?

With 7.2, you should be able to edit the outgoing email address and sender name from the "Emails" section in the admin panel. Before 7.2, you'll have to use Rails command to make the change.

**Comment by BruhKofi** [comment]
the latest I should think. im working on master the master branch on a clone i made this morning bt its still not editable. so maybe the rails command?

**Comment by thomasmalbaux** [comment]
Would you share a screenshot of how the "Emails" section in your admin panel looks like?

**Comment by BruhKofi** [comment]
<img width="849" alt="screen shot 2018-01-07 at 13 05 48" src="https://user-images.githubusercontent.com/4693008/34649257-ba191732-f3ab-11e7-9823-70b876e88cd3.png">

**Comment by thomasmalbaux** [comment]
Thanks!

So indeed you should consider upgrading to [Release 7.2.0](https://github.com/sharetribe/sharetribe/releases/tag/v7.2.0). You'll then be able to use a new feature: "Allow admins to edit their Custom Outgoing Email and Sender Name".

Once upgraded, the Emails section will look like below, with the "Change sender email" option.

![sharetribe_outgoing-email-address](https://user-images.githubusercontent.com/2463785/34649332-c2842eac-f3b5-11e7-9a6f-56fdd110096d.png)

If you prefer not to upgrade, you'll have to work with Rails command or makes changes in the database to change the email. Unfortunately I won't be able to help with this, so upgrading might a good way to move forward!

Hopefully this helps.
