### ISSUE TITLE
e-mail configuration is not working

### ISSUE THREAD

**Issue by bhanunischal** [sharetribe/sharetribe#3207]
I have installed Sharetribe Community edition on AWS Ubuntu in Oregon region and using AWS SES service for sending e-mail. I am able to send e-mails from AWS SES service but the same is not working from Sharetribe application and I am unable to find any fail logs/emails. 
mail verification is not working because I am not getting e-mails. Also I tried to test forgot password option to check but that link is not active for me.

Please check application at store.globalfarming.co 
STORE.GLOBAL.FARMING.CO

**Comment by thomasmalbaux** [comment]
Hi there,

thanks for reporting!

Unfortunately we're not able to help with such specific setup but don't hesitate to share your situation in [Sharetribe's Community forum](https://www.sharetribe.com/community/) where other open-source users may be able to help you, it's possible that some people already had to configure emails in a way similar to yours!

Hopefully this helps.

**Comment by goldenstar999** [comment]
Hi,
I installed Sharetribe open source on Digital Ocean.
How to configure google alias email address without password in config.yml file?
I will be happy if you will help me.

Thanks,
