### ISSUE TITLE
Disable Community Subdomain

### ISSUE THREAD

**Issue by BruhKofi** [sharetribe/sharetribe#3219]
How do I disable the community subdomain being added to my url. 
i.e. Installed sharetribe (production) on abc.com, logged in and created the first admin and filled in name of community as abc

the confirmation email directed me to abc.abc.com and every email send thereafter

is there a way to disable this entirely?

**Comment by BruhKofi** [comment]
I went around it by setting domain in confg file as ".com" but I think this should not be the situation so bug?

**Comment by thomasmalbaux** [comment]
Hi there!

If you want to make your domain the main address, you should add it (like `www.abc.com` to the `communities.domain` field. Then, just set `communities.use_domain` to `true` (or `1`) and all traffic will be automatically redirected from your `communities.ident` address to your full `communities.domain` address.

In the future, don't forget to discuss this kind of question directly with other open-source users in [Sharetribe's Community forum](https://www.sharetribe.com/community/)!
