### ISSUE TITLE
Error message appears while pressing a user´s follow button

### ISSUE THREAD

**Issue by pabloglod** [sharetribe/sharetribe#3222]
##### Sharetribe Version:
v6.2.0

##### Environment:
AWS EC2 and RDS

node v6.9.5.
npm v3.10.10

##### Server mode:
Production mode

##### Description:
Error message appears while pressing a user´s follow button

Error message:
Page not found. 
The requested page does not exist. 
Return to main page.

##### Steps To Reproduce:
1. Access other user´s profile
2. Press follow button

Expected result: follow a user without error message

Actual result: error message appears

**Comment by thomasmalbaux** [comment]
Thanks for reporting.

I'm unable to reproduce this though. Everything seems to work fine.

Can you tell us a bit more?
Do you see more information from your console or logs? What is the page that is loaded (but fails)?

**Comment by pabloglod** [comment]
Hello @thomasmalbaux,

The error occurs when I access other user´s profile and I click the "Follow" button.

This is whats happens (sorry for the inconvenience but is in Spanish).
![follow-user-error](https://user-images.githubusercontent.com/35743358/35439042-67ffe424-0299-11e8-9c3b-382723439554.png)

This is what I found in the log:

Cache read: /translation_service/community/1
Cache fetch_hit: /translation_service/community/1
Cache read: /translation_service/community/1
Cache fetch_hit: /translation_service/community/1
{"method":"POST","path":"/es-ES/pablogleon/followers","format":"js","controller":"followers","action":"create","status":200,"duration":63.72,"view":2.72,"db":37.63,"params":{"locale":"es-ES","person_id":"pablogleon"},"host":"www.frinket.com","community_id":1,"current_user_id":"GDkyTcLs2S-JbQlGz_J1jA","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"https://www.frinket.com/es-ES/pablogleon","forwarded_for":"82.213.205.86, 10.0.3.27","request_uuid":"d30624c7-019b-4d04-819e-8671f58ca3f8"}
{"method":"POST","path":"/es-ES/pablogleon/followers","format":"js","controller":"followers","action":"create","status":500,"error":"ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'hKWWqkVrmc-G50pOeyGNjQ-GDkyTcLs2S-JbQlGz_J1jA' for key 'index_follower_relationships_on_person_id_and_follower_id': INSERT INTO `follower_relationships` (`person_id`, `follower_id`, `created_at`, `updated_at`) VALUES ('hKWWqkVrmc-G50pOeyGNjQ', 'GDkyTcLs2S-JbQlGz_J1jA', '2018-01-26 11:37:52', '2018-01-26 11:37:52')","duration":46.01,"view":0.0,"db":29.46,"params":{"locale":"es-ES","person_id":"pablogleon"},"host":"www.frinket.com","community_id":1,"current_user_id":"GDkyTcLs2S-JbQlGz_J1jA","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"https://www.frinket.com/es-ES/pablogleon","forwarded_for":"82.213.205.86, 10.0.3.27","request_uuid":"3495defb-eb95-4de1-9768-9ac07ce3bd7e"}
** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? true         
  API key set? false

ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry 'hKWWqkVrmc-G50pOeyGNjQ-GDkyTcLs2S-JbQlGz_J1jA' for key 'index_follower_relationships_on_person_id_and_follower_id': INSERT INTO `follower_relationships` (`person_id`, `follower_id`, `created_at`, `updated_at`) VALUES ('hKWWqkVrmc-G50pOeyGNjQ', 'GDkyTcLs2S-JbQlGz_J1jA', '2018-01-26 11:37:52', '2018-01-26 11:37:52')):
  app/controllers/followers_controller.rb:11:in `create'
  lib/jsroutes_middleware.rb:48:in `call'
  lib/rack_middleware/session_context_middleware.rb:15:in `call'
  lib/rack_middleware/marketplace_lookup.rb:33:in `call'
  lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
  lib/rack_middleware/enforce_ssl.rb:23:in `call'
  lib/rack_middleware/health_check.rb:12:in `call'


{"method":"POST","path":"/500","format":"js","controller":"errors","action":"not_found","status":404,"duration":16.42,"view":9.09,"db":3.22,"params":{"locale":"es-ES","person_id":"pablogleon","path":"500"},"host":null,"community_id":null,"current_user_id":null,"user_agent":null,"referer":null,"forwarded_for":null,"request_uuid":null}

Thank you very much for your help.

**Comment by thomasmalbaux** [comment]
Hey there,

thanks for the details.

As you can read in the logs, the error is pretty clear: 
`Duplicate entry 'hKWWqkVrmc-G50pOeyGNjQ-GDkyTcLs2S-JbQlGz_J1jA' for key 'index_follower_relationships_on_person_id_and_follower_id': INSERT INTO `follower_relationships` (`person_id`, `follower_id`, `created_at`, `updated_at`) VALUES ('hKWWqkVrmc-G50pOeyGNjQ', 'GDkyTcLs2S-JbQlGz_J1jA', '2018-01-26 11:37:52', '2018-01-26 11:37:52'))`

It seems that, for some reasons, this entry already exists in the database. I'm not sure exactly what's happening but somehow the relationship between the two users is already set.
It's true that it shouldn't be possible to "Follow" someone that you follow already (you should be able to unfollow only), but first it would be great to clear this first error.

You could try to delete all the relationships between those two users and try again. If it still fails, at least it won't be because of an existing relationship, so you might be able to learn more.

Hopefully this helps.

**Comment by pabloglod** [comment]
Hi @thomasmalbaux !

We have found that there is DB resctriction that prevents the creation of a relationship if ithe relationship already exists. When we press the follow button it tries to create the relatinship twice and that is why the error message shows. 

Do you know why this happens?

Thank you very much.

**Comment by thomasmalbaux** [comment]
Indeed, it's important to keep data unique there so it isn't possible to insert duplicate values.

> it tries to create the relationship twice

Do you mean that when you a user tries to follow another user for the first time (no relationship exists already), then it try to insert the data twice?

Unfortunately I'm not able to reproduce this behavior at all, so it's a bit difficult to figure out and it might be somehow related to your setup, but I don't have any clue at this point.

Let me know.

**Comment by pabloglod** [comment]
> Do you mean that when you a user tries to follow another user for the first time (no relationship exists already), then it try to insert the data twice?

Yes, that is what I meant. When I press the follow button for the first time, It tries to insert a duplicate relationship.

We will keep trying to find out what is going on.

**Comment by thomasmalbaux** [comment]
Hey there,

how are things? Had you a chance to investigate your setup to maybe find something that explains this behavior?

**Comment by pabloglod** [comment]
Hi Thomas,

We have solve the issue! The error was that the javascript that made this action was duplicated. What had to be done was to find where this duplicity was taking place and delete it.

Thank you very much for your help!

**Comment by thomasmalbaux** [comment]
Thanks for the follow-up, good to hear that this was fixed!
