### ISSUE TITLE
Password reset and welcome message send thru SMTP. Invitation and confirmation send thru SENDMAIL

### ISSUE THREAD

**Issue by michielauerbach** [sharetribe/sharetribe#3231]
We send out e-mails with MailGun, so I have a good track of the mails.

The system works with MailGun/ SMTP settings for the password reset and the welcome message.

But the invitation mails (invite other users) and the confirmation of your account messages are still beeing send thru sendmail (this I can see in the sendmail/ mail logs of the server)

So any thoughts?

**Comment by michielauerbach** [comment]
Hello? Anyone ready to look into this because I certainly do not know how/ where to solve it :-(

**Comment by thomasmalbaux** [comment]
Hey there,

thanks for reporting!

Indeed, sounds strange but I'm not able to reproduce this at all. Unfortunately we don't offer support about the open-source version but hopefully someone with a similar setup to yours will be able to help in [Sharetribe's Community Forum](https://www.sharetribe.com/community/)!

Keep up the good work.
