### ISSUE TITLE
Best Practices for Quick Iteration in Development Environment.

### ISSUE THREAD

**Issue by brendancol** [sharetribe/sharetribe#3261]
I would love any tips from core devs on this topic:

https://www.sharetribe.com/community/t/best-practices-for-quick-iteration-in-development-environment/1019

Thanks in advance.  Great project!

**Comment by thomasmalbaux** [comment]
Thanks for the post, Brendan!

Most of our team browse the Community Forum too so maybe some tips there and it will be also interesting to learn from others. Within the Sharetribe team, we may have a rather different workflow so hopefully input from many people there.

**Comment by brendancol** [comment]
@thomasmalbaux would you mind sharing a rough overview of you workflow...at a minimum when you are making changes to Sass files / erb templates?
