### ISSUE TITLE
RSpec::Expectations::ExpectationNotMetError

### ISSUE THREAD

**Issue by AndreyKos** [sharetribe/sharetribe#3263]
Hi all. When i tried run test "RAILS_ENV=test cucumber features -p ci" with phantomjs  i have error.

      expected #has_no_content?("new access token") to return true, got false (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/web_steps.rb:210:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/web_steps.rb:39:in `with_scope'
      ./features/step_definitions/web_steps.rb:209:in `/^(?:|I )should not see "([^"]*)"(?: within "([^"]*)")?$/'
      features/people/user_creates_the_webhooks.feature:28:in `Then I should not see "new access token"'

Please tell me where to look for the answer or how to fixed this problem.

> phantomjs version 2.1.1

File  features/people/user_creates_the_webhooks.feature:

  

> Feature: User add and delete webhooks
> 
>   @javascript
>   Scenario: user add new webhook
>     Given I am logged in as "alexeycharly"
>     And I am on webhooks page
>     When I follow "New Webhook"
>     Then I should see "Send me everything"
>     And I should see "Let me select individual events"
>     And I should not see "Event Type"
>     And I should not see "Listing Type"
>     Then I fill in "webhook_title" with "new test webhook"
>     And I fill in "webhook_webhook_url" with "http://example.com"
>     And I fill in "webhook_secret" with "secret key"
>     And I press "Add Webhook"
>     Then I should see "new test webhook"
> 
>   @javascript
>   Scenario: user generate new token and delete
>     Given I am logged in as "alexeycharly"
>     And I am on tokens page
>     When I click ".link-general-token"
>     And I fill in "person_token_title" with "new access token"
>     And I press "Generate new token"
>     Then I should see "new token"
>     And I click ".link-general-revoke"
>     And I confirm alert popup
>     Then I should not see "new access token"
>

**Comment by zenikk** [comment]
@AndreyKos 
Although your issue is related to your own code, not from Sharetribe, one possible workaround that can probably work, would be to add some waiting for server response:

> And I click ".link-general-revoke"
> And I confirm alert popup
> **And I wait for 1 second**
> Then I should not see "new access token"

If that does not  help, I could recommend you first to insert something like line **An wait for 1000 seconds** before 
```
And I press "Generate new token"
Then I should see "new token"
```
Then launch this single feature 
```RAILS_ENV=test cucumber  features/people/user_creates_the_webhooks.feature```
and open test site url in your browser, watch log/test.log output and try to perform actions using browser, maybe some errors in javascript console appear, or some exceptions in backend are raised.

**Comment by thomasmalbaux** [comment]
Thanks Zenikk for the help with this!

@AndreyKos Indeed as this is related to your own code, don't hesitate to continue this discussion with other open-source users on Sharetribe's Community Forum at https://www.sharetribe.com/community/ :-)
