### ISSUE TITLE
what does it mean and iam getting this error while execting this command "bundle exec rake jobs:work" and in this "http://lvh.me:3000/" iam getting connection refused

### ISSUE THREAD

**Issue by aithavinay** [sharetribe/sharetribe#3270]
DEBUG   SQL (0.5ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2018-03-23 07:33:34', `delayed_jobs`.`locked_by` = 'host:vinay-desktop pid:24072' WHERE ((run_at <= '2018-03-23 07:33:34.829681' AND (locked_at IS NULL OR locked_at < '2018-03-23 07:30:34.829722') OR locked_by = 'host:vinay-desktop pid:24072') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1

**Comment by thomasmalbaux** [comment]
Hey there.

Everything looks good here. This is a log of the command ran automatically to process all delayed_jobs every few seconds, to process tasks that are pending.

This shouldn't be related to your connection refused error, so you might want to check other logs to find out what's wrong and maybe double check that http://lvh.me:3000/ is the correct address for your marketplace (maybe you could try with `localhost` and double check that 3000 is your configured port? 5000 is sometimes a value that works too.

Don't hesitate to discuss this with other open-source users in Sharetribe's Community forum at https://www.sharetribe.com/community/!

Hopefully this helps.

**Comment by sriharsha1235** [comment]
Is the issue fixed aithavinay ?
