### ISSUE TITLE
when i try to add new listing iam not getting anything and i added listing categories also.How to fix this error

### ISSUE THREAD

**Issue by aithavinay** [sharetribe/sharetribe#3272]
![screenshot from 2018-03-26 16-25-39](https://user-images.githubusercontent.com/31407959/37902663-bb98f114-3112-11e8-9948-54941d6f0056.png)
![image](https://user-images.githubusercontent.com/31407959/37902874-7c3f7258-3113-11e8-98b3-5d2abb9b78a5.png)

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

As you can see from the error it seems that some component is missing from your installation setup, or possibly some translation files.

I noticed that you've posted in the Community forum already, which is the best way to get support and help from others about the open-source version. Let's continue the discussion there!

**Comment by aithavinay** [comment]
ok thankyou for your responce 
can you tell how to find where is the error means in which installation i made wrong
