### ISSUE TITLE
npm install stuck at i18n-js

### ISSUE THREAD

**Issue by chaitanya1985** [sharetribe/sharetribe#3276]
Working on Sharetribe "latest" branch
Using following sharetribe version:
66adb5a71e33286c8880f0c2e662b17ab865f307

##### Environment:
ubuntu 16.10
node v7.8.0
npm  v4.2.0

##### Server mode:
development

##### Description:
Got following error while installing npm
npm ERR! not a package ../github.com/sharetribe/i18n-js/archive/interpolation-mode.tar.gz

##### Steps To Reproduce:
npm install

**Comment by thomasmalbaux** [comment]
Hi there!

Unfortunately I'm not able to reproduce this issue at all. Can you tell us a bit more?

Would you have a chance to try again? This package is hosted on Github and it could be that, for some reason, it wasn't possible to download it when you tried.

Let us know!

**Comment by pcm211** [comment]
i think you are using an AWS free tier server for the installation of Sharetribe. 
There are a lot of tweaks that are needed to make a free version of AWS run shartribe. 

Try installing it locally first

**Comment by thomasmalbaux** [comment]
Unfortunately no more details and information about this, so closing for now.
