### ISSUE TITLE
Order Summary sharetribe

### ISSUE THREAD

**Issue by DemonRem** [sharetribe/sharetribe#3292]
i wonder if it's possible to do thing like this after payment in sharetribe
![screen-20 46 15 18 04 2018](https://user-images.githubusercontent.com/29927382/38948980-bf67a1b6-4349-11e8-9255-366b2be76bcf.png)

**Comment by thomasmalbaux** [comment]
Hi there!

Indeed right now we don't offer such template but this is an interesting suggestion. We'll consider it for future developments, but I don't have any timeline to share yet.

You could of course build this yourself on top of the open-source version, on your own server though. Maybe you could discuss it with other open-source users at https://www.sharetribe.com/community/c/os-users?

Keep us posted!
