### ISSUE TITLE
Issues in login with facebook

### ISSUE THREAD

**Issue by sainitawgt** [sharetribe/sharetribe#3339]
Login with facebook option is not working in my site. Login is successful but its showing the following.. 
This page isn't available
The link you followed may be broken, or the page may have been removed.

It was working perfectly initially. I have upgraded the version to v5.6.2 now but its showing the above mentioned error.

**Comment by thomasmalbaux** [comment]
Hi there,

can you tell us a bit more?

Indeed lots of things have changed overtime with Facebook Login and it's recommended to use the latest version (7.3.0) to get things up to date.

Did you also follow [the instructions in Sharetribe's Help Center](https://help.sharetribe.com/managing-your-marketplace/social-media/how-to-configure-facebook-login) to configure things?

Let us know.

**Comment by sainitawgt** [comment]
@thomasmalbaux  
Please check the below link. These are settings in my client OAuth section 
https://user-images.githubusercontent.com/27990982/40828965-bd10442c-659f-11e8-9f0d-a2351b60d7ef.png

It seems there is some issue in redirect url which I am unable to figure out. As after successful login its shows the mentioned message.
Check this link regarding this:

https://user-images.githubusercontent.com/27990982/40829233-76a1cf28-65a0-11e8-9268-292e86bd15a4.png

**Comment by zenikk** [comment]
> https://user-images.githubusercontent.com/27990982/40829233-76a1cf28-65a0-11e8-9268-292e86bd15a4.png

The request goes to facebook.com/v5.6.2 but the latest Graph API is only 3.0 :)

> I have upgraded the version to v5.6.2

Did you modify config/facebook_sdk_version.rb ? You should only change the version to value that is displayed here:

![facebook-app-advanced-settings](https://user-images.githubusercontent.com/37075460/40829812-4c016e9e-658d-11e8-8f7d-5fe53e0a223b.png)

**Comment by sainitawgt** [comment]
@zenikk Thank you so much. After changing the graph API version it worked fine.
