### ISSUE TITLE
SSL issue in login with facebook option

### ISSUE THREAD

**Issue by sainitawgt** [sharetribe/sharetribe#3343]
I am working on a site where login with facebook feature is needed. But I am facing an issue in filling privacy policy url for App review. Its showing the following error 

**"You must submit a valid Privacy Policy URL in order to be compliant with Facebook Platform. Request failed with error: SSL Error: Can't validate SSL Certificate. Either it is self-signed (which will cause browser warnings) or it is invalid."**

The site is already SSL secured. Still I am getting this message. Please let me know how to solve this issue?

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

Can you tell us a bit more? Is your SSL certificate still valid indeed? Did you make sure to add "https" in your Privacy page URL?

Maybe you could share a few details:
- your marketplace address
- a few screenshots of your Facebook setup

Let us know!

**Comment by zenikk** [comment]
Check that your site has correctly installed full certificate chain
https://whatsmychaincert.com

**Comment by sainitawgt** [comment]
Please check the below image regarding basic settings section. My site is fully secured. It has that green lock sign in address bar
https://user-images.githubusercontent.com/27990982/41081942-36a59540-6a4a-11e8-9f7f-07db46129c35.JPG

**Comment by pcm211** [comment]
@sainitawgt this could be a config problem as there are so many users who have already installed it and are using it without an issue. Also do check the well documented article https://help.sharetribe.com/managing-your-marketplace/social-media/how-to-configure-facebook-login
