### ISSUE TITLE
server creating incorrect domain links

### ISSUE THREAD

**Issue by sainineeraj** [sharetribe/sharetribe#3348]
Sharetribe Version:

```
7.3.0
Share the git commit hash of the version of Sharetribe that you are using. You can find it by running git rev-parse HEAD in your Sharetribe directory.
66adb5a

Environment:

Linux ip-172-26-1-66 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
on AWS LIGHTSAIL

node -v
v7.8.0
npm -v
4.2.0
```

I have a strange issue with my setup. I am using sendmail to send out emails using gmail credentials. while emails go out fine but the links in the email( e.g. activation link, password reset etc.) are of incorrect subdomain then my website. I can’t seem to figure out what conf settings will fix it.

e.g.

My website is xxx.example.com
The links in email point to zzz.example.com.

Once I fix the url in the browser the links work fine.
The same issue is with sharing listings in twitter/facebook, they all pick the incorrect domain. 

Anyone has idea how to fix this?

**Comment by sainineeraj** [comment]
Its similar to this issue - https://www.sharetribe.com/community/t/smtp-mailer-without-community-subdomain/219/7

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

Unfortunately I'm not able to reproduce but good that [you asked already in the Community forum](https://www.sharetribe.com/community/t/emails-being-sent-to-wrong-domain/1224) and found some possible things to test already, this is the best way to go!

Hopefully someone with a similar situation will be able to share their setup and details!

**Comment by sainineeraj** [comment]
thanks!  was able to fix t by updating communities table
mysql> UPDATE communities SET domain='yourdomain.com',  use_domain=1;
