### ISSUE TITLE
Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by tomlear** [sharetribe/sharetribe#3372]
Tried a million things from Google but to no avail. 

Whenever I run 'bundle exec rake db:create db:structure:load' the error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' is returned. 

GIT HASH: 958a83718c444055bc24078b6a54abdbcf172c39

MAC OSX

Toms-MBP:sharetribe Tom$ bundle exec rake db:create db:structure:load
#<Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
Couldn't create database for {"adapter"=>"mysql2", "database"=>"sharetribe_development", "encoding"=>"utf8", "username"=>1234, "password"=>1234, "host"=>"localhost"}, {:charset=>"utf8"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'sharetribe_development'
#<Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
Couldn't create database for {"adapter"=>"mysql2", "database"=>"sharetribe_test", "encoding"=>"utf8", "username"=>123, "password"=>123, "host"=>"localhost"}, {:charset=>"utf8"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'sharetribe_test'
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/connection_handling.rb:88:in `connection'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/migration.rb:1038:in `current_version'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/migration.rb:1271:in `last_stored_environment'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:56:in `check_protected_environments!'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/airbrake-6.1.2/lib/airbrake/rake.rb:19:in `execute'
/Users/Tom/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/Tom/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/Tom/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:structure:load => db:check_protected_environments
(See full trace by running task with --trace)

**Comment by navjotdhanawat** [comment]
Same issue
@tomlear any solution for it?

**Comment by LuisReyes98** [comment]
that is most likely a problem of the mysql user and password setup 
I recommend you to check this https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost
this is a similar problem in ubuntu https://stackoverflow.com/questions/41984956/cant-reset-root-password-with-skip-grant-tables-on-ubuntu-16 sorry I don't if something similar would woek on mac
