### ISSUE TITLE
The test run via Zeus fail

### ISSUE THREAD

**Issue by GildedHonour** [sharetribe/sharetribe#3377]
How Zeus should be used? Should it be run in a different tab? Or in background?

When running it, I get this:

![captura de pantalla_2018-07-26_01-31-56](https://user-images.githubusercontent.com/2032888/43220342-0003e0b4-9074-11e8-9dca-0ceb453351d6.png)

What should I do this it? I'm trying to type something, but nothing is getting displayed

It says - "run". Where and how? I tried running "zeus rspec spec" in a different window:

```
$ zeus runner 
/home/alex/.gem/ruby/2.3.4/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- rails/commands/runner (LoadError)

```

This or any other command returns an exception

**Comment by emmanuelapp** [comment]
Open up a new window or tab

**Comment by GildedHonour** [comment]
"I tried running "zeus rspec spec" in a different window:"
