### ISSUE TITLE
Calendar sync

### ISSUE THREAD

**Issue by roni-frantchi** [sharetribe/sharetribe#3391]
##### Description:

We are looking to build a donation based marketplace for short term rentals.

We need the ability to sync the host's calendar between other platforms such as Airbnb to Sharetribe.

This is an essential feature for hosts, as homes are often listed across multiple platforms and so the home must be made available only for dates available across all platforms. 

Airbnb and others often use iCal for two-way sync between calendars - one iCal address to publish events to other platforms, and another to consume. [Here's](https://www.airbnb.com/help/article/99/how-do-i-sync-my-airbnb-calendar-with-another-calendar) AirBnB's user documentation on the matter.

We opened this issue to try and see if such feature is already listed on your roadmap, as well as see if there's any traction for others who'd like to see this feature.

**Comment by thomasmalbaux** [comment]
Hi there,

and thanks for the idea!

Indeed right now there isn't such feature. This is a great suggestion though, and we'll keep it in mind for future improvements!
We are not working on this right now so I don't have any timeline to share though.

Maybe you could discuss in [Sharetribe's Community forum](https://www.sharetribe.com/community/) to learn if others have already built this feature, and would agree to share it with you or sell it to your team for your project?

Hopefully this helps.

**Comment by roni-frantchi** [comment]
Thanks @thomasmalbaux .
Sorry I didn't realise you don't use GitHub issues to request or show intention to develop a new feature. We'll have a look at the forum instead.
