### ISSUE TITLE
Uncaught Error: ReactOnRails encountered an error while rendering component: TopbarApp.

### ISSUE THREAD

**Issue by aboutkrin** [sharetribe/sharetribe#3392]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:

`958a83718c444055bc24078b6a54abdbcf172c39`

##### Environment:

Digital Ocean 
2 GB Memory / 50 GB Disk / SGP1 - Ubuntu 16.04.4 x64
Node version: v7.8.0
Npm version: 4.2.0

##### Server mode:

Production mode

##### Description:

I cannot set the menu limit on my Sharetribe admin dashboard so I inspect with Google Chrome developer tools and found:

![alt text](http://i63.tinypic.com/66es5h.png)

**Comment by pilgrim2go** [comment]
@aboutkrin : i have the same issue - can you share how to fix it?
