### ISSUE TITLE
customize Sharetribe search by pasing radius to search

### ISSUE THREAD

**Issue by ali-ssi** [sharetribe/sharetribe#3397]
I am using the latest version of sharetribe and I want nearby places listings I went through search code and passed location_longitude and location_latitude to search with radius by seems like radius isn't working perfectly can anyone tell me how to pass radius correctly?

I am passing like -

    search = {
        author_id: @person.id,
        include_closed: include_closed,
        page: 1,
        # address: @listing.origin,
        location_latitude: @listing.origin_loc.try(:latitude),
        location_longitude: @listing.origin_loc.try(:longitude),
        radius: 80,
        per_page: @per_page
    }

Am I passing correctly?
Do I am eligible to pass sorting to this search? I mean the result should be like the closest record would come first.

Please address. if there is any other way also suggest me that too.

**Comment by ali-ssi** [comment]
@rap1ds @thomasmalbaux Can you guys please address this query.

**Comment by ali-ssi** [comment]
@Luis-RG

**Comment by thomasmalbaux** [comment]
Hi there!

Thanks for sharing such details about your customization idea.

Unfortunately I'm not sure what to recommend here, but maybe you could discuss this with other open-source users in [Sharetribe's Community Forum](https://www.sharetribe.com/community/). 

Hopefully someone else might have insights to share if they've tried to build a similar customization!
