### ISSUE TITLE
Cucumber doesn't detect PhantomJS env variable

### ISSUE THREAD

**Issue by levioza** [sharetribe/sharetribe#3420]
The acceptance tests are failing. The error message suggests to install firefox. However, I believe that the acceptance should work with PhantomJS by setting PHANTOMJS env variable to true.

##### Sharetribe Version:

Tree-ish: 2c99c910ecd6f0200b0803139e95d9325b99af7d

##### Environment:

Environment: Mac OS X.
Node: v10.5.0
NPM: 6.4.0

##### Description:

The acceptance tests are failing. The error message:

```
Could not find Firefox binary (os=macosx). Make sure Firefox is installed or set the path manually with Selenium::WebDriver::Firefox::Binary.path= (Selenium::WebDriver::Error::WebDriverError)
```

I get the same error after setting the PhantomJS env variable.

##### Steps To Reproduce:

Follow the steps of the README file.

Expected result: All the tests to pass.

**Comment by thomasmalbaux** [comment]
Unfortunately no update. Keep us posted if you still experience such error with the latest versions and master branch.
