### ISSUE TITLE
Sphinx error after adding a new category and rename the default category

### ISSUE THREAD

**Issue by williamn** [sharetribe/sharetribe#3431]
##### Sharetribe Version:

958a83718c444055bc24078b6a54abdbcf172c39

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_ 

Mac OS X

_What's your node version? Run the following commands and copy the result here:_

node v7.8.0
npm 4.2.0

##### Server mode:

_Are you running in development or production mode?_

##### Description:

When I visit URL http://gimme.lvh.me:5000/?category=baby-equipment

I saw an error like this

```
ThinkingSphinx::SphinxError at /

Unknown MySQL error - SELECT * FROM `listing_core`, `listing_delta` WHERE `community_id` = 1 AND `category_id` IN (1) AND `sphinx_deleted` = 0 ORDER BY `sort_date` DESC LIMIT 0, 24 OPTION field_weights=(title=10, category=8, description=3), max_query_time=1000; SHOW META
```

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

1. Add a new category e.g. Hobby
1. Rename the default category to something else. In my case: Baby Equipment

Expected result: _What was the expected result after running the steps above?_

I should be able to view the listing by category

Actual result: _What was the actual result after running the steps above?_

I saw Sphinx error

##### Additional information

Request parameters

```{"category"=>"baby-equipment", "controller"=>"homepage", "action"=>"index"}```

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

Did you rename the default category through the admin panel? Was Sphinx running properly to index new things?

Unfortunately I'm not able to reproduce such behavior so don't hesitate to share your specific setup with others at https://www.sharetribe.com/community/. Hopefully someone with a similar experience will share their insights!

**Comment by mezbahalam** [comment]
@williamn are you able encounter this bug ?
