### ISSUE TITLE
Wrong argument name

### ISSUE THREAD

**Issue by frontandstart** [sharetribe/sharetribe#3485]
wrong argument name here https://github.com/sharetribe/sharetribe/blob/d236f631393f2e2d6143f549aa8b37fae3ee1c9c/app/services/stripe_service/api/payments.rb#L140
```ruby
  currency: total.currency.iso_code,
```
should be: 
```ruby
  amount_currency: total.currency.iso_code,
```
![screen shot 2018-11-01 at 4 06 54 pm](https://user-images.githubusercontent.com/8098344/47853578-36700280-ddf0-11e8-8493-3f181aaec0e9.png)

**Comment by thomasmalbaux** [comment]
Thanks a lot for the report!

This has been fixed in https://github.com/sharetribe/sharetribe/pull/3551
