### ISSUE TITLE
Translate with wrong language

### ISSUE THREAD

**Issue by khoatranthanh** [sharetribe/sharetribe#3488]
My site: `https://www.freelensia.com/`
Hello team!
I have a problem when trying to switch from `en` to `th-TH`. 
Everything is ok, only `Order Type` translate has some problem (maybe with another language also).
Some `Listing` can change, but some are not.
Can I have any suggestion to resolve this problem?
Thank!

**Comment by thomasmalbaux** [comment]
Unfortunately I'm not able to reproduce such behavior but you could share that question at https://www.sharetribe.com/community/ to learn if someone else has somehow experienced the same challenges!
