### ISSUE TITLE
Important notice from Amplitude: please update to v4.1.1 or newer

### ISSUE THREAD

**Issue by ryanashcraft** [sharetribe/sharetribe#3492]
Amplitude is encouraging all of our customers using our JavaScript SDK < v4.1.1 to update immediately in order to avoid possible data contamination. We plan to stop collecting data from older versions of the SDK in early 2019. For more context, please see this [article](https://amplitude.zendesk.com/hc/en-us/articles/360019036051-11-1-2018-Pre-v-4-1-1-JS-SDK-Deprecation).

This project seems to be currently using v3.x. Please update to the latest SDK version v4.5.0.

**Comment by thomasmalbaux** [comment]
Thanks for the information, we'll definitely consider it!
