### ISSUE TITLE
Creating duplicate transactions with same date/time range, duplication payments(stripe)

### ISSUE THREAD

**Issue by frontandstart** [sharetribe/sharetribe#3498]
##### Environment:
OSX, (Digitalocean)
node 7.8.0
##### Server mode:
development, production, staging
##### Description:
I solve tasks for my client and one of them was saving card(card token) for ability payments. This part work fine.  
Problem in two methods of [PreauthorizeTransactionsController](https://github.com/sharetribe/sharetribe/blob/e527e9bcc464fcebb815427f348338e074a9a73e/app/controllers/preauthorize_transactions_controller.rb#L2) class.  

```ruby
  def initiate
```
and
```ruby
  def initiated
```
Initiate need for validates ability of booking data and render page where users can pay. 
When user pay (input card data and get successful token from stripe for example) share tribe make XHR POST request to /listing/:id/initiated route and we again validate our data to confirm payment/bookings using `def initiated` at this time.

The problem is when we pay (successfully) and got redirected to transaction show page (:username/transaction/:id) - user can click back button in browser. But in this case browser not send HTTP GET request to initiate page (where we make validation of booking). Browser just render page from cache - so all forms will be same(and input data inside) so if we/user will do that(by mistake for example) he will see page with booking data and 'confirm payment' button - 50/50 % that he click on this button again (in my case more I have saved card button that retrieve card token from stripe API). And If he did it - XHR POST request repeated to /listing/:id/initiated and it should redirect us to listing page and flash error that booking unavailable - but its no happens because there(in `def initiated`) different validation than `initiate`
Both of them call TransactionService::Validation::Validator [inside initiate](https://github.com/sharetribe/sharetribe/blob/e527e9bcc464fcebb815427f348338e074a9a73e/app/controllers/preauthorize_transactions_controller.rb#L22) and [inside initiated](https://github.com/sharetribe/sharetribe/blob/e527e9bcc464fcebb815427f348338e074a9a73e/app/controllers/preauthorize_transactions_controller.rb#L49)
but difference that to TransactionService::Validation::Validator.validate_initiated_param inside **initiate** we pass `availability_enabled: listing.availability.to_sym == :booking,` and inside **initiated** we don't and in initiated we have booking_validation that check bookings only for hourly contracts.
##### Steps To Reproduce:
1. sign in as one user
1. open and order listing
1. pay (I use stripe in test mode)
2. click back in browser 
4. click 'confirm payment' again
Expected result:
Should deny creating another Transactions with same params and flash error or redirect (using location key from XHR response)
Actual result:
Create second/third and a lot of transactions with same params and make payment again 
##### Additional information
3 Transaction related to same item & dates
![screen shot 2018-11-10 at 4 15 27 am](https://user-images.githubusercontent.com/8098344/48296314-4a79cb00-e4a6-11e8-8dbf-48d6fd118244.png)

**Comment by thomasmalbaux** [comment]
Thanks again for your contribution! This has been fixed in https://github.com/sharetribe/sharetribe/pull/3550
