### ISSUE TITLE
IBAN Verification (France)

### ISSUE THREAD

**Issue by sr7439** [sharetribe/sharetribe#3517]
Hi,
IBAN check presents an issue for french IBAN
I am entering an IBAN whose structure respect the regexp rule FR[0-9]{2}[0-9]{10}[A-Z0-9]{11}[0-9]{2}

but I get the error message telling that the IBAN structure is not correct.

By the way, in the error message, the IBAN structure is not correct since its structure is FR[0-9]{2}[0-9]{10}[A-Z0-9]{8}

##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

c6cb4747bf299bd9a569cb016c83d241160ae789

##### Environment:

MacOS 10.14.1

_What's your node version? Run the following commands and copy the result here:_

```
> node -v v7.8.0

> npm -v 4.2.0

```

##### Server mode:

_Are you running in development or production mode?_ Development

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

Sign in
Go to user parameters
Payment preference
input first name, last name, birth date, country, IBAN
when mouse out of the IBAN field, I get the message telling the IBAN structure is not correct.

Expected: the IBAN should be accepted

Actual result: Error message about the IBAN structure.

##### Additional information

![capture d ecran 2018-11-30 a 11 36 21](https://user-images.githubusercontent.com/45485046/49284237-4254f000-f494-11e8-98b0-8ec79eb0083d.png)

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

If you are using Stripe in Development (with Stripe test API keys), you should enter a test IBAN: https://stripe.com/docs/connect/testing#account-numbers

Give it a try and keep us posted!

**Comment by sr7439** [comment]
Hi Thanks for your answer.
I works with test IBAN.
The API Keys I use for Stripe connection are test keys.
Sharetribe doesn't accept live API Keys from Stripe.

**Comment by thomasmalbaux** [comment]
Thanks for the details.

I you rely on test keys, then you should use test bank numbers as listed at 
For a FR account, you should use the test IBAN `FR89370400440532013000`.

In your own installation, you can definitely run Sharetribe Go with live Stripe keys, but it's indeed a good idea to test things with test keys while you develop and customize things.
