### ISSUE TITLE
Don't know how to build task 'sharetribe:landing_page:install_static'

### ISSUE THREAD

**Issue by kernel-debugger** [sharetribe/sharetribe#3540]
I tried to install the sample landing page using the command  
`bundle exec rake sharetribe:landing_page:install_static`
and bumped into  Don't know how to build task 'sharetribe:landing_page:install_static'

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

Unfortunately I'm not able to reproduce but don't hesitate to discuss this with other open-source users at https://www.sharetribe.com/community/

Maybe someone has experienced the same issue and will be able to share their experience!

**Comment by kernel-debugger** [comment]
I'm using the latest version, after some debugging I found in latest version `sharetribe:landing_page:install_static` is changed to `sharetribe:landing_pages:install_static`
there's an s at the end of landing_page, this resolved my issue.
