### ISSUE TITLE
Customize Sharetribe to support selling digital content

### ISSUE THREAD

**Issue by phuc-it** [sharetribe/sharetribe#3588]
##### Description:
I'm going to customize Sharetribe to support selling digital content. The feature is ability to upload a file (digital conetent) and secure the download link. Please let me know if it's possible with the opensource version of Sharetribe and any directions. Thanks.

**Comment by thomasmalbaux** [comment]
Good to hear about your plans!

That requires some thinking, but would definitely be doable with your own customizations and team with the open-source version.

Don't hesitate to discuss this with other open-source users at https://www.sharetribe.com/community/, maybe someone has already built support for digital content and would be OK to share their code with you?

Hopefully this helps.
