### ISSUE TITLE
Instance works on port 5000 and not 3000

### ISSUE THREAD

**Issue by fazilazri** [sharetribe/sharetribe#3593]
Hello Team. After following the documentation mentioned here, the new instance was up on port 5000 and not on 3000. Please update the document so that it saves time of debugging the issue.

https://github.com/sharetribe/sharetribe

##### Sharetribe Version:

2e630252c413b53866ce2fcd1d0fa8cde4c95814

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_ 
Ubuntu 16.04

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
> npm -v
```
$ node -v
v7.8.0
$ npm -v
4.2.0

##### Server mode:

_Are you running in development or production mode?_

Development

##### Description:

The instance is running on port 5000 and not 3000 port. Is it correct and was 3000 port wrongly mentioned in the documentation?

**Comment by thomasmalbaux** [comment]
Thanks for the suggestion. I'm not sure what defines exactly that port, and for most people (myself included) it still works on 3000 by default, but this has been reported a few times so I've now updated the readme file to mention both possibilities.

Thanks for your help
