### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema

### ISSUE THREAD

**Issue by Chetan07j** [sharetribe/sharetribe#3603]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:
7.5.0

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._
32c51a2cb05f8954039513f3ea959323eed7bf94

##### Environment:
Production

_What's your environment? Mac OS X, Heroku, or something else?_
Linux

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
7.8.0
> npm -v
4.2.0
```

##### Server mode:

_Are you running in development or production mode?_
Production

##### Description:

`RAILS_ENV=production NODE_ENV=production bundle exec rake assets:precompile`
This command gives below error:
```shell
cd client && npm run build:client

> @ build:client /root/sharetribe/client
> npm run ensure-node-version && webpack --config webpack.client.config.js


> @ ensure-node-version /root/sharetribe/client
> check-node-version --package

Webpack production build for Rails
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           postcss: ...
         }
       })
     ]
 - configuration.output.path: The provided value "../app/assets/webpack" is not an absolute path!
   -> The output directory as **absolute path** (required).
 - configuration.resolve.extensions[0] should not be empty.
   -> A non-empty string

npm ERR! Linux 4.4.0-1072-aws
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:client: `npm run ensure-node-version && webpack --config webpack.client.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:client script 'npm run ensure-node-version && webpack --config webpack.client.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ensure-node-version && webpack --config webpack.client.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2019-02-06T04_22_49_038Z-debug.log
rake aborted!
Command failed with status (1): [cd client && npm run build:client...]
/root/sharetribe/lib/tasks/assets.rake:21:in `block (2 levels) in <top (required)>'
/usr/share/rvm/gems/ruby-2.3.4/gems/airbrake-6.1.2/lib/airbrake/rake.rb:19:in `execute'
/usr/share/rvm/gems/ruby-2.3.4/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/usr/share/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile => assets:compile_environment => assets:webpack
(See full trace by running task with --trace)
```

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _clone this repo_
2. _and perform steps defined in doc and production setup steps_

Expected result: _What was the expected result after running the steps above?_ 
DON'T KNOW

Actual result: _What was the actual result after running the steps above?_
Error as mentioned above.

**Comment by thomasmalbaux** [comment]
Thanks for reporting. It seems that there is something wrong with your install of Node.js and/or n or npm.

Unfortunately I'm not able to reproduce but maybe you could review your npm/n and node setup?
A few open-source users also reported similar situations and have shared their insights at https://www.sharetribe.com/community/. Have a look and don't hesitate to post your details there if needed!

**Comment by firefiks** [comment]
`Webpack production build for Rails
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[2] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[1].loader should be a non-empty string.
      -> A loader request.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build:client: `npm run ensure-node-version && webpack --mode=production --config webpack.client.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-24T13_43_32_884Z-debug.log
rake aborted!
`
any idea?

**Comment by firefiks** [comment]
I was able to solve the problem with a downgrade to webpack@4.44.1
