### ISSUE TITLE
Sharetribe Installation Error bundle exec rake db:create db:structure:load

### ISSUE THREAD

**Issue by mrkhanakia** [sharetribe/sharetribe#3618]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version: Latest 7.5.0 (32c51a2cb05f8954039513f3ea959323eed7bf94)

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_
MAC Mojave
_What's your node version? Run the following commands and copy the result here:_
v10.11.0
6.4.1
```
> node -v
> npm -v
```

##### Server mode:

_Are you running in development or production mode?_
No
##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._
Installation error while using command **bundle exec rake db:create db:structure:load**
##### Steps To Reproduce:

_List the actions that will reproduce the issue._

`khanakias-MacBook-Pro:sharetribe khanakia$ bundle exec rake db:create db:structure:load
rake aborted!
NoMethodError: undefined method `yaml_as' for ActiveRecord::Base:Class
Did you mean?  yaml_tag
/usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.1.6.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/usr/local/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:4:in `<class:Base>'
/usr/local/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:3:in `<module:ActiveRecord>'
/usr/local/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
/usr/local/lib/ruby/gems/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/lib/ruby/gems/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/lib/ruby/gems/2.6.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
/usr/local/lib/ruby/gems/2.6.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:66:in `backend='
/usr/local/lib/ruby/gems/2.6.0/gems/delayed_job_active_record-4.1.2/lib/delayed_job_active_record.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
/Volumes/D/www/php/sharetribe/config/application.rb:22:in `<top (required)>'
/Volumes/D/www/php/sharetribe/Rakefile:4:in `require'
/Volumes/D/www/php/sharetribe/Rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/usr/local/opt/ruby/bin/bundle:23:in `load'
/usr/local/opt/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)`

<img width="981" alt="screenshot 2019-02-16 at 1 49 24 pm" src="https://user-images.githubusercontent.com/2174170/52896738-b2505800-31f1-11e9-8528-485f661a846a.png">

Expected result: _What was the expected result after running the steps above?_
Installation should be fine

Actual result: _What was the actual result after running the steps above?_
Error
##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by Sultan91** [comment]
Same problem on Linux 18.10

sula@sula-pc:~/.rvm/gems/ruby-2.6.2/gems$ bundle env
## Environment

```
Bundler             2.0.2
  Platforms         ruby, x86_64-linux
Ruby                2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
  Full Path         /home/sula/.rvm/rubies/ruby-2.6.2/bin/ruby
  Config Dir        /home/sula/.rvm/rubies/ruby-2.6.2/etc
RubyGems            3.0.4
  Gem Home          /home/sula/.rvm/gems/ruby-2.6.2
  Gem Path          /home/sula/.rvm/gems/ruby-2.6.2:/home/sula/.rvm/gems/ruby-2.6.2@global
  User Path         /home/sula/.gem/ruby/2.6.0
  Bin Dir           /home/sula/.rvm/gems/ruby-2.6.2/bin
Tools               
  Git               2.19.1
  RVM               1.29.8-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2019-06-13
Git SHA           496bca538
Released Version  true

**Comment by Sultan91** [comment]
Cured by `bundle update delayed_job`
