### ISSUE TITLE
Ruby and Node version upgrade

### ISSUE THREAD

**Issue by mysticaltech** [sharetribe/sharetribe#3650]
Hey guys, newbie question. The Ruby and Node version are both pretty old, why aren't you upgrading them to the latest versions? Isn't it better for speed and security? For instance, "Ruby 2.3.x" has almost reached EOL. Or am I missing something?

**Comment by thomasmalbaux** [comment]
Hey there!

I noticed you've also posted the question in the Community forum and [answered there](https://www.sharetribe.com/community/t/sharetribe-version-7-5-0-is-now-available/1766/26?u=thomasmalbaux).
