### ISSUE TITLE
Rendering error when new top bar enabled

### ISSUE THREAD

**Issue by georgejeffery** [sharetribe/sharetribe#3658]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:

4a13c489256c597ed402383187bdd03a51426fad

##### Environment:

Mac OS X

_What's your node version? Run the following commands and copy the result here:_

```
> node -v v7.8.0
> npm -v 4.2.0
```

##### Server mode:

Development

##### Description:

Turned on the new nav bar in Admin settings. Getting "ERROR in SERVER PRERENDERING
when prerendering TopbarApp" with "Cannot read property 'inbox' of undefined" seeming to be the cause. 

I don't necessarily want to have the new top bar, but I can't work out how to disable the setting in config/the database.

Have restarted the server multiple times to make sure it's not just needing to re-render. 

##### Steps To Reproduce:

See above

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by shoesack** [comment]
Hey @georgejeffery 

what was your fix back then? I'm getting the same behaviour now after updating to the newest version. 

Node and NPM meet the requirements (via NVM on MAC M1).
