### ISSUE TITLE
Ruby 2.3 has just ended

### ISSUE THREAD

**Issue by mysticaltech** [sharetribe/sharetribe#3697]
Guys, thank you for your great work! Just wanted to let you know that ruby 2.3 has ended. Please try to update soon, otherwise, it may cause a huge security risk to everyone using the platform.

https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

**Comment by thomasmalbaux** [comment]
Thanks for sharing your concern!

You're right, this is now important. We are actually working on this and you can expect quite a few updates of the technology stack in the coming days/weeks.

Upgrading version of any tool we use is always quite challenging, as it often generates lots of surprises and requires tons of testings to make sure that nothing will be among the dozens of thousands of marketplaces we host.

But again we're now working on this: I'll keep that issue open and it will be closed after the Ruby update.

**Comment by mysticaltech** [comment]
Thanks, Thomas! I'm also really looking forward to the elasticsearch integration... Keep up the good work.

**Comment by thomasmalbaux** [comment]
Quick update: Ruby has been updated few days ago, see https://github.com/sharetribe/sharetribe/pull/3701

FYI Rails upgrade is a work in progress, and Node is coming soon.

**Comment by mysticaltech** [comment]
Great to hear this Thomas!
