### ISSUE TITLE
Sitemap not available in sharetribe

### ISSUE THREAD

**Issue by olubiyi80** [sharetribe/sharetribe#3711]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version: 7.5

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._ 9f3c573aa7461ef0beae291b8a945595479d4a20

##### Environment: ruby 2.3.8

_What's your environment? Mac OS X, Heroku, or something else?_ Ubuntu

_What's your node version? Run the following commands and copy the result here:_7.8

```
> node -v
> npm -v
```

##### Server mode:

_Are you running in development or production mode?_ production

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

Sharetribe sitemap not available, 

Cannot find sitemap.xml.gz in sharetribe.

Please how can I create it?

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_

Actual result: _What was the actual result after running the steps above?_

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment]
Unfortunately I'm not able to reproduce, and everything looks great by default.

Would you share the URL to your marketplace? Or is it on a local machine only.
Do you have it enabled (true) at https://github.com/sharetribe/sharetribe/blob/master/config/config.defaults.yml#L445?

**Comment by olubiyi80** [comment]
Yes it's enabled in the config.default.yml file. 
https://www.renvery.com

**Comment by olubiyi80** [comment]
It's uses S3, it's not there also. And it's not in the server.

The link redirects somewhere else when I try to open it, what could be wrong?

**Comment by thomasmalbaux** [comment]
Hmm given the error displayed at https://www.renvery.com/sitemap.xml.gz, it seems that this is related to your storage, where static assets are stored.

Hopefully this will help to figure it out. If this is your post at https://www.sharetribe.com/community/t/sitemap-not-available-in-sharetribe/1956/1, hopefully someone will be able to share their experience and if this isn't your post, maybe you could followup there?

Unfortunately we won't be able to help so continuing the discussion in Community is a good way to move forward.

**Comment by olubiyi80** [comment]
@mooreds Please how do i create sitemap on sharetribe? Thanks.
