### ISSUE TITLE
Update documentation regarding harmony

### ISSUE THREAD

**Issue by levioza** [sharetribe/sharetribe#3739]
It seems that harmony works with stripe according to "https://www.sharetribe.com/community/t/stripe-payments-and-harmony-bookings-for-rental-marketplaces/937/4". However, it's written that it works with PayPal only here "https://github.com/sharetribe/sharetribe/blob/master/docs/configure_harmony.md". So, I wonder if the documentation is accurate.

**Comment by thomasmalbaux** [comment]
Good catch, thanks for reporting!

Docs have been updated at https://github.com/sharetribe/sharetribe/commit/27a7e3cac9354683885251bf2be99b86e8d931b5

Thanks again.
