### ISSUE TITLE
How to install Sharetribe for Windows 10

### ISSUE THREAD

**Issue by Siva1797** [sharetribe/sharetribe#3783]
i found the lot Share tribe installation for MAC os and Ubntu but not for Windows.

please help me and assist the sharetribe installation on Windows.

**Comment by thomasmalbaux** [comment]
Hi there!

Unfortunately we don't have instructions ready for an installation with Windows 10.
A tip: you should consider enabling the Windows Subsystem for Linux (WSL) on your machine and continue from there with the regular Linus installation.

You can also discuss this with other open-source users at https://www.sharetribe.com/community/, most likely some of them have installed it on Windows and will hopefully share their experience.
