### ISSUE TITLE
rake aborted! 11:33:24 rails-server-assets.1 | LoadError: Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.

### ISSUE THREAD

**Issue by Sultan91** [sharetribe/sharetribe#3788]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues. Fails at :
`foreman start -f Procfile.static`

##### Sharetribe Version:
latest

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._
8948491e096f7918c89c8f2066c9e1d467b5d472
##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_
Local machine Ubuntu
_What's your node version? Run the following commands and copy the result here:_

```
> node -v
7.8.0
> npm -v
4.2.0
```

##### Server mode:

_Are you running in development or production mode?_
Development
##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._
`foreman start -f Procfile.static` command fails with an error

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

Proceed with installation steps until step 10.
Previously i had an issue with rake giving similar 'LoadError: Could not load 'active_record/connection_adapters/mysql2_adapter'' error so used `rake -T` flag to handle it. 
Expected result:  running server

Actual result: Error
`
/my_work/storage marketplace/sharetribe$ foreman start -f Procfile.static
Ignoring bcrypt-3.1.13 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.13
Ignoring bcrypt-3.1.12 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.12
Ignoring bigdecimal-1.4.4 because its extensions are not built. Try: gem pristine bigdecimal --version 1.4.4
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
Ignoring binding_of_caller-0.8.0 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.8.0
Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-11.0.1 because its extensions are not built. Try: gem pristine byebug --version 11.0.1
Ignoring byebug-9.0.6 because its extensions are not built. Try: gem pristine byebug --version 9.0.6
Ignoring childprocess-2.0.0 because its extensions are not built. Try: gem pristine childprocess --version 2.0.0
Ignoring debug_inspector-0.0.3 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.3
Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Ignoring ffi-1.11.1 because its extensions are not built. Try: gem pristine ffi --version 1.11.1
Ignoring ffi-1.10.0 because its extensions are not built. Try: gem pristine ffi --version 1.10.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring hiredis-0.6.3 because its extensions are not built. Try: gem pristine hiredis --version 0.6.3
Ignoring hiredis-0.6.1 because its extensions are not built. Try: gem pristine hiredis --version 0.6.1
Ignoring io-console-0.4.8 because its extensions are not built. Try: gem pristine io-console --version 0.4.8
Ignoring jaro_winkler-1.5.3 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.3
Ignoring json-2.2.0 because its extensions are not built. Try: gem pristine json --version 2.2.0
Ignoring msgpack-1.3.0 because its extensions are not built. Try: gem pristine msgpack --version 1.3.0
Ignoring msgpack-1.1.0 because its extensions are not built. Try: gem pristine msgpack --version 1.1.0
Ignoring mysql2-0.5.2 because its extensions are not built. Try: gem pristine mysql2 --version 0.5.2
Ignoring mysql2-0.4.10 because its extensions are not built. Try: gem pristine mysql2 --version 0.4.10
Ignoring nio4r-2.4.0 because its extensions are not built. Try: gem pristine nio4r --version 2.4.0
Ignoring nio4r-2.3.1 because its extensions are not built. Try: gem pristine nio4r --version 2.3.1
Ignoring nokogiri-1.10.3 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.3
Ignoring nokogiri-1.10.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.1
Ignoring oj-3.7.12 because its extensions are not built. Try: gem pristine oj --version 3.7.12
Ignoring oj-2.18.5 because its extensions are not built. Try: gem pristine oj --version 2.18.5
Ignoring passenger-6.0.2 because its extensions are not built. Try: gem pristine passenger --version 6.0.2
Ignoring passenger-6.0.1 because its extensions are not built. Try: gem pristine passenger --version 6.0.1
Ignoring rainbow-2.2.2 because its extensions are not built. Try: gem pristine rainbow --version 2.2.2
Ignoring rbtree3-0.5.0 because its extensions are not built. Try: gem pristine rbtree3 --version 0.5.0
Ignoring redcarpet-3.4.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.4.0
Ignoring therubyracer-0.12.3 because its extensions are not built. Try: gem pristine therubyracer --version 0.12.3
Ignoring unf_ext-0.0.7.6 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.6
Ignoring unf_ext-0.0.7.4 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.4
Ignoring websocket-driver-0.7.1 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.1
Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5
11:33:20 rails.1               | started with pid 10134
11:33:20 rails-client-assets.1 | started with pid 10135
11:33:20 rails-server-assets.1 | started with pid 10138
11:33:20 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
11:33:20 rails-client-assets.1 | Exporting routes...
11:33:20 rails-server-assets.1 | Exporting translations...
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils/version.rb:4: warning: already initialized constant FileUtils::VERSION
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils/version.rb:4: warning: previous definition of VERSION was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils/version.rb:4: warning: already initialized constant FileUtils::VERSION
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils/version.rb:4: warning: previous definition of VERSION was here
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1267: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1540: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1547: warning: previous definition of DIRECTORY_TERM was here
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1542: warning: already initialized constant FileUtils::Entry_::SYSCASE
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1549: warning: previous definition of SYSCASE was here
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1595: warning: already initialized constant FileUtils::OPT_TABLE
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1602: warning: previous definition of OPT_TABLE was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1267: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1649: warning: already initialized constant FileUtils::LOW_METHODS
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1656: warning: previous definition of LOW_METHODS was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1540: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
11:33:21 rails-server-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1656: warning: already initialized constant FileUtils::METHODS
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1547: warning: previous definition of DIRECTORY_TERM was here
11:33:21 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1663: warning: previous definition of METHODS was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1542: warning: already initialized constant FileUtils::Entry_::SYSCASE
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1549: warning: previous definition of SYSCASE was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1595: warning: already initialized constant FileUtils::OPT_TABLE
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1602: warning: previous definition of OPT_TABLE was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1649: warning: already initialized constant FileUtils::LOW_METHODS
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1656: warning: previous definition of LOW_METHODS was here
11:33:21 rails-client-assets.1 | /home/sula/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/fileutils.rb:1656: warning: already initialized constant FileUtils::METHODS
11:33:21 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/fileutils-1.2.0/lib/fileutils.rb:1663: warning: previous definition of METHODS was here
11:33:24 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/transit-ruby-0.8.599/lib/transit/write_handlers.rb:418: warning: constant ::Fixnum is deprecated
11:33:24 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/transit-ruby-0.8.599/lib/transit/write_handlers.rb:419: warning: constant ::Bignum is deprecated
11:33:24 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/transit-ruby-0.8.599/lib/transit/write_handlers.rb:418: warning: constant ::Fixnum is deprecated
11:33:24 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/gems/transit-ruby-0.8.599/lib/transit/write_handlers.rb:419: warning: constant ::Bignum is deprecated
11:33:24 rails-server-assets.1 | rake aborted!
11:33:24 rails-server-assets.1 | LoadError: Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.
11:33:24 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks: undefined method `reject' for nil:NilClass (NoMethodError)
11:33:24 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks: Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
11:33:24 rails-server-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks: cannot load such file -- active_record/connection_adapters/mysql2_adapter (LoadError)
11:33:24 rails-client-assets.1 | rake aborted!
11:33:24 rails-client-assets.1 | LoadError: Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.
11:33:24 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks: undefined method `reject' for nil:NilClass (NoMethodError)
11:33:24 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks: Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
11:33:24 rails-client-assets.1 | /home/sula/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks: cannot load such file -- active_record/connection_adapters/mysql2_adapter (LoadError)
11:33:24 rails-client-assets.1 | exited with code 1
11:33:24 system                | sending SIGTERM to all processes
11:33:24 rails-server-assets.1 | exited with code 1
11:33:24 rails.1               | terminated by SIGTERM

`
My Database.yml file:
`
development:
    adapter: mysql2
    database: sharetribe_development
    encoding: utf8
    username: admin# ADD DATABASE USERNAME
    password: admin# ADD DATABASE PASSWORD
    host: localhost
GEMFILE: [https://pastebin.com/LXiwrria](url)

**Comment by nghiapdx** [comment]
@Sultan91 please checkout https://www.sharetribe.com/community/  
Seems like you don't have mysql installed on your computer.

**Comment by Sultan91** [comment]
Thanks for response, but mysql2 and mysql2 gem are installed

**Comment by thomasmalbaux** [comment]
Unfortunately not able to reproduce that situation but indeed, asking other open-source users if someone has faced a similar issue, at https://www.sharetribe.com/community/, is a good way to move forward!
