### ISSUE TITLE
Sprockets::Rails::Helper::AssetNotFound - The asset "server-bundle.js" is not present in the asset pipeline.:

### ISSUE THREAD

**Issue by Siva1797** [sharetribe/sharetribe#3792]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

DEBUG   ↳ app/models/community.rb:369
DEBUG   MarketplaceSetupSteps Load (2.2ms)  SELECT  `marketplace_setup_steps`.* FROM `marketplace_setup_steps` WHERE `marketplace_setup_steps`.`community_id` = 1 LIMIT 1
DEBUG   ↳ app/services/admin/onboarding_wizard.rb:128
INFO {"method":"GET","path":"/","format":"html","controller":"HomepageController","action":"index","status":500,"duration":533.9,"view":0.0,"db":27.44,"params":{},"host":"localhost","community_id":1,"current_user_id":"ZW4umaGP5JbShIEs3RIyGg","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0","referer":"","forwarded_for":"","request_uuid":"01cb846d-67ab-4c37-a6fe-3e2eaf6436ae"}
FATAL 
Sprockets::Rails::Helper::AssetNotFound - The asset "server-bundle.js" is not present in the asset pipeline.:

i am getting the above error. please help me on above.

**Comment by thomasmalbaux** [comment]
Hi there!

Hmm unfortunately I'm not able to reproduce the issue, but it sounds like you should try and run `bundle install` again.

Don't hesitate to ask other open-source users if someone has been facing a similar situation, at https://www.sharetribe.com/community/. Hopefully someone will share their experience if they had the same error!
