### ISSUE TITLE
Unsupported languages

### ISSUE THREAD

**Issue by geopast** [sharetribe/sharetribe#3809]
Hi @thomasmalbaux,
I just wanted to ask what the reason is behind explicitly unsupporting a language like the recent 8.0.0 mentioning Albanian and Macedonian? Personally i'd love to see all languages being eventually supported.
Many thanks,
Neil

**Comment by thomasmalbaux** [comment]
Hey Neil,

good question!

We rely on open-source contributors for most languages and when a language is "officially supported", that means it will be visible in the admin panel selection.

However, not all languages are ready, reviewed and translated enough. Sometimes, a few people will start translating it but stop at 10%. It wouldn't make sense to promote and offer that language via the admin panel, as it would be quite disappointing.

Instead, we regularly review the status of translations and, when they are good enough, we promote them to "officially supported".

But of course, you can still use a language that we haven't classified as "supported"! It's there, it works and you can enable it manually via your Rails Console or edit your setting files to move it to the supported languages, for your own installation. Just don't expect something fully reviewed yet ;-)

Does it answer your question?
Let us know and keep up the good work!

**Comment by geopast** [comment]
Perfect! Thanks for taking the time to explain @thomasmalbaux! I noticed in my self hosted 7.6.0 I have the following message and no apparent way to deselect that language:

Language selection is disabled for your marketplace because you are using following unofficial languages: Ελληνικά. Please contact Sharetribe support if you want to modify your language settings.

How would i re-enable language selection from self hosted?

**Comment by thomasmalbaux** [comment]
Hey there!

If you use at least one unsupported language, you then have to edit the language list (and order) via your Rails console.

You can use:
1. `com = Community.find(YOUR_COMMUNITY_ID)`
2. `com.settings["locales"]`
3. `com.settings["locales"] = ["en", "fr", "de"]` (for example, replace with whatever you would like to have and in what order)
4. `com.save!`

Then the language set and order will be updated immediately.

Hopefully this helps.

**Comment by NikhilSharma972** [comment]
I have created a video and scripts to help everyone to translate yml files on the go https://www.youtube.com/watch?v=tVKI9tY6ZEA

**Comment by thomasmalbaux** [comment]
@NikhilSharma972 Thanks, this might help others indeed. I think you should share it with other users of the Community Edition at https://www.sharetribe.com/community/.

**Comment by NikhilSharma972** [comment]
Thanks for your email, i have done it.,
https://www.sharetribe.com/community/t/how-to-translate-locale-yml-files-to-any-language-easy/3061

Thanks,
Nikhil
