### ISSUE TITLE
Same bug as: #1566

### ISSUE THREAD

**Issue by georgejeffery** [sharetribe/sharetribe#3812]
I have exactly the same bug as #1566.

It looks like it was closed without fixing the actual bug... did anything actually get worked out?

Thanks!

**Comment by thomasmalbaux** [comment]
Hey there!

There was a fix done on Aug 26, 2016 (see timeline at https://github.com/sharetribe/sharetribe/issues/1566#event-768548793) with the commit https://github.com/sharetribe/sharetribe/commit/4ce8b41fe9fe08fcfc298f7c05513dcbfaf511c3

I haven't seen any related question over the past three years and I'm not able to reproduce anything. 

Hopefully someone who experiences some similar issues will answer your thread in Community forum at https://www.sharetribe.com/community/t/https-and-emails/2187!

**Comment by georgejeffery** [comment]
Hi @thomasmalbaux I've got that fix in my code and it's still having the same issue, weirdly enough.

I'll see if the community has any advice!
