### ISSUE TITLE
Should the "Google Site Verification" token be moved to config? 

### ISSUE THREAD

**Issue by MrHakala** [sharetribe/sharetribe#3818]
Currently the meta-tag for "google-site-verification" has a static value in _head.haml. Thus allowing the owner of said verification token to claim ownership of any "property" using the code. Or am I mistaken?

**Comment by thomasmalbaux** [comment]
Hey there,

and thanks for reporting.

You are right, something is wrong there. It shouldn't be done like that and I believe it's just something that we've missed and never cleaned/updated, as it has been there for nearly six years already...

I'll investigate this and review things with other team members, to make sure I'm not confusing things.

I'll keep you posted in the coming days. Again, thanks a lot for noticing and sharing! Stay tuned!

**Comment by thomasmalbaux** [comment]
Hello!

And again, thanks for your help.

This is something that has been added more than 6 years ago (https://github.com/sharetribe/sharetribe/commit/8f1408adf92df9499d57731a5a491c83b9ea1686#diff-86f059f37f4659a0407aadbfe69f0b20R23) and it was simply a mistake to forget it. It should have been removed earlier.

This is now done, via https://github.com/sharetribe/sharetribe/pull/3825 and https://github.com/sharetribe/sharetribe/pull/3826.

Thanks!
