### ISSUE TITLE
Page not load on mobile

### ISSUE THREAD

**Issue by ElMandrillo** [sharetribe/sharetribe#3925]
##### Environment: development
node version: v10.15.3
npm version: 6.4.1

##### Description:

hi, I would have problems with sharetribe on mobile devices. If I had to load from my sharetribe laptop, it works very well. But when I do the same from my phone or tablet, the platform is not really loaded as if the site didn't exist.

##### Steps To Reproduce:
Go on andrea.fujikon.it from desktop or laptop-> work
Go on andrea.fujikon.it from smartphone or tablet-> not work

##### Additional information

sharetribe run on ruby with apache web server, i have control the log file (sharetribe, apache) but the log file is clean

**Comment by thomasmalbaux** [comment]
Hey there!

Hmm unfortunately your website also seems to be unavailable on Desktop at the moment, so I'd advise to double check your infrastructure settings.

I'm not able to reproduce any mobile issue with the latest version but don't hesitate to discuss that situation, if it continues, with other users of the Community Edition at https://www.sharetribe.com/community/.
