### ISSUE TITLE
Support for PostgreSQL still being considered?

### ISSUE THREAD

**Issue by Rex-am-I** [sharetribe/sharetribe#3929]
Is support for PostgreSQL something that is still being considered?

**Comment by Rex-am-I** [comment]
Nevermind... I'll go to the community site for answers

**Comment by thomasmalbaux** [comment]
Hey there!

Indeed this is not something we are working on right now, so I don't have any timeline to share and I'm not sure if we'll prioritize that anytime soon. But as you've said, learning from others in the Community forum if they have built such support is the right thing to do :-)
