### ISSUE TITLE
log file too big 

### ISSUE THREAD

**Issue by mickvega** [sharetribe/sharetribe#3981]
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

git hash 1604c980b5790e3f6340d1682e403c3e379ce044

##### Environment: ubuntu

_What's your environment? Mac OS X, Heroku, or something else?_

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
> npm -v
```

##### Server mode: production

_Are you running in development or production mode?_

##### Description:

the file production.searchd.log is taking 100% of the disk space

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. _Step 1_
1. _Step 2_
1. _Step 3_

Expected result: _What was the expected result after running the steps above?_

Actual result: _What was the actual result after running the steps above?_

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment]
Thanks for reporting. Indeed it seems that your log file setup isn't ideal.

This is not something that directly relates to the code of Sharetribe Go, but is about your own infrastructure. You should discuss it on the Community forum, with other users of the Community Edition, at https://www.sharetribe.com/community/.

For example, the thread at https://www.sharetribe.com/community/t/sphinxsearch-searchd-logs-growing-massive-big/1919/2 could be a good starting point.

Hopefully this helps!
