### ISSUE TITLE
Messages/Conversations in admin dashboard not working

### ISSUE THREAD

**Issue by aulinang** [sharetribe/sharetribe#3985]
##### Environment: Ubuntu 18.04
> node -v 10.15
> npm -v 2.6

##### Description:
Messages/Conversations in admin dashboard not working

##### Steps To Reproduce:
1.  Install https://github.com/sharetribe/sharetribe#installation
2.  Create 2 Users and communicate each other
3.  Messages are in database but nothing shown in Dashboard -> Conversations

**Comment by thomasmalbaux** [comment]
Hey there,

and thanks for reporting!

To clarify, this is about conversations started from the "Contact" button on the listing or profile pages, right?

If this is about discussions started from the "Buy" button (without online payments enabled), you'll find them in Transactions, as free transactions.

Could you clarify?

If this is not the case, a couple ideas of things to check:
- anything in your logs? Some error message?
- is the data actually stored in the database? If not, can you see the insert requests from your logs?
- are users able to do other activities (start transactions, ...)?

**Comment by aulinang** [comment]
> If this is about discussions started from the "Buy" button (without online payments enabled), you'll find them in Transactions, as free transactions.

Sorry you are absolutely right. Thank you!

**Comment by thomasmalbaux** [comment]
Good to hear, keep up the good work!
