### ISSUE TITLE
Rails sever is running but if i type localhost:3000 into the browser the server stops working

### ISSUE THREAD

**Issue by parmardhaval48107** [sharetribe/sharetribe#4108]
I am a beginner in the ROR and I am making a movie review application in ROR. yesterday my server is working completely fine but doesn't know what happened if I try it running `rails s` the server is starting as normally but, I goto the browser and type `localhost:3000` the server is not running and it goes to the new line in the CMD. **I tried running my rails application on my friend's computer and it works perfectly fine it seems like it only doesn't work on my computer.** 

I also tried `curl  localhost:3000` but it shows error like below
`curl: (56) Recv failure: Connection was reset`

I also tried various other tricks 
`rails s -b 0.0.0.0 -p 3000`
`bundle exec rails s -b localhost -p 3000`
 I tried lots of solution but it didn't work for me
if you have a solution so please explain me in simple language and in details because i am beginner into this and don't know very much about it

**Comment by thomasmalbaux** [comment]
Hey there!

Hmm unfortunately I'm not able to reproduce this so I'm not sure what's going on exactly.

Don't hesitate to discuss that situation with other users of the Community Edition at https://www.sharetribe.com/community/, maybe someone has experienced something similar and will be able to share their experience!
