### ISSUE TITLE
Rake fails due to AWS non-AWS installation

### ISSUE THREAD

**Issue by jeremyevans6** [sharetribe/sharetribe#4139]
In my new build of ST, I get errors regarding AWS with or without AWS keys present:

```
$ bundle exec rake db:create db:structure:load
rake aborted!
Aws::Sigv4::Errors::MissingCredentialsError: Cannot load `Rails.config.active_storage.service`:
missing credentials, provide credentials with one of the following options:
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider

```

##### Sharetribe Version:

 53703a2 

##### Environment:
Ubuntu 20.04
Node: 10.15.3
NPM: 6.4.1

##### Server mode:
Development, also fails in production

##### Steps To Reproduce:
Standard installation, following the steps in the readme
Fails in step 7 of "Setting up the development environment"
I expect it to succeed using the local harddisk as a fallback, but it insists on AWS credentials and fails to compile

##### Additional information

I've attempted to comment out all AWS fields, which produces an error when it attempts to read the fields using an "empty?" function. I've added dummy keys and the same thing happens, generating an error when checking my values as "empty?"

**Comment by jeremyevans6** [comment]
To be clear, I'd like to avoid AWS entirely. I was under the impression that I could do this simply by leaving the AWS keys blank.

I commented out the AWS gems from the Gemfile and commented out one line from config/environments/development.rb:
`#  config.active_storage.service = :amazon`

This allowed me to complete the compilation, though sphinx indexing failed (perhaps for unrelated reasons, I'm hoping). I now have the webserver up and will continue to document if anything breaks when performing this workaround.

**Comment by hoasung01** [comment]
we should have updated README for this

**Comment by hoasung01** [comment]
You can set it as local `config.active_storage.service = :local`

**Comment by jeremyevans6** [comment]
Ah, I see. It seems that this is was my default option when I commented out the :amazon line at the end of the file.

The :local line exists a few lines before and was overridden by the Amazon line until I commented it out. Glad to know I hadn't entered into a weird state as a result of commenting out this line. Thank you, @hoasung01.

I'm taken care of, so I don't necessarily care what happens with the project. I was under the supposition that lacking Amazon keys would default to local or that perhaps the development server would default to local. It may be worth noting in the docs that this change is necessary for the first build. 

I understand that AWS is essential for Heroku, though I'd wager that most DIY implementations are on VPSs since Heroku is expensive. Addressing small issues like disabling AWS could help those folks like me. Even just adding Karibou's great tutorial as a link in the docs would be an asset: https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04

**Comment by thomasmalbaux** [comment]
Thanks a lot for the discussion and input, this is really valuable!

You're right, having this setting set to `local` makes much more sense. It's just one of these that got changed when working on things, there wasn't really a design to make the life of users of the Community Edition more difficult ;-)

We have now returned to `local` for the test environment, and added more ways to configure this. See https://github.com/sharetribe/sharetribe/pull/4143/files.

It should be more straightforward from now on for people starting from scratch!

**Comment by thomasmalbaux** [comment]
> Even just adding Karibou's great tutorial as a link in the docs would be an asset: https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04

@jeremyevans6 I'm not against linking to such resources (see https://github.com/sharetribe/sharetribe#unofficial-installation-instructions). However Karibu's tutorial is a bit outdated I believe (we've received questions about it, especially about the Node.js version that should be higher). I've tried some time ago to reach them and asked if they'd like to update their post a bit but unfortunately haven't received any answer :'( So for the time being, I'd prefer not to link it as it actually creates a bit of confusion on some parts too.

Does it make sense? What do you think? Are you in touch with them?
