### ISSUE TITLE
Muti Currency Option

### ISSUE THREAD

**Issue by ali-hassan** [sharetribe/sharetribe#4142]
Does Sharetribe's current version supported the multi-currency option for listings?

if yes then how to use it?

**Comment by thomasmalbaux** [comment]
Hello @ali-hassan!

Right now Sharetribe Go supports only one currency at a time. But you could build that customization yourself, independently from us, if you'd like to.

For future questions, don't hesitate to contact us via your Admin panel if you use the hosted version, or discuss things with other users of the Community Edition at https://www.sharetribe.com/community/!
