### ISSUE TITLE
Cannot setup sphinx search on Mac OS X 10.15

### ISSUE THREAD

**Issue by mico** [sharetribe/sharetribe#4144]
Trying to setup sphinx search on os x.
Using sphinx 2.2.11 and MySQL 5.7.29, installed using brew.

Checking if I can connect to sphinx searchd using MySQL console client:
```
% mysql -P 3563 -h 127.0.0.1
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 2.2.11-id64-release (95ae9a6)
```

Looks like everything is ok.
But when I try to connect to searchd using mysql2 gem (0.4.10) I get error:
```
2.6.5 :010 > Mysql2::Client.new(host: '127.0.0.1', port: 3563)
Traceback (most recent call last):
        3: from (irb):10
        2: from (irb):10:in `rescue in irb_binding'
        1: from (irb):10:in `new'
Mysql2::Error (Unknown MySQL error)

```
Updating mysql2 gem doesn't solve the issue.

**Comment by thomasmalbaux** [comment]
Hey Mico!

Unfortunately I'm not able to reproduce that issue but don't hesitate to browse the Community Edition forum (there are a few topics about Sphinx setup already, see https://www.sharetribe.com/community/search?q=sphinx) or simply post a new thread at https://www.sharetribe.com/community/c/os-users/5, hopefully someone who has faced the same issue will share their experience :-)
