### ISSUE TITLE
Post a new listing button not responding

### ISSUE THREAD

**Issue by Chuseuiti** [sharetribe/sharetribe#4186]
After initializing the sharetribe marketplace following the steps given in the README, the button "Post a new listing" doesnt seem to do anything. Any documentation on how to create a new listing would be awesome!

##### Sharetribe Version:

Master

##### Environment:

_What's your environment? Mac OS X, Heroku, or something else?_
Linux 
_What's your node version? Run the following commands and copy the result here:_

node: 10.15.3
npm: 6.4.1
```
> node -v
> npm -v
```

##### Server mode:

Development 

##### Description:

Create New listing button not responding.

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

1. git clone master

2. follow the installation steps on the readme up to:
```
foreman start -f Procfile.static
bundle exec rake jobs:work
```

3. try to create a new listing with a logged in user.

Expected result: To visualize an input form with options to create the listing

Actual result: Nothing

**Comment by thomasmalbaux** [comment]
Hi there!

Unfortunately I'm not able to reproduce this, but this is mostly related to your JavaScript setup. The "New listing form" heavily relies on JavaScript to load and display its content.

Do you have all JavaScript setup completed correctly?
Do you have JavaScript enabled in your own browser?
Can you see any error message in your browser Console? 
Can you see any error message in your application logs?

Let us know!

**Comment by Chuseuiti** [comment]
retried on v10.0.0 and it works well, in any case thanks!
