### ISSUE TITLE
(Feat request) Inventory management / tracking

### ISSUE THREAD

**Issue by aTylerRice** [sharetribe/sharetribe#4306]
I’m a current customer of the sharetribe saas hosted solution. It seemed like a quick choice to get something up quickly.

What is the current roadmap for having some sort of inventory management? I’d really like something similar to Etsy or just a way to add a number of units to listings that gets counted down as people buy for each listing.

This seems like it currently isn’t possible with flex or sharetribe go. For my use case it seems this should be pretty simple, but obviously I’m not familiar with the code base. I went to cancel my subscription as I’m unsure if this works for my needs without this.

is it possible to get a rundown of what would need to be done to add this in and get it merged so it takes affect on my go hosted instance? I’m familiar with the tech stack but I want to make sure if I contribute this I’d actually be able to use it. This seems much easier than building a bespoke solution ( I built a custom marketplace at my second startup and it took close to a year) I’d like this not to take a year lol.

anyway thanks for the great software. I’m awaiting for the cancellation email as hopefully that discussion with ease my quarrels and I’ll be able to use the hosted version as is which is definitely preferable.

**Comment by thomasmalbaux** [comment]
Thanks for the suggestion, @aTylerRice!

This is not something we are working on right now, so I don't have any timeline to share. I haven't done research or thinking about this feature, so unfortunately I don't have any tips to share.

This is something that can be built with Sharetribe Flex though, and would take definitely way way less than a year! Did you have a chance to get started with Flex? If not, give it a try, we'll also be happy to recommend a partner that can build this feature for you, in Flex, if you don't have the technical knowledge yourself.

Happy to continue that discussion through our support channel: you can message us from the chat widget in your Sharetribe Go Admin panel or your Sharetribe Flex Console.
