### ISSUE TITLE
Calendar availability management

### ISSUE THREAD

**Issue by dla002** [sharetribe/sharetribe#4352]
Couldn't find the "per person" availability calendar feature as Sharetribe only supports per hour, per day, and per night. However, our nature of business is experience-based, i.e. customers book a session depending on service providers' availability. They have been reporting many issues/complaints that it's very inconvenient not being able to select the date & time when booking. The current system requires customers to manually send a message to service providers to check their availability before booking. How is it possible to activate per person availability calendar? Thanks.

![Sharetribe](https://user-images.githubusercontent.com/80027807/109925331-9054a000-7cfc-11eb-8bfe-0b29f998ebbf.PNG)

**Comment by thomasmalbaux** [comment]
Hey there,

and thanks for the message. Good to learn more about your marketplace flow!

Right now, such feature doesn't exist in Sharetribe Go. You can create your own pricing unit to be "Per day per person", for example, but the availability calendar wouldn't be enabled. 

If this is a key feature for your marketplace, you could consider our other product, [Sharetribe Flex](https://www.sharetribe.com/products/flex/)! It supports such unit (and much more) so you now that you've learned that this is key for your growth, you could customize your transaction process to match your unique flow.

Give it a try!
