### ISSUE TITLE
Error while installing using docker

### ISSUE THREAD

**Issue by igensis** [sharetribe/sharetribe#4379]
I have installed Sharetribe using docker but i found that error
We’re sorry, but something went wrong.

### You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Passenger is   ### run with environment set to development and/or with the friendly error pages option set to on.

and when i check `docker ps -a ` i found that 3/4 containers are working and one of the exited just the time of starting the container

1. CONTAINER ID   IMAGE                 COMMAND                  CREATED        STATUS                     PORTS                                                                                                                       NAMES
2. 2fefa6449aa5   sharetribe_web        "script/entrypoint.s…"   38 hours ago   Up 4 minutes               0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:80->3000/tcp, 0.0.0.0:443->3000/tcp, :::80->3000/tcp, :::443->3000/tcp   sharetribe_web_1
### 3. 21dacdf0a353   sharetribe_worker     "script/entrypoint.s…"   38 hours ago   Exited (1) 3 minutes ago                                                                                                                               sharetribe_worker_1
4. 4bca1b28ebd5   sharetribe_shredder   "script/entrypoint.s…"   2 days ago     Up 4 minutes               3000/tcp                                                                                                                    sharetribe_shredder_1
5. 3f374ebd87e7   memcached:latest      "docker-entrypoint.s…"   2 days ago     Up 4 minutes               11211/tcp                                                                                                                   sharetribe_memcached_1

I hope you can help me

**Comment by thomasmalbaux** [comment]
Hey there!

Unfortunately I'm not able to reproduce that error and we won't be able to help you there.

I think you're already familiar with the Community forum at https://www.sharetribe.com/community/, it's a good resource to discuss that issue, and hopefully other people who may have experienced a similar situation will be able to share the solution they've found!
