### ISSUE TITLE
undefined method `html_safe' for nil:NilClass Did you mean? html_safe?

### ISSUE THREAD

**Issue by rpmcoding** [sharetribe/sharetribe#4386]
##### Sharetribe Version:

6271b7a77932ba0e15a0ed6229fbccb01ff3b682

##### Environment:

Linux (digitalocean)

node v10.15.3
npm 6.4.1

##### Server mode:

production

##### Description:

When switching to UK language via the admin panel, if you then go to rent an item

e.g. domain.com/en-GB/listings/4/initiate?end_on=2022-11-16&start_on=2022-11-15

You get the error 

"Marketplace temporarily unavailable

The service is unable to process your request right now. Please try again in few moments.

We hate when this happens! We have been informed about the situation and we are fixing it."

##### Additional information

Sentry error log gives:

undefined method `html_safe' for nil:NilClass Did you mean? html_safe?

**Comment by thomasmalbaux** [comment]
Thanks for reporting!

Hmm I'm not able to reproduce so this seems unique to your setup, and the error message isn't the clearest. Are there other errors or warnings you can find?

A few questions and things that come to mind:

1. Does the order type you use for that listing have a name configured for en-gb (you can check by editing your order type)?
2. Does your marketplace has a name for en-gb (you can check by browsing General / Essentials in your Admin panel)?
3. In your database, is there a row for the en-gb locale in the community_customizations table?
4. Have you made changes to the https://github.com/sharetribe/sharetribe/blob/master/config/locales/en-GB.yml file and do you have the en.yml still there (as it is the fallback)?
5. Does this work with another language (en, fr, ...)?
6. Have you tried creating a new listing with a new order type, just to make sure this is not related to other settings?

Let us know!

**Comment by rpmcoding** [comment]
I located the issue to be with a missing value for en-gb in community_customizations.transaction_agreement_label and community_customizations.transaction_agreement_content fields.
