### ISSUE TITLE
Command Failed: bundle exec rake ts:index

### ISSUE THREAD

**Issue by faizananwardeveloper** [sharetribe/sharetribe#4390]
I run the following command  
```
bundle exec rake ts:index
```

then I got the error
```
sh: indexer: command not found

The Sphinx indexing command failed:
  Command: indexer --config "/sharetribe/config/development.sphinx.conf" --all
  Status:  127
  Output:  See above

There may be more information about the failure in /sharetribe/log/development.searchd.log.
```

Before run this I tried to install the **sphinx** using homebrew. Then I found **sphinx** is disabled in homebrew. After that I install with **pip3** then I found **sphinx** installed successfully.

Please guide me, How can I fix it ?

**Comment by thomasmalbaux** [comment]
Thanks for reporting @faizananwardeveloper!

Unfortunately, this sounds related to your own setup so we won't be able to help here. However, you can share this question with other developers using the Community Edition of Sharetribe Go, on the forum at https://www.sharetribe.com/community.

There has been a few threads posted about issues with Sphinx in the past, so do give these a look: https://www.sharetribe.com/community/search?q=sphinx. And if you can't find the answer already, don't hesitate to open a new thread there.

Hopefully, this helps.
