### ISSUE TITLE
Capistrano support?

### ISSUE THREAD

**Issue by kjakub** [sharetribe/sharetribe#448]
Did anybody deploy this application with capistrano?

**Comment by vivek2007** [comment]
@kjakub Hi, I am also using capistrano, I need to deploy following command in staging or production

RAILS_ENV=production bundle exec rake ts:index
RAILS_ENV=production bundle exec rake ts:start
RAILS_ENV=production NODE_ENV=production bundle exec rake assets:precompile
Invoke the delayed job worker:
RAILS_ENV=production bundle exec rake jobs:work

**Comment by kjakub** [comment]
@vivek2007 commands seems correct, however not sure where the file  https://github.com/sharetribe/sharetribe/blob/master/docs/vps-deployment.md go, too long time ago and i have not been around since. But i was able to find this https://github.com/kjakub/sharetribe/blob/fd1e7b4f8b4efac656c806b1fc5569fdedf93ce9/docs/vps-deployment.md

**Comment by vivek2007** [comment]
@kjakub, Hi my request and question is, sometimes search not working and mail notifications not workng in that cases we need to run bundle exec rake jobs:work and ts:index

but how to run those commads from local system

**Comment by kjakub** [comment]
![screenshot from 2018-02-22 00-52-28](https://user-images.githubusercontent.com/660833/36496452-d7bd8a56-176a-11e8-9d57-0dab0a2c6b91.png)

something like that from you local machine, but your email issue is related somewhere else

**Comment by vivek2007** [comment]
@kjakub, need to add rake tasks in deploy.rb or not required ?

**Comment by kjakub** [comment]
no, you should just run those capistrano tasks
