### ISSUE TITLE
application cannot be started in production environment - missing mangopay config 

### ISSUE THREAD

**Issue by kjakub** [sharetribe/sharetribe#462]
in config/initilazers/mangopay_initilizer.rb

provide the keys in config.example.yml

**Comment by sebfie** [comment]
Hello,

I want to implement que MangoPay feature on my project, what features were supported and which one were not?

Thx

**Comment by rap1ds** [comment]
@sebfie MangoPay was never finished and it was never in use in production. So in that sense, I'd say that none of it was supported at any point.
