### ISSUE TITLE
Unable to access community in main domain instead of subdomain

### ISSUE THREAD

**Issue by brgnepal** [sharetribe/sharetribe#598]
Hi,

I have been trying to access community `abc` which I access now as `abc.foo.com` through `foo.com` but unable to configure it properly through `nginx`.

I referred this <a href='https://github.com/sharetribe/sharetribe/issues/385' target='_blank'>similar issue</a> and changed the `domain` of my community table from `abc` to `foo.com` but still unable to access the community.

Am I missing anything?

**Comment by harshad26** [comment]
Subdomain is compulsory for sharetribe?

If i have domain name "xyz.trade" then how to run sharetribe site on it? Subdomain must be there?

Its work on subdomain (abc.xyz.trade) but not on main domain(xyz.trade). I want to run on main domain.

**Comment by rkrevolution** [comment]
Thanks! we had this same issue.

**Comment by jimrambow** [comment]
Yes, thank you to all who wrote about this, I was working with rkrevolution and we were trying to figure this out for almost 2 days.

**Comment by bingxie** [comment]
But I found there is validation in Community model, it doesn't allow having '.' in the domain field.
