### ISSUE TITLE
Unable to use S3

### ISSUE THREAD

**Issue by brgnepal** [sharetribe/sharetribe#665]
Hi Folks,

I am trying to use Amazon S3 but I am unable to upload listing image.
The upload stuck in 0% and there are no error logs at both worker and server sides.

I added following fields in `config.yml`:

```
s3_bucket_name:
s3_upload_bucket_name:
aws_access_key_id:
aws_secret_access_key:
```

Any other customization required to make S3 work?
What might be the problem? 
Also, is it related to S3 security groups?

**Comment by Sivan1525** [comment]
@budhrg , I am getting same issue so can you tell me how did you do this?

**Comment by bingxie** [comment]
@budhrg  yes, I have the same issue. I created group and user. What do you mean for 'CORS settings'?

**Comment by budhrg** [comment]
@bingxie @Sivan1525 : This might help you.
http://blogs.aws.amazon.com/security/post/TxPOJBY6FE360K/IAM-policies-and-Bucket-Policies-and-ACLs-Oh-My-Controlling-Access-to-S3-Resourc

My policy looks simple:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

**Comment by bingxie** [comment]
Thank you @budhrg 
After I configed the CORS in bucket's permissions settings like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```
Then it worked.

**Comment by budhrg** [comment]
Cool @bingxie :+1:

**Comment by sainineeraj** [comment]
I am unable to upload images after configuring s3, when I attempt to upload I see this error in the javascript console.


"[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (xxxxxx.s3.amazonaws.com, line 0)"


I have the following CORS settings:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

Bucket policy is empty

I have also create IAM group and User with Full S3acess
