### ISSUE TITLE
structure.sql not found

### ISSUE THREAD

**Issue by whatsdis** [sharetribe/sharetribe#684]
```
TASK: [webserver | mysql_db name=mysite_prod login_user=mysite login_password=cool 
state=import target=/root/sharetribe/db/structure.sql] ***
failed: [localhost] => {"failed": true}
msg: target /root/sharetribe/db/structure.sql does not exist on the host
```

I was running this ansible script and it stops there. structure.sql is indeed not found.

https://github.com/nicolasblanco/ansible-sharetribe

**Comment by jarvisjohnson** [comment]
@ovan FYI the main readme.md still references `rake db:structure:load` for both development and production databases.  It works for development but I needed `rake db:schema:load` for the production db.

**Comment by ovan** [comment]
@jarvisjohnson Actually in the master we today switched back to structure.sql and this is reflected in readme too.

**Comment by jarvisjohnson** [comment]
Well that makes sense!  cheers @ovan
