### ISSUE TITLE
"Page Loading Failed!" Error when running production site on local server

### ISSUE THREAD

**Issue by biddercount** [sharetribe/sharetribe#760]
Am trying to install sharetribe locally with OSX 10.9.5, Ruby set to 2.1.2 with RVM, using MySQL and all other specified software following the readme file instructions, and am encountering errors when trying to create and run a marketplace locally. 

Trying to run the server locally in production mode, after starting the server and running the README commands to create a new marketplace, I get the "Page loading failed!" message at http://0.0.0.0:3000/ . I am not able to view a cover image. If I do anything further I get the following error:

rails server -e production
=> Booting WEBrick
=> Rails 3.2.19 application starting in production on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
[2014-11-08 17:29:47] INFO WEBrick 1.3.1
[2014-11-08 17:29:47] INFO ruby 2.1.2 (2014-05-08) [x86_64-darwin13.0]
[2014-11-08 17:29:47] INFO WEBrick::HTTPServer#start: pid=55013 port=3000
Connecting to database specified by database.yml
Creating scope :public. Overwriting existing method Listing.public.
Creating scope :private. Overwriting existing method Listing.private.
127.0.0.1:11211 failed (count: 0)
DalliError: No server available
Started GET "/" for 127.0.0.1 at 2014-11-08 17:31:52 +0100
Processing by DashboardController#index as 
Rendered dashboard/_contact_request_form.haml (7.6ms)
Rendered dashboard/_contact_request_form.haml (1.1ms)
Rendered dashboard/index.haml within layouts/dashboard (27.0ms)
Rendered layouts/_kissmetrics.haml (2.3ms)
Rendered layouts/_network_head.haml (4771.1ms)
Rendered layouts/_head.haml (4781.2ms)
Completed 200 OK in 4837.2ms (Views: 4824.2ms | ActiveRecord: 0.0ms)
127.0.0.1 GET / 200 OK DashboardController#index HTML 4837.2 (DB 0.0, View 4824.2) {} {}
127.0.0.1:11211 failed (count: 1)
127.0.0.1:11211 is down
DalliError: No server available
DalliError: No server available
DalliError: No server available
127.0.0.1:11211 failed (count: 2)
DalliError: No server available
127.0.0.1:11211 failed (count: 3)
DalliError: No server available
Started GET "/" for 127.0.0.1 at 2014-11-08 17:32:13 +0100
Processing by DashboardController#index as 
Rendered dashboard/_contact_request_form.haml (2.0ms)
Rendered dashboard/_contact_request_form.haml (1.7ms)
Rendered dashboard/index.haml within layouts/dashboard (5.3ms)
Rendered layouts/_kissmetrics.haml (0.1ms)
Rendered layouts/_network_head.haml (6.3ms)
Rendered layouts/_head.haml (7.8ms)
Completed 200 OK in 17.4ms (Views: 16.1ms | ActiveRecord: 0.0ms)
127.0.0.1 GET / 200 OK DashboardController#index HTML 17.4 (DB 0.0, View 16.1) {} {}
DalliError: No server available
DalliError: No server available
DalliError: No server available
127.0.0.1:11211 failed (count: 4)
DalliError: No server available
Started GET "/" for 127.0.0.1 at 2014-11-08 17:32:48 +0100

TypeError (no implicit conversion of nil into String):
lib/routes/community_domain.rb:3:in include?' lib/routes/community_domain.rb:3:inmatches?'
lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

Processing by ErrorsController#server_error as 
Rendered errors/_status_500.haml (1.5ms)
Rendered errors/_error_layout.haml (6.5ms)
Rendered errors/500.haml (10.4ms)
Completed 500 Internal Server Error in 14.2ms (Views: 13.8ms | ActiveRecord: 0.0ms)
127.0.0.1 GET /500 500 Internal Server Error ErrorsController#server_error HTML 14.2 (DB 0.0, View 13.8) {} {}
DalliError: No server available
DalliError: No server available
DalliError: No server available
DalliError: No server available
DalliError: No server available
[2014-11-08 17:32:48] ERROR NoMethodError: undefined method each' for nil:NilClass /Users/.rvm/gems/ruby-2.1.2/gems/rack-1.4.5/lib/rack/deflater.rb:64:ineach'
/Users/.rvm/gems/ruby-2.1.2/gems/rack-1.4.5/lib/rack/handler/webrick.rb:71:in service' /Users/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:inservice'
/Users/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in run' /Users/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:inblock in start_thread'

I have tried restarting and running "rake precompile" or restarting and running "rake sharetribe:generate_customization_stylesheets" but to no avail.

Any suggestions as to what's the problem?

**Comment by niiamon** [comment]
@rap1ds is there a guide on how to run multiple communities in the same sharetribe install? The community creation URL redirects to home page once there's a single community in the db.

**Comment by ramesh2007** [comment]
Hi @gnomet, 

in opensource pagination not working with while using with apache, but when I tried to run with following command 
foreman start -f Procfile.static
pagination working but not with apache and nginx

Thanks

**Comment by ramesh2007** [comment]
Hi @rap1ds 

in opensource pagination not working with while using with apache, but when I tried to run with following command
foreman start -f Procfile.static
pagination working but not with apache and nginx

Thanks
