### ISSUE TITLE
Community Subdomain didn't works on production server.

### ISSUE THREAD

**Issue by sahidursuman** [sharetribe/sharetribe#795]
Hello,
I installed sharetribe application following the sharetribe github page instructions. I installed it in a Digital ocean droplet including Ubuntu 14.04 + nginx + passenger + rvm. The main site is working perfectly on production server, but community site is didn't work. I didn't get any error message from production.log file.

Can you please give me any suggestion, How can i overcome this problem ?

Thanks
Sahidur Rahman Suman

**Comment by math29** [comment]
Hey I have got exactly the same problem with my AWS configuration.
It works perfectly for the main site but for my "community site" it doesn't work !
I just changed the domain parameter in config.yml : 
domain: "ec2-52-19-82-115.eu-west-1.compute.amazonaws.com:3000"
Some idea ? :)

**Comment by softcomet** [comment]
Hello, now I am trying to run the sharetribe app on DIGITAL OCEAN, but not sure how domain setting is working.

I cloned the repo and configured for all things and tried to run the sharetribe server by using
bundle exec rails server -e production

Currently in config.defaults.yml file, domain setting is following
 # Fill here the domain where you will be running Sharetribe.
  # If you are running on localhost, you can write here "lvh.me:3000" (which redirects to localhost port 3000)
  # The community subdomains will be added to this top domain.
  # NOTE: Do not include http(s) here, or subdomains, just the top level domain, like "sharetribe.com" for example
  domain: "lvh.me:3000"

Should I change the domain name with raw IP, i.e. xx.xx.xx.xx ?

Any suggestion would be appreciated.

**Comment by softcomet** [comment]
Hello, now I am trying to run the sharetribe app on DIGITAL OCEAN, but not sure how domain setting is working.

I cloned the repo and configured for all things and tried to run the sharetribe server by using
bundle exec rails server -e production

Currently in config.defaults.yml file, domain setting is following
# Fill here the domain where you will be running Sharetribe.
# If you are running on localhost, you can write here "lvh.me:3000" (which redirects to localhost port 3000)
# The community subdomains will be added to this top domain.
# NOTE: Do not include http(s) here, or subdomains, just the top level domain, like "sharetribe.com" for example
domain: "lvh.me:3000"

Should I change the domain name with raw IP, i.e. xx.xx.xx.xx ?

Any suggestion would be appreciated.

**Comment by thomasmalbaux** [comment]
Hey there!

Unfortunately we won't be able to help as the custom domain setup will be quite specific to your own infrastructure, but don't hesitate to discuss this with other users of the Community Edition at https://www.sharetribe.com/community/!
