### ISSUE TITLE
Table 'sharetribe_development.communities' doesn't exist

### ISSUE THREAD

**Issue by codecakes** [sharetribe/sharetribe#804]
Platform Ubuntu 12.10 x64;

I followed the instructions but ran into this error:

ActiveRecord::StatementInvalid in HomepageController#index

Mysql2::Error: Table 'sharetribe_development.communities' doesn't exist: SHOW FULL FIELDS FROM `communities`

App trace on site:

app/models/community.rb:478:in `find_by_domain'
app/controllers/application_controller.rb:147:in`block in fetch_community'
app/controllers/application_controller.rb:131:in `call'
app/controllers/application_controller.rb:131:in`fetch_community_by_strategy'
app/controllers/application_controller.rb:146:in `fetch_community'
config/initializers/oneline_detailed_logging.rb:31:in`block (2 levels) in <top (required)>'
config/initializers/oneline_detailed_logging.rb:30:in `block in <top (required)>'
lib/rack_middleware/custom_domain_cookie.rb:20:in`call'

console trace:

/sharetribe$ rails s -p 7778
Digest::Digest is deprecated; use Digest
=> Booting WEBrick
=> Rails 3.2.19 application starting in development on http://0.0.0.0:7778
=> Call with -d to detach
=> Ctrl-C to shutdown server

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
[2014-11-18 13:27:10] INFO  WEBrick 1.3.1
[2014-11-18 13:27:10] INFO  ruby 2.1.2 (2014-05-08) [x86_64-linux]
[2014-11-18 13:27:10] INFO  WEBrick::HTTPServer#start: pid=32305 port=7778

Started GET "/" for 117.253.103.22 at 2014-11-18 13:27:46 +0400
Processing by HomepageController#index as
Mysql2::Error: Table 'sharetribe_development.communities' doesn't exist: SHOW FULL FIELDS FROM `communities`
Completed 500 Internal Server Error in 150.9ms
117.253.103.22 GET / 500 Internal Server Error HomepageController#index HTML 150.9 (DB 0.0, View 0.0) {} {}
*\* [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'sharetribe_development.communities' doesn't exist: SHOW FULL FIELDS FROM `communities`):
  app/models/community.rb:478:in `find_by_domain'
  app/controllers/application_controller.rb:147:in`block in fetch_community'
  app/controllers/application_controller.rb:131:in `call'
  app/controllers/application_controller.rb:131:in`fetch_community_by_strategy'
  app/controllers/application_controller.rb:146:in `fetch_community'
  config/initializers/oneline_detailed_logging.rb:31:in`block (2 levels) in <top (required)>'
  config/initializers/oneline_detailed_logging.rb:30:in `block in <top (required)>'
  lib/rack_middleware/custom_domain_cookie.rb:20:in`call'

  Rendered /home/akul/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.19/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.7ms)
  Rendered /home/akul/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.19/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.3ms)
  Rendered /home/akul/.rvm/gems/ruby-2.1.2/gems/actionpack-3.2.19/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (13.2ms)

Started GET "/" for 117.253.103.22 at 2014-11-18 13:30:04 +0400
Processing by HomepageController#index as
Mysql2::Error: Table 'sharetribe_development.communities' doesn't exist: SHOW FULL FIELDS FROM `communities`
Completed 500 Internal Server Error in 3.0ms
117.253.103.22 GET / 500 Internal Server Error HomepageController#index HTML 3.0 (DB 0.0, View 0.0) {} {}
*\* [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? false

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'sharetribe_development.communities' doesn't exist: SHOW FULL FIELDS FROM `communities`):
  app/models/community.rb:478:in `find_by_domain'
  app/controllers/application_controller.rb:147:in`block in fetch_community'
  app/controllers/application_controller.rb:131:in `call'
  app/controllers/application_controller.rb:131:in`fetch_community_by_strategy'
  app/controllers/application_controller.rb:146:in `fetch_community'
  config/initializers/oneline_detailed_logging.rb:31:in`block (2 levels) in <top (required)>'
  config/initializers/oneline_detailed_logging.rb:30:in `block in <top (required)>'
  lib/rack_middleware/custom_domain_cookie.rb:20:in`call'

before running the server I ran 

> > rake db:migrate

and got this:

/sharetribe$ rake db:migrate
Digest::Digest is deprecated; use Digest

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
==  CreateItems: migrating ====================================================
-- create_table(:items)
   -> 0.0211s
==  CreateItems: migrated (0.0212s) ===========================================

==  CreateFavors: migrating ===================================================
-- create_table(:favors)
   -> 0.0541s
==  CreateFavors: migrated (0.0543s) ==========================================

==  CreatePeople: migrating ===================================================
-- create_table(:people, {:id=>false})
   -> 0.0399s
-- execute("ALTER TABLE people ADD PRIMARY KEY (id)")
   -> 0.1064s
==  CreatePeople: migrated (0.1465s) ==========================================

==  CreateListings: migrating =================================================
-- create_table(:listings)
   -> 0.1026s
==  CreateListings: migrated (0.1027s) ========================================

==  CreateMessages: migrating =================================================
-- create_table(:messages)
   -> 0.1361s
==  CreateMessages: migrated (0.1362s) ========================================

==  CreateListingComments: migrating ==========================================
-- create_table(:listing_comments)
   -> 0.1043s
==  CreateListingComments: migrated (0.1044s) =================================

==  CreatePersonComments: migrating ===========================================
-- create_table(:person_comments)
   -> 0.0508s
==  CreatePersonComments: migrated (0.0508s) ==================================

==  CreateReadListings: migrating =============================================
-- create_table(:read_listings)
   -> 0.0139s
==  CreateReadListings: migrated (0.0140s) ====================================

==  CreateInterestingListings: migrating ======================================
-- create_table(:interesting_listings)
   -> 0.0430s
==  CreateInterestingListings: migrated (0.0434s) =============================

==  CreateFilters: migrating ==================================================
-- create_table(:filters)
   -> 0.0416s
==  CreateFilters: migrated (0.0417s) =========================================

==  ChangePaymentColumnToInteger: migrating ===================================
-- change_column(:favors, :payment, :integer)
   -> 0.0800s
==  ChangePaymentColumnToInteger: migrated (0.0801s) ==========================

==  AddColumnPaymentToItem: migrating =========================================
-- add_column(:items, :payment, :integer)
   -> 0.1237s
==  AddColumnPaymentToItem: migrated (0.1238s) ================================

==  AddCosCookieToPerson: migrating ===========================================
-- add_column(:people, :cos_cookie, :string)
   -> 0.0848s
==  AddCosCookieToPerson: migrated (0.0849s) ==================================

==  CreateConversations: migrating ============================================
-- create_table(:conversations)
   -> 0.0331s
==  CreateConversations: migrated (0.0332s) ===================================

==  CreatePersonConversations: migrating ======================================
-- create_table(:person_conversations)
   -> 0.0262s
==  CreatePersonConversations: migrated (0.0264s) =============================

==  RenameInterestingListingsToPersonInterestingListings: migrating ===========
-- rename_table(:interesting_listings, :person_interesting_listings)
   -> 0.0244s
==  RenameInterestingListingsToPersonInterestingListings: migrated (0.0245s) ==

==  RenameReadListingsToPersonReadListings: migrating =========================
-- rename_table(:read_listings, :person_read_listings)
   -> 0.0201s
==  RenameReadListingsToPersonReadListings: migrated (0.0202s) ================

==  RemoveReceiverIdAndListingIdFromMessage: migrating ========================
-- remove_column(:messages, :receiver_id)
   -> 0.1140s
-- remove_column(:messages, :listing_id)
   -> 0.1236s
==  RemoveReceiverIdAndListingIdFromMessage: migrated (0.2378s) ===============

==  AddConversationIdToMessage: migrating =====================================
-- add_column(:messages, :conversation_id, :integer)
   -> 0.1524s
==  AddConversationIdToMessage: migrated (0.1526s) ============================

==  RemoveCosCookieFromPerson: migrating ======================================
-- remove_column(:people, :cos_cookie)
   -> 0.0648s
==  RemoveCosCookieFromPerson: migrated (0.0649s) =============================

==  AddReadToPersonConversation: migrating ====================================
-- add_column(:person_conversations, :read, :boolean, {:default=>0})
   -> 0.0688s
==  AddReadToPersonConversation: migrated (0.0689s) ===========================

==  RemoveReadAndAddIsReadToPersonConversation: migrating =====================
-- remove_column(:person_conversations, :read)
   -> 0.0753s
-- add_column(:person_conversations, :is_read, :integer, {:default=>0})
   -> 0.1172s
==  RemoveReadAndAddIsReadToPersonConversation: migrated (0.1928s) ============

==  CreateTransactions: migrating =============================================
-- create_table(:transactions)
   -> 0.0152s
==  CreateTransactions: migrated (0.0154s) ====================================

==  CreateFeedbacks: migrating ================================================
-- create_table(:feedbacks)
   -> 0.0130s
==  CreateFeedbacks: migrated (0.0131s) =======================================

==  ChangeFeedbackContentToText: migrating ====================================
-- change_column(:feedbacks, :content, :text)
   -> 0.1145s
==  ChangeFeedbackContentToText: migrated (0.1146s) ===========================

==  AddIsAdminToPerson: migrating =============================================
-- add_column(:people, :is_admin, :integer, {:default=>0})
   -> 0.1032s
==  AddIsAdminToPerson: migrated (0.1034s) ====================================

==  RemoveCoinAmountFromPerson: migrating =====================================
-- remove_column(:people, :coin_amount)
   -> 0.1708s
==  RemoveCoinAmountFromPerson: migrated (0.1710s) ============================

==  AddLastSentAtAndLastReceivedAtToPersonConversation: migrating =============
-- add_column(:person_conversations, :last_sent_at, :datetime)
   -> 0.0875s
-- add_column(:person_conversations, :last_received_at, :datetime)
   -> 0.1077s
==  AddLastSentAtAndLastReceivedAtToPersonConversation: migrated (0.1955s) ====

==  CreateKassiEvents: migrating ==============================================
-- create_table(:kassi_events)
   -> 0.0056s
==  CreateKassiEvents: migrated (0.0058s) =====================================

==  CreateKassiEventsPeople: migrating ========================================
-- create_table(:kassi_events_people)
   -> 0.0184s
==  CreateKassiEventsPeople: migrated (0.0185s) ===============================

==  RemoveIdFromKassiEventsPeople: migrating ==================================
-- drop_table(:kassi_events_people)
   -> 0.0137s
-- create_table(:kassi_events_people, {:id=>false})
   -> 0.0437s
==  RemoveIdFromKassiEventsPeople: migrated (0.0578s) =========================

==  AddKassiEventIdToPersonComment: migrating =================================
-- add_column(:person_comments, :kassi_event_id, :integer)
   -> 0.0802s
==  AddKassiEventIdToPersonComment: migrated (0.0803s) ========================

==  AddStatusToItem: migrating ================================================
-- add_column(:items, :status, :string, {:default=>"enabled"})
   -> 0.0811s
==  AddStatusToItem: migrated (0.0813s) =======================================

==  AddStatusToFavor: migrating ===============================================
-- add_column(:favors, :status, :string, {:default=>"enabled"})
   -> 0.0803s
==  AddStatusToFavor: migrated (0.0804s) ======================================

==  AddIsReadToListingComment: migrating ======================================
-- add_column(:listing_comments, :is_read, :integer, {:default=>0})
   -> 0.0507s
==  AddIsReadToListingComment: migrated (0.0509s) =============================

==  ChangeListingTimesViewedDefault: migrating ================================
-- change_column(:listings, :times_viewed, :integer, {:default=>0})
   -> 0.0297s
==  ChangeListingTimesViewedDefault: migrated (0.0299s) =======================

==  AddDescriptionToItem: migrating ===========================================
-- add_column(:items, :description, :text, {:default=>""})
   -> 0.0920s
==  AddDescriptionToItem: migrated (0.0921s) ==================================

==  AddColumnLastModifiedToListing: migrating =================================
-- add_column(:listings, :last_modified, :datetime)
   -> 0.0897s
==  AddColumnLastModifiedToListing: migrated (0.1535s) ========================

==  InsertIsHandledToFeedbacks: migrating =====================================
-- add_column(:feedbacks, :is_handled, :integer, {:default=>0})
   -> 0.0623s
==  InsertIsHandledToFeedbacks: migrated (0.0625s) ============================

==  CreateSettings: migrating =================================================
-- create_table(:settings)
   -> 0.0467s
==  CreateSettings: migrated (0.0468s) ========================================

==  AddPersonIdToSettings: migrating ==========================================
-- add_column(:settings, :person_id, :string)
   -> 0.0540s
==  AddPersonIdToSettings: migrated (0.0541s) =================================

==  AddSettingsToExistingPeople: migrating ====================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `find_by_username' for #<Class:0x00000007e67600>/home/akul/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.19/lib/active_record/dynamic_matchers.rb:27:in`method_missing'

**Comment by brakon** [comment]
It started working for me once I ran this before the db:migrate script
`bundle exec rake db:schema:load`
