### ISSUE TITLE
Payment not working for Sharetribe using braintree

### ISSUE THREAD

**Issue by usmanarif** [sharetribe/sharetribe#876]
I am using default Braintree payment gateway in my sharetribe application but getting the following error message
        The listing author has not added their payment details so they cannot receive payments right now. Please contact the author.

I am providing following credentials for payment from Admin side:
    Environment: Sandbox
    Public Key: jszqqxxxxxxxb83gp
    Private Key: 161b1xxxxxxx7f44d
    Merchant Id: q5p95xxxxxxxxq4695
    CSE Key: MIIBCxxxxxxxxxxDAQAB
    Commission Percentage for seller: 10

My Master Merchant Id is blank. Please suggest as what I am missing?

**Comment by arvindvyas** [comment]
@usmanarif how you resolved this? because I am also facing same issue.
