### ISSUE TITLE
Can i use sharetribe application with amazon public DNS

### ISSUE THREAD

**Issue by harshad26** [sharetribe/sharetribe#885]
Hi,

I set up sharetribe in local and its work fine in local 

But  i uploaded on amazon ec2 instance and try to setup. Everything setup but when i tried to run at that time i face problem
I know that using ip it does not work so i use public DNS of amazon ec2 instance.

suppose my public DNS of amazon instance is: ec2-11-111-11-111.compute-1.amazonaws.com

then how to set this in run in browser. I set in config default file in domain and try to run  http://ec2-xx-xxx-xx-xxx.compute-1.amazonaws.com:3000/  then got error "This webpage is not available"

What should i do for it.

Thanks

**Comment by harshad26** [comment]
I solved it

Thanks

**Comment by math29** [comment]
Hey :) 

How did you do to solve your problem of DNS ?

Thanks
Math
