### ISSUE TITLE
Images seem to be processing but the worker isn't updating the database with the newly processed images

### ISSUE THREAD

**Issue by hvent90** [sharetribe/sharetribe#893]
The delayed job worker is repeatedly saying that jobs are being completed with 0 errors. 

/log/production.log are showing lines such as:
Command :: convert '/tmp/10525990_10152757277949130_952053413298731933_n20150102-24420-10a36zr20150102-24420-1m1gexr20150102-24420-r37kib[0]' -auto-orient -resize "240x" -crop "240x160+0+10" +repage '/tmp/10525990_10152757277949130_952053413298731933_n20150102-24420-10a36zr20150102-24420-1m1gexr20150102-24420-r37kib20150102-24420-ijgb79'
Command :: file -b --mime '/tmp/10525990_10152757277949130_952053413298731933_n20150102-24420-10a36zr20150102-24420-1m1gexr20150102-24420-r37kib20150102-24420-ijgb79'

This leads me to believe that the images are being correctly processed.

Checking the database shows that listing_images.image_processing still remains at 1.

**Comment by hvent90** [comment]
This is in /log/production.log
Connecting to database specified by database.yml
Creating scope :public. Overwriting existing method Listing.public.
Creating scope :private. Overwriting existing method Listing.private.

that seems to suggest it worked

**Comment by rap1ds** [comment]
Did you manage to fix the issue or do you still have it? Are you using S3 or saving the images locally?

**Comment by rap1ds** [comment]
Closed as inactive
