### ISSUE TITLE
braintree_accounts.status not changing from 'pending'

### ISSUE THREAD

**Issue by hvent90** [sharetribe/sharetribe#894]
Hello! This software rocks.

Accounts are staying as 'pending' upon entering in payment info. I've waited a couple days to see if the status changes...it doesn't change.

What file could I check for a clue?

Cheers

**Comment by ovan** [comment]
Hi, can you see in your logs if the braintree webhook has triggered? Have you added your sharetribe braintree webhook URL at braintree?

**Comment by hvent90** [comment]
Hi Ovan, what log file should I check? Also, please reopen this issue. Apologies for not replying sooner.

**Comment by ovan** [comment]
@hvent90  This would be your server output. How that happens exactly depends where and how you host the server. You need to have the application running all the time to receive post from braintree. This is the way braintree sends you information about submerchant accounts being approved. From log files you can see if this post has happened.

Unfortunately at the moment we have very limited resources for providing open source installation support. Your best bet for quick answers currently is the developer community and chat room: https://www.flowdock.com/invitations/4f606b0784e5758bfdb25c30515df47cff28f7d5-main

**Comment by hvent90** [comment]
Resolved: The issue was my unfamiliarity with needing to create a webhook with Braintree. Might want to throw that in your installation instructions for those who are aren't aware of those unmentioned steps.
