### ISSUE TITLE
Error  while sharetribe setup on production

### ISSUE THREAD

**Issue by harshad26** [sharetribe/sharetribe#896]
Hi,

I installed it in a Digital ocean droplet including Ubuntu 14.04 + nginx + passenger + rvm.
My domain name is www.abc.trade
when i run then display page of email box where i put my email then ask me "where do you come from" and "what kind of marketplace do you need?"
I filled above and click on "send" then display error below
--------------------------------------------------------------------
Marketplace temporarily unavailable
The service is unable to process your request right now. Please try again in few moments.
We hate when this happens! We have been informed about the situation and we are fixing it.
--------------------------------------------------------------------
What is actual problem?

Its run perfect in development server. I put development database on production server and changed only domain name still not work. Its open to enter email page.
I set domain in config/config.defaults.yml 
domain: "www.abc.trade"

Is it perfact or any need to chage?

Thanks

**Comment by harshad26** [comment]
I solved it. Use subdomain then its soved.

Thanks

**Comment by RileySpiller** [comment]
I am getting this also. What do you mean by "Use subdomain"? Thanks.

**Comment by harshad26** [comment]
Sub-domain use means before i used http://xyz.com but after used sub-domain means http://test.xyz.com so solved it.

**Comment by orignMaster** [comment]
the subdomain hasn worked for me
