### ISSUE TITLE
Find person by username doesn't allow to apply migrations

### ISSUE THREAD

**Issue by 18augst** [sharetribe/sharetribe#903]
Hello! I've tried to install app from scratch. But I've got following error during `rake db:migrate`:

    NoMethodError: undefined method `find_by_username' for #<Class:0x00000004669dc0>
    /home/augst/.rvm/gems/ruby-2.1.2@sharetribe/gems/activerecord-3.2.19/lib/active_record/dynamic_matchers.rb:27:in `method_missing'
    /home/augst/work/rails/sharetribe/app/models/person.rb:123:in `find'
    /home/augst/work/rails/sharetribe/db/migrate/20090330072036_add_settings_to_existing_people.rb:3:in `up'

When I comment following code in `Person.rb` model, it procceds few next steps and breaks again.

    # def self.find(username)
    #   super(self.find_by(username: username).try(:id) || username)
    # end

I get error: 

     NameError: uninitialized constant  MoveDataFromKassiEventsPeopleToKassiEventParticipation::KassiEvent
    /home/augst/work/rails/sharetribe/db/migrate/20090730094216_move_data_from_kassi_events_people_to_kassi_event_participation.rb:3:in `up'
    /home/augst/.rvm/gems/ruby-2.1.2@sharetribe/gems/activerecord-3.2.19/lib/active_record/migration.rb:370:in `up'

**Comment by ovan** [comment]
@18augst You don't run migrations when installing from scratch. Just do `rake db:schema:load` instead. Migrations are for incrementally maintaining the database structure as schema evolves.

**Comment by 18augst** [comment]
@ovan Thank you very much! I did not know this before.
