### ISSUE TITLE
rails 4

### ISSUE THREAD

**Issue by heydiplo** [sharetribe/sharetribe#909]
Hi! Do you have plans to upgrade to Rails 4? Maybe there is some work in progress I can help with?

**Comment by bingxie** [comment]
I would like to help too.

**Comment by ovan** [comment]
Hi. At the moment we don't have any plans to upgrade. That being said, I'd be happy to hear your thoughts about if this would be important and why? What would we gain by doing it beyond the joy of using the latest and greatest? What does this mean in terms of code changes?

**Comment by heydiplo** [comment]
For me it's primarily about support.

We're about to start a new project and consider going with Sharetribe. However, Rails 3.2 are only getting severe security updates by now and will be dropped as soon as Rails 5 is released. And it's going to be sad to be left with the outdated software shortly after the start.

There are also a lot of awesome new features in the current version. Release notes are written much better then I will do, so there are the links:
http://guides.rubyonrails.org/4_0_release_notes.html
http://guides.rubyonrails.org/4_1_release_notes.html
http://guides.rubyonrails.org/4_2_release_notes.html

Also consider performance optimizations, e.g. http://tenderlovemaking.com/2014/02/19/adequaterecord-pro-like-activerecord.html.

The upgrade process is mostly about reorganizing things, there are no really breaking changes. Most things can be left as there are now and updated gracefully.

http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0 (also check 4.0→4.1 and 4.1→4.2 in the right menu).

Sorry for not being very specific, but it really about a bunch of small things. So I think it's better to read the original guide, it's short and also well-written.

My point is you probably have to update sooner or later, so why hesitate – we're here to help you right now.

**Comment by ovan** [comment]
Thanks for your input. I can understand your reasoning here. We need to have a look at the material you linked and see what this would mean in practice for us.

**Comment by bingxie** [comment]
Here is another good article about upgrade:
http://technology.customink.com/blog/2014/09/16/from-rails-3.2-to-4.2/

I have used these good new features:
* Action Pack Variants
* Spring
* Postgresql Hstore data type
* Cache Digests

**Comment by gugl** [comment]
Any news on the timeline for the upgrade?

**Comment by ssoulless** [comment]
Hi, Im also willing to help in this, is there any advance on this topic?

**Comment by likelazyeyes** [comment]
In Rails 5, Rails API will be default. Turbolinks 3.0 and others.
You must upgrade ruby version certainly. Because new rails releases will not support under ruby 2.0
An article: https://blog.engineyard.com/2015/a-look-at-rails-5

**Comment by ovan** [comment]
Hi all. We've given some more thought to this lately and it's been agreed that this work will start soon. The core team will handle it but we could certainly use help with testing. I still cannot give exact timeline because the work hasn't started. After we finish some bigger ongoing work items this is one is right at the top of the priority list. We'll post updates to this issue.

**Comment by bingxie** [comment]
That's a very good news.

**Comment by redhedjim** [comment]
I am interesting in lending a hand when the time comes.

**Comment by JahBrewski** [comment]
Any update on this re: timeline? Talking to a client about using sharetribe.. but we're concerned about compatibility issues with Rails 3.2.

**Comment by ssoulless** [comment]
Hi, anything you need just ask, Im very interested in see this working with Rails 4, even better if Rails 5

**Comment by voyera** [comment]
I would be interested in having a look at it. Do you guys plan to have a rails4 branch ? I'm sure some of us could help your team.

**Comment by rap1ds** [comment]
Good news! We are finally working on this! Thanks for you patience.

Past few days I have been upgrading to some gems to Rails 4 compatible versions and that's now done and merged to master branch. At the moment I'm changing the code parts where we are using features that have been removed from Rails 4. I'll try to merge all these changes in small pieces to master as often as possible. I'm trying to avoid having a huge rails4 branch, because big changes at once make big bugs.
