### ISSUE TITLE
Always failed rspec test

### ISSUE THREAD

**Issue by bingxie** [sharetribe/sharetribe#911]
I always have a failed rspec test on my local machine, I run the test with:
rake test:prepare
rspec spec

The failed test is:

Failures:

  1) BraintreeService::EscrowReleaseHelper#release_from_escrow when escrow status changed from "hold_pending" to "held" releases from escrow later
     Failure/Error: successes.should == 1
       expected: 1
            got: 0 (using ==)
     # ./spec/services/braintree_service/escrow_release_helper_spec.rb:37:in `block (4 levels) in <top (required)>'

Seems like the failed reason is Delayed::Worker.new.work_off returns [0, 0] not [1, 0], do I need to config anything for the delayed job?

**Comment by bingxie** [comment]
I also found actually there are two jobs in the table:

pry(#<RSpec::Core::ExampleGroup::Nested_2::Nested_1::Nested_2>)> Delayed::Backend::ActiveRecord::Job.all
=> [#<Delayed::Backend::ActiveRecord::Job id: 4, priority: 6, attempts: 0, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject:...", last_error: nil, run_at: "2014-03-13 01:00:00", locked_at: nil, failed_at: nil, locked_by: nil, created_at: "2014-03-11 20:00:00", updated_at: "2014-03-11 20:00:00", queue: nil>,
 #<Delayed::Backend::ActiveRecord::Job id: 5, priority: 6, attempts: 0, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject:...", last_error: nil, run_at: "2014-03-13 01:00:00", locked_at: nil, failed_at: nil, locked_by: nil, created_at: "2014-03-11 20:00:00", updated_at: "2014-03-11 20:00:00", queue: nil>]

**Comment by bingxie** [comment]
Thank you @heydiplo for fixing this issue.

**Comment by rap1ds** [comment]
Thanks @bingxie for reporting and thanks @heydiplo for fixing!
