### ISSUE TITLE
Error connecting to Sphinx via the MySQL protocol.

### ISSUE THREAD

**Issue by xiaominger** [sharetribe/sharetribe#916]
I'm using coreseek4.2，but there are some issues:“ connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (111) - SELECT * FROM `listing_core`, `listing_delta` WHERE MATCH('*股票*') AND `community_ids` = 1 AND `sphinx_deleted` = 0 ORDER BY `sort_date` DESC LIMIT 0, 24; SHOW META”

**Comment by ovan** [comment]
Hi @xiaominger. Unfortunately we don't have resources to provide environment specific installation support here, especially since you are using a component we don't use ourselves (coreseek). You can try the community chat linked in README for help.
