### ISSUE TITLE
Issue in domain name

### ISSUE THREAD

**Issue by harshad26** [sharetribe/sharetribe#919]
I run sharetribe on production server.

Domain name is:  http://xyz.trade  (Not sub-domain. Its a main domain. Site run on main domain)

Now when i type www.xyz.trade then its redirect to www.www.xyz.trade

Why this problem occurs? How to solve it?

I want to run site on http://xyz.trade  and http://www.xyz.trade  then how to config server or sharetrabe configuration file.

**Comment by rap1ds** [comment]
Hi!

I guess that not possible with the current implementation.

Just out of curiosity, why do you want to run the site both on naked domain (http://xyz.trade) and on www domain (http://www.xyz.trade)?

A common practice is to pick one as a main domain and then do redirect from the other (e.g. http://xyz.trade redirects to http://www.xyz.trade). To my understanding that also good for search engines.
