### ISSUE TITLE
Missing step for newbies in README.MD Installation

### ISSUE THREAD

**Issue by camerojo** [sharetribe/sharetribe#921]
I am a new user, starting from scratch using the Sharetribe installation instructions.

There is a missing step if someone is starting from scratch:

rake db:create needs to be run before rake db:schema:load will work

**Comment by rap1ds** [comment]
Hi! Good point, would you like to PR?

**Comment by camerojo** [comment]
Sorry - I am a real newbie. What does PR mean? If it means updating the doc, it would be better if someone else did it. I don't think I will be using Sharetribe now so will not be contributing further. Good luck with this project.
