### ISSUE TITLE
delayed_paperclip.rb:52:in `process_in_background': undefined method `[]=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by younes0** [sharetribe/sharetribe#942]
When trying to run server, I get :
```
/usr/share/rvm/gems/ruby-2.1.2/gems/delayed_paperclip-2.9.0/lib/delayed_paperclip.rb:52:in `process_in_background': undefined method `[]=' for nil:NilClass (NoMethodError)
        from /www/shic/app/models/community.rb:204:in `<class:Community>'
        from /www/shic/app/models/community.rb:102:in `<top (required)>'
```
Sorry if this question might be not related to sharetribe as I'm a newbie to ruby.

**Comment by younes0** [comment]
Commented all process_in_background in community then the setup was possible.

**Comment by rap1ds** [comment]
Hi! Have you run `bundle install` to install all the gem dependencies?

Besides from that, it's very hard to give any additional advices, so I'm going to close this ticket. Please comment and add more information if you find out something useful.

**Comment by younes0** [comment]
Thanks @rap1ds , I'll keep this thread updated then if I solve my problem.

**Comment by aug-riedinger** [comment]
I've had the same error. Found the related issue through Github repo's search (don't know why google doesn't) :
https://github.com/jrgifford/delayed_paperclip/issues/129

All `process_in_background` must be declared after `has_attached_file`
```
  process_in_background :logo
  process_in_background :wide_logo
  process_in_background :cover_photo
  process_in_background :small_cover_photo
  process_in_background :favicon
```

**Comment by danielbonnell** [comment]
I can confirm @augnustin solution works. To further clarify though, all `process_in_background` must be declared after all `has_attached_file`. In other words, you cannot do something like this:
```
has_attached_file :image
process_in_background :image
has_attached_file :logo
process_in_background :logo
```
I had this setup and it wasn't working. Thought I was loosing my mind.🙃
