### ISSUE TITLE
Process does not run in background

### ISSUE THREAD

**Issue by harshad26** [sharetribe/sharetribe#945]
I setup project on production environment on server.

Now i tried to RUN jobs work in background using below command:

>>>>>>>   rake RAILS_ENV=production jobs:work &

When i RUN in background then start process but not in background. When i closed terminal then process not worked.

What is solution? any one?

**Comment by mrzor** [comment]
You may use the `disown` shell builtin to allow the process to continue after you close to the terminal.
Otherwise, if you're running `zsh`, you can disown from the start by using `&!` instead of `&`.

**Comment by harshad26** [comment]
Hi @mrzor 

Thanks for reply.

i Used nohup command to RUN proecss in BG after close terminal.

nohup rake RAILS_ENV=production jobs:work

Many Thanks
