### ISSUE TITLE
Getting error page while opening Messages

### ISSUE THREAD

**Issue by usmanarif** [sharetribe/sharetribe#956]
I am getting "ArgumentError: argument out of range" error for 

    utc_str_to_time(str)
present in app/utils/time_utils.rb file

In order to get the value coming in "str" I have raised it and found the following value with error in log file

    RuntimeError (2015-0)
Please tell if I am missing anything

**Comment by rap1ds** [comment]
There's another issue #1375 which seems to be duplicated.

I'll close this and let's continue discussion in #1375
