### ISSUE TITLE
Filters/custom fields doesn't work

### ISSUE THREAD

**Issue by jounih** [sharetribe/sharetribe#959]
https://testi.sharetribe.com

I am trying to create custom fields/filtering for phone brands - seems that it's not working at all.

In the front end the custom fields are shown at the bottom of EACH category listing, even when it's only applied to one. And tapping a filtering option doesn't actually filter the results anyway

Would expect the custom fields/filtering to only be shown on the selected category view

**Comment by rap1ds** [comment]
Hi!

All custom filters are shown, even if they are only associated with one category. That's definitely not optimal. We are looking for a better solution for that.

What do you mean by saying that "filtering doesn't actually filter the results"? Can you give me an example? I tried the filtering in one other marketplace and it seems to be working ok. 

I see that you don't have any listings in your marketplace, so first you have to create a listing or two to see the filtering in action.

**Comment by rap1ds** [comment]
Closed due to inactivity
