### ISSUE TITLE
User cannot update their payout information

### ISSUE THREAD

**Issue by rkrevolution** [sharetribe/sharetribe#967]
There is no UI process if a user needs to update their payout information? Is this available?  It seems like a needed feature..

it is possible in braintree - however, the functionality needs to be added to the OS version sharetribe so that marketplace members can adjust their payout details 

https://developers.braintreepayments.com/javascript+ruby/guides/marketplace/update

**Comment by rap1ds** [comment]
Hi!

When we implemented the Braintree integration, there was no possibility to update payout details via the API. Good to know that they have added that!

The core team is currently concentrating on PayPal and it's not likely that we will add this feature in the near future.

I'll leave this issue open for a while if there's more conversation around the topic.
